### ISSUE TITLE
docs.winglang.io open-graph metadata is missing an image and a good description

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1014]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

Share a link from docs.winglang.io via social channels such as Twitter, LinkedIn, etc.

### I expected this:

To see a nice sharing image

### Instead, this happened:

See this: https://www.opengraph.xyz/url/https%3A%2F%2Fdocs.winglang.io

### Component:

Documentation

**Comment by ekeren** [comment]
@ainvoner - are you aware of this one?

**Comment by ainvoner** [comment]
1. we should select an image that will be shown for all pages
2. for each page we need to add a title and description metadata

Docusaurus will automatically add relevant "og:" metadata properties for facebook and linkedin support.
for twitter we will have to add specific "twitter:" metadata properties in the config file.

**Comment by ainvoner** [comment]
tested on:
Facebook: https://developers.facebook.com/tools/debug/
Twitter: https://cards-dev.twitter.com/validator
LinkedIn: https://www.linkedin.com/post-inspector/

and in general: https://www.opengraph.xyz/
