### ISSUE TITLE
Resource idea - aggregation queue

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1022]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

The concept of an aggregation queue is that it's like a queue, but it aggregates messages until it reaches a "threshold" at which point a batch of messages are processed by a single function. I heard about the idea while reading [The Distributed Computing Manifesto](https://www.allthingsdistributed.com/2022/11/amazon-1998-distributed-computing-manifesto.html). 

(AWS SQS lets you do some basic aggregation as it can send up to 10 messages at a time to a consumer, but that's sort of a small amount)

```
new cloud.AggQueue(agg_func, batch_size: 1000);
```

If it's possible to make this easily out of existing resources (maybe with `Queue` and `Counter`) then we might not even need to include it as a primitive, and instead we can add it to our [wing examples](https://docs.winglang.io/contributors/handbook#%EF%B8%8F-how-do-i-add-an-example).

### Use Cases

As described in the original paper (in the context of preparing Amazon orders for a warehouse):

> A batch of customer shipments has to accumulate so that picklist has enough information to print out picks according to shipment method, etc. Once the picklist processing is done, the shipments go on to the next stop in their workflow. The holding areas for this third type of data are called aggregation queues since they exhibit the properties of both queues and database tables.

### Implementation Notes

Maybe some combination of a DynamoDB table and a SQS queue for AWS? (And something similar on other clouds)?

### Component

SDK

**Comment by eladb** [comment]
I am curious if this is something that [Kinesis Streams] can address.

[Kinesis Streams]: https://aws.amazon.com/kinesis/data-streams
