### ISSUE TITLE
String parsing is duplicating variables

### ISSUE THREAD

**Issue by marciocadev** [winglang/wing#1041]
### Community Note

When we create a string with interpolation, if we include more than 1 variable all variables except the last one are duplicated

### I tried this:

When compile this code

```w
bring cloud;

let q = new cloud.Queue();
let b = new cloud.Bucket();
let c = new cloud.Counter(initial: 1000);

let handler = inflight (message: str): str => {
  let value = c.inc();
  b.put("wing.txt", "${message}${value}");
};

q.on_message(handler);
```

### I expected this:

I expect this code on my inflight function (javascript)

```js
async handle(message) { const { b, c } = this; {
  const value = (await c.inc());
  (await b.put("wing.txt",`${message}${value}`));
} };
```

### Instead, this happened:

```js
async handle(message) { const { b, c } = this; {
  const value = (await c.inc());
  (await b.put("wing.txt",`${message}${message}${value}`));
} };
```

the `message` variable duplicate, if I add more variables all except the last will be duplicated

### Component:

Compiler

### Wing Version:

0.4.51

### Node.js Version:

v18.12.1

### Platform(s):

Linux

### Anything else?

I believe the problem is in the parser between lines 613 to 650 of the file `wing/libs/wingc/src/parser.rs`

When running this test
```bash
npx nx dev -- wing/examples/tests/valid/expressions_string_interpolation.w 
```

We can see duplicated data on this file `wing/examples/tests/valid/expressions_string_interpolation.w.out/preflight.js`

**Comment by eladb** [comment]
Ha! Yes this is the bug we encountered when we demoed wing on twitch!

**Comment by eladb** [comment]
@marciocadev let us know if you want to take a whack at it. Sounds like you pinpointed the location.

**Comment by marciocadev** [comment]
I already submitted the PR, but I don't program in Rust, please review carefully

I believe that we should try to validate what is generated in the compiler because today it is compiling but not validating the result
