### ISSUE TITLE
Improve resize handling and media queries

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#1051]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

The console has media queries for different screen sizes.

The console has a minimum width (typical of 400px.)

### Use Cases

Resizing the Console window should resize the content accordingly to display it as well as possible to make it usable.

### Implementation Notes

_electron/main/index.ts_
`const window = new BrowserWindow({
     ...
    minWidth: 400,
    minHeight: 270,
`

_src/components/VscodeLayout.tsx_
<img width="690" alt="image" src="https://user-images.githubusercontent.com/5547636/210807360-39d50193-9f13-4a39-a241-ceebf415c311.png">

### Component

Wing Console

**Comment by ainvoner** [comment]
keep open
