### ISSUE TITLE
docsite search 

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#1066]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

docs.winglang.io doesn't have search 

### Use Cases

Look for something I know is in the docs, but I am not sure where it is

### Component

Documentation

**Comment by Chriscbr** [comment]
It looks like we might be able to use Algolia for free since our project is open-source: https://docusaurus.io/docs/search

**Comment by ainvoner** [comment]
applied Aloglia: [tracking link](http://support.algolia.com/hc/requests/536292)
