### ISSUE TITLE
playground.winglang.io is still up but not updates

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#1067]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

I've noticed that https://playground.winglang.io/ is still up, we should close it

### I expected this:

This link should not exists

### Instead, this happened:

The link works with outdated version

### Component:

Other

### Wing Version:

NA

### Node.js Version:

NA

### Platform(s):

Other

**Comment by staycoolcall911** [comment]
We said we'll keep this url working for now. @ekeren, please decide with @eladb if you guys want to remove it.
