### ISSUE TITLE
Unable to see errors when opening wing console with a faulty app

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1068]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

Create `foo.w`:

```js
19@Cknkj
```

Run:

```sh
wing it foo.w
```

### I expected this:

Wing Console should open and show me the logs with a compiler error.

### Instead, this happened:

I just got this, but logs were empty. So there's no way to tell what is the error.

![Screenshot 2023-01-08 at 12 06 28](https://user-images.githubusercontent.com/598796/211190299-5f1c0ce5-8a47-4538-b202-ee6aa7df3028.png)

### Component:

Wing Console

### Wing Version:

0.1.22

### Platform(s):

MacOS

**Comment by ainvoner** [comment]
@polamoros related to https://github.com/winglang/console/commit/5dd6ceb88ff6fc30b0470d080ccb05bdea745889
