### ISSUE TITLE
console not running simulator 

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#1070]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

I am running `wing it <some_wing_file>.w`

### I expected this:

The console to be constantly updates

### Instead, this happened:

This happens quite frequent 
![image](https://user-images.githubusercontent.com/1727147/211191721-0f6ae17c-fe3c-4157-bad3-18db407c8e57.png)

### Component:

Wing Console

### Wing Version:

0.4.46 (console 0.1.22)

### Platform(s):

MacOS

### Anything else?

I was using the code from story10.md

It doesn't happen every time, I suspect it has something to do with multiple saves compiles.. but I don't really know

https://github.com/winglang/wing/blob/aa8e4510cd508ed38213d0afda65d6f4cc860cd1/rfcs/story10.md?plain=1#L18-L112

**Comment by ainvoner** [comment]
@ekeren can you share the code you were trying to run?
It will be easier to solve if we will have a real example for what broke the simulator

**Comment by ekeren** [comment]
Sure, I was using the code from story10.md, but it happens inconsistently (but quite often), updating description

I can try to reproduce if you have some debugging/logs that you want me to capture

**Comment by ekeren** [comment]
Lets see if this thing return, closing for now
