### ISSUE TITLE
string interpolation fails on dollar sign

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#1071]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

```ts (wing)
print("this cost $50");
```

### I expected this:

To compile and work

### Instead, this happened:

It assumed that I am doing string interpolation because of the `$` sign 
```sh
Compilation failed with 1 errors
Error at code.w:1:18 | Unknown parser error.
```

### Component:

Compiler

### Wing Version:

0.4.61

**Comment by staycoolcall911** [comment]
We should implement escaping `$` with backslash as described [here in the spec](https://docs.winglang.io/reference/spec#611-normal-strings-).

**Comment by staycoolcall911** [comment]
After testing, this actually works:
```ts
print("this cost \$50");
```
Closing the issue - @ekeren if I missed anything, please reopen

**Comment by ekeren** [comment]
The way I read the spec is that the interpolation should happen when we have the dollar and the curly brackets together. 

Meaning: 
```ts
print("this cost $50"); // should print this cost $50
print("this cost \${50}"); // should print this cost ${50} 
let num = 50;
print("this cost $${num}");// should print this cost $50
print("this cost $\${num}");// should print this cost $${num}
```

I verified this with nodejs backticks behavior:
```js
> let num = 50;
> console.log(`this cost $50`) // this cost $50
> console.log(`this cost \${50}`) // this cost ${50}
> console.log(`this cost $${num}`) // this cost $50
> console.log(`this cost $\${num}`) // this cost $${num}

**Comment by staycoolcall911** [comment]
Thanks for clarifying.

**Comment by Chriscbr** [comment]
It looks like the issue has been resolved since removing $ from the string interpolation syntax - all of these print the correct messages:

```
log("this cost $50");
log("this cost \${50}");
let n = 50;
log("this cost $${n}");
log("this cost $\${n}");

log("hello$");
log("cool${n} stuff");

log("foo$\{}bar");
```

and this is a syntax error (expected)

```
log("foo${}bar");
```

I'll close this out. If there's still a bug lurking here, feel free to reopen or create a new issue 🙂
