### ISSUE TITLE
Captured values are not recognized in string interpolation

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1075]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

```js
bring cloud;

let b = new cloud.Bucket();

new cloud.Function(inflight (s: str): str => {
  print("value=${b.get("hello.txt")}");
});
```

### I expected this:

`b` to be captured.

### Instead, this happened:

It's not captured

### Component:

Compiler

### Wing Version:

0.4.57

### Platform(s):

MacOS

**Comment by staycoolcall911** [comment]
I'm guessing the workaround would simply be to split the inflight code to 2 lines, like this:
```ts
bring cloud;

let b = new cloud.Bucket();

new cloud.Function(inflight (s: str): str => {
  let id = b.get("hello.txt");
  print("value=${id}");
});
```

Giving this issue a p3 priority.

**Comment by eladb** [comment]
I think this is p2 (the fact that there's workaround means it's not p1), but I still think it's something we need to fix before we release our beta.

(it also implies that there's some weirdness in the capturing mechanism that needs to be cleaned up).

**Comment by eladb** [comment]
(happy to pick this up)

**Comment by marciocadev** [comment]
@eladb I was poked around and I think one of the problems is its expect a `variable_definition_statement`  to create this line -> `const { b } = this;`

**Comment by eladb** [comment]
> @eladb I was poked around and I think one of the problems is its expect a `variable_definition_statement` to create this line -> `const { b } = this;`

Indeed, it seems like the capturing system doesn't identify `b` to capture when it is inside a string interpolation.

**Comment by marciocadev** [comment]
good, I think that leaves plenty of room for a descriptive name

**Comment by staycoolcall911** [comment]
Closing - this was recently fixed.
