### ISSUE TITLE
Performance: Embed wingsdk JSII manifest directly into wingc

### ISSUE THREAD

**Issue by MarkMcCulloh** [winglang/wing#1083]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

wingc now always includes the JSII spec for wingsdk embedded in the compiled output and is no longer required to be resolved externally before type-checking.

### Use Cases

While this will increase the size of wingc, it improves both the speed of compilation and reduces build complexity for projects consuming wingc (vscode-wing, wing-language-server, wing, wing-playground).

### Implementation Notes

https://doc.rust-lang.org/std/macro.include_str.html

### Component

Compiler

**Comment by eladb** [comment]
Yes please!

**Comment by eladb** [comment]
@staycoolcall911 bumped this to P2

**Comment by staycoolcall911** [comment]
We decided to close this for now as it seems this optimization won't yield much.
