### ISSUE TITLE
register to newsletter

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#1092]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

We want to allow visitors of winglang.io to register to wing newsletter 

### Use Cases

- Register from winglang.io
- Register from our doc site 
- Register from our blog site

### Implementation Notes

I don't believe that registration  to the newsletter should be our strong CTA on the landing page. 
IMO, it should be the getting-started part.

My suggestion: 
- Create a "Getting Started" CTA on the right side of the Star CTA 
- Move the Slack away from there 
- Add a Launchdarkly style register to our newsletter box above the footer
- Have the same box in the doc and blog site 

### GO 

In GO, they have a link on the footer to go-weekly 
![image](https://user-images.githubusercontent.com/1727147/211523619-afc98545-15a4-49aa-a4d6-fc616d1c660b.png)

Once clicking the link you land on a register page:
![image](https://user-images.githubusercontent.com/1727147/211523567-ddba5294-30fe-472c-9adc-cd0e96e59adc.png)

### LaunchDarkly

Launchdarkly has this on top of the page footer for featureflags.io lanuchdarkly.com website 
![image](https://user-images.githubusercontent.com/1727147/211524394-6d93c575-7f8e-4f71-9a35-059606463cfa.png)

### Component

Documentation

**Comment by ShaiBer** [comment]
The homepage is done.
Docs and blog site not yet
