### ISSUE TITLE
chore: use @electron/osx-sign instead of electron-osx-sign

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#1095]
>  WARN  deprecated electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different

**Comment by ainvoner** [comment]
keep open

**Comment by Chriscbr** [comment]
@skyrpex Is the console still using electron? Double checking if this can be closed or not

**Comment by ainvoner** [comment]
not using electron anymore :)
