### ISSUE TITLE
Std objects API - add a layer to allow customization on top of the standard js API

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#1101]
Add a layer on top of std objects to create our own api and not just delegate directly to js api (e.g. so we could use `str.contains()` instead of `.includes()`).

This issue refers to adding the mechanism, while #1116 defines the actual changes to our `std` objects APIs

**Comment by ekeren** [comment]
I am lowering priority for this in because of #1170

**Comment by staycoolcall911** [comment]
Closing - this is part of #1116
