### ISSUE TITLE
Symbol shadowing doesn't work

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1109]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

```js
bring cloud;

let s = "hello";

new cloud.Function(inflight (s: str): str => {
  print("hello, ${s}");
});
```

Also:

```js
let a = "hello";
if true {
  let a = "world";
}
```

### I expected this:

The inner `s` should have shadowed the outer `s`.

### Instead, this happened:

```
Error at ./hello.w:5:30 | Symbol "s" already defined in parent scope.
```

### Component:

Compiler

### Wing Version:

0.4.75

**Comment by staycoolcall911** [comment]
Duplicates #223, but it has a better code sample so I'll keep it and close #223.

**Comment by eladb** [comment]
Cool, added your code snippet to #1109 as well, because they could be two
different use cases.

**Comment by MarkMcCulloh** [comment]
This was intentional, shadowing makes it easy to get confused about what a given symbol is. There has been previous discussion on it, but I can't find it atm.

Regardless, it isn't currently in the spec, so we should make sure to first update the spec to clarify whether or not we allow it.

**Comment by eladb** [comment]
No problem. No rush. I am fine with leaving it like this for now.

**Comment by yoav-steinberg** [comment]
For reference, this is by design and all you need to do is delete this: https://github.com/winglang/wing/blob/57e09cb98a0c06c95d4a5a652a07601964dac6fa/libs/wingc/src/type_check/symbol_env.rs#L110-L131
to get it working.

**Comment by eladb** [comment]
In this meet-up,  senior software developers at Winglang, will guide you through Winglang's core concepts, background, how it's constructed

Hi friend,

The Winglang team is hosting a Virtual Meet Up!

Curious about how Winglang operates behind the scenes? Winglang (https://email.winglang.io/e3t/Ctc/5G+113/d37W-X04/VWNblL3Np5dQW34Vj741grXzHW6hm-BV53T2-7MfRfk-3l5QzW7lCdLW6lZ3lkW3QS6B92cWGsMW4KrtvN4NDBTLV_ppmm2W5ljCW2bfYmh1g7tdxW7b_x366pYlqxW5bQLWK2zdTHPN5jDnVkTNRgdW1slVxK97mfL5W7pv8pF2gDnR3W6g60Hv8g4r4kW1QgnrV2b05M8W8405qp5bTBR3VMYjRh2RRCjlW7x9BjF42SNqZW1TPKPg3qW03kW70Bmjk8zw1GPW65Sxhg2ZVM9LW82yDnH2HbrL6W2LN1tS4y12Y0W4MD7833nDNMbN978R7yNnMqBW5KZ9kZ3mKg5YVqS-hn1n02YCW66n0Q75m1p72dlNgpF04 ) , for those new to it, is a unified programming model that combines both infrastructure and application code into a single programming language. Our goal is simple - to enable developers to stay in their creative flow, and to deliver better software, faster and more securely.

In this meet-up, Tsuf Cohen (https://email.winglang.io/e3t/Ctc/5G+113/d37W-X04/VWNblL3Np5dQW34Vj741grXzHW6hm-BV53T2-7MfRflz3l5QzW8wLKSR6lZ3kRW1fvXXb8GT671N7ZzNg2wT4tVW7xVTQv7L0ZTmN6cmLVFmLFTyW5vb44m2HsK3gW1HtQyG6PPcy4W5hTT3n1PHs7RVD-pkT8844C9N1CXvjgxn90YW1n8rVL2nF4ZcN8yGv7CHBDDNW9gzs2W4tp6QXW6MdFF63Ws0ygW4wCYpl2jSNg-W8lbdkH1Lpl6rN3jQt5XCW52pW3ZT-Zr6TWFX7W5zWWWF7ly_KZN72d-v75v426F8YkydCTpCrW5g3qSD4qDwf-W3JB-R02MW46MW22wGZx6CC5FHVTX7-R3vgsS5N3wk5H5Zqk1mW4HpvfY8VN-9pW7D6hmj4GsxsfW6GXPXz6fH1FYf8WVQCd04 ) and Hasan Abu-Rayyan (https://email.winglang.io/e3t/Ctc/5G+113/d37W-X04/VWNblL3Np5dQW34Vj741grXzHW6hm-BV53T2-7MfRflz3l5QzW8wLKSR6lZ3lpW3zRcc86zr3tDN45SGb88NTYmW6cH2Yw6Y-kcBW25x2T65xtWv2W437BVC82tQNGW6TbW4W9hQnL4W4yngZD3Wz_y0W4L_PYC5gy26LW7hyg975v2w-4N52cgrlrtBZjW9lgPxn65zXwgW1JppHM9b3lb6W40qRZH8rfgS_W1vKGSD66P00cW1FFYGZ5y0drjW9hXwWc8_8RM4W8KmLNr6rZ_L9W2M39YM7LlvQhN4qQ_6tj4RwCW3ySQT610YskTVt7hC8972lhHW1QSwyk2fwLq5W2gZV2-4qlP-bW5XD-8p6z2gbGW62wrJh66YBlxW5v_c2-19gwk0W1fZf1z42jm_hW7hNcRr8Gfnpdf8nlnn804 ) , senior software developers at Winglang, will guide you through Winglang's core concepts, background, how it's constructed, and even showcase a couple live coding sessions.

Agenda:

Hasan will delve into the essence of the Wing SDK, touching on defining the cloud through it and highlighting key resources, as well as reviewing foundational concepts of Winglang, distinguishing between 'inflight' and 'preflight', explaining compiler targets, and unpacking the revolutionary idea of instantiating abstract classes over the traditional concrete ones.

Tsuf will walk us through adding a new method to an existing resource. This process includes taking us from issue assignment, through necessary code and documentation adjustments, introducing the code and directory structures, onto testing, and culminating with the process of placing a PR.

When:

Wednesday, October 4th, 2023 at 3:00 pm UTC.

Ready to save your seat? Make sure to register here (https://email.winglang.io/e3t/Ctc/5G+113/d37W-X04/VWNblL3Np5dQW34Vj741grXzHW6hm-BV53T2-7MfRflg3l5QzW7Y8-PT6lZ3k_W3fbyl35Yp4-zW51gq1m8L23cGMZynw3tvg8xW3TnVXS223T7KW1VKCK35z0ZrLW98WS1F3SkFzNN47hgJz8CFwMW1Syq4B20yDvKW8Q0-FJ3tJ5x5W3jvMDh3qmWfVW75lv9g5tV26WVQy93L6WNR_rW5KVFDz7Qp329W82Pr9s1q8NlzW3sgBhN8l3j3yW4rlTyT7jpbkLW7nzBP097J8RJW3VPYxV1VTCsfW38Z2b52X5rp0W6YPpjw2KKfnKW2vRTwr5plSccW4HLftV6WJFfcW28LfwS1z6G1HW8RmNP54F9zBNW98X_7z1Gy0CjV2HYgy65Y1FNf3DQZfz04 ) !

The Winglang Team

Unsubscribe (https://email.winglang.io/hs/manage-preferences/unsubscribe-all?languagePreference=en&d=VnBg1D971hLnW2p76LK3-1rCSW3z9cWG3H4lqcW4px75Z3zgDs-W3yQD_P3yQF5RW45M3kF3KbsvFW3R0gKw3R4swtW3JP0gk45RlhdW3P28X24hCPvhW43T2NP90PJzbW17f7hv6jrmkrW6gXmYn5n2MZFW5QjfTt8Gtx_jV28MR65VnSCSVGKdY75jw6htN70-d1VhcMnsW79FD382Q35vn4CWhg1&v=3&_hsenc=p2ANqtz-8qWcWe4HfrqA2bkjxrA_jtmE5bdcmPMLxfZgAIRAsMeX4vz7bzfdgw4u-OIBkJHtBOvYoVacdfU3pEuOCqIgL8vs5EyDcENuEOdfnCupRXgcOHdewIbZwPameiqYV0rLkvjGf85rESTpPXRidby5b6XR9z8Q&_hsmi=76598473 )

Wing Cloud,
30 Shlomo Ibn Gabirol Street,
Tel Aviv-Yafo, 6407807
Israel

**Comment by eladb** [comment]
Get hands-on with Eyal, Wing's CPO, as he walks us through the process of constructing a full-fledged React.js app supported by Winglang.

Hi friend,

We're hosting a live workshop (https://email.winglang.io/e3t/Ctc/5G+113/d37W-X04/VWlQqG7w-dLWW6_Wgh91jjvLkW69sl4k566lcFN5LPbS85fkwKW69t95C6lZ3njW7-1RtG8JG25sW5wnNQG8dPQt5W3vphMT56JkPBW1bn7YF6LWyMBW1K847H3V9BFqW1kdPmL2BtM5YVmM2Pm5qbsCrN2XXR8kN1B0NW5t4-v83KKc8KVpLBwq17mFt5W6FlZLV2nqmBhW7Rvgwz2sHFFQN5jJ_b0PpvbwN8ys404QPS7cW6yQWVP8tDG5MW1H_tT29llQN6W8RNkK06gGzvtVytQlK60XLstW7Bm1vq19RRbZW8NqJGc5c1MCqW5n3dcH92HxZgVbx8gt7nh2mjW5Wdw041Bnk32W84Nb1L1y65tgW4qx8n28lCDW7W2hqqCm7Ms0m9W4ZJpss4X_W-cW685pTk6lSgMyW53dpG16k4gNMW36LqNN89C7DpW4kKQ-T7dXmV2W5TrtbB5CpWSKW8JrRnV3KvygVN2Qq_51J7sxtN1RhLxG6XbpzW4wdT_v94R8Jtf1k2F-C04 ) - and we'd love to see you there!

Get hands-on with Eyal, Wing's CPO, as he walks us through the process of constructing a full-fledged React.js application supported by Winglang (https://email.winglang.io/e3t/Ctc/5G+113/d37W-X04/VWlQqG7w-dLWW6_Wgh91jjvLkW69sl4k566lcFN5LPbTl3gP0xW8wLKSR6lZ3lKN4MpMbbj5jFZVCS8pc2J1qYhW1xSY9p2dV3CkW6dT_-f4JPmNdW8C73jL1VNFHDW3Syqp18CjRxSW3tffJJ1q1GnZW8bnFhT5y_5YMW1zCX5l7KLzGQN36yNnb-62gsW75JyG88JZsGVW2XhDxC1tmcDkN25hZ-4r02pTW6QhXnd7qfcVMN56PJQRy49n8W7qpJcQ7km6mBW82JSYB6n1n3lW2sgNf52m8QsfN5D4pBzbyq4WN90YxlLlcFhlW8PtLGp8S47T6W6fQBks6Kyv60W2hBHwX1G6dL6W7g3GBQ5gghzcW3N1KS01nBBDyW4TS_Kx9bVkKsN2y_MtDBQk7_W4J5f-07lS5SKf47CJYj04 ) .

In this workshop, you will discover how to:

🔹 Craft and bundle a React.js website

🔹 Set up a secure API gateway with auth measures

🔹 Implement real-time updates with websockets

🔹 Manage data using DynamoDB

🔹 Launch your site on Amazon S3 with AWS’s Content Delivery Network

By the end of the workshop, you will acquire the essential technical skills and practical approaches necessary for using Winglang to build a web application that meets production standards.

When:

Wednesday, December 6th @2:30pm UTC

Ready to save your seat? Make sure to register here (https://email.winglang.io/e3t/Ctc/5G+113/d37W-X04/VWlQqG7w-dLWW6_Wgh91jjvLkW69sl4k566lcFN5LPbS85fkwKW69t95C6lZ3njW7-1RtG8JG25sW5wnNQG8dPQt5W3vphMT56JkPBW1bn7YF6LWyMBW1K847H3V9BFqW1kdPmL2BtM5YVmM2Pm5qbsCrN2XXR8kN1B0NW5t4-v83KKc8KVpLBwq17mFt5W6FlZLV2nqmBhW7Rvgwz2sHFFQN5jJ_b0PpvbwN8ys404QPS7cW6yQWVP8tDG5MW1H_tT29llQN6W8RNkK06gGzvtVytQlK60XLstW7Bm1vq19RRbZW8NqJGc5c1MCqW5n3dcH92HxZgVbx8gt7nh2mjW5Wdw041Bnk32W84Nb1L1y65tgW4qx8n28lCDW7W2hqqCm7Ms0m9W4ZJpss4X_W-cW685pTk6lSgMyW53dpG16k4gNMW36LqNN89C7DpW4kKQ-T7dXmV2W5TrtbB5CpWSKW8JrRnV3KvygVN2Qq_51J7sxtN1RhLxG6XbpzW4wdT_v94R8Jtf1k2F-C04 ) !

The Winglang Team

Unsubscribe (https://email.winglang.io/hs/manage-preferences/unsubscribe-all?languagePreference=en&d=VnBg1D971hLnW2p76LK3-1rCSW3z9cWG3H4lqcW4px75Z3zgDs-W3yQD_P3yQF5RW45M3kF3KbsvFW3R0gKw3R4swtW3JP0gk45RlhdW3P28X24hCPvhW43T2NP90PJzbW17f7hv6bM2KGW6RMWQs4WpGpSW5t9jtg96WRmhV28PLr85643BVGKdY75jw6jHW1KgRDy50dp_JW4KGJ1g2JKq9t4wwKZ1&v=3&_hsenc=p2ANqtz-8OKED_3ngWjDkPPGfahX6XzvovmajW6Xhmd-QG4vyGsSJzAjHcmNaMByO5tM4i4L7JttFNLeHOsjta6l2DPhmLLF0uREsGBYFOVp97JwMuSV1zT-SV19bfCY11RUMpwnMJcaYJbcEBo_Y5beiOkIqwFRIBaQ&_hsmi=78979326 )

Wing Cloud,
30 Shlomo Ibn Gabirol Street,
Tel Aviv-Yafo, 6407807
Israel

**Comment by eladb** [comment]
In the workshop we'll be showing how to implement this GitHub bot from zero to hero using Amazon Bedrock & Winglang.

Hi friend,

I'm thrilled to remind you about our "Winglang + Amazon Bedrock Workshop" happening today!

I am planning to have interactive session that includes hands-on activities that will make learning both effective and, hopefully, also fun.

Arik Porat, (https://email.winglang.io/e3t/Ctc/5G+113/d37W-X04/VX5TcX3dqfWQW3RBtF-4qhrKNW46ZLVZ57R-gQN26s5_d5m_5PW50kH_H6lZ3pZW72njLP8XbdpbW1SHtMG8qX70-W6zMvQx2TwQCWW8G4FtF7nSnhtW2kMDXT6xKs3pN2gmgmCrHlLvW6B66nv6Y2yqkW4Hbtns4rtR3RW7HR7KK7TYdhTW8GzpR92ZgNcHW8tXCxk4Qq-q-W6BrRPP535kP0N27MP1CMygZPW8Kmqkl5GHml5W8gwCQr6NCC6NN79Ft9cMQH1CW2p2yr51vb5mHW1H0mYl2RBS4HW5V-Km77FmlkzW60Dx8X2nhGRTVj1hW67qDh5FW8ypLLD6nbhN2W2GzWx37HKV1fW3rwHwP6MNTXsW68724G3Tr68CW5LS59y8Rdw9CW24MwDz4FGhjVW7TKK131z9cRyW3C8YfY3cwGRBN7D9lwy2xpx3W2GlvwM11wxRzW3kZphT1tvNqvf5--Whq04 ) a solution architect at AWS, will be joining us as our special guest, and will be explaining and demoing Amazon Bedrock capabilities.

In the workshop we'll be showing how to implement this GitHub bot from zero to hero using Amazon Bedrock & Winglang.

In only 90 minutes you'll build and deploy your own GitHub application on your own AWS account using terraform.

In the session, we will go through:

- Learn about Amazon Bedrock
- Creating a GitHub application
- Setting up API Gateway and Lambda functions with Access to Bedrock's Foundation Model
- Developing the GitHub application locally
- Deploying it to your AWS account

Check out this 2 minute video (https://email.winglang.io/e3t/Ctc/5G+113/d37W-X04/VX5TcX3dqfWQW3RBtF-4qhrKNW46ZLVZ57R-gQN26s6103prCCW8wLKSR6lZ3m-W4P4Gg98qpz2KW63DVsQ7kDjRyN90qPycWzHV2W1sR7Db3NlC-zN5DhFpPTZPD6W57rpms4-HV4NW6Rgn6j8Qm4FVW1xVPYm7_9VB_W5Tb-LD28pg5pW1QRWvb14Tx2JW1npVCT1qLgVyN1Kg0vxRnpJfW4SPGKX2mPVQGN8yrsQC2DqL4W4YPnSj5w6g-cN14RV7m1hkmHW3vkH6T7zdf85N7Z98lWT7YcRW2HdbjV1fwjbkW9fJYxd7CD6y6W1wR5Fw2zj0cZW1Pyw1W6LB6s6W7YlX4z2Gf_S8VRm7D63s3WLdN7cycZ6ByFHNW5XGVPX8m-059VYHCdv1wdqs3W67Gb5M5rm9hhf2vTH_l04 ) of what we will build, I think it is freaking awesome!!!

Details:

- Date: January 3rd
- Time: 1:00pm EST
- Venue:  online event (https://email.winglang.io/e3t/Ctc/5G+113/d37W-X04/VX5TcX3dqfWQW3RBtF-4qhrKNW46ZLVZ57R-gQN26s5_x5m_5PW5BWr2F6lZ3nwW3N4X0H5XL5c3W2lD6G65ClcBCW1zKLSs38BkXQW5lGVG315p9yFN84gD3nsw-3xW6LCVNH31v95GW6nbrT57Hz6L3W8xw9bN1RL5NKW6z2L9f7Z88jrW6KKXRK2p37mqVb-gxy8VVhMlN3brFYnrtVKfW6HbRrB2zLyC6W5n1Xsf45lp6bW5clH093ZL6MWV16XK93RyyL4V7XK4P4DvfHWN1xCTSKBxrVpW82_Br38ttB-6VJQhbt28sJDSN8jhwZ0LVvCHN2vFQG1hfq63W4ncNYZ4hd3wyMmGdZ4fGvmwW6shXLF3sLzMNW5VRm022VCnyvW3k_9wg67Mw1YVqTcYf8r-Tw5W2lsj8x5YwPLWW8Kngyz4q1GMJW56xR-_3BwXQTW63tRSX6kmgFmVVCH167KHQYtW2qjG3H7VW9_hf6vrvTx04 )

Thanks,

Eyal.

Unsubscribe (https://email.winglang.io/hs/manage-preferences/unsubscribe-all?languagePreference=en&d=VnBg1D971hLnW2p76LK3-1rCSW3z9cWG3H4lqcW4px75Z3zgDs-W3yQD_P3yQF5RW45M3kF3KbsvFW3R0gKw3R4swtW3JP0gk45RlhdW3P28X24hCPvhW43T2Qr85BhDsW17f7hv8Sg5MDW57ljRL6ybf3YW5QsBpR8CH0zVV28ShC5SHXxpVGKdY75jw6j7VXJGyw7Mdzj1W7BpBHJ8XyXYn51yDKV1&v=3&_hsenc=p2ANqtz-8UUF6NUkedh90ABInmAJWF-hfQicz5U_aqZqDWM14rRQvmhY74ZU-_OGdrk2WyvCJHqbBfGgB49Fero1BHGa6mHPax_Uo2in6VR8NHC6b4HOF8AENeDFYL4i59fr4mXSArazA2ThOrtSQVksHBwjrXSRIO4g&_hsmi=80900034 )

Wing Cloud,
30 Shlomo Ibn Gabirol Street,
Tel Aviv-Yafo, 6407807
Israel
