### ISSUE TITLE
Console crashes when executing `panic`

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1111]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

```js
bring cloud;

new cloud.Function(inflight (x: str): str => {
  panic("hello");
});
```

### I expected this:

To see the "panic" message in the logs of the console

### Instead, this happened:

The console exited.

### Component:

Compiler, SDK, Wing Console

**Comment by ainvoner** [comment]
note: `panic()` is being translated to `process.exit(1)`

**Comment by eladb** [comment]
Indeed it is. When we run the inflight code inside the JS VM, we can override `process.exit`.

**Comment by ainvoner** [comment]
override `process.exit(1)` with `throw new Error("process.exit() was called with exit code " + code);`
