### ISSUE TITLE
Console window won't open twice for an invalid wing file

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#1114]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

- Create an invalid wing file, for example:
    ```w
    bring cloud;

    let bucket = new cloud.Bucke
    ```
- Start the Console and open the wing file
- Close the window (but not the application, MacOS only)
- Open the wing file again

### I expected this:

The window should open and show that there were some compilation errors.

### Instead, this happened:

The window didn't show, with no feedback at all.

### Component:

Wing Console

### Platform(s):

MacOS

**Comment by skyrpex** [comment]
This can be fixed with a nice refactor of the simulator, logger and window management.

**Comment by ainvoner** [comment]
keep

**Comment by ainvoner** [comment]
resolved
