### ISSUE TITLE
Container Types + str: objects APIs

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#1116]
We need to define (and implement) the supported API for all our `std` objects (e.g. `Set.has()`) - this includes mainly `str` and our [container types](https://docs.winglang.io/reference/spec#112-container-types).
We should also add reference documentation for that (perhaps in [here](https://docs.winglang.io/reference/sdk)).
A preceding step is to implement this: #1101 
- [ ] #1233
- [ ] #1234
- [ ] Reference doc
- [ ] Update the [wing language spec](https://docs.winglang.io/reference/spec) with a link to the reference doc (e.g. in the Strings and Arrays sections, for instance)
- [ ] add conversion from immutable container types to mutable `.to_mut()` and vice versa
- [ ] add a way to create a `Set` from `Array` - see [this comment](https://github.com/winglang/wing/issues/982#issuecomment-1380312690)

**Comment by Chriscbr** [comment]
> allow creating a new set from an array

Also creating an array from a set would be good 👍

**Comment by ekeren** [comment]
Notice that #1170 is related

@staycoolcall911 , lets try to split this and break this to less prioritized issues

**Comment by ekeren** [comment]
duplicated with #1234 and #1233
