### ISSUE TITLE
Mutable container type cannot be inferred

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1117]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

```js
let arr: MutArray<str> = [1,2,3];
```

(same for `MutMap` and `MutSet`)

### I expected this:

That `[1,2,3]` will be inferred as a mutable array

### Instead, this happened:

```
Expected type to be one of "MutArray<num>", but got "Array<num>" instead
```

### Component:

Compiler

### Anything else?

This works:

```js
let arr = MutArray<str>[1,2,3];
```

So this is a low-priority issue.

**Comment by eladb** [comment]
See @yoav-steinberg's comment here: https://github.com/winglang/wing/pull/1118#discussion_r1067001218

In a sense, we want to allow mutable containers to be initialized from immutable (implicit casting).

**Comment by MarkMcCulloh** [comment]
So if we have implicit casting, we can do this?

```
let a = [1, 2, 3];
let b: MutArray<num> = a;
b.push(4);
```

Because either:
1. `b` is a "mutable pointer" to `a`'s data, basically defeating the purpose of `a` being immutable
2. `b` is a copy of `a`

**Comment by Chriscbr** [comment]
2 cents - I feel like the original compiler error is correct here.

Instead of:
```js
let arr: MutArray<num> = [1,2,3];
```

(this is surprising... [1, 2, 3] could be initializing an immutable or mutable array? 😱)

Why not instead write:

```js
let arr = [1,2,3].to_mut(); // inferred: MutArray<num>
```

**Comment by eladb** [comment]
OK, I am happy to close this as "no fix". I like the explicit approach and `.to_mut()` makes things reasonably easy.

@yoav-steinberg @staycoolcall911 any objections to close this for now?

**Comment by staycoolcall911** [comment]
No objections

**Comment by yoav-steinberg** [comment]
Sure. Lets live a bit with the `.to_mut()` approach and see how it goes.

**Comment by eladb** [comment]
Closing for now!

**Comment by staycoolcall911** [comment]
I'm guessing we need to add `.to_mut()` to our `Array`, `Set`, `Map` std objects API - adding here #1116
