### ISSUE TITLE
Class Declaration: Add the ability to override methods

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1124]
https://github.com/winglang/wing/blob/main/docs/04-reference/winglang-spec.md#32-classes

**Comment by staycoolcall911** [comment]
We should probably start by adding #1123 and then add the ability to override `resource` methods, instead of `class`.

**Comment by staycoolcall911** [comment]
Looks like this already works:
```ts
class A {
  inflight do() {
    log("in A");
  }
}

class B extends A {
  inflight do() {
    log("in B");
  }
}

let b = new B();

test "override" {
  b.do();  
}
```

[Playground link](https://www.winglang.io/play/?code=YwBsAGEAcwBzACAAQQAgAHsACgAgACAAaQBuAGYAbABpAGcAaAB0ACAAZABvACgAKQAgAHsACgAgACAAIAAgAGwAbwBnACgAIgBpAG4AIABBACIAKQA7AAoAIAAgAH0ACgB9AAoACgBjAGwAYQBzAHMAIABCACAAZQB4AHQAZQBuAGQAcwAgAEEAIAB7AAoAIAAgAGkAbgBmAGwAaQBnAGgAdAAgAGQAbwAoACkAIAB7AAoAIAAgACAAIABsAG8AZwAoACIAaQBuACAAQgAiACkAOwAKACAAIAB9AAoAfQAKAAoAbABlAHQAIABiACAAPQAgAG4AZQB3ACAAQgAoACkAOwAKAAoAdABlAHMAdAAgACIAbwB2AGUAcgByAGkAZABlACIAIAB7AAoAIAAgAGIALgBkAG8AKAApADsAIAAgAAoAfQA%3D).

The only thing which is still missing from the original spec is the `override` keyword, which I think we should not add.
I'm closing this issue, please reopen or create a separate issue for the `override` keyword if you think it should not be left out.
