### ISSUE TITLE
Resource Declaration: inflight constructor (`inflight init()`)

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1125]
https://github.com/winglang/wing/blob/main/docs/04-reference/winglang-spec.md#33-resources

**Comment by eladb** [comment]
I think this is P1. It will be a major limitation for building resources.

**Comment by ekeren** [comment]
Elad, can you please provide the use cases for this. 

Also, does the `inflight init` function gets called each time that the client is initialized (on every capture) ?

**Comment by staycoolcall911** [comment]
Duplicates #67
