### ISSUE TITLE
winglang.io/docs should redirect to docs.winglang.io

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1135]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

winglang.io/docs should redirect to docs.winglang.io

### Use Cases

Someone is looking for types and knows our website is winglang.io, so they might type winglang.io/docs in their browser

### Component

Documentation

**Comment by Chriscbr** [comment]
@ainvoner I am still getting an error message on https://www.winglang.io/docs "404 - Page not found"

**Comment by ainvoner** [comment]
@Chriscbr I thought you were talking about the docs link in our site header. My mistake. Totally agree!
@dannac2 / @ShaiBer can you take it with whoever handles our site?
