### ISSUE TITLE
Preflight VM is not ready to bring 3rd party libraries

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1148]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

See discussion [here](https://github.com/winglang/wing/pull/1144#discussion_r1068782140).

### I expected this:

The preflight VM should be more isolated and allow brining 3rd party libs.

### Instead, this happened:

The sdk is assumed to be already required by the outer environment, and resolving inside the VM happens relative to the temporary preflight directory.

### Component:

SDK

**Comment by ekeren** [comment]
@Chriscbr is this related to bring jsii?

**Comment by Chriscbr** [comment]
I'm having trouble understanding this issue so I'm not sure. @eladb @MarkMcCulloh can you add any more context?

Is this resolved by the `preflightRequire` code I added here?

https://github.com/winglang/wing/blob/e7551dcda97eab78aa17a9bc08385ff78d8503fe/apps/wing/src/commands/compile.ts#L103-L110

**Comment by staycoolcall911** [comment]
@eladb - do you know what's the status of this issue? And if it's still relevant - is this p1?

**Comment by eladb** [comment]
we can close
