### ISSUE TITLE
Improve auto updater

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#1151]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

Improve Console auto-updater.

Show a notification during and after an update has been downloaded.

We should display a changelog with the changes of the latest versions.

### Use Cases

Downloading an update can take several minutes, depending on the internet connection. 
Currently, the Console doesn't have any progress status/notification during the download of the update. This can lead to not upgrading the Console and trying to download the new version many times if the console doesn't stay open long enough.

### Component

Wing Console

**Comment by ainvoner** [comment]
1. show app update status at the  footer bar
2. show download progress bar
3. once installer is ready, allow the user to click on a button to restart and install the new version
4. if user tries to exit the app during download, display a warning that download is in progress
