### ISSUE TITLE
update console EULA after adding analytics

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#1159]
related to https://github.com/winglang/console/pull/276

**Comment by ainvoner** [comment]
@ShaiBer FYI

**Comment by skyrpex** [comment]
Do we need an EULA now that the Console is a local dev server? @ainvoner @ShaiBer

**Comment by ShaiBer** [comment]
We need a privacy policy which we don't have right?
Who knows exactly what data we collect? @ekeren , @ainvoner ?
If we have a final list, we should send it to the lawyers so they create a privacy policy and add a link to it in the EULA

**Comment by ekeren** [comment]
@ShaiBer , can we close?

**Comment by ShaiBer** [comment]
yes
