### ISSUE TITLE
`wing compile` output for files inside non-existent folders is not informative

### ISSUE THREAD

**Issue by guywaldman** [winglang/wing#1193]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

Ran from the repo root directory:

```sh
wing compile --target tf-aws non-existent-folder/non-existent-file.w
```

Received t

### I expected this:

This output:

```
Compilation failed with 1 errors
Error | Error reading source file: non-existent-folder/non-existent-file.w: Os { code: 44, kind: NotFound, message: "No such file or directory" }
```

> **Note**: This is the output received if the file is in an _existent_ folder. e.g., running:
> ```sh
>  wing compile --target tf-aws non-existent-folder/non-existent-file.w
>  ```

### Instead, this happened:

Received this output:

```
node:wasi:79
    const wrap = new _WASI(args, env, preopens, stdio);
                 ^

Error: UVWASI_ENOENT, uvwasi_init
    at new WASI (node:wasi:79:18)
    at Command.<anonymous> (/usr/local/lib/node_modules/winglang/dist/commands/compile.js:105:28)
    at step (/usr/local/lib/node_modules/winglang/dist/commands/compile.js:46:23)
    at Object.next (/usr/local/lib/node_modules/winglang/dist/commands/compile.js:27:53)
    at fulfilled (/usr/local/lib/node_modules/winglang/dist/commands/compile.js:18:58) {
  errno: 44,
  code: 'UVWASI_ENOENT',
  syscall: 'uvwasi_init'
}

Node.js v18.13.0
```

### Component:

Compiler, Other

### Wing Version:

0.4.109

### Node.js Version:

v18.13.0

### Platform(s):

MacOS

**Comment by Chriscbr** [comment]
Hey @guywaldman, thanks for reporting the bug - I'm able to reproduce it as well. The expected output you proposed makes sense to me. Contributions are welcome!

I think we need to pre-check for non-existent files before invoking the webassembly: https://github.com/winglang/wing/blob/main/apps/wing/src/commands/compile.ts
