### ISSUE TITLE
support dark and light theme in the console

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#1235]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

Add the ability to toggle between a light and dark theme in the console.
After a user selects a theme, persist it.

### Use Cases

As a user who likes dark theme for dev tools and environments, I would like to be able to switch between modes.
Once I chose my favorite theme mode, I would like the console to open in this mode until I'll change it again.

### Component

Wing Console

**Comment by ekeren** [comment]
I would simply add this to the View top toolbar and while I am on it, lets remove "Toggle Developer Tools"


![Image](https://user-images.githubusercontent.com/1727147/233008935-9463c479-32de-4ad5-ba7a-8f22cae07635.png)

**Comment by ainvoner** [comment]
see https://github.com/winglang/wing/issues/2062
