### ISSUE TITLE
Allow referencing immutable property values from inflight context

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1251]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

It is now possible to reference immutable ***preflight*** properties of any resource/construct from inflight context.

For example:

```js
bring cloud;
bring "aws-cdk" as aws;

let cdk_bucket = new aws.s3.Bucket();
let wing_bucket = new cloud.Bucket();
let arr = [1,2,3,4];

let handler = inflight () => {
  print(cdk_bucket.bucket_arn);
  print(wing_bucket.is_public);
  print(arr.length);
};
```

Both `bucket_arn` and `is_public` are *preflight properties* of their respective constructs. But since they are immutable strings, they can be referenced within an inflight context.

Bear in mind that `bucket_arn` is not only an immutable string but also a CDK attribute (which resolves only during deployment). This is seamlessly handled by the Wing compiler for your satisfaction and joy.

The property `length` is an immutable property of an immutable array. In this case, the compiler will only capture the number `4` instead of the entire array.

> ☝️ this is not the current behavior.

### Use Cases

It is common to need to need to use attributes of resources/constructs within inflight context.

### Implementation Notes

I think this should be implemented to also cover something like this:

```js
bring cloud;

let my_array = ["hello", "world"];

new cloud.Function(inflight (_: str) => { 
  assert(my_array.length == 2); 
}) as "test";
```

In the above example, I would expect Wing to capture `my_array.length` (with the fixed value 2) instead of capturing the entire array. This is a kick ass optimization.

### Component

Compiler, SDK

**Comment by Chriscbr** [comment]
I feel like we might already get this for free, since these are nearly equivalent:

```js
resource A {
  field: str;
  init() { this.field = "hey" }
}
let a = new A();
inflight () => {
  print(a.field);
}
```

```js
struct A {
  field: str;
}
let a = A { field: "hey" }
inflight () => {
  print(a.field);
}
```

I think the one exception would be the cases where the values are CDKTF tokens etc.

**Comment by ekeren** [comment]
I am able to capture **preflight**  properties of a user resource. 
This works:

```ts (wing)
bring cloud;

resource A {
  field: str;
  init() { this.field = "hey"; }
  inflight f(): str{
    return "hello";
  }
}

let a = new A();
new cloud.Function(inflight () => {
 assert("hello" == a.f());
 assert("hey" == a.field);
}) as "test";
```

**Comment by ekeren** [comment]
Opened a related bug https://github.com/winglang/wing/issues/1559

**Comment by ekeren** [comment]
There is a comment in this ticket of an optimization option for capturing the `length` value of the immutable array... 

But it is not the essence of this issue, closing this one
