### ISSUE TITLE
Use versions and aliases to prevent downtime upon deployment

### ISSUE THREAD

**Issue by schosterbarak** [winglang/wing#1253]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

When deploying a lambda there is some down time.
There are various approaches to solving it: 
https://www.aws-community-day.de/slides/Continuous%20deployment%20of%20Serverless%20resources.pdf |https://docs.aws.amazon.com/cdk/api/v1/docs/aws-lambda-readme.html#versions

### Use Cases

minimize deployment downtime

### Component

Compiler, SDK

**Comment by staycoolcall911** [comment]
Thanks @schosterbarak, great use case. 

@eladb, @hasanaburayyan - is that something we may be able to solve with a [wing plugin](https://github.com/winglang/wing/pull/1218)? If so, then maybe we can just add this use case to the RFC and close the issue.

**Comment by eladb** [comment]
I think we can bake this behavior by default to the `Function` implementation for `tf-aws`.

**Comment by eladb** [comment]
Yes, definitely not P2.

(also, you can make as good-first-issue)

**Comment by ShaiBer** [comment]
> Can I try solving this? 🙌🏻

Sure @raywonkari , I assigned you to it now, so no one will try to work on it in parallel.
Please let us know if you need any help.

**Comment by staycoolcall911** [comment]
Already supported - closing
