### ISSUE TITLE
Generating SDK API reference docs is very slow

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1270]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

In the `libs/wingsdk` directory:
```
npm i
npm run compile
time npm run docgen
...
npm run docgen  22.94s user 28.80s system 163% cpu 31.596 total
```

(run while working on a pull request where I was adding a new cloud target)

### I expected this:

Generating docs within a few seconds

### Instead, this happened:

It takes 20-30 seconds to generate docs. (On a M1 Macbook Pro). It might take longer in CI/CD.

### Component:

SDK, Documentation

### Anything else?

My guess is that jsii-docgen is probably trying to load all of the assemblies for all of the CDKTF provider dependencies we're using (`@cdktf/provider-aws`, `@cdktf/provider-azure`, etc.) -- even though we don't actually reference any of their APIs in our public API AFAIK. We should find a way so that jsii-docgen (or jsii-reflect) just lazy-loads dependencies when they're requested.

Alternatively, if that's too hard, we could try something hacky where we remove these dependencies from the .jsii file so that no tools try to load them. :-)

**Comment by staycoolcall911** [comment]
I rechecked this issue and the problem remains (though this is p3):
```sh
npm run docgen  28.04s user 41.96s system 104% cpu 1:06.71 total
```

**Comment by Chriscbr** [comment]
Addressed this in https://github.com/winglang/wing/pull/2809 - generating the API reference should no longer be as severe of a bottleneck for SDK builds
