### ISSUE TITLE
Filter out traces that are triggered by console

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1275]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

Starting today, the Wing Console will now automatically filter out traces produced by internal API calls.

The Wing Console interacts with the Wing Simulator in order to produce information in the UI, such as the number of files in a `Bucket`, or the value of a `Counter`, etc. However, these inflight method calls produce traces that are unrelated to events produced by the user or triggered by entrypoints of your Wing application (such as the traces produced by calling `invoke` on a `cloud.Function` or started by a `cloud.Schedule` event). In the traces panel, you will now see all of these traces are automatically hidden, and by clicking on a checkbox in the UI, they will be included (but annotated as "console-internal").

### Use Cases

As a user, I would only like to see logs and traces related to triggers started by the application (e.g. timers) or by myself, and not those due to console implementation details.

### Implementation Notes

We probably need to add some kind of extra annotations/context to the current trace data model in the SDK to support this.

### Component

SDK, Wing Console

**Comment by Chriscbr** [comment]
cc @skyrpex @polamoros @ainvoner

**Comment by ainvoner** [comment]
in addition:
1. remove console application logs (log file)
2. remove compiler errors (dedicated compiler error views)
3. remove SDK Simulator internal logs (log file)

**Comment by skyrpex** [comment]
Correct me if I'm wrong: first of all, we should submit a PR to the Simulator so it annotates some traces with a "console-internal". Then, we filter them out from the Console log, right?

**Comment by polamoros** [comment]
Here is a use case I'm thinking about:

Ex: 
_console_
`
const client = simulator.getResource(resourcePath) as ICounterClient;

// on-demand, this peek should generate traces as console-internal
const response = await client.peek();
`

I'm thinking about having some method to set a custom trace type globally:

Ex:
_console_
`
const client = simulator.getResource(resourcePath) as ICounterClient;

simulator->setCustomTraceType('console-internal'); // or better name
const response = await client.peek();
simulator->removeCustomTraceType();
`

any better approach?

**Comment by Chriscbr** [comment]
I think the trace may need to be set while initiating the inflight operation (at the time `client.peek()` is called) and not as a piece of global state in the simulator, since inflight methods are async, and console-initiated operations may get interleaved with user-initiated operations. hypothetical example:

```
1. user clicks "invoke" on a function in the console window
2. console calls function.invoke() [label=user]
3. user clicks a bucket in the console window
4. console calls bucket.list() in order to show objects [label=internal]
5. function from (1) calls bucket.put() [label=user]
6. bucket.list() finishes reading from file system and returns list [label=internal]
7. console renders objects on bucket page
8. function from (1) returns [label=user]
```

**Comment by skyrpex** [comment]
What kind of interface would you use to accomplish it? I think `simulator.getResource` is a good candidate to pass some parameters such as tracing labels... 

```ts
const bucket = simulator.getResource("my-bucket", { tracing: { label: "user" } });
await bucket.put("a", "b");
```

**Comment by polamoros** [comment]
> What kind of interface would you use to accomplish it? I think `simulator.getResource` is a good candidate to pass some parameters such as tracing labels...
> 
> ```ts
> const bucket = simulator.getResource("my-bucket", { tracing: { label: "user" } });
> await bucket.put("a", "b");
> ```

I like this solution, but I don't see how we pass this tracing metadata to the simulator easily..
@Chriscbr  what do you think?

**Comment by Chriscbr** [comment]
That API sounds fine to me 👍

**Comment by polamoros** [comment]
From the `Tracing discussion` meeting:

We'll set all logs to verbose except the `prints` done by the user. 

That can be done easily due `prints` are logged with the TraceType "log" ([here](https://github.com/winglang/wing/blob/main/libs/wingsdk/src/target-sim/logger.inflight.ts#L44))
