### ISSUE TITLE
Custom Wing targets and resource injection using plugins

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1365]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

Remember all these Wing targets you used to love? The ones behind the `--target` switch of `wing`?

Don't worry, they are not going anyway!

Not only they are not going away, now, anyone can create and share targets through [Wing Plugins](#1218). In fact, you can completely customize how resources are created in Wing and inject an alternative instance.

So how does this work?

Plugins can now implement a `newResource` hook:

```ts
newResource(type: string, scope: Construct, id: string, ...args: any[]): Construct | undefined;
```

This hook gets called whenever a new resources is defined (`new Foo()`) in preflight code. The hook can use the resource fully qualified wing `type`, construct `scope`, user-defined `id` and the list of arguments passed to the initializer (constructor) to produce a new instance of this resource. 

(if `undefined` is returned, the next plugin can give this an attempt, or fall through to an error).

So, for example, here is how the `tf-aws` target is implemented:

```js
const wing = require('@winglang/sdk`);
const tfaws = wing.tfaws;
const cloud = wing.cloud;

exports.newResource = function(type, scope, id, ...args) {
  switch (type) {
    case cloud.BUCKET_TYPE:   return new tfaws.Bucket(scope, id, args[0]);
    case cloud.FUNCTION_TYPE: return new tfaws.Function(scope, id, args[0], args[1]);
    case cloud.QUEUE_TYPE:    return new tfaws.Queue(scope, id, args[0]);
    case cloud.LOGGER_TYPE:   return new tfaws.Logger(scope, id);
    case cloud.COUNTER_TYPE:  return new tfaws.Counter(scope, id, args[0]);
    case cloud.TOPIC_TYPE:    return new tfaws.Topic(scope, id, args[0]);
  }

  return undefined;
};
```

This means that, for example, specifying a `--target tf-gcp` is the same as adding `--plugin "@winglang/sdk.targets.tfgcp"` as the last switch.

```sh
wing compile --target tf-gcp
# same as:
wing compile --plugin "@winglang/sdk.targets.tfgcp"
```

Since returning `undefined` indicates "pass", you can use this to implement cool things like `dropbox-bucket.js`:

```js
const { DropBoxBucket } = require('@winglang/dropbox');

exports.newResource = (type, scope, id, ...args) {
  if (type === "cloud.Bucket") {
    return new DropBoxBucket(scope, id, ...args);
  }

  return undefined;
};
```

So now, when I run:

```sh
wing compile -target tf-aws -p ./dropbox-bucket.js
```

It will fall back to using tf-aws after trying to resolve every new resource with our plugin.

### Use Cases

Listed above

### Implementation Notes

Initially, let's support polycon-based resources. This should be easy to implement (basically invoke the plugins instead of the polycons factory).

But... I think that eventually we should get rid of polycons altogether and basically implement this in the preflight jsification.

This Wing code:

```js
bring something;

let bang = new something.Dramping();
```

Should be jsified to:

```js
const bang = this.node.root.newResource("something.Dramping", this, "Dramping");
```

Where `newResource` is implement at the global `App` level and delegates to the plugins... Something like that.

**Comment by eladb** [comment]
@Chriscbr @MarkMcCulloh any objections if I picked this up? Any objections about the design?

Basically my plan is to change the compiler code so that instead of emitting `new Foo(args...)` it will emit something like `this.node.root.new(Foo, args...)`. This will give the root an opportunity to inject a different object instead of the default one.

Then, we could basically:

1. Remove the dependency on polycons.
2. Merge `XxxBase` classes with `Xxx` and turn `Xxx` into `abstract`.

I still need to think how to identify the type. I am thinking go with FQNs all the way (basically use JSII FQNs as a universal type identifier for wing).

I have prototyped this and it generally works, but wanted to get some inputs from y'all before moving further.

**Comment by MarkMcCulloh** [comment]
Is there not a chicken-and-egg problem with `this.node.root.new`? Like, is the root construct treated/created differently from others?

What if we created a `Wing` js global that handles Construct creation and the plugin functionality? That way no constructs a special. Normally globals kinda suck, but the wing toolchain itself effectively contains a JS runtime so it's well within our control.

I'm overall in favor of the move away from what polycons look like now.

**Comment by eladb** [comment]
> Is there not a chicken-and-egg problem with `this.node.root.new`? Like, is the root construct treated/created differently from others?

The app root is implicitly created by the SDK/compiler so I don't think there's a chicken-and-egg issue.


> What if we created a `Wing` js global that handles Polycon-esque Construct creation and the plugin functionality? That way no constructs a special. Normally globals kinda suck, but the wing toolchain itself effectively contains a JS runtime so it's well within our control.
> 

I am trying to avoid any global facilities.

> I'm overall in favor of the move away from what polycons look like now.

Cool beans!

**Comment by MarkMcCulloh** [comment]
> I am trying to avoid any global facilities.

The root app is effectively being used as a global (available almost everywhere, singleton, mutable even). I understand it's part of the tree (which technically means it doesn't have to be a singleton) but that's the only difference. 
And with this change to use plugins more heavily, I don't think that difference matters much.

Regardless, I think the change described here is worth doing and maybe I just need to see the implementation to squash my concerns.

**Comment by eladb** [comment]
> The root app is effectively being used as a global 

Indeed, but it is still scoped within a tree. So, for example, when we run tests that include multiple app instances, the trees are isolated from each other. If we used globals, we would need to isolate apps using VMs or something similar.

**Comment by staycoolcall911** [comment]
@eladb - is that issue done?

**Comment by eladb** [comment]
No. Only the infrastructure (removing Polycons). 

But I don't think we need it for beta.

**Comment by eladb** [comment]
No. Only the infrastructure (removing Polycons). 

But I don't think we need it for beta.

**Comment by staycoolcall911** [comment]
Great, changing it to p2.

**Comment by staycoolcall911** [comment]
Following the introduction of #1418 and #3620 I believe this issue can be closed. @eladb reopen if you disagree
