### ISSUE TITLE
page not found when clicking on some links in winglang docs

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#1366]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

clicked on the following links and got "page not found":
- [ ] in https://docs.winglang.io/contributors/rfcs/overview#rfc-process clicked on [CONTRIBUTING.md](https://docs.winglang.io/contributors/06-contributors/handbook.md#what-is-an-rfc).
- [ ] in https://docs.winglang.io/contributors/rfcs/overview clicked on https://github.com/winglang/wing/blob/main/docs/05-rfcs/2022-06-14-polycons.md
- [ ] in https://docs.winglang.io/contributors/rfcs/stories/story-04#notes clicked on [Wing SDK](https://docs.winglang.io/contributors/rfcs/stories/github.com/monadahq/wingsdk)
- [ ] in https://docs.winglang.io/contributors/rfcs/stories/story-04#notes clicked on [monadahq/winglang](https://docs.winglang.io/contributors/rfcs/stories/github.com/monadahq/winglang/)
- [ ] in [portal.aws.amazon.com/billing/signup](https://docs.winglang.io/contributors/rfcs/stories/story-04#aws-account-and-credentials) clicked on [AWS account](https://docs.winglang.io/contributors/rfcs/stories/portal.aws.amazon.com/billing/signup)

### I expected this:

see the links content

### Instead, this happened:

page not found

### Component:

Documentation

### Wing Version:

0.4.154

### Platform(s):

MacOS

**Comment by ainvoner** [comment]
@ekeren @ShaiBer how do you want to handle this one?

**Comment by ekeren** [comment]
I'll assign to myself and figure this out

**Comment by staycoolcall911** [comment]
@ekeren - can you please see if we can close this issue? From a quick look it doesn't seem to be relevant anymore

**Comment by ekeren** [comment]
Issue is resovled
