### ISSUE TITLE
Compile and test the todo app (story 10) on Azure

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#1376]
We would like to check that the [todo app in story 10](https://docs.winglang.io/contributors/rfcs/stories/story-10) successfully compiles to tf-azure and see that it deploys successfully.

We will need to remove the counter from the story and use an alternative (uuid?).

**Comment by Chriscbr** [comment]
Implementing counter for Azure could be another good first issue BTW. @revitalbarletz also mentioned she wants to implement an Azure resource, this could be a good candidate (it might be implemented with Azure CosmosDB?)

**Comment by staycoolcall911** [comment]
Sounds good @Chriscbr - I marked it as a good first issue.
[cloud.Counter - Azure implementation#629](https://github.com/winglang/wing/issues/629)

**Comment by staycoolcall911** [comment]
Closing - we decided Azure is out of scope for beta, so this issue is too specific to keep
