### ISSUE TITLE
cloud.Queue.add_consumer()

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#1384]
https://docs.winglang.io/reference/wingsdk-spec#queue

**Comment by flyingImer** [comment]
how is this different from `on_message`? seems to me that either `on_message` needs to be in the spec or the spec to rename `add_consumer`

**Comment by Chriscbr** [comment]
@flyingImer You're right, this issue just requires a simple rename in the SDK. 🙂 We want to reserve the `on_xxx` method name pattern in the SDK for "fire-and-forget" event patterns, like `topic.on_publish` or `bucket.on_upload`, where any number of listeners can receive events without affecting others.

**Comment by flyingImer** [comment]
@Chriscbr sanity check: `add_consumer` is the desired method name for the `on_message` functionality, so the action item is to rename `on_message` to `add_consumer` in SDK to reflect the spec, correct? if so, please assign it to me, lets see how wild it can be 😆

**Comment by Chriscbr** [comment]
You got it

**Comment by staycoolcall911** [comment]
Closed by #2013
