### ISSUE TITLE
Wing Console showing multiple relationships to same object

### ISSUE THREAD

**Issue by perpil** [winglang/wing#1399]
### Community Note

The relationships section in the wing console lists the relationship multiple times.  In this case, you see HelloWingBucket 4 times:

<img width="315" alt="image" src="https://user-images.githubusercontent.com/97474956/215951488-ec79e7f0-66d9-44e4-b065-36fbe2bff5b3.png">

If it had a qualifier like (put/get/delete/list) it would be less confusing why it is listed multiple times.

### Feature Spec

Display reason for relationship between two objects to remove ambiguity in Wing Console

### Use Cases

Confusion as to why you see multiple relationships to the same thing when there is really only one with multiple permissions.

### Implementation Notes

There are a couple of ways to solve this:

1. Add something to the display (put/get/delete/list) like how it is shown in the root:

<img width="235" alt="image" src="https://user-images.githubusercontent.com/97474956/215952555-a866a486-9b20-4b0b-ad0d-2a3d63fe75e8.png">

2. Same as 1, but add it to the tooltip for the relationship
3. Don't show a relationship for each permission, only show 1

### Component

Wing Console

**Comment by ainvoner** [comment]
@perpil totally agree! we are working on a new representation of resources relationships. We believe it will make more sense :)
thanks for your feedback, it is very important for us to know if our chosen visual representations makes sense
