### ISSUE TITLE
Run all tests in monorepo with single command

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1411]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

Starting today, when you run `npm run test` at the root of the monorepo, it will run tests for all projects in the monorepo. This command will update all test snapshots for you automatically.

### Use Cases

Simplifying contributor instructions

### Implementation Notes

Can be implemented with https://nx.dev/packages/nx/documents/run-many

### Component

Contributor Experience

**Comment by staycoolcall911** [comment]
Need to update the contributor handbook when this task is done
