### ISSUE TITLE
invoke cloud.bucket inflight methods

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#1419]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

click a cloud.bucket terminal resource will open a modal which will enable the user to invoke its' inflight methods.
The modal looks like a file explorer and list all existing files in the bucket.
The user can upload, download and delete files from the bucket.

### Use Cases

See all files in a bucket, upload new files, download files and deleted existing files

### Component

Wing Console

**Comment by polamoros** [comment]
[Guts design](https://app.clickup.com/t/860ptkejm)
