### ISSUE TITLE
invoke cloud.counter inflight methods

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#1422]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

Users can now see the counter terminal resource value, and also can increment or decrement its' current value in this new simple modal.

### Use Cases

see the counter value and execute its' inflight methods

### Component

Wing Console

**Comment by polamoros** [comment]
<img width="383" alt="image" src="https://user-images.githubusercontent.com/5547636/220306414-52d5e18d-15c3-4269-aa07-c9583c8b4d8f.png">
https://app.clickup.com/t/860ptkejm

**Comment by polamoros** [comment]
https://dribbble.com/shots/14964128-Stepper-UI-design-templates-Figma-Material-X-kit
