### ISSUE TITLE
[Tracking Issue] "readme" documentation for each SDK resource

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1438]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

The Wing docsite now includes a documentation topic for each SDK resource (we call it the "readme" of the resource). It is a human-written document that describes the resource and how it behaves, as well as target-specific details such as #1405.

### Use Cases

Give user detailed information about how to use resources and how they behave.

### Implementation Notes

The proposed implementation is to create an `.md` file next to each file [here](https://github.com/winglang/wing/tree/main/libs/wingsdk/src/cloud) which will include the readme for this resource. For example, `bucket.md`.

Each readme will contain basic information about how to use the resource, and any relevant details about how the resource is implemented on different cloud targets (like AWS, Azure, or the Wing simulator).

### Component

SDK

-----

Issues:

- [x] #2652
- [x] #2653
- [x] #2654
- [x] #2655
- [x] #2656
- [ ] #2657
- [x] #2658
- [x] #2659
- [x] #2660
- [x] #2661
- [x] #2662

**Comment by eladb** [comment]
We need this!

**Comment by ekeren** [comment]
done
