### ISSUE TITLE
Capture permissions: automatically resolve least privileged permissions

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#1449]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

Wing compiler would now automatically generate the least privileged permissions for captured resources.

### Use Cases

See the discussion on #76

### Implementation Notes

We would need to implement basic CFA (control flow analysis) for generating the binding metadata. Compiler error (unless custom binding metadata is provided). At this phase we don’t allow stuff like variable assignments, passing a resource as an argument, returning a resource…

### Component

Compiler

**Comment by eladb** [comment]
This is addressed by https://github.com/winglang/wing/pull/1743
