### ISSUE TITLE
Remove tree.json backwards compatibility introduced in Wing 0.5.0

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1452]
https://github.com/winglang/wing/blob/925951e07ffd58662260a0000a1c604c9efe4a7c/libs/wingsdk/src/target-sim/app.ts#L64-L66

The file format for `.wsim` files was changed so that `tree.json` is now bundled inside the file (and is no longer separate / outside). For backwards compatibility with the current Wing console, we are still generating the `tree.json` file outside as well. We should remove this once the Wing console supports the updated format since it makes the Wing `target/` directory more confusing for users.

**Comment by skyrpex** [comment]
Since the `.wsim` extension is kind of Wing SDK-proprietary, it'd be nice if the simulator API had a method to retrieve the contents of the `tree.json`. Otherwise:

- The console needs to assume the format and the content of `.wsim`
- The console needs to extract the contents, while the simulator is already doing that

**Comment by Chriscbr** [comment]
@skyrpex I agree 👍 Should be straightforward to add

**Comment by skyrpex** [comment]
> @skyrpex I'm imagining an API like this:
> 
> ```ts
> import * as sdk from "@winglang/sdk";
> const sim: Simulator = new sdk.testing.Simulator({ simfile : "./target/hello.wsim"});
> const tree: Tree = sim.tree();
> const content = tree.rawData(); // return the raw JSON
> ```
> 
> This way we can add more APIs to the `Tree` class for querying for constructs and extracting information etc. WDYT?

That'd be wonderful 👍🏻

**Comment by skyrpex** [comment]
Feel free to work on this issue :) 💪🏻
