### ISSUE TITLE
some links are not correctly parsed on the error screen view

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#1465]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

```
bring cloud;

let bucket = new cloud.Bucket();
let queue = new cloud.Queue();

let handler = inflight (message: str): str => {
  bucket.put("hello.txt", "Hello, ${message}!");
  return message;
};

queue.on_message(handle

let counter = new cloud.Counter(initial: 0);
new cloud.Function(inflight (message: str): str => {
  counter.inc();
  return message;
}) as "IncrementCounter

let topic = new cloud.Topic() as "Topi
```

### I expected this:

The link should be parsed correctly.

### Instead, this happened:

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/5547636/217010243-c9c10f02-d255-41f9-b659-4dd04d440d01.png">
<img width="291" alt="image" src="https://user-images.githubusercontent.com/5547636/217010657-14c510d0-fa4b-4c20-a720-8216de03dbf8.png">

### Component:

Wing Console

**Comment by ainvoner** [comment]
https://github.com/winglang/console/pull/293
