### ISSUE TITLE
SymbolEnv should not require a return type

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1486]
There is a data modeling issue in the compiler where every single use of a `SymbolEnv` requires defining a return type, even though not every symbol environment corresponds to a function body etc.

https://github.com/winglang/wing/blob/4087df6abfd3a72295fc88caa80fbe83f7e508ab/libs/wingc/src/type_check/symbol_env.rs#L16-L18

**Comment by staycoolcall911** [comment]
Looks like this TODO was handled. Closing.
