### ISSUE TITLE
Add hidden display property to unwanted resources

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#1493]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

`Code` and `OnMessageHandler` resources are hidden from the Console.

### Use Cases

Now, `Code` and `OnMessageHandler` are visible on the Console.

<img width="769" alt="image" src="https://user-images.githubusercontent.com/5547636/217756369-8f4e2425-278c-43f4-8676-4e8f16939491.png">

### Implementation Notes

Set display.hidden to false for `Code` and `OnMessageHandler` resources.

ex:
```
export abstract class LoggerBase extends Resource {
  public readonly stateful = true;

  constructor(scope: Construct, id: string) {
    super(scope, id);

    this.display.hidden = true;
    this.display.title = "Logger";
    this.display.description = "A cloud logging facility";
  }
...
```

### Component

SDK, Wing Console

**Comment by ainvoner** [comment]
duplication of https://github.com/winglang/wing/issues/1493
