### ISSUE TITLE
console not working with counter.dec and failing to print logs

### ISSUE THREAD

**Issue by flyingImer** [winglang/wing#1504]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

using console from `wing it` for the code below:
```
bring cloud;

let counter = new cloud.Counter(initial: 100);

new cloud.Function(inflight (s: str): str => {
    let peek = counter.peek();
    print("peek: ${peek}");
    let post_inc = counter.inc();
    print("inc: ${post_inc}");
    let post_dec = counter.dec();
    print("dec: ${post_dec}");
    return "gg";
});
```

### I expected this:

cloud.Counter goes back down to `100`
cloud.Function responds:
```
{
  "success": true
}
```
and logs printed:
```
peek: 100
inc: 100
dec: 101
```

### Instead, this happened:

cloud.Counter remains `101`
cloud.Function responds:
```
{
  "success": false,
  "error": {}
}
```
and logs printed:
```
peek: 100
inc: 100
```

### Component:

Wing Console

### Wing Version:

0.5.23

### Node.js Version:

v18.14.0

### Platform(s):

MacOS

### Anything else?

also tried below and `wing test` was happy:
```
bring cloud;

let counter = new cloud.Counter(initial: 100);

new cloud.Function(inflight (s: str): str => {
    let peek = counter.peek();
    print("peek: ${peek}");
    assert(peek == 100);
    let post_inc = counter.inc();
    assert(post_inc == 100);
    print("inc: ${post_inc}");
    let post_dec = counter.dec();
    assert(post_dec == 101);
    print("dec: ${post_dec}");
    return "gg";
}) as "test";
```

@marciocadev helped to verify the Simulator side (from standalone sdk) is all good by interacting directly with counter.dec

@skyrpex suspected, quote: "the simulator (the one bundled in the console) is throwing when reaching counter.dec and it's not being logged"

slack thread for additional context: https://winglang.slack.com/archives/C048QCN2XLJ/p1676005800646669

**Comment by skyrpex** [comment]
Thanks for reporting :)

I can confirm that it works after upgrading the `@winglang/sdk` bundled in the console, but this is still a problem we need to face. Possible solutions to this problem that come to my mind right now:

- Make the Wing CLI bundle the SDK files when using the `sim` target. The Console would still consume a SDK package that provides a basic interface to interact with the `.wsim` file. We can use semantic versioning to check if the Console can run the `.wsim` file.
- Make the Console use the globally installed Wing SDK, if available (the Wing CLI should provide a method to retrieve the path to the SDK package). Using semantic versioning, the Console should be able to verify if it can consume it or not.

**Comment by skyrpex** [comment]
The first option (bundling the necessary SDK files in the `.wsim` file) makes more sense IMO. The compiler bundles a fully working `.wsim` file, and the console just starts it and provides an interface to interact with it.

What do you think, @eladb @ainvoner @Chriscbr?

**Comment by Chriscbr** [comment]
Option 1 will be necessary to support simulated user-defined resources, but option 2 sounds like a good thing to do as well. Maybe it makes sense to view the Wing CLI as the entrypoint of the Wing toolchain -- so just like it exposes the compiler or the language server, exposing the sdk as a library could make sense as well. I'm tempted to suggest starting with that, but curious to hear @eladb's thoughts

**Comment by flyingImer** [comment]
would it be possible for console to identify and use the matching SDK version from some metadata inside `.wsim` by default?

Also, it may be good to have the capability to override with `wing it some.w --WING_SDK=./user/my-lovely-project/node_modules/@winglang/sdk`, for example, I can use a local build one for development as needed
