### ISSUE TITLE
Import individual namespaces and types from jsii libraries

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1516]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

Examples syntaxes (made up):

```js
bring "@cdktf/provider-aws".s3Bucket as s3Bucket;
// new s3bucket.S3Bucket();

bring "@cdktf/provider-aws/lib/s3-bucket" as s3Bucket;
// new s3Bucket.S3Bucket();

bring "@cdktf/provider-aws/lib/s3-bucket".S3Bucket as S3Bucket;
// new S3Bucket();

bring "@cdktf/provider-aws":[s3Bucket.S3Bucket as Bucket];
// new Bucket();

...
```

### Use Cases

- Add a syntax to allow individual namespaces in a jsii library to be brought into the user's code with an alias.
- Add a syntax to allow individual types in a jsii library (at the root namespace, or from a sub-namespace) to be brought into the user's code with an alias.
- Add a syntax to allow individual namespaces or types to be brought into the user's code from a "deep import" (aka "barrel import") like "@cdktf/provider-aws/lib/s3-bucket".

### Implementation Notes

First we will need an amendment to the [Wing Language Spec](https://docs.winglang.io/reference/spec#4-module-system) with the proposed syntax(es)

### Component

Compiler

**Comment by staycoolcall911** [comment]
Duplicates #3352
