### ISSUE TITLE
std.sleep

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1535]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

An inflight utility function named `sleep` is now available in Wing through `std.sleep`. `std.sleep` expects a `duration` as its argument. Example usage:

```js
bring cloud;

new cloud.Function(inflight () => {
  print("Good night...");
  std.sleep(5s);
  print("Ready to rock!");
});
```

`std` is a globally defined variable for accessing standard utility functions. Internally, `std.sleep` desugars into `std.Globals.sleep`, which is a static inflight method on the class `Globals`. (implementation detail)

### Use Cases

Unit/integration tests that require waiting for some operation to be completed

### Implementation Notes

There could be value in having a general purpose rule where any `my_lib.my_method` where `my_lib` is a library or JSII namespace automatically desugars into `my_lib.Globals.my_method` if a `Globals` class exists. But we can also just start with defining a symbol `std` at the root that points to `@winglang/sdk.std.Globals`.

We could also support `sleep` as a preflight method but it would need to be async, and the use case for it is less clear. (P2)

### Component

Language Design, Compiler, SDK

**Comment by MarkMcCulloh** [comment]
Alternative implementation: Add sleep(duration) as a global utility similar to others that currently exist.

I think the method described originally

> std.sleep desugars into std.Globals.sleep, which is a static inflight method on the class Globals

is better, but statics are not implemented yet. When we do implement it, we could move over most of the existing utility methods to `std` at the same time (including `sleep`).

**Comment by revitalbarletz** [comment]
Issue is taken by Matt Johnson, will reassign once joined the repo.

**Comment by Chriscbr** [comment]
Finished in https://github.com/winglang/wing/pull/2906
