### ISSUE TITLE
Methods can't be defined in classes

### ISSUE THREAD

**Issue by guywaldman** [winglang/wing#1536]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

Running `wing compile` on this file:

```
class Base {
  init() { }
  public foo() { }
}
```

### I expected this:

Successful compilation.

### Instead, this happened:

Seems that methods (regular methods, excluding the `init` constructor), with or without access modifiers, can't be compiled (and even crash the LSP server).

Panics with the following error:

```
thread '<unnamed>' panicked at 'Unexpected class element node type function_definition || {Node function_definition (2, 2) - (2, 18)}', libs/wingc/src/parser.rs:365:21
```

### Component:

Compiler

### Wing Version:

0.5.37

### Node.js Version:

v18.13.0

### Platform(s):

MacOS

### Anything else?

Relates to #1123 and #1124

**Comment by staycoolcall911** [comment]
@guywaldman - thank you for bringing this up - we are aware of this issue, here's the TL;DR: 
Classes are currently supported only inflight, so to make progress with #1123 please start with `resource` instead of `class`.
This will also work:
```ts
class Foo {
  init(){}
  inflight bar(){}
}
```

**Comment by staycoolcall911** [comment]
In some more words: 
Our current design assumption is that `resource` is the object oriented tool for preflight and `class` is what we use for inflight.
However, we may want to revisit this assumption once we start dogfooding and writing more wing code, to better understand the use cases of object oriented code in wing.

At the very least, we need to add better compiler errors and documentation if we intend to keep classes inflight only. 

We could decide classes can only be defined inflight, but that will limit the ability to reuse classes in different inflights (scope issue).
One quick way to address this is to keep allowing classes to be defined  in preflight scope, but fix our syntax to indicate classes are only for inflight like this:
```
inflight class Foo {
  init(){}
  bar(){}
}
```
(please note that the `inflight` keyword appears only once on class definition and not on each method definition)

We will keep this issue open, to remind us that we should address this poor developer experience issue and to serve as a place for discussion.

**Comment by staycoolcall911** [comment]
Yes, @flyingImer, I agree. If the team still thinks this assumption holds water, we should update the spec. Let’s see if there are other opinions

**Comment by staycoolcall911** [comment]
@flyingImer, @guywaldman - following up with an update. We have discussed this topic and opened an issue to [Spec the relationship between classes and preflight/inflight scopes ](https://github.com/winglang/wing/issues/1657).

I'm closing this issue for now.
