### ISSUE TITLE
Improve minimum size calculations for the Console Map nodes

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#1543]
The current implementation creates a new React root every time it needs to gather the minimum node sizes, and uses `setTimeout` as a hack to wait for the render to finish.

A proper implementation would render the nodes in an invisible element using the same React root as the rest of the application.

**Comment by ainvoner** [comment]
keep open

**Comment by ainvoner** [comment]
@skyrpex what is the status of this issue?

**Comment by ainvoner** [comment]
not sure it is relevant anymore, @skyrpex if needed, please reopen and remove the `stale` label
