### ISSUE TITLE
Confusing error message when returning a value in a function typed as returning void

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1550]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

```js
// wing
bring cloud;

let func = new cloud.Function(inflight (x: num) => {
  return x + 1;
});
```

### I expected this:

An error saying that the function cannot return a value since func's signature says it returns `void`

(We are assuming Wing doesn't infer function return types for now)

### Instead, this happened:

"Return statement outside of function cannot return a value." (huh? the return statement is inside the function)

### Component:

Compiler

### Wing Version:

0.5.36

### Node.js Version:

18.12.1

### Platform(s):

MacOS

**Comment by yoav-steinberg** [comment]
Here's a simple example that recreates this and shows when the error makes sense and when it doesn't
```wing
return 1; // Return outside of function

let x = () => {
  return 1; // Return value when type is void
};
```
We should probably have a hard coded test for the root scope which produces the current error, and in all other cases produce something like "Unexpected return value from void function".

**Comment by Chriscbr** [comment]
> We should probably have a hard coded test for the root scope which produces the current error, and in all other cases produce something like "Unexpected return value from void function".

Something about scopes having an associated return type feels off to me....
