### ISSUE TITLE
Use npm 9 in our CI/CD

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1553]
This change should not affect how consumers use Wing

**Comment by MarkMcCulloh** [comment]
Explored this issue in https://github.com/winglang/wing/pull/1603 and found that `npm pack` did not include bundled dependencies in the resulting tarball with npm 9, causing missing `@aws-sdk` packages failing during preflight.

**Comment by MarkMcCulloh** [comment]
Closing, moved to pnpm
