### ISSUE TITLE
Inflight initializer

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1567]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

https://docs.winglang.io/reference/spec#33-resources

```
bring cloud;

resource A {
  init() {}
  inflight init () {}
}

let a = new A();
```

### I expected this:

It compiles

### Instead, this happened:

```
Error at hello.w:3:10 | Symbol "init" already defined in this scope
Error at hello.w:8:9 | Expected type to be "A", but got "void" instead
Error at hello.w:8:9 | Expected 1 arguments but got 0 when instantiating "A"
```

### Component:

Compiler

### Wing Version:

0.5.48

### Node.js Version:

18.12.1

### Platform(s):

MacOS

**Comment by staycoolcall911** [comment]
Duplicates #67
