### ISSUE TITLE
Highlight hierarchical edges of the selected node

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#1592]
Currently, only the node edges are highlighted (these edges start or end to the node in question). We also want to highlight the hierarchical edges, which are edges that cross the node in question.

From the [ELK documentation](https://www.eclipse.org/elk/documentation/tooldevelopers/graphdatastructure.html):

![image](https://user-images.githubusercontent.com/1077520/220065631-6b837360-9bdc-4077-a14f-3dc2dc4ea677.png)

**Comment by ainvoner** [comment]
not sure it is relevant anymore. @skyrpex if need to keep open, remove `stale` and reopen
