### ISSUE TITLE
Update contributor list periodically

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1619]
As a daily / weekly job using GitHub actions

**Comment by jakepage91** [comment]
Hey there I was just wondering if using [contrib.rocks](https://contrib.rocks/preview?repo=winglang%2Fwing) might be a more straightforward and easily maintainable solution for keeping an up to date contributors list. 

This is pretty much all thats needed to be added to the README.md file:
```
<a href="https://github.com/winglang/wing/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=winglang/wing" />
</a>
```

**Comment by Chriscbr** [comment]
Neat find @jakepage91 - that sounds like a good option! Pull requests are welcome 👍 

(If we go with that option, we can also remove [these](https://github.com/winglang/wing/blob/dac91c2d78a45862484222f723a2f1f2dc98b6e9/package.json#L15-L17) handful of scripts)

**Comment by jakepage91** [comment]
Sounds good! I just assigned the issue to myself if that's ok. I'll prob have a PR at some stage tomorrow @Chriscbr  👍

**Comment by staycoolcall911** [comment]
Closing, since @jakepage91 handled this in #1773
