### ISSUE TITLE
Get rid of all IPC communications

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#1625]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

To remove our dependency on electron framework, we should get rid of all IPC communications between the main and renderer process, replacing them with WebScockets and HTTP requests.

### Use Cases

decoupling our FE / BE / electron in order to eventually separate the server to an external lib

### Implementation Notes

use ws and http req. (trpc) instead of IPC

### Component

Wing Console

**Comment by skyrpex** [comment]
These are the IPC events that we currently use:

## From the main process to the renderer process

- `trpc.invalidate`
- `trpc.invalidate(path: string)`

- `app.cloudAppState(state: string)` - This one is only setting the state value in the frontend, so we could just use `trpc.invalidate` and a `app.cloudAppState` query

## From the renderer process to the render process

- `open-external-url` - Could use a mutation
