### ISSUE TITLE
Internal server separation

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#1626]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

Create an internally separated server lib

### Use Cases

Our final goal is to publish the server as a private gh package.
I order to achieve this goal and maintain a stable console build, we are taking it step by step.

### Implementation Notes

Move server to a new different directory
Find free port in electron and start the server using this port
Serving the app index.html by the server

### Component

Wing Console

**Comment by skyrpex** [comment]
I think this task shouldn't include the static file serving from the Console Server (just yet). We don't know the requisites for the playground... maybe a React Console component is enough 🤔 

I'm proposing to leave the refactor of serving the static files for later, when we know more.
