### ISSUE TITLE
cloud.Counter.reset()

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#1641]
https://docs.winglang.io/reference/wingsdk-spec#counter

**Comment by YarivLevy81** [comment]
Hi there, first attempt to contribute to wing. 
https://github.com/winglang/wing/pull/1667

**Comment by staycoolcall911** [comment]
@YarivLevy81 thanks so much for picking up this issue. I've assigned it to you. Let me know if you need any help or pointers

**Comment by Chriscbr** [comment]
Implemented in #1667
