### ISSUE TITLE
SDK development watch command does not watch for all changes

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#166]
Since we've divided compilation into two stages in monadahq/wingsdk#103, the watch command does not actually watch everything, such as changes to `*.inflight.ts`, `*.sim.ts`, and `*.test.ts` files.

**Comment by staycoolcall911** [comment]
Keep

**Comment by Chriscbr** [comment]
I don't think this issue applies anymore, since we've updated the TypeScript SDK so it's built with a single compile.
