### ISSUE TITLE
vscode plugin doesn't recognize duration

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#1675]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

![image](https://user-images.githubusercontent.com/1727147/221537458-9e298260-cd57-4413-a573-4c7f555550fa.png)

### I expected this:

duration to be recognized as a type

### Instead, this happened:

I got an error

### Component:

IDE Extension

### Wing Version:

0.5.78

### Platform(s):

MacOS

### Anything else?

![image](https://user-images.githubusercontent.com/1727147/221537793-9fd02a88-d1ca-4457-8b5a-bf241112521c.png)

**Comment by staycoolcall911** [comment]
I believe this was recently fixed by @MarkMcCulloh. Closing
