### ISSUE TITLE
Improve compile times for `bring`-ing large libraries

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1685]
## Problem

When a user tries to import a very large library like `@cdktf/provider-aws`, compiling the Wing program takes at least 20 seconds (with a fast machine).

```
bring "@cdktf/provider-aws" as aws;
```

## Technical details

To try and summarize where the performance bottleneck is, when the compiler sees a `bring` annotation, it currently tries to load all of the type information from that library into Wing's type system. The type information comes in the form of a JSON file that can be 100+ MB in size. There are two stages that take up the most time:

1. Loading the JSON into memory and parsing it into a structured type (handled in `wingii` using the [serde_json](https://docs.rs/serde_json/latest/serde_json/) crate)
2. Importing the structured data as a type in our type system (handled in `wingc`'s `jsii_importer` module) -- this includes logic  like creating symbol environments and so on.

In theory this problem could also affect the SDK since the SDK internally depends on several large cdktf libraries, but since the cdktf types are not referenced in any public APIs, the compiler does not have to import their type information (see #1684).

## Commentary

Like most optimization matters, we Probably Shouldn't Prioritize This until it's necessary. That said, if anyone has ideas for quick wins, all suggestions are welcome. 😀

**Comment by MarkMcCulloh** [comment]
One of many possible improvements I noticed when looking at a flamegraph: 
https://github.com/winglang/wing/blob/548000da1b4ce023346495c6c9bb163fc5115cbf/libs/wingii/src/lib.rs#L128

The clone here is avoidable. We only do it to get ownership of the value from the hashmap, but we don't ever read the value from the hashmap more than once so if we can find a way to do that serialization by removing it from the hashmap or moving it somehow it would greatly improve a hotspot.

**Comment by staycoolcall911** [comment]
@MarkMcCulloh , thanks for addressing this quickly. Do we have information on what was the impact of #1709 on this issue?

**Comment by MarkMcCulloh** [comment]
Partially addressed again in https://github.com/winglang/wing/pull/1982

I think there is still a possibility to get the time down further, but this is a big chunk

**Comment by staycoolcall911** [comment]
No additional low hanging fruits, according to @MarkMcCulloh. Discussed with @eladb and decided to close for now.
