### ISSUE TITLE
Api Gateway resource in Wing Console

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#1687]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

Users can interact with the Api Gateway resource.
TBD

### Use Cases

call endpoints defined in an api gateway

### Implementation Notes

TBD

### Component

Wing Console

**Comment by polamoros** [comment]
Depends on https://github.com/winglang/wing/pull/1852
