### ISSUE TITLE
Redis in Wing Console

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#1688]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

Users are able to interact with a Redis resource

TBD

### Use Cases

local/remote interaction with a Redis resource
TBD

### Implementation Notes

TBD

### Component

Wing Console

**Comment by ainvoner** [comment]
https://redis.io/commands/set/#examples

**Comment by polamoros** [comment]
Related to https://github.com/winglang/wing/pull/1742

**Comment by polamoros** [comment]
Related to https://github.com/winglang/wing/pull/1951

**Comment by polamoros** [comment]
UI examples:

`Redisinsight`
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/5547636/229771495-55dddac7-cfae-448a-949f-e1395442a9a4.png">

Creation of different types of keys
<img width="717" alt="image" src="https://user-images.githubusercontent.com/5547636/229771845-5da8f8ea-745e-4990-ba70-fe6b9aa905f5.png">

List of keys with filtering
<img width="712" alt="image" src="https://user-images.githubusercontent.com/5547636/229772015-4f6948f4-38b2-406b-a786-958a60ba93fd.png">


View values
<img width="708" alt="image" src="https://user-images.githubusercontent.com/5547636/229771943-5e8bc27b-b8f7-4923-bebb-7c931e66c7d6.png">

CLI
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/5547636/229772184-be54a31c-8a70-4a51-9c99-9348aaa42c93.png">
