### ISSUE TITLE
Support duration in `json`

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#1689]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

```ts
let task = Json {
   title: "this is a task",
   estimation: 2d
};
```

### Use Cases

[story 15](https://github.com/winglang/wing/blob/ekeren/task-list-with-api-and-db/docs/06-contributors/999-rfcs/000-stories/story-15.md)

### Component

Compiler

**Comment by Chriscbr** [comment]
Discussed this a little bit offline with @hasanaburayyan -- some options might be:
- come up with a custom serialization strategy (where a duration expression gets serialized into a special format of object, that Wing knows how to deserialize back into a duration value)
- leave this unsupported for now (require users to call `duration.seconds` or `duration.minutes` etc.)

**Comment by MarkMcCulloh** [comment]
I think leaving it unsupported for now makes sense because it makes the resulting JSON content ambiguous to the average user

**Comment by staycoolcall911** [comment]
I think you are correct. @ekeren - do you think it makes sense to remove this from the current sprint?

**Comment by ekeren** [comment]
Should we remove it from the P1 list?

**Comment by staycoolcall911** [comment]
We don't plan to support this
