### ISSUE TITLE
Create durations from numbers

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1695]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

Wing now lets you create `duration` values from a `num` through `Duration.from_seconds`, `Duration.from_minutes`, and `Duration.from_hours`:

```js
// wing
let x = 2m; // type: duration
let y = x.seconds; // type: num
let z = Duration.from_seconds(y); // type: duration
```

### Use Cases

Taking information from external data sources (like foreign HTTP APIs) and converting it into wing types for doing calculations or storing in well-typed structs etc.

### Implementation Notes

These methods exist on the `Duration` class already but don't seem to be available in the global namespace. Could be related to how we import the SDK's `std` namespace by default into all Wing programs.

### Component

Compiler

**Comment by staycoolcall911** [comment]
Implementation note: I believe we simply need to declare these methods on the [std library object](https://github.com/winglang/wing/blob/main/libs/wingsdk/src/std/duration.ts).

**Comment by staycoolcall911** [comment]
This is already done.
