### ISSUE TITLE
RFC: schedule days-of-week

### ISSUE THREAD

**Issue by marciocadev** [winglang/wing#1706]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

AWS Cron is implemented from Quartz Cron, where days of the week are numbered from 1 (Sunday) to 7 (Saturday), and it is recommended to use SUN-SAT.

### Use Cases

Other clouds may use different implementations. I think sticking with Unix Cron is the best way to create a standard across different clouds.

### Implementation Notes

We would need to adjust the AWS cron string to ensure that the day of the week starts from 0 and does not use SUN-SAT.

### Component

SDK

**Comment by staycoolcall911** [comment]
Great catch @marciocadev - I like your idea, but interested to see if others have more ideas - perhaps we should support multiple cron formats.
