### ISSUE TITLE
Add information about origin of the trace

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#1713]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

I have information inside the trace to distinguish what was the calling method that generated it.

### Use Cases

As a Console developer, I need to know who generated a given Trace to be able to refetch some queries when certain things happen.

Ex:
```
queue.push("Hello world");
const size = queue.approxSize(); // returns 1
```

After 100ms message is processed by processMessages(), and generates the following Trace
```
{
  type: 'resource',
  data: {
    message: 'Sending messages (messages=["test"], subscriber=sim-2).'
  },
  sourcePath: 'root/cloud.Queue',
  sourceType: 'wingsdk.cloud.Queue',
  timestamp: '2023-03-03T10:42:21.390Z'
}
```

When the Console receives this Trace, the `approxSize` should be refetched.
The only thing we can do to filter this log from others is to use the "message".

### Implementation Notes

```
{
  type: 'resource',
  data: {
    message: 'Push (message=test).',
    status: 'success',
    result: undefined
  },
  sourcePath: 'root/cloud.Queue',
  sourceType: 'wingsdk.cloud.Queue',
  timestamp: '2023-03-03T10:42:21.384Z',
  
 // New key: (key TBD)
  method: 'push',
}
```

### Component

SDK

**Comment by Chriscbr** [comment]
Related to #974 and #833
