### ISSUE TITLE
Wing tests output are omitted when running in a browser

### ISSUE THREAD

**Issue by eladcon** [winglang/wing#1714]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

I was running tests with the wing CLI inside a [Webcontainer](https://webcontainers.io/), specifically:

`wing test test.w` 

where `test.w` is:

```ts
bring cloud;

let b = new cloud.Bucket();

new cloud.Function(inflight (_: str) => {
  assert(b.list().length == 0);
  b.put("hello.txt", "world");
  assert(b.list().length == 1);
}) as "test:put";
```

### I expected this:

Wing CLI outputting the results of the test

### Instead, this happened:

There was no output from the CLI process, although its exit code is accurately indicating success/failure.

### Component:

CLI

### Anything else?

I believe the problem is with the inflight function code that overrides the `console.log`. e.g.

```ts
console.log = (...args) => $logger.print(...args);
exports.handler = async function(event) {
  return await new (function() {
    return class Handler {
      constructor(clients) {
        for (const [name, client] of Object.entries(clients)) {
          this[name] = client;
        }
      }
      async handle() {
        while (true) {
        }
        ;
      }
    };
  }())({}).handle(event);
};
```

Because this code is running in a browser, and specifically in the context of `eval`, writing to `console.log` is overriding the original `console.log` function as well. Probably need to restore the original function once the function ends.

**Comment by staycoolcall911** [comment]
@eladcon - this seems to be already done, please reopen if I'm wrong.
