### ISSUE TITLE
`Json` type comparison order matters

### ISSUE THREAD

**Issue by yoav-steinberg** [winglang/wing#1717]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

I used wingc to compile this
`cargo run --example compile ../../tmp/tst.w`
```wing
// tst.w
assert(1 == Json 1);
assert(Json 1 == 1);
```

### I expected this:

to compile

### Instead, this happened:

```
Compilation failed with 1 errors
Error at ../../tmp/tst.w:1:8 | Expected type to be "num", but got "Json" instead
```

### Component:

Compiler

### Anything else?

This is due to the fact that comparison type checking is performed by checking if the right expression (`Json 1`) is a subtype of the left expression (`1`). Currently all types a defined as subtypes of `Json` but `Json` itself isn't a subtype of all types. This is why line 2 passes type checking but line 1 fails.

I think basing json type checking on "subtypes" is wrong. I don't think we need to treat all types as subtypes of json but instead implement the following logic:
1) On *assignment* the wing type system *implicitly* converts primitive types to json if the target is a json type:
```wing
let x: Json = 1; // We implicitly convert the primitive 1 to a `Json 1` on assignment.
let s = "hello"; // Primitive string
let y = Json {a: s}; // We implicitly convert the primitive `s` of type `str` to `Json` because of the assignment into the literal
(arg: Json) => { print("${arg} }("hello"); // We implicitly convert the primitive string `"hello"` because it's being assigned into a `Json` argument
```
2) On comparison we require an explicit type conversion:
```wing
assert(JSON.from_num(1) == Json 1);
```

**Comment by ekeren** [comment]
> I don't think we need to treat all types as subtypes of json

💯

**Comment by staycoolcall911** [comment]
We have decided to do:
1. Add implicit casting as Yoav suggested.
2. Fix our implementation for equality check to compare types and not regard subtype as equal to its parent type (so e.g. Json 1 does not equal 1).

**Comment by hasanaburayyan** [comment]
Since this issue was open we have made 2 significant changes.
1. The subtyping issue is gone
2. Inference magic

So actually the ordering comparison order no longer matters. @staycoolcall911 I think we can close the issue unless Im missing something

**Comment by staycoolcall911** [comment]
You're correct. Closing.
