### ISSUE TITLE
Primitives and containers

### ISSUE THREAD

**Issue by eladb** [winglang/wing#172]
We need a mechanism for implementing APIs for primitives and collection types in wing:

```ts
let my_list = MutArray<str>;
my_list.add("bam");

// or
let n = sizeof("hello");
```

The question is how do we implement the `mut_list` type and it's APIs, or `str`, `num`, `list`, etc.

Can we come up with a way that will allow us to implement this in the compiler's "jsify" phase and implement it as a "pseudo api" layer on top of javascript arrays?

Is it part of our sdk or part of the compiler or some combination thereof?

@Chriscbr @yoav-steinberg

**Comment by MarkMcCulloh** [comment]
Foundations of this resolved in https://github.com/winglang/wing/pull/1045

**Comment by eladb** [comment]
@staycoolcall911 @MarkMcCulloh should we close this? (following our discussion today). We need *some* tracking issue for full support for primitives and container types and their entire APIs. It could be a new issue or we can reopen this as the top-level tracking issue.

**Comment by staycoolcall911** [comment]
I'd rather leave this issue as the one for implementing the mechanism (see the description above).
I opened a new one for the std objects APIs: #1116
