### ISSUE TITLE
Json Advanced Functionality

### ISSUE THREAD

**Issue by hasanaburayyan** [winglang/wing#1737]
- [ ] Json.equals()
- [ ]  Json.diff()
- [ ]  Json.patch()
- [ ]  Json.entries()
- [ ]  Structs Schema
- [ ]  To native types:
	- [ ]  unsafe mode
	- [ ]  try_from_json()

**Comment by staycoolcall911** [comment]
@hasanaburayyan - please note I added "Structs Schema" and "To native types" so this issue basically contains all our p2 work related to `json`.

**Comment by staycoolcall911** [comment]
Broken down the tasks listed in this issue to several issues: #3139, #3140, #3142.
Closing
