### ISSUE TITLE
Resource can be assigned to Json variables

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1749]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

```
bring cloud;

let x: Json = new cloud.Bucket();
```

### I expected this:

Compile error

### Instead, this happened:

No error

### Component:

Compiler

### Wing Version:

0.5.104

### Node.js Version:

18.14.1

### Platform(s):

MacOS

**Comment by Chriscbr** [comment]
Not sure if this is a duplicate of #1717

**Comment by staycoolcall911** [comment]
This was fixed by @hasanaburayyan in #3018. The error message is now `Expected type to be "Json", but got "Bucket" instead`.
Closing.
