### ISSUE TITLE
Compile wing app without test resources

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1783]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

Wing now supports a "--no-tests" compiler flag that allows you to synthesize your app with all "test" cloud resources and fixtures omitted.

### Use Cases

When deploying an app to production, you may not want to generate the full set of resources in your app in order to reduce costs / cloud spend. 

### Implementation Notes

Alternative name: "--release"

We might also want to consider trying this in plain Wing and see what the user experience is like (before adding it as a CLI flag), for example:

```js
resource Tests {
  init() {
    new cloud.Function(...) as "test";
  }
}

if os.env.get("WING_TEST") {
  new Tests();
}
```

### Component

Language Design, Compiler, CLI

**Comment by skorfmann** [comment]
Was surprised to see test related resources in a normal `wing compile -t tf-aws main.w`. Perhaps it would be interesting to have something like a `WING_ENV` which could be `dev`, `test` & `production`. This could be used to control behaviour like this

**Comment by tsuf239** [comment]
@Chriscbr @staycoolcall911 don't we have this already?

**Comment by Chriscbr** [comment]
You're right, I think this is the default behavior for 'wing compile' now. I'll close this
