### ISSUE TITLE
VSCode extension not working with incompatible `wing` version

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1784]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

Updated VSCode extension to latest version and use completion.

### I expected this:

To work, but it didn't.

I realized I might have an older Wing version, so I upgraded it and now it's working !! ❤️ 

### Instead, this happened:

https://user-images.githubusercontent.com/598796/224535992-55953729-c4d9-43ff-b110-14409f125acb.mov

### Component:

IDE Extension

### Wing Version:

0.5.100

### Anything else?

I think we need some kind of compatibility handshake between the VSCode extension and the toolchain to make sure this doesn't happen in the future.

Perhaps as a simple first step we can just verify that the toolchain is exactly the version the extension was compiled with. In the future we can add some more relaxed comparison.

**Comment by staycoolcall911** [comment]
Not happening anymore. Closing.
