### ISSUE TITLE
Polish npm package READMEs

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1801]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

Rewrite and clean up the READMEs for the npm packages we publish ([winglang](https://www.npmjs.com/package/winglang) and [@winglang/sdk](https://www.npmjs.com/package/@winglang/sdk)). If we don't think this is a high traffic area, then they can just point to our website / docsite

### Use Cases

npm may be one of the places developers look to or link to others when they first hear about Wing

### Component

Documentation

**Comment by staycoolcall911** [comment]
This was done
