### ISSUE TITLE
spec for mutating struct values or easily creating new struct instances from existing ones

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#1804]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

Currently, I can't change a value of a struct instance because structs are immutable. 
So I need to create a new instance, notice this code:
```ts (wing) 
struct Person {
 id: str;
 name: str;
}


let rename_person = (p: Person, new_name: str): Person => {
   return Person { id: p.id, name: new_name };  
};
let john = Person { id: "0123456789", name: "John the first" } ;
let new_john = rename_person(john, "John the last");
assert("John the last".name == new_john.name); 
assert(john.id == new_john.id); 
```

It is easy to write because `Person` has only two fields, but in the case of 10 fields in Person rename_person becomes a nightmare 

### Use Cases

Changing a struct instance (or creating a new one) 

### Implementation Notes

I see a couple of options:

#### no mutability concept 
- `from` static factory
```ts (wing)
let rename_person = (p: Person, new_name: str): Person => {
   return Person.from({name: new_name }, p);  
};
```
- Rust way (thanks @yoav-steinberg)
```ts (wing)
let rename_person = (p: Person, new_name: str): Person => {
   return Person { name: new_name, ..p };  
};
```
#### Add mutability concept to struct 
Automatically create a `Person.Mut` type and the `copy, copy_mut` tuple
```ts (wing)
let rename_person = (p: Person, new_name: str): Person => {
   let res =  p.copy_mut();
   res.name = new_name;
   return res.copy(); 
};
```

### Component

Language Design

**Comment by yoav-steinberg** [comment]
In rust there's this syntax:
```rust
struct Person {
  id: String;
  name: String;
}
let john = Person { id: "0123456789", name:  "John the first" };
let new_john = Person { name: "John the last", ..john };
```

**Comment by ekeren** [comment]
> In rust there's this syntax:
> 
> ```rust
> struct Person {
>   id: String;
>   name: String;
> }
> let john = Person { id: "0123456789", name:  "John the first" };
> let new_john = Person { name: "John the last", ..john };
> ```

Oh, nice! Adding to description

**Comment by eladb** [comment]
I am leaning towards the [spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax). We can debate if we want 3 or 2 dots.
