### ISSUE TITLE
Json.to_str api is confusing

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#1806]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

When writing wing code I came across the `json.to_str = (Json): str` and `str.from_json = (Json): str` 
When looking at these two functions name and signature, one might assume that they are similar, but they are not

### I expected this:

if meaning is different name should be different.
> json to str  == str from json 

When I look at the two functions together, I assume that the following statement is correct
```ts (wing) 
assert(str.from_json(Json "hello") == Json.to_str(Json "hello"))
```

### Instead, this happened:

but in fact:
```ts (wing) 
assert("hello" == str.from_json(Json "hello"));
assert("\"hello\"" == Json.to_str(Json "hello"));
```

Because `Json.to_str` is actually `JSON.stringify` so I would consider renaming it

### Component:

Language Design

**Comment by eladb** [comment]
I tend to agree. The original name was `Json.format` which may work better

**Comment by hasanaburayyan** [comment]
I don’t recall the discussion to change this from .format() to .to_str() but without that context I’m personally in favor for the original .format()

**Comment by staycoolcall911** [comment]
Let's go with `stringify`.  
I'll close this issue and open a simple `good first issue` in a few hours, so any contributor could pick it up.
If anyone objects that or wants a different name please reopen and continue the discussion.
