### ISSUE TITLE
"invalid" tests catches only compiler errors

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#1808]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

- placed this code in the invalid dir:
```
bring cloud;

let bucket = new cloud.Bucket();

new cloud.Function(inflight () => {
    bucket.put("hello", "world");
    bucket.public_url("hello");
//        ^Error: Cannot provide public url for a non-public bucket

}) as "test";
``` 
when running locally a run time error occurs: 
`npx nx wing -- "test" ../../examples/tests/invalid/bucket_public_url.w`

![image](https://user-images.githubusercontent.com/39455181/224984985-3cec19c4-3414-4cb1-9137-3d9428cd21e3.png)

I looked up the others- and they're all "compilation" errors, as far as I could see:
![image](https://user-images.githubusercontent.com/39455181/224985856-5eb1be0d-d99d-4741-b53e-b70a4aa3d758.png)

### I expected this:

this run-time error to be recognized by the test executed and the test to pass as invalid.

### Instead, this happened:

the test didn't pass as invalid:
![image](https://user-images.githubusercontent.com/39455181/224985345-cabf276b-fcfe-4569-bdec-d62d6b2db576.png)
(seems like the error didn't pass to stderr somehow)

### Component:

Other

**Comment by tsuf239** [comment]
@staycoolcall911 spoke with @MarkMcCulloh,
The tests right now intentionally only cover compilation, so it’s not a bug. 
He thinks it'll be okay to add a separate type of suite in hangar to cover this case too.

**Comment by staycoolcall911** [comment]
Thanks for following up @tsuf239, that sounds good to me

**Comment by MarkMcCulloh** [comment]
For a while we've had an https://github.com/winglang/wing/tree/main/examples/tests/error directory. Adding files here will run any tests and snapshot any failures, so it's not limited to compiler errors.
