### ISSUE TITLE
Bucket: Improve interaction view

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#1814]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

- Preview all files (a part from txt, json)
- show "open in a new tab" If the file is too big

### Use Cases

TBD

### Component

Wing Console

**Comment by ainvoner** [comment]
see also https://github.com/winglang/wing/issues/2292

**Comment by ainvoner** [comment]
@polamoros can we close it after https://github.com/winglang/console/pull/567 will be merged?

**Comment by polamoros** [comment]
> @polamoros can we close it after [winglang/console#567](https://github.com/winglang/console/pull/567) will be merged?

I'm adding support for previewing images / videos / pdfs, etc. on this PR :) 
https://github.com/winglang/console/pull/582/files
