### ISSUE TITLE
Store offsets in span information for compiler errors

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1815]
Currently we just store line and column information in the AST of the compiler:

https://github.com/winglang/wing/blob/e6779aa055365fdb2d9b128e9669b9d6043c2020/libs/wingc/src/diagnostic.rs#L15-L18

If we store the offset into the actual file, then other parts of the code (e.g. #1799) that render error diagnostics can find the part of the file without having to read the whole file. (small performance improvement)

open questions:
- Should this be a "byte" offset (number of bytes into the file) or a "character" offset (number of characters into the file -- where multi-byte graphemes count as one characters)
- How to handle cases where we can't obtain this information (e.g. referencing spans from JSII modules)

**Comment by ekeren** [comment]
Keep
