### ISSUE TITLE
Console design system - Typography

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#1826]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

As part of the Wing Console design system we have a Typography component.
Our Typography uses the proper html elements for each variant and follow all relevant accessibility guidelines

### Use Cases

Use text properly in wing console

### Component

Wing Console

**Comment by ainvoner** [comment]
2 font sizes:
- [ ] text-xs
- [ ] text-sm - will our base size
2 font wights:
- [ ] font-normal
- [ ] font-medium
3 font colors:
- text-slate-300 - for dimmed text (no logs)
- text-slate-500 - for slightly dimmed text (metadata keys strings)
- text-slate-800 - for regular text
4 variants:
- [ ] h3 - h3
- [ ] span - span
- [ ] span-sm - span
- [ ] body - p

**Comment by ainvoner** [comment]
keep

**Comment by ekeren** [comment]
Keep

**Comment by ainvoner** [comment]
when we will work on a new design system we will have to go over all components and building blocks
