### ISSUE TITLE
Should we allow Resource fields with the same name and different phase modifiers?

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#183]
Currently the spec allows that. It is possible that we should avoid it - see the discussion here:
https://github.com/monadahq/winglang-spec/pull/9#discussion_r964727329

**Comment by eladb** [comment]
I think we can close this for now. I am comfortable with allowing this.

**Comment by staycoolcall911** [comment]
This will surely fail, as @3p3r observed [here](https://github.com/winglang/wing/issues/1024), but it's ok to close this and reopen an issue in the future.
