### ISSUE TITLE
Capturing should not work for collections of collections of resources (for now)

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1830]
This doesn't handle collections of collections of resources - maybe we want some kind of `contains_resources()` function?

(not that important)

_Originally posted by @Chriscbr in https://github.com/winglang/wing/pull/1743#discussion_r1137806103_

**Comment by staycoolcall911** [comment]
An example which currently succeeds when running `wing test`:
```ts
bring cloud;

let a = new cloud.Bucket() as "ba";
let b = new cloud.Bucket() as "bb";

let arrOfBuckets1 = [a, b];
let arrOfBuckets2 = [a];

let arrOfArrOfBuckets = [arrOfBuckets1, arrOfBuckets2];

test "Capture array of array of bucket" {
  log(arrOfArrOfBuckets.at(0).at(0).node.id);
}
```

**Comment by staycoolcall911** [comment]
Seems like this is currently aligned with the requirement of this issue - getting a lifting error.
