### ISSUE TITLE
set is implicitly casted into Json 

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#1834]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

```ts (wing)
let j: Json = Set<str> {"a", "a", "b"};
print("j=${j}");
```

```sh
wing test a.w
```

### I expected this:

not to compile

### Instead, this happened:

```sh
j={}
pass ─ aaa.w (no tests)
```

### Component:

Compiler

### Wing Version:

0.5.134

**Comment by ekeren** [comment]
@YarivLevy81  and @hasanaburayyan FYI

**Comment by Chriscbr** [comment]
Related to #1749 (I think)

**Comment by staycoolcall911** [comment]
This is now fixed and the correct error message is thrown ("Expected type to be "Json", but got "Set<str>" instead"). Must have been fixed by @hasanaburayyan a few weeks ago. Closing.
