### ISSUE TITLE
Should we change the name for inflight init method?

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#184]
There's a need to allow the developer to run some code when the compiler initializes the resource client.

Currently `inflight init` is this lifecycle method, but I suggest we change the name for this method.

Conceptually, looking from the developer's perspective, the resource is initialized only once - on preflight. Having another `inflight init` method on inflight is therefore confusing.

**Comment by eladb** [comment]
I am comfortable with `inflight init()`. Associating the `inflight` modifier with any resource element puts it in the inflight context, and I think it makes sense that if you want to perform certain initializations within an inflight context for this resource, you will simply define it through `inflight init()` constructor.

I am comfortable closing this for now and revisiting if we see push back from the community.

**Comment by staycoolcall911** [comment]
I agree. Closing
