### ISSUE TITLE
cloud.Api - `request` inflight method

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1850]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

https://docs.winglang.io/reference/wingsdk-spec#api

This inflight method makes a HTTP request to the endpoint associated with the Api. Similar to JavaScript's [fetch](https://developer.mozilla.org/en-US/docs/Web/API/fetch) function except that the base URL is always the URL of the API endpoint.

### Use Cases

Unit testing `API`s, or calling your own APIs

### Component

SDK

**Comment by staycoolcall911** [comment]
Reducing the priority for this and removing assignee because of #2169

**Comment by staycoolcall911** [comment]
We are implementing fetch - reducing priority again

**Comment by Chriscbr** [comment]
Since the `http` module has been added, I'm not sure this is needed. Closing for now
