### ISSUE TITLE
Dogfooding ideas

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#1858]
This is the place to put some brilliant ideas for dogfooding Wing. Ideally we'd like to put a few of these apps in production.

**Comment by revitalbarletz** [comment]
- Release notes web page that aggregates our release notes from github 
- Good first issues web page that shows issues and their domain queried from github api or something

**Comment by ShaiBer** [comment]
These were discussed in several occasions:
1. Backend for Playground
2. Backend for preview environment
