### ISSUE TITLE
Add `tryAt` (and other `tryXXX` methods) to standard library APIs

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1868]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

When using `array.at(i)`, if the element does not exist in the array, an error is thrown. The new `tryAt()` method can be used to return a optional:

```js
if let v1 = my_array.tryAt(i) {
  print("array contains a value: ${v1}");
}

// or
let v2 = my_array.tryAt(i) ?? "default_value";
print(v2);

// etc...
```

This also applies to other retrieval standard collection APIs.

### Use Cases

It is a common use.

### Implementation Notes

I believe that currently `at()` does _not_ throw an error, which is a bug.

### Component

Compiler, SDK

**Comment by Chriscbr** [comment]
If `array.at(i)` is going to be equivalent to `array[i]`, what is `array.try_at(i)` going to be equivalent to?

**Comment by eladb** [comment]
Why do we need a shorthand syntax for `try_at()`?

**Comment by revitalbarletz** [comment]
@eladb what other methods were you thinking? tryConcat and other friends? or anything specific?

**Comment by giovanni-orciuolo** [comment]
This is related to issue #3575. I'm in the process of implementing `tryGet` (even though I'm in the process of getting familiarity with the codebase).

**Comment by staycoolcall911** [comment]
The `Array.tryAt()` method has been added - I'll close this for housekeeping until we get more specific requirements to add any additional `tryXXX` methods. 
Feel free to reopen if you disagree.
