### ISSUE TITLE
`T?` should not be interpolatable

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1876]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

```js
let f = (y: str?) => {
  log("y is ${y}");
};

f();
```

### I expected this:

To be a compiler error because `str?` cannot be interpolated.

### Instead, this happened:

```
y is undefined
```

### Component:

Compiler

**Comment by staycoolcall911** [comment]
The error message is much clearer now, so I'm closing this issue:
```sh
Failed to compile.

error: Expected type to be "stringable", but got "str?" instead
  --> wing/main.w:2:15
  |
2 |   log("y is ${y}");
  |               ^
  |
  = hint: str? is an optional, try unwrapping it with 'x ?? "nil"' or 'x!'
```
