### ISSUE TITLE
Replace alpha with beta

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#1882]
currently we have the word "alpha" mentioned in our repo and docs, we need to replace it with beta.

## Details

- [ ] We need to find all mentions of our the word `alpha` in our repo and docs and replace it with `beta`, for example:
- [ ] VSCode Extension README
- [ ] Wing Console

**Note:** Not for now,  need to wait for this one close to the beta release 

![image](https://user-images.githubusercontent.com/1727147/227159509-2fb943f2-8824-4526-b57a-505a4c518cb4.png)

**Comment by Bharadwajshivam28** [comment]
@ekeren Hello sir i can do it so please assign to me sir

**Comment by ekeren** [comment]
Hey @Bharadwajshivam28 , 

We should wait for with this issue close to the beta release (the date is not final yet).

**Comment by Bharadwajshivam28** [comment]
okay @ekeren

**Comment by ekeren** [comment]
update description, thanks @Bharadwajshivam28 🙏

**Comment by Bharadwajshivam28** [comment]
replace alpha with beta wherever used?

**Comment by Bharadwajshivam28** [comment]
> yes, updated description. anyhow it will take a couple of month before this should be done.

Okay
