### ISSUE TITLE
Some capture errors do not show red underline in IDE

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1893]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

```js
bring cloud;

resource A impl cloud.IFunctionHandler {
  var x: num;
  init() {}
  inflight handle() {
    print("${this.x}");
  }
}

new cloud.Function(new A());
```

### I expected this:

When I compile the code, I get:

```
error: Cannot capture reassignable field 'x'
  --> test.w:7:14
  |
7 |     print("${this.x}");
  |              ^^^^^^ Cannot capture reassignable field 'x'
```

So I expected `this.x` to be underlined in my IDE

### Instead, this happened:

No red underline in my IDE

### Component:

IDE Extension

### Wing Version:

0.6.7

### Node.js Version:

18.12.1

### Platform(s):

MacOS

### Anything else?

Previous issue #1802 (that case example was fixed, but it looks like this capture error is triggered by a different code path)

I think we may need to separate capturing logic from the "jsifier" stage of the compiler - currently some of the capture analysis work is performed within that phase, even though it shouldn't be related to emitting code.

**Comment by staycoolcall911** [comment]
This is basically a duplicate of #2548. Closing.
