### ISSUE TITLE
Regex in std lib

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#1894]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

Wing introduces a new built-in `regex` type as part of the standard library (similar to `duration`, `string`, `array`, etc.).

### Use Cases

Make regular expressions easy to use in wing and reduce boilerplate code currently needed to use regex. Currently this is supported via the `extern` syntax - see an example as part of [story 15](https://docs.winglang.io/contributors/rfcs/stories/story-15).

### Implementation Notes

As other builtin types, this should be implemented in [wingsdk's std library](https://github.com/winglang/wing/tree/main/libs/wingsdk/src/std) as a thin wrapper over javascripts RegExp.

Please also make sure to update the reference docs (should be done automatically after you add the regex class to the std lib and run `npm run build` from the [wingsdk folder](https://github.com/winglang/wing/tree/main/libs/wingsdk/)).

### Component

SDK

**Comment by Bharadwajshivam28** [comment]
@staycoolcall911 Hello sir i want to work on this issue

**Comment by Bharadwajshivam28** [comment]
sir please elaborate this issue little more in simple words @staycoolcall911

**Comment by revitalbarletz** [comment]
Hi @Bharadwajshivam28! I want to chat with you, how about joining our [slack](https://t.winglang.io/slack) channel?

**Comment by Bharadwajshivam28** [comment]
> Hi @Bharadwajshivam28! I want to chat with you, how about joining our [slack](https://t.winglang.io/slack) channel? 

Ya sure

**Comment by Bharadwajshivam28** [comment]
> Hi @Bharadwajshivam28! I want to chat with you, how about joining our [slack](https://t.winglang.io/slack) channel? 

I joined the channel

**Comment by revitalbarletz** [comment]
Since there is no spec for Regex, I am removing the 'good first issue' tag.

**Comment by ekeren** [comment]
I'll work on the spec first, and then we can turn this into "good first issue"

**Comment by Bharadwajshivam28** [comment]
> Since there is no spec for Regex, I am removing the 'good first issue' tag.

ok

**Comment by Bharadwajshivam28** [comment]
> I'll work on the spec first, and then we can turn this into "good first issue"

ok

**Comment by olivernybroe** [comment]
@Bharadwajshivam28 are you currently working on this?

**Comment by staycoolcall911** [comment]
This was done by @harsh9607 in #4039
