### ISSUE TITLE
Can't deploy resources with AWS when using MFA with assume role.

### ISSUE THREAD

**Issue by Tolluset** [winglang/wing#1910]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

I tried this code.

```ts
// wing.w
bring cloud;

let queue = new cloud.Queue(timeout: 2m);
let bucket = new cloud.Bucket();
let counter = new cloud.Counter(initial: 100);

queue.on_message(inflight (body: str): str => {
  let next = counter.inc();
  let key = "myfile-${next}.txt";
  bucket.put(key, body);
});
```

and going to deploy.

```bash
wing compile -t tf-aws wing.w    
cd ./target/wing.tfaws
terraform init
terraform apply
```

### I expected this:

Expect for able to deploy to cloud.

### Instead, this happened:

The error happened.

```text
Error: configuring Terraform AWS Provider: loading configuration: assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.

  on main.tf.json line 14, in provider.aws[0]:
  14:       }
```

### Component:

SDK

### Wing Version:

0.6.9

### Node.js Version:

v18.15.0

### Platform(s):

MacOS

### Anything else?

This issue is probably rare, or can get away by disable MFA with assume role. But it would be pleasure able to deploy with MFA with assume role.

**Comment by Tolluset** [comment]
This issue is not for wing's issue. The problem was in terrarorm. Who with faced this issue, can avoid by using aws-vault.

https://stackoverflow.com/questions/52432717/terraform-unable-to-assume-roles-with-mfa-enabled

**Comment by hasanaburayyan** [comment]
👋 Hey @Tolluset thanks for reporting an issue. Actually this is a terraform issue and there are a few options to make this work. You could use a AWS credentials tool like `aws-vault` or `awsume` etc..  You could also use a wing plugin to get around this but thats probably more complicated 😁
