### ISSUE TITLE
saving wing application changes multiple times causes the console to display the blue screen of death

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#1911]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

Create a wing application with the console open.
Bring : `bring "@cdktf/provider-aws" as aws;` to have a slow compilation process.
Change the application code multiple times (and save the changes) rapidly. 

### I expected this:

The wing console will successfully load the newly updated code and run the latest version of the simulator

### Instead, this happened:

After several code changes the console displayed the blue screen of death with different compiler errors:
- no such file or directory .//<path>/prefiight.js
- empty error message 

### Component:

Compiler, Wing Console

### Wing Version:

0.6.3

### Node.js Version:

v18.0.0

### Platform(s):

MacOS

### Anything else?

compiler - replace the target directory in an atomic way
console - prevent multiple unnecessary compilations, stop blocking the whole ui while compiling (move the loader to the bottom bar)

**Comment by eladb** [comment]
@ainvoner did we resolve this yet?
