### ISSUE TITLE
testing programmatically doesn't work

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#1912]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

Following instructions https://docs.winglang.io/getting-started/simulator

### I expected this:

to work

### Instead, this happened:

the function didn't run when the queue message got sent 

### Component:

Compiler

### Wing Version:

0.8.3

### Anything else?

probably related to latest method wrapping solution

**Comment by marciocadev** [comment]
It worked in the past.
I tried it now and it gave me an error.
I used the `--trace-deprecation` command to show the trace.

```bash
$ node --experimental-repl-await --trace-deprecation                                                                                        ─╯
Welcome to Node.js v18.12.1.
Type ".help" for more information.
> const sdk = require("@winglang/sdk");
undefined
> const simulator = new sdk.testing.Simulator({ simfile : "./target/hello.wsim"});
undefined
> await simulator.start();
undefined
> const queue = simulator.getResource("root/cloud.Queue");
undefined
> await queue.push("Wing");
undefined
> (node:1240) [DEP0025] DeprecationWarning: sys is deprecated. Use util instead.
    at node:sys:28:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/loaders:331:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/loaders:269:10)
    at loadBuiltinModule (node:internal/modules/cjs/helpers:50:9)
    at Module._load (node:internal/modules/cjs/loader:855:15)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at get (node:internal/modules/cjs/helpers:177:33)
    at runInSandbox (/home/marcio/code/wing-playground/prog-test/node_modules/@winglang/sdk/lib/target-sim/function.inflight.js:100:24)
    at Object.activity (/home/marcio/code/wing-playground/prog-test/node_modules/@winglang/sdk/lib/target-sim/function.inflight.js:55:24)
    at Object.withTrace (/home/marcio/code/wing-playground/prog-test/node_modules/@winglang/sdk/lib/testing/simulator.js:82:50)
```

**Comment by Chriscbr** [comment]
@ekeren Can you confirm the error @marciocadev is receiving is the same error you are getting? I am also getting this deprecation warning, but I can continue entering commands after the warning appears, and the rest example works as expected on my end.

It looks like the deprecation error is caused by this line introduced in #1859:

https://github.com/winglang/wing/blob/015ab4fe0d918445496119a4d1ddc57fb715a8ae/libs/wingsdk/src/target-sim/function.inflight.ts#L108-L108

A couple of options for removing the deprecation warning:
- We could blacklist copying deprecated Node modules into VM contexts (https://nodejs.org/api/deprecations.html)
- Tell users to run the REPL with `--no-deprecation` or `--no-warnings`

If there are no other errors running the example, then I think this bug can be downgraded to P1 or P2.

**Comment by ekeren** [comment]
@Chriscbr does the bucket contains a file after you push a message to the queue?

**Comment by Chriscbr** [comment]
@ekeren Here's a screenshot of my logs:

<img width="647" alt="Screenshot 2023-03-26 at 11 16 47 AM" src="https://user-images.githubusercontent.com/5008987/227785485-6d2b90ae-7a97-4f71-a3ce-3a7fd9fc4724.png">

**Comment by ekeren** [comment]
Ok, I'll check what the issue is on my side

**Comment by ekeren** [comment]
I am away from computer, @Chriscbr can you lower priority and assign to me (so I'll check on my side )

**Comment by marciocadev** [comment]
I updated my installation and tried again, but the file was not created in the bucket.

```bash
$ node --experimental-repl-await                                                                                                            ─╯
Welcome to Node.js v18.12.1.
Type ".help" for more information.
> const sdk = require("@winglang/sdk");
undefined
> const simulator = new sdk.testing.Simulator({ simfile : "./target/hello.wsim"});
undefined
> await simulator.start();
undefined
> const queue = simulator.getResource("root/cloud.Queue");
undefined
>  await queue.push("Wing");
undefined
> (node:2764) [DEP0025] DeprecationWarning: sys is deprecated. Use util instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
const bucket = simulator.getResource("root/cloud.Bucket");
undefined
> await bucket.list();
[]
>
```

**Comment by marciocadev** [comment]
I updated my installation and tried again, but the file was not created in the bucket.

```bash
$ node --experimental-repl-await                                                                                                            ─╯
Welcome to Node.js v18.12.1.
Type ".help" for more information.
> const sdk = require("@winglang/sdk"); // import the wing sdk library
undefined
> const simulator = new sdk.testing.Simulator({ simfile : "./target/hello.wsim"}); // create an instance of the Simulator
undefined
> await simulator.start();
undefined
>  const queue = simulator.getResource("root/cloud.Queue"); // retrieve the queue resource
undefined
>  await queue.push("Wing");
undefined
> (node:3239) [DEP0025] DeprecationWarning: sys is deprecated. Use util instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

> const bucket = simulator.getResource("root/cloud.Bucket"); // retrieve the bucket resource
undefined
> await bucket.list();
[]
>
```

**Comment by Chriscbr** [comment]
@marciocadev I'm still unable to reproduce. Could you try installing older versions to see when the error starts appearing?

**Comment by marciocadev** [comment]
Downgrade to 0.6.0, @Chriscbr. It didn't work, but I pushed messages to the queue, and I think the queue was not delivered to the function.

```bash
> await queue.push("Wing");
undefined
> await queue.push("Wing2");
undefined
> queue
Queue {
  messages: [ 'Wing', 'Wing2' ],
  subscribers: [ { functionHandle: 'sim-2', batchSize: 1 } ],
  intervalId: Timeout {
    _idleTimeout: 100,
    _idlePrev: [TimersList],
    _idleNext: [TimersList],
    _idleStart: 130945,
    _onTimeout: [Function (anonymous)],
    _timerArgs: undefined,
    _repeat: 100,
    _destroyed: false,
    [Symbol(refed)]: true,
    [Symbol(kHasPrimitive)]: false,
    [Symbol(asyncId)]: 150,
    [Symbol(triggerId)]: 149
  },
  context: {
    simdir: './target/hello.wsim',
    resourcePath: 'root/cloud.Queue',
    findInstance: [Function: findInstance],
    addTrace: [Function: addTrace],
    withTrace: [AsyncFunction: withTrace]
  }
}
```

**Comment by marciocadev** [comment]
@Chriscbr Its strange

the same version (0.8.4) works on my Windows but not on my Linux

**Comment by ekeren** [comment]
It doesn't work for me on 0.8.4

**Comment by staycoolcall911** [comment]
We have pinpointed the issue - it is related to node version.
Works on node 19.3.0
Fails on node  18.12.1

**Comment by staycoolcall911** [comment]
@MarkMcCulloh, @Chriscbr - would be great if one of you could take it, please. 
If anyone from our team or contributors could suggest a test that reveals this  it would be highly appreciated.

**Comment by ekeren** [comment]
works on node: 18.12.1 wing v0.5.X
doesn't work on node:18.12.1 wing v0.60.0

==> the issue is with version 0.6.0 but only reproducible in node 18.12.1

**Comment by MarkMcCulloh** [comment]
I don't think there has been a fundamental regression, although a race condition has now surfaced more obviously.

`await`ing the `queue.push()` doesn't wait for listeners to finish running (and it shouldn't, imo).

I can replicate this with this js script:

```js
(async () => {
  const sdk = require("@winglang/sdk");
  const simulator = new sdk.testing.Simulator({
    simfile: "./target/test.wsim",
  });
  await simulator.start();
  const queue = simulator.getResource("root/cloud.Queue");
  await queue.push("Wing");
  const bucket = simulator.getResource("root/cloud.Bucket");

  console.log(await bucket.list()); // -> []
})();
```

If I add a sleep, the bucket contents are as expected:

```js
(async () => {
  const sdk = require("@winglang/sdk");
  const simulator = new sdk.testing.Simulator({
    simfile: "./target/test.wsim",
  });
  await simulator.start();
  const queue = simulator.getResource("root/cloud.Queue");
  await queue.push("Wing");
  const bucket = simulator.getResource("root/cloud.Bucket");

  // Wait for the bucket to be populated
  await new Promise((resolve) => setTimeout(resolve, 1000));

  console.log(await bucket.list()); // -> ["Wing"]
})();
```

---

So, a few options:
- Document this, requiring users to add a sleep for now before they assert anything
- Add some sort of simulator global that tracks if any promises are inflight, giving us something to await
- Recommend using onTrace (or creating something better) for asserting states and/or state changes

**Comment by ekeren** [comment]
@MarkMcCulloh

Did you try above on 0.8.4 node 18? 


https://user-images.githubusercontent.com/1727147/228170977-f95769c6-5316-4988-b6ec-48b244dd042e.mov


I can reproduce this even when adding the sleep.

**Comment by ekeren** [comment]
@MarkMcCulloh , If you can't lets jump on a call and see what I am missing
