### ISSUE TITLE
Simulator custom resources

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1915]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

The Wing simulator can now be extended to support resources which are not part of the Wing SDK. This allows providing localhost implementations of any cloud resource that will be used during development.

There are two ways to use custom resources in the Wing simulator:

1. Explicitly include a `SimulatorResource` in your Wing code.
2. Implicitly load a custom resource instead of a Terraform resource when targeting the simulator.

### Explicit custom resources

Here's how to use the `sim.CustomResource` resource in your Wing code:

```js
bring sim;

new sim.CustomResource(
  module: "./my-custom-resource.js",
  props: {
    my_prop: 1234,
    your_prop: "hello"
  }
) as "MyCustomResource";
```

> When compiled/tested for `--target sim`, this will result in a special entry in the 
> `simulator.json` file which will tell the simulator that the implementation of 
> `MyCustomResource` is provided by the `my-custom-resource.js` file 
> (this can also be an npm module BTW).

When the simulator is loaded, it will `require("./my-custom-resource")` and will expect the default export to be a JavaScript class with the following contract:

- `constructor(props, context)` - called when the simulator is started
  - `props` - resource preflight props passed from `simulator.json` above (e.g. `my_prop` and `your_prop`).
  - `context` - the [ISimulatorContext] object
- `async init()` - called to start the resource instance. Returns a map of runtime attributes to values.
- `async cleanup()` - called to clean up the resource instance upon shutdown.

For example:

```js
// my-custom-resource.js

class MyCustomResource {
  constructor(props, context) {
    this.my_prop = props.my_prop;
    this.your_prop = props.your_prop;
  }

  async init() {
    console.log("starting my custom resource...");
    console.log(`my_prop=${this.my_prop}`);
    console.log(`your_prop=${this.your_prop}`);
  }

  async cleanup() {
    console.log("cleanning up...");
  }
}

module.exports = MyCustomResource;
```

### Implicit custom resources

You can also tell the simulator to load a custom resource implicitly by configuring it to hook into *Terraform resources* in your Wing program.

For example, say you want to offer a simulated implementation for the DynamoDB resource:

```js
bring "@cdktf/provider-aws" as tfaws;

let table = new tfaws.dynamodbTable.DynamodbTable(
  name: "my-table",
  billing_mode: "PAY_PER_REQUEST",
  hash_key: "id",
  attribute: [{ name: "id", type: "S" }]
);

new cloud.Function(inflight () => {
  print(table.name);
});
```

When compiled to `sim`, you will get the following error:

```sh
$ wing compile -t sim test.w
ERROR: Unable to use "@cdktf/provider-aws.dynamodbTable.DynamodbTable" in simulator.
Please add an entry to your `wing.yaml` file with a custom resource mapping.
```

To resolve this, we can add an entry to `wing.yaml` like this:

```yaml
simulator:
  customize:
    @cdktf/provider-aws.dynamodbTable.DynamodbTable:
      module: ./my-custom-resource.js
```

Now, we should be able to compile to the simulator target, and the simulator will use the implementation under `./my-custom-resource.js` when it needs to initialize the `DynamodbTable`.

### Use Cases

See spec

### Component

SDK

**Comment by RaphaelManke** [comment]
Is the explicit declaration a real use case? When I think of a wing app it's overall purpose is to run in the cloud. 
So why would I need a simulator only resource? 

The implicit version makes sense. Because there will always be resources that are not part of wing. Therefore it would be useful to provide a simulator version of it. 
I see an alternative solution for that. Maybe the plug-in system can be used for that as well? That's just an idea, don't know if it works.

**Comment by eladb** [comment]
@RaphaelManke you are right that the explicit use case is likely not useful (at the moment). I am including it more as an implementation note given it's the base case. But perhaps it's confusing more than adding.

**Comment by Chriscbr** [comment]
I dig the design! I like how `sim.CustomResource` establishes a clear boundary for providing simulator implementations. It also feels cohesive with the story we have for `extern` and Wing plugins.

One piece that feels missing to me is detail about how the user interacts with `sim.CustomResource` (i.e. how does the user create a simulated resource with inflight methods). I think I see a way it can be accomplished using `extern` methods, but adding it as an example in the spec/issue might make it clearer.

---

I'd like to suggest a variation of the design which groups "supporting simulator custom resources" and "supporting target-specific custom resources" under a single umbrella. It reuses some ideas proposed by @skinny85 [here](https://github.com/winglang/wing/pull/1853#discussion_r1141392935).

Let's say I want a resource representing a DynamoDB table on AWS, but I want to also support it on the simulator. I feel like the Wing-y solution to this could be to create an abstract resource, and then define concrete implementations for each target:

```js
abstract resource DynamoTable {
  inflight put_item();
}

[target="tf-aws"]
resource AwsDynamoTable extends DynamoTable {
  init() {
    new tfaws.dynamodbTable.DynamodbTable(
      name: "my-table",
      billing_mode: "PAY_PER_REQUEST",
      hash_key: "id",
      attribute: [{ name: "id", type: "S" }]
    );
  }
  extern "./dynamo-client.js" inflight put_item();
}

[target="sim"]
resource SimDynamoTable extends DynamoTable {
  init() {
    new sim.CustomResource(
      module: "./dynamo-simulation.js",
      props: /* ... */,
    );
  }
  extern "./dynamo-simulation.js" inflight put_item();
}
```

The `[target="tf-aws"]` lines (placeholder syntax) are annotations to the compiler indicating how `DynamoTable` gets resolved. If two or more resources (extending the same abstract class) are annotated with the same target, a compiler error is thrown. (Under the hood, the annotations would be used to produce a dependency-injection factory that can be instantiated and passed to the root of the `App` class during preflight).

Some benefits of this approach would be increased consistency (sim is just another target!), and that it avoids the need for a configuration file (something I'm sure everyone can agree would be pretty nice).

**Comment by staycoolcall911** [comment]
For the beta, we plan to allow the following:
```ts (wing)
bring cloud;

resource TaskList {
  init() {
    if env.get("WING_TARGET") == "tf-aws" {

    }
  }
}
```
Closing for now.
