### ISSUE TITLE
Passing more than one argument per cloud function

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#1927]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

1. assuming I want to be able to write the following .w code:
```
bring cloud;
let bucket = new cloud.Bucket();

bucket.on_event(inflight (key: str, type: BucketEventType) => {
....
})
```
(for subscribing to this inflight function to be notified upon bucket event. The subscription is done by creating a topic- and a cloud function containing the inflight code.)

2. We are limited by the ability of the topic to publish only a single string and its subscribers get a single string as an argument

I am wondering what will be the best approach to overcome it
** Please note that the function above contains two arguments instead of the original single object containing the "type" and "key" keys suggested in the spec since structs weren't supported at a time https://docs.winglang.io/reference/wingsdk-spec#bucket

### Use Cases

see above

### Component

SDK

**Comment by Chriscbr** [comment]
+1, this feels like something that would be handy to support (better developer ergonomics), even though it might be possible to work around it with structs
