### ISSUE TITLE
confusing error message

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#1946]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

I got the following error:
![image](https://user-images.githubusercontent.com/1727147/228791307-6b4ee52e-1107-407b-933b-6e92f5ce820e.png)

### I expected this:

To know from the error which method call has wrong argument count

@yoav-steinberg suggested:
```
if r.test(j.get("title")) {
     ^ Expected....
```
### Instead, this happened:

I can't determine it 

### Component:

Compiler

### Wing Version:

0.8.13

**Comment by yoav-steinberg** [comment]
It's just that we use the span information for the entire expression and my suggestion above implies we need to just use the span information for the name of the method. That introduces some complexity because in some cases a call-expression doesn't have a method name.

**Comment by Chriscbr** [comment]
For a point of comparison, here's what TypeScript annotates in the case that you're putting extra arguments, and the case that you're missing arguments:

<img width="219" alt="Screenshot 2023-03-30 at 11 20 44 AM" src="https://user-images.githubusercontent.com/5008987/228884716-f9553467-8a4b-49d8-afda-4a4aceade9e6.png">

**Comment by ekeren** [comment]
> It's just that we use the span information for the entire expression and my suggestion above implies we need to just use the span information for the name of the method. That introduces some complexity because in some cases a call-expression doesn't have a method name.

I have probably fully assimilated into the PM position 😅, because the complexity you are talking about just sounds like another `if` statement to me 🤪

**Comment by staycoolcall911** [comment]
Closing (@ekeren is on board)
