### ISSUE TITLE
Add interaction view data persistence

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#1950]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

Resource interaction views preserve the state when navigating within the app. 

### Use Cases

- Avoid losing form data on the API interaction view when navigating within the Console.

## Reproduce

1. Click on Queue -> push a message (the message persist)
2. Click on bucket
3. Go back to the queue, no message 🤷

**Comment by ainvoner** [comment]
There are more specific issues to address this feature
