### ISSUE TITLE
Inflight functions can not access std classes

### ISSUE THREAD

**Issue by marciocadev** [winglang/wing#1957]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

Currently, when compiling a project, the preflight file imports the Wing library and has access to the `std` classes.
However, the generated file for inflight functions does not have access to the resources of the Wing library.

### Use Cases

Enable access to library resources during inflight functions.

### Component

SDK

**Comment by staycoolcall911** [comment]
@marciocadev - is this issue basically the same as #1629? If not, can you please share a small code sample so we could look into the issue? Thanks!

**Comment by marciocadev** [comment]
You're right @staycoolcall911
