### ISSUE TITLE
Wing Console displays the entrypoint file name

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#1970]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

When you `wing it some-file.w` you can now see an indication of the file name (`some-file.w`) on wing console.

### Use Cases

If you open multiple instances of the Wing Console - you'll know which instance is related to which wing code file.

### Component

Wing Console

**Comment by ainvoner** [comment]
we have the file name as the console app title

![Image](https://user-images.githubusercontent.com/2538825/232512881-a27443d7-fb62-4da4-8f9d-2b980a840333.png)

is this what you meant?

**Comment by staycoolcall911** [comment]
Yes, that's great - closing
