### ISSUE TITLE
Display of cloud.Api resource error messages in Wing Console 

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#1971]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

`wing it` for a cloud.Api resource, then try using `POST` for example with a scenario that fails.
I tried the scenario described in issue #1969, but any other scenario that yields a failure would reveal the bug.

### I expected this:

Error message to appear in a readable manner.

### Instead, this happened:

Error message was a raw html. See attached pic.

<img width="282" alt="image" src="https://user-images.githubusercontent.com/106860404/229558687-1252f0a8-48ca-4c75-8a2a-12455ac87a30.png">

Error message text:
```sh
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Missing environment variable: BUCKET_HANDLE_5f3a2e5e<br> &nbsp; &nbsp;at evalmachine.&lt;anonymous&gt;:31:17<br> &nbsp; &nbsp;at exports.handler (evalmachine.&lt;anonymous&gt;:34:9)<br> &nbsp; &nbsp;at evalmachine.&lt;anonymous&gt;:37:9<br> &nbsp; &nbsp;at Script.runInContext (node:vm:141:12)<br> &nbsp; &nbsp;at Object.runInContext (node:vm:297:6)<br> &nbsp; &nbsp;at /Applications/Wing Console.app/Contents/Resources/app.asar/dist/vite/electron/main/index.js:238:149<br> &nbsp; &nbsp;at new Promise (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at n2t (/Applications/Wing Console.app/Contents/Resources/app.asar/dist/vite/electron/main/index.js:237:9364)<br> &nbsp; &nbsp;at Object.activity (/Applications/Wing Console.app/Contents/Resources/app.asar/dist/vite/electron/main/index.js:237:8767)<br> &nbsp; &nbsp;at Object.withTrace (/Applications/Wing Console.app/Contents/Resources/app.asar/dist/vite/electron/main/index.js:238:8269)</pre>
</body>
</html>
```

### Component:

Wing Console

### Wing Version:

0.8.26

### Node.js Version:

19.3.0

### Platform(s):

MacOS

**Comment by Chriscbr** [comment]
@staycoolcall911 out of curiosity, how do tools like Postman or Insomnia handle this scenario?

**Comment by staycoolcall911** [comment]
Yeah, that's a good point. They have the same behavior. Not sure if we shouldn't give a better DX, though, but I guess the priority for that is not too high
