### ISSUE TITLE
Only add one `cloud.Test` in each isolated test environment

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#1972]
> Maybe in a subsequent PR, but I'd like us to change how tests are modeled in apps.
>
> Instead of cloud.Functions with special IDs, let's create a cloud.Test resource and only materialize it into a Function in the environment in which it will be executed.
>
> This means that only a single test cloud function will be defined in each environment.

_Originally posted by @eladb in https://github.com/winglang/wing/pull/1926#discussion_r1155155476_

**Comment by tsuf239** [comment]
Tried to run a file with 3 tests- it seems that there are only 3 lambdas created- not 9:
<img width="537" alt="image" src="https://github.com/winglang/wing/assets/39455181/26949b90-b759-4a73-b1c6-1cec6fc3b8d0">

**Comment by Chriscbr** [comment]
Yep
