### ISSUE TITLE
Cannot create an empty JSON object

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1974]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

```js
let empty_obj = Json { };
```

### I expected this:

To compile and for `empty_obj` to contain an empty JSON object.

### Instead, this happened:

error: Cannot infer type of empty map

### Is there a workaround?

Not that I am aware (@hasanaburayyan might be able to say)

### Component:

Compiler

### Wing Version:

0.8.26

**Comment by staycoolcall911** [comment]
Duplicate #1947
