### ISSUE TITLE
Inflight documentation not clear to everyone

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2022]
### Feature Spec

Feedback about our docs from: https://www.reddit.com/r/serverless/comments/12cilol/comment/jf4fkld/?utm_source=share&utm_medium=web2x&context=3 -

The ‘inflight’ functionality is vague or unclea in the docs. I have no sense for how it’s deployed, since it can be deployed so many ways. Am I responsible for that? If so… why the abstraction?

“compile down to” - this is vague. I’d love to see in the docs more explanation of how this gets deployed or maintained. Am I building a wing pipeline or a terraform pipeline? What does this look like when deployed? How is a wing file updated and then reflected in my stack? Are flavors of “stuff” between GCP and AWS similar enough to warrant more abstraction than terraform?

Hope this helps.

### Use Cases

This is needed s developers can get started with Wing

### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
@ShaiBer - can we put a link to your tutorial that will try to make this more clear?

**Comment by ShaiBer** [comment]
Yes, off course

**Comment by ShaiBer** [comment]
But the main solution is @Chriscbr's excellent new doc

**Comment by ekeren** [comment]
Done
