### ISSUE TITLE
IDE completion is not working as expected in `new` expressions

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2036]
### I tried this

```js
bring "@cdktf/provider-aws" as aws;

new aws.dynamodbTable.DynamodbTable();
```

### I expected this:

Completion should work

### Instead, this happened

https://user-images.githubusercontent.com/598796/231104621-979a25d7-6b36-4fcc-ae1c-cfe614a5928e.mov

### Component

IDE Extension

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
The core issue here was resolved with #2295

However, there is an additional follow-up here https://github.com/winglang/wing/issues/2036 that causes a similar-looking issue.
