### ISSUE TITLE
add error/unknown type to the type checker

### ISSUE THREAD

**Issue by yoav-steinberg** [winglang/wing#2038]
In order to improve error reporting and avoid potential bugs we should make the type-checker evaluate unknown or error expressions to a dedicated "error type" instead of any which is technically a valid type.

This new type can include some span information on where it was generated so we can improve diagnostics:
```
log(x);
// Error: `x` can't be used here, its type is unknown, this may be related to this expression: `let x = "hi" + 1;`
```

**Comment by eladb** [comment]
@staycoolcall911 @MarkMcCulloh let's prioritize this. I think this can dramatically improve DX and there are too many weird behaviors that are caused by this wrong modeling of errors.

**Comment by yoav-steinberg** [comment]
> Absolutely. Isn't this issue a duplicate of https://github.com/winglang/wing/issues/884?

Yes, it's a dup, I wasn't sure we had an issue for this. Closing.

**Comment by staycoolcall911** [comment]
Cheers. I prioritized #884 as p1 and added to the next sprint
