### ISSUE TITLE
Performance regression (from 0.5s to 1.1s)

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2047]
### I tried this

I ran my little performance benchmark (the one we showed on [Wingly](https://youtu.be/QG65zbxeays)).

[bench.zip](https://github.com/winglang/wing/files/11208051/bench.zip)

### I expected this:

The average result was about 0.5s in the Wingly.

### Instead, this happened

```
        1.12 real         1.10 user         0.15 sys bench-1-bucket.w
        1.13 real         1.12 user         0.16 sys bench-1-inflight.w
        1.11 real         1.14 user         0.16 sys bench-5-buckets.w
        1.09 real         1.11 user         0.16 sys bench-5-inflights.w
```

### Component

Other

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment]
@MarkMcCulloh any idea?

**Comment by MarkMcCulloh** [comment]
I can't match that big time difference locally, so there may be a difference in your current environment causing it. My guess: https://github.com/winglang/wing/blob/main/apps/wing/src/cli.ts#L35

We still have this code checking for updates. 
Depending on network conditions, this could easily add 500ms.

---

Other thought: The inclusion of AWS CDK probably had non-negligible effects on module resolution. time (`require("@winglang/sdk")` takes about 160ms longer after awscdk was added)

**Comment by eladb** [comment]
@MarkMcCulloh what's the status of adding some perf regression test to our build?

**Comment by eladb** [comment]
OK, made a few more tests:

> We still have this code checking for updates.

Indeed, this has a lot of impact on compilation time. I was under the impression that this only happens once a day or something like that but it seems like it goes to the network every time.

That's definitely a log hanging fruit that we should address: opened - https://github.com/winglang/wing/issues/2074

I disabled the version checker by commenting out the javascript code. Here are the results:

```
0.6.0
        0.55 real         0.73 user         0.09 sys bench-1-bucket.w
        0.57 real         0.78 user         0.09 sys bench-1-inflight.w
        0.56 real         0.78 user         0.09 sys bench-5-buckets.w
        0.58 real         0.80 user         0.10 sys bench-5-inflights.w
```

And the latest version:

```
0.10.6
        1.00 real         1.16 user         0.16 sys bench-1-bucket.w
        1.01 real         1.21 user         0.17 sys bench-1-inflight.w
        0.99 real         1.21 user         0.17 sys bench-5-buckets.w
        1.01 real         1.22 user         0.17 sys bench-5-inflights.w
```

So it's about 500ms difference between 0.6.0 and 0.10.6.
```

> The inclusion of AWS CDK probably had non-negligible effects on module resolution

I think that's definitely one of the reasons. I removed the export of the targets from the sdk's index file manually and here are the new results:

```
0.10.6
        0.64 real         0.79 user         0.11 sys bench-1-bucket.w
        0.65 real         0.85 user         0.12 sys bench-1-inflight.w
        0.66 real         0.85 user         0.12 sys bench-5-buckets.w
        0.65 real         0.87 user         0.12 sys bench-5-inflights.w
```

Still have some degradation from 0.6.0, but definitely getting closer. Opened this issue to track: https://github.com/winglang/wing/issues/2075

So @MarkMcCulloh, we are still left with about 100ms difference between the versions... Any idea?

**Comment by Chriscbr** [comment]
@eladb have you tried using a profiler? There ought to be some way to hook up the Chrome debugger to the CLI

**Comment by MarkMcCulloh** [comment]
https://clinicjs.org/flame/ generates pretty useful stuff as well

**Comment by staycoolcall911** [comment]
Solved
