### ISSUE TITLE
Integration tests that can be run on all targets

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#205]
We would like to be able to create an app, and then assert that aspects of its behavior are the same when simulated as when deployed to a cloud provider.

Perhaps we need create polycons for test assertions that are target-agnostic, and which have implementations for the respective clouds.

For example, as a user, I'd like to make an assertion like "when `hello.txt` is put inside this bucket, then the Handler function gets called and returns this value" -- and I'd like to write this assertion in a way that is target-independent.

We should also dogfood this framework to test the Wing SDK, and run tests periodically through CI/CD.

**Comment by ekeren** [comment]
duplicate with #1368
