### ISSUE TITLE
Show in the console how many lines of code using wing saved me

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2052]
### Feature Spec

I'd like to be able to see how many lines of code I would have to write if I didn't use Winf

### Use Cases

This is to allow me to feel good about choosing to use Wing by seeing how much work the compiler has saved me :)

### Implementation Notes

We can show this after compiling to a cloud and provisioning engine.
We can compare the length of wing code to the length of the resulting artifacts

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
Closing as out of scope
