### ISSUE TITLE
manually change the console application theme

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#2062]
### Feature Spec

Add an option to toggle the dark theme on the Console.

### Use Cases

The Console Dark theme is toggled automatically using the system theme configuration. Users would want to change the application theme manually as well.
Users would also want to use key shortcuts in order to change the theme.

### Implementation Notes

Related discussions

https://github.com/winglang/console/pull/400#discussion_r1165323826
https://github.com/winglang/console/pull/400#discussion_r1165269019

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
see also https://github.com/winglang/wing/issues/1235#issuecomment-1514305212
