### ISSUE TITLE
inflight logs are not showing in Wing console

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2070]
### I tried this

```js
bring cloud;

resource Foo {
  init() {}
  inflight foo() {
    log("hi");
  }
}

let f = new Foo();

new cloud.Function(inflight () => {
  log("there");
  f.foo();
}) as "test";
```

### I expected this:

To see these in the log pane:

```
there
hi
```

### Instead, this happened

No logs

### Is there a workaround?

When running with `wing test`, logs are displayed correctly:

```sh
pass ┌ test.wsim » root/env0/test
     │ there
     └ hi
```

This indicates that they are captured by the inflight sandbox (https://github.com/winglang/wing/pull/1879), but for some reason the console doesn't display them.

### Component

Wing Console

### Wing Console Version

0.2.31

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
inflight logs are shown, tested on console version 0.2.91, sdk and wing version 0.14.4
<img width="478" alt="Screenshot 2023-04-30 at 19 05 06" src="https://user-images.githubusercontent.com/2538825/235363590-a8bfce1f-cb24-4c7b-9fc0-ff9afe7114d2.png">
