### ISSUE TITLE
Resource method captures won't resolve attributes

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2071]
### I tried this

```js
bring cloud;

let api = new cloud.Api();

class Forwarder {
  api: cloud.Api;
  url: str;

  init(api: cloud.Api) {
    this.api = api;
    this.url = this.api.url;
  }

  inflight bind() {
    log(this.url);
  }
}

let fw = new Forwarder(api);

test "print url twice" {
  fw.bind();
  log(api.url);
}
```

and run:

```sh
wing test
```

### I expected this:

To print the URL twice (once from the inflight *closure* and once from the inflight *method*).

### Instead, this happened

```
pass ┌ test.wsim » root/env0/test
     │ ${root/env0/cloud.Api#attrs.url}
     └ http://127.0.0.1:50710
```

It seems like the inflight method did not resolve the attribute.

### Is there a workaround?

In this case we can utilize this inconsistent behavior to pass the actual url during inflight:

```js
bring cloud;

let api = new cloud.Api();

resource Forwarder {
  init() {}

  inflight bind(url: str) {
    log(url);
  }
}

let fw = new Forwarder();

new cloud.Function(inflight () => {
  fw.bind(api.url);
  log(api.url);
}) as "test";
```

This works.

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
This now works. Closing
