### ISSUE TITLE
Console UX: immediate recompilation indication is in the background

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2072]
### I tried this

Open the Wing Console with some code and then update it in my IDE and save it.

### I expected this:

To get an **immediate** indication that the Console have picked up the change and is working to recompile and reload.

I think the right UX here is to basically show that the console is reloading as soon as we pick up the file change and not only when the compilation finishes.

### Instead, this happened

It appeared as if nothing happened for a while (apparently there's a tiny little indication in the status bar that we are compiling) and then the app updated.

### Is there a workaround?

N/A

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
basically revert our current changes :)

**Comment by eladb** [comment]
Let's discuss this before you do anything. I don't want duplicate work...

**Comment by ainvoner** [comment]
resolve dark theme issue when loading @ainvoner
