### ISSUE TITLE
CLI version checker dramatically hurts performance

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2074]
### I tried this

Run the CLI from different network conditions.

### I expected this:

To be fast and furious.

Here's the behavior I would expect:

- Version checking should happen at most once per day (there should be some local cache that tells the CLI not to go to the network if it already did it today).
- Add support for disabling the version check (e.g. when compiling from Wing Console).
- If the network is off, no version checking should happen at all.

### Instead, this happened

Depending on my network conditions, the new version checker added between 1s to 3s to every invocation.

When my network was disconnected, it took 3+ seconds to work.

### Is there a workaround?

When I commented out the code for version checking, I got a consistent 

### Component

CLI

### Wing Version

0.10.6

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Fixed by @MarkMcCulloh
