### ISSUE TITLE
Manage Secrets in State Elegantly and Securely

### ISSUE THREAD

**Issue by mbuotidem** [winglang/wing#2092]
### Feature Spec

Wing should have first class support for managing secrets in state. Current solutions handwave over this requirement so it would be helpful to give upfront thought to it as it is more difficult to retrofit.

### Use Cases

As a developer, if i create an cloud database, how do I safely store its password so that its not in plaintext on a file on my computer. 

### Implementation Notes

Maybe automatically create secrets in the respective cloud's secret store. Not sure I like this idea but I didn't want to leave this field empty. 

### Component

Language Design, Development Environment

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Thanks for bringing this topic @mbuotidem - extremely important. May I ask you to add your great input at the relevant issue for the [Secret resource](#1329)?
There's also an initial PR for that resource: #2042

**Comment by revitalbarletz** [comment]
And... may I ask that you will join our [slack channel](https://www.linkedin.com/safety/go?url=https%3A%2F%2Ft.winglang.io%2Fslack&trk=flagship-messaging-web&messageThreadUrn=urn%3Ali%3AmessagingThread%3A2-MTVhYjI5ZTItYmUzOS01MGJkLTg5ZTItMGQxNmQwMjAwZTNjXzAwMA%3D%3D&lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3Bin41fc91Q5OLJVDJBwtBvg%3D%3D)?

 It will be great to connect :)

**Comment by staycoolcall911** [comment]
@mbuotidem - Wing's cloud.Secret resource is now available for AWS and local simulator - you may view these PRs #2042  #2156 and if anything is missing, please let us know. Thank you, closing this issue for now
