### ISSUE TITLE
Expected type to be `IConstruct`, but got `Queue` instead

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2098]
### I tried this

```js
bring cloud;
bring "constructs" as constructs;

let q = new cloud.Queue();

log(constructs.Node.of(q).path);
```

### I expected this:

To work, since all Wing resources implement `IResource` which extends `IConstruct`.

### Instead, this happened

```sh
Expected type to be `IConstruct`, but got `Queue` instead
```

### Is there a workaround?

Not that I am aware of

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
Working in Wing 0.25.23
