### ISSUE TITLE
Unable to set resource display title

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2099]
### I tried this

```js
r.display.title = "bang";
```

### I expected this:

To work

### Instead, this happened

Error that title is not reassignable (despite the fact it is in the sdk)

### Is there a workaround?

Nope

### Component

Compiler, SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
solved in the sdk, there is an issue to add to the console
