### ISSUE TITLE
Struct Declaration: advanced behavior

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#2118]
- [ ] [json struct](https://github.com/winglang/wing/issues/120#issuecomment-1485473969) - p2
	- [ ] Limit allowable struct fields in json struct
- [x] struct `.fromJson()`
- [ ] Spread operator (...) - p2

**Comment by ekeren** [comment]
Keep

**Comment by staycoolcall911** [comment]
Added #3854, #3855 for the remaining sub-tasks and closing this issue.
