### ISSUE TITLE
Lockfile updates are not enforced by CI

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#2122]
### I tried this

Committing a change but not updating all lock files

### I expected this:

CI to fail

### Instead, this happened

CI passes

### Is there a workaround?

N/A

### Component

Development Environment, Contributor Experience

### Anything else?

Put another way, running `npm install` in a freshly-cloned copy of the monorepo should not result in lockfiles being changed. To do that, CI could check that when a build is performed, no additional changes get made to committed files during the build process.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
This issue is resolved since the move to pnpm. In CI we run `pnpm install --frozen-lockfile`, and unlike before there is only a single lockfile to worry about.
