### ISSUE TITLE
Computed property names

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#2126]
### I tried this

Compile this wing code:
```ts (wing)
let prop_name_pre = "some_";
let prop_name_post = "_string";
let m = {"a":1, "b":2, prop_name_pre.concat(prop_name_post):3};
```

### I expected this:

To compile

### Instead, this happened

![image](https://user-images.githubusercontent.com/106860404/232698298-f5c840ac-72a5-4ebe-88d9-024c0ac4b152.png)

### Is there a workaround?

Not really - even if we would use a parameter it still doesn't work and the parameter name string is used as the key instead of the value.

So this Wing code:
```ts (wing)
let prop_name_pre = "some_";
let prop_name_post = "_string";
let concatenated_string = prop_name_pre.concat(prop_name_post);
let m = {"a":1, "b":2, concatenated_string:3};
```
Jsifies to:
```js
const prop_name_pre = "some_";
const prop_name_post = "_string";
const concatenated_string = (prop_name_pre.concat(prop_name_post));
const m = Object.freeze({"a":1,"b":2,"concatenated_string":3});
```

### Component

Compiler

### Wing Version

0.11.7

### Node.js Version

19.3.0

### Platform(s)

MacOS

### Anything else?

We should allow expressions as map keys and in type_check.rs we should validate that it evaluates to string, otherwise throw an error

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
I think this is the same as [computed property names](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#computed_property_names) in JS - recently added to the language in 2015.

I'd mark this as P3 because we would probably need a dedicated syntax for it. In your example the code is unambiguous because you have a complex expression:
```js
let m = {"a":1, "b":2, prop_name_pre.concat(prop_name_post):3};
```
But in general the expression may be a simple one, and then it's not clear -- does the user want the prop name to be "prop_name" or to be "bar"?
```js
let prop_name = "foo";
let m = {a:1, "b":2, prop_name:3};
```

**Comment by staycoolcall911** [comment]
> -- does the user want the prop name to be "prop_name" or to be "foo"?

I'd say "foo".
But in any case you're right it's a p3, so we can put this issue aside for now.

**Comment by marciocadev** [comment]
@staycoolcall911 I don't know why but if you do this works

```ts
let prop_name_pre = "some_";
let prop_name_post = "_string";
let m = {"a":1, "b":2, "${prop_name_pre.concat(prop_name_post)}":3};
```

**Comment by staycoolcall911** [comment]
That makes sense @marciocadev , thanks! We'd still want to be able to pass an expression as key, but it’s good to have a workaround.

**Comment by staycoolcall911** [comment]
This works now. Closing.
Test code:
```ts
bring expect;

let prop_name_pre = "some_";
let prop_name_post = "_string";
let m = {"a"=>1, "b"=>2, prop_name_pre.concat(prop_name_post)=>3};

test "expression as a map key" {
   expect.equal(m.get("some__string"), 3);
}
```
