### ISSUE TITLE
Compiler allows invalid cloud.Function input types

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#2129]
### I tried this

Compiled this program:

```
bring cloud;

let wants_json = new cloud.Function(inflight (json: Json) => {
    log("${json}");
    log("${json.get("id")}");
}) as "fn";
```

### I expected this:

The compiler should error since you can only invoke using strings right now.

### Instead, this happened

The program compiles but the runtime won't work: `json.get(...)` will always return undefined.

### Component

Compiler

### Wing Version

0.12.7

### Node.js Version

18.12.1

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
I think this is an issue with how we're type checking `Json` as a subtype of every other type here:

https://github.com/winglang/wing/blob/1044a7aa9cb1b696b4d59acdcb36ea6484875703/libs/wingc/src/type_check.rs#L530-L532

**Comment by Chriscbr** [comment]
The issue is unrelated to #1448. The compiler doesn't detect an error because of how it currently treats `str` as a subtype of `Json`, e.g.

```js
// this compiles
let x: Json = "hello";
```

(I think a fix might require removing this subtyping relationship) 

Note also if we take the original code and switch `Json` with another type like `num` then we do get a compile-time error:

```js
bring cloud;

let wants_json = new cloud.Function(inflight (json: num) => {
    // code
}) as "fn";
```

**Comment by Chriscbr** [comment]
Related: https://github.com/winglang/wing/issues/1717

**Comment by staycoolcall911** [comment]
Fixed
