### ISSUE TITLE
Table resource throws ugly error when updating unexisting resource

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#2131]
### I tried this

Open this program in the Console:

```
bring cloud;

let users = new cloud.Table(
    name: "users",
    primary_key: "id",
    columns: {
        id: cloud.ColumnType.STRING,
    },
);

let create_user = new cloud.Function(inflight () => {
    users.update(Json {
        id: "1",
    });
});
```

And invoke the function.

### I expected this:

A more descriptive error should be thrown.

### Instead, this happened

This error is thrown:

```
Cannot set properties of undefined (setting 'id')
```

### Component

SDK

### Wing Version

0.12.7

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by garysassano** [comment]
I've just tested this and the error you get now is:
```
Unknown error: The primary key "1" was not found in the "users" table.
```
