### ISSUE TITLE
Unsuccessful compilation creates an empty main.wsim.######.tmp folder

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#2133]
### I tried this

`wing compile main.w`, where main.w contains some code that is expected to fail compilation (in this example: ^^^^^^ Variable x is not reassignable):
```ts(wing)
let x = 1;
x = 2;
```

### I expected this:

No empty folder to be created under `target/`.

### Instead, this happened

Empty folder main.wsim.######.tmp is created under `target/`.

### Component

SDK

### Wing Version

0.12.9

### Node.js Version

19.3.0

### Platform(s)

MacOS

### Anything else?

I think we decided that even if compilation fails, we will keep the generated artifacts (JS/Terraform) if there are any. 
The idea behind this decision was to help users debug their programs by reviewing the artifacts. 
However, if compilation fails in an earlier phase, we don't have any artifacts, so it should be ok to cleanup the empty directory.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
This no longer happens, tmp dirs are not created during compilation
