### ISSUE TITLE
Bucket.addFile()

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#2138]
### Feature Spec

The Bucket preflight `addFile` method allows uploading file/folder:
`addFile(fileName: str, path: str): void`

### Use Cases
Uploading folders and files to a bucket using their path. 

### Implementation Notes
we have a similar mechanism in the website resource

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by tsuf239** [comment]
For the path argument, you can look here:
https://github.com/winglang/wing/blob/746c0f17a4362b77b9c1095f7f28bc3a8ee238b7/libs/wingsdk/src/cloud/website.ts#L42-L45

**Comment by garysassano** [comment]
@tsuf239 What's the difference between this and `bucket.addObject`? Isn't the use case of this already covered by `cloud.Website`?

**Comment by tsuf239** [comment]
> @tsuf239 What's the difference between this and `bucket.addObject`? Isn't the use case of this already covered by `cloud.Website`?

Not really, Website and Bucket are different resources, one stores files, while the other one serves static files (they are both implemented by s3 in tf-aws target, but that's all) the comment was written before implementing the website and might be misleading, you're right, I'll change it :)
Right now, we can only upload a string and save it as a file in the s3, this issue is for uploading a file when its path is supplied (we have a similar mechanism in the website resource)

**Comment by 0018akhil** [comment]
Hi @revitalbarletz 
Can you assign this me I'll work on this.

**Comment by 0018akhil** [comment]
Hey @staycoolcall911 

This functionally can only add text files to the bucket ?

**Comment by staycoolcall911** [comment]
Hey @0018akhil - apologies for the late reply, as I was on vacation. I see you got some answers on Slack. Please let me know if anything is still unclear

**Comment by 0018akhil** [comment]
Hi @staycoolcall911 
Users can only upload only absolute path?

**Comment by staycoolcall911** [comment]
I think it's ok to start with absolute path

**Comment by 0018akhil** [comment]
Hi @tsuf239 

![image](https://github.com/winglang/wing/assets/62931444/6977f762-2b20-4d62-8005-e7fc2ec55e7e)

I'm getting this scope error in code spaces not in my local system. Any idea?

**Comment by tsuf239** [comment]
> Is this an ESlint error?

hey :) 
yes, something like that,
you have an unused variable named `scope` in libs/wingsdk/src/target-sim/bucket.ts
just remove it and it'll be fine (on lines 20 and 23), I did it after checking out to your branch to test your changes on aws (it passes! 🎉 )

**Comment by Chriscbr** [comment]
Implemented in #3801
