### ISSUE TITLE
View list of all events recently published to a topic

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#2143]
### Feature Spec

In the console I would like to have a way to view a list of all events recently published to a topic, and when they were published.

### Use Cases

Debugging / so I don't have to sift through logs

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
can also be solved by seeing the logs of a specific resource. 

@Chriscbr , would that be a suitable solution for your use case?

**Comment by Chriscbr** [comment]
@ekeren Yes

**Comment by ekeren** [comment]
We will cover this as part of the log view
