### ISSUE TITLE
`cloud.GraphQL` resource

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#2155]
### Feature Spec

A resource for creating serverless GraphQL endpoints.

### Use Cases

GraphQL APIs let clients request the exact data they want and nothing more, in a standard way.

### Implementation Notes

It's also possible we could addthis to the existing `Api` resource -- we just need to think about how the APIs should look, and a rough idea of how this could be implemented across multiple public cloud providers (we want to avoid designing towards the specifics of AWS for example).

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by olivernybroe** [comment]
I think a new resource under `cloud` would be cleanest I think, e.g.

```wing
bring cloud;

let gql = new cloud.Gql('schema.gql');

gql.mutation("createPost", inflight (request: cloud.GqlRequest): cloud.GqlResponse => {
    return cloud.GqlResponse {
        title: "My title"
    };
});
```

**Comment by olivernybroe** [comment]
This is actually a duplicate of #1341

**Comment by staycoolcall911** [comment]
Thanks @olivernybroe - kept this one

**Comment by staycoolcall911** [comment]
Duplicates #4769
