### ISSUE TITLE
Restarting Wing console does not reopen the console to the same file

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#2159]
### I tried this

- Ran `wing it my_code.w`
- Wing Console told me there was an update available
- Clicked "Restart to update" in the bottom-right corner of the window
- Wing Console re-opened

### I expected this:

Wing Console opens to the same file

### Instead, this happened

Wing Console shows me a file chooser screen

### Is there a workaround?

Run `wing it my_code.w` again

### Component

Wing Console

### Wing Console Version

0.2.40

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skyrpex** [comment]
Solved by https://github.com/winglang/wing/pull/3021. There's no updater anymore.
