### ISSUE TITLE
SDK reference documentation enhancements

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#2165]
### Feature Spec

Our [SDK reference documentation](https://docs.winglang.io/reference/sdk) needs some love.
Some of the things that should be addressed:
- [x] The initializers section (see [example](https://docs.winglang.io/reference/sdk#initializers--24)) only makes sense for our `cloud` package objects (e.g. Bucket, Queue, etc.). It should be fixed for `std` package objects such as `Map`, 'Json', etc. (note that it currently calls `bring std;` which is done implicitly in wing for the `std` package). - https://github.com/winglang/wing/issues/3162
- [x] Change [ImmutableArray](https://docs.winglang.io/reference/sdk#immutablearray-) => Array, MutableArray => MutArray, etc. (for map, set as well).
- [x] https://github.com/winglang/wing/issues/3161
- [x] Add a link from the [Wing language spec](https://docs.winglang.io/reference/spec) to the relevant types in the [reference docs](https://docs.winglang.io/reference/sdk).
- [x] While you're there, please also add the `redis` package to `VISIBLE_SUBMODULES` and fremove `fs` (which was deleted) in https://github.com/winglang/wing/blob/main/apps/jsii-docgen/src/docgen/view/wing-filters.ts.
- [ ] Should also make sure the @return docstring of methods is visible (see for example [Array.ts.indexOf](https://github.com/winglang/wing/blob/91fae0528452d538e52aac196b95232d24e60e62/libs/wingsdk/src/std/array.ts#L80)).

### Use Cases

A list reference documentation for wing users

### Implementation Notes

We extended [jsii-docgen](https://github.com/cdklabs/jsii-docgen), so  most fixes are expected to be done in https://github.com/winglang/wing/blob/main/apps/jsii-docgen/src/docgen/transpile/wing.ts

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
@Chriscbr according to @staycoolcall911 you are already on it

**Comment by Chriscbr** [comment]
Initializers are hidden for types like MutArray and Array but the docs for static methods still shows `std.MutArray` etc. which is a bug

**Comment by ekeren** [comment]
opened other bugs, closing this for now
