### ISSUE TITLE
Benchmarks hide progress when run through nx

### ISSUE THREAD

**Issue by MarkMcCulloh** [winglang/wing#2201]
### I tried this

`nx bench hangar`

### I expected this:

Run benchmark, showing (mostly) the same output that the underlying `vitest` command would show

### Instead, this happened

The in-progress

### Is there a workaround?

No, although the lack of output itself is not necessarily a blocker

### Component

Development Environment

### Anything else?

When this is resolved, `bench` should be added as a target to the root `npm run build` command.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
I believe we can close this.
