### ISSUE TITLE
POST with API resource always receives an empty body in the simulator.

### ISSUE THREAD

**Issue by marciocadev** [winglang/wing#2204]
### I tried this

When I use the wing-console passing { a: 1 } in the body of a POST with this code.

```ts (wing)
bring cloud;

let api = new cloud.Api();

api.post("/", inflight (req: cloud.ApiRequest): cloud.ApiResponse => {
  log("${Json.stringify(req)}");
  return cloud.ApiResponse {
    status: 200,
    body: "test"
  };
});
```

### I expected this:

```json
{
    "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip, deflate, br",
        "connection": "close",
        "content-length": "8",
        "content-type": "text/plain;charset=UTF-8",
        "user-agent": "node-fetch",
        "host": "127.0.0.1:51207"
    },
    "body": {
        "a": 1
    },
    "method": "POST",
    "path": "/",
    "query": {},
    "vars": {}
}
```

### Instead, this happened

```json
{
    "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip, deflate, br",
        "connection": "close",
        "content-length": "8",
        "content-type": "text/plain;charset=UTF-8",
        "user-agent": "node-fetch",
        "host": "127.0.0.1:51207"
    },
    "body": {},
    "method": "POST",
    "path": "/",
    "query": {},
    "vars": {}
}
```

### Component

Wing Console

### Wing Version

0.13.8

### Wing Console Version

the last one

### Node.js Version

v18.14.2

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
This happened due to not passing in the `Content-type:application/json` header.
Perhaps we should address that at some point, to give a better DX, but since this is the behavior of most similar tools (e.g. Postman), I'm closing this for now
