### ISSUE TITLE
VS Code IntelliSense not working unless you create at least one cloud object

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#2208]
### I tried this

I tried to list all attributes and methods of `cloud` module.

### I expected this:

I expected IntelliSense to list all attributes and methods of `cloud` module.

### Instead, this happened

Intellisense wasn't giving me any prompt.

### Is there a workaround?

If you create at least one cloud object (Bucket, Queue, Function, etc.), then IntelliSense will work correctly from that point on in your code. Video showing the issue 🡆 [HERE](https://winglang.slack.com/files/U04PR9VBDQD/F054EMP3CKW/vscode-weird.mkv)

### Component

SDK

### Wing Version

0.13.13

### Node.js Version

v18.12.1

### Platform(s)

Linux

### Anything else?

No response

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Duplicates #2339
