### ISSUE TITLE
Can't load file from WSL2 in Wing Console (Windows) using `wslpath`

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#2220]
### I tried this

With Windows 10 v1803, Microsoft [introduced wslpath](https://devblogs.microsoft.com/commandline/windows10v1803/#interoperability). This tool allows you to convert paths from within your Linux environment to URI‑compliant paths that Windows can understand, thus allowing your Windows OS to access files that live in WSL2 very easily.

My problem is that, when I run `wing it <path-to-file.w>` from Windows, the Wing Console keeps loading forever and I'm unable to determine what's the culprit that causes the issue.

`<path-to-file.w>` in this case is the path to a file within WSL2 that got converted by `wslpath`.

### I expected this:

I expected Wing Console to compile to sim target and load my app.

### Instead, this happened

Wing Console opened up and got stuck in a loading loop.

### Component

Wing Console

### Wing Version

0.13.16

### Wing Console Version

0.2.6.1

### Node.js Version

18.15.0

### Platform(s)

Linux, Windows

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
@garysassano , we  have moved away from using electron. Do you mind verifying if the problem still exists?
