### ISSUE TITLE
Webhook Local Development Experience (ngrok-like capabilities)

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2227]
### Feature Spec

Wing now has built-in support for developing applications that receive webhooks (such as slack bots, github apps and more).

DX to be defined

### Use Cases

Webhook development

### Implementation Notes

Basically, we will need some kind of support for an ngrok-like service where users are able to allocate some stable public dns name on the internet and requests will be routed to their local machine.

### Component

SDK, Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment]
Changing to p1

**Comment by skorfmann** [comment]
btw: a hacky workaround for this could be something like https://gist.github.com/skorfmann/c3bb0f53e5f244cb7b1f13f15c6a499b in combination with [Tailscale Funnel](https://tailscale.com/kb/1223/tailscale-funnel/)

**Comment by eladb** [comment]
super keep

**Comment by staycoolcall911** [comment]
Please look at the thread #2271

**Comment by eladb** [comment]
https://vt.tiktok.com/ZSLKXLfWU/

**Comment by Chriscbr** [comment]
@eladb Is this solved by the ngrok winglib?

**Comment by eladb** [comment]
We are looking into a more holistic approach. @eladcon is on it.

**Comment by staycoolcall911** [comment]
We have that implemented via tunnels. Closing
