### ISSUE TITLE
Wing console not reloading app when saving an extern file

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2238]
### I tried this

Update an extern file in my wing app

### I expected this:

The console to reload

### Instead, this happened

No reload

### Is there a workaround?

Touch the .w file

### Component

Compiler, Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
suggested solution:
watch: all files and directories under .w file parent dir.
ignore: node_modules and target directories
