### ISSUE TITLE
Unable to define inflight init

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2239]
### I tried this

```js
resource MyResource {
  init() { }
  inflight init() { }
}
```

### I expected this:

To be supported

### Instead, this happened

```sh
1 | resource MyResource {
  |          ^^^^^^^^^^ Symbol "init" already defined in this scope
```

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
Fixed by #2021
