### ISSUE TITLE
a way to see all resource and which targets they are currently available in

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#2240]
**Goal:** have a one stop shop for wing users to see which resources are supported on which target, also what functionality is supported on these resources

See attache image from the [slack discussion](https://winglang.slack.com/archives/C047QFSUL5R/p1682067832653459)
![image](https://user-images.githubusercontent.com/1727147/233950557-827d0466-2bfe-42ee-8ae7-039d4e519518.png)

**Comment by ShaiBer** [comment]
Nice! I opened #2241 to add this to the FAQ

**Comment by schosterbarak** [comment]
Having a CTA to recompile all or a portion of what is supported to a new target can be cool (Next step) too

**Comment by ekeren** [comment]
> Having a CTA to recompile all or a portion of what is supported to a new target can be cool (Next step) too

@schosterbarak , I am not sure I completely understand this, can you elaborate please

**Comment by schosterbarak** [comment]
If I have V across all targets in the table, it would be cool to have "port resource from current to selected target" call to action on the table

**Comment by ekeren** [comment]
Currnently we zero'ed in on something similar to this:
![image](https://user-images.githubusercontent.com/1727147/235470133-e1cf828e-d04f-4ae4-ac7d-10fedb153046.png)


@tsuf239 will work on a more realistic example that takes into account our data (but still static)

**Comment by ekeren** [comment]
☝️ is from https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#browser_compatibility

**Comment by garysassano** [comment]
@ekeren That looks great, I like it!

**Comment by ekeren** [comment]
Another example, closer to our data.  (thanks @tsuf239) 

Feedback is welcomed 

![image](https://user-images.githubusercontent.com/1727147/235885228-cdc63d1a-4516-4c64-88d9-c52df7ce5089.png)

**Comment by Chriscbr** [comment]
@ekeren I really like it!

**Comment by tsuf239** [comment]
fixed by #2388
