### ISSUE TITLE
Add resource table to FAQ

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2241]
### Feature Spec

Add the resource table from #2240 to the FAQ

### Use Cases

So developers will know which resources are supported where

### Component

Documentation

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
Our compatibility matrix is linked from the FAQ here now (https://www.winglang.io/docs/faq/supported-clouds-services-and-engines/supported-services)
