### ISSUE TITLE
Console: improve ergonomics of displaying large log entries

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2245]
### I tried this

Emit a log entry with lots of content

### I expected this:

To allow me to expand/collapse the log line and view the entire contents

### Instead, this happened

I wasn't able to view the entire line

### Is there a workaround?

None

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skyrpex** [comment]
Expanding and collapsing log entries was implemented a long ago, can't recall exactly when.

If this is still an issue, feel free to reopen.
