### ISSUE TITLE
URLs should be clickable in the Wing Console log

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2247]
### Feature Spec

When a log in Wing Console contains a URL, it can be clicked

### Use Cases

Follow URLs

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
Resolved in https://github.com/winglang/wing/pull/4717
