### ISSUE TITLE
Test functions shouldn't be deployed when deploying for production (I think)

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2250]
### I tried this

compile & deploy a wing app

### I expected this:

The `test:*` cloud functions not to be included in my deployment, because that's a production system

### Instead, this happened

They were included

### Component

Compiler, SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
How does a user indicate they are compiling an app for production vs for testing in a staging account?

**Comment by MarkMcCulloh** [comment]
This no longer occurs: `wing test` includes test infra while `wing compile` does not.
