### ISSUE TITLE
Add new operations to resources and specify IAM permissions

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#2260]
### Feature Spec

This capability allows developers to implement a new API to a resource even if that specific API requires permissions that are not modeled in the system

### Use Cases

currently `queue.pop` doesn't exist, if a user wants to overcome this problem locally, he can choose to add an extern function that implements the pop command using aws-sdk.

The problem that this operation needs to add the desired IAM roles for the queue instance. 

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment]
OK, I am going to try and implement this and see where I get.

First attempt:

```js
bring cloud;

resource QueueWithPop {
  q: cloud.Queue;

  init() {
    this.q = new cloud.Queue();
  }

  inflight pop(): Json {
    this._queue_pop(this.q);
  }

  extern "./pop.js" inflight _queue_pop(queue: cloud.Queue): Json;
}

new QueueWithPop();
```

Error is really nice (who wrote it?):

```
   |                     ^^^^^^ Unable to qualify which operations are performed on 'this.q' of type 'Queue'. This is not supported yet.
```

**Comment by Chriscbr** [comment]
This should be possible now through the `onLift` hook and the `aws.Queue.from()` API:

```js
bring aws;
bring cloud;

class CustomQueue {
  queue: aws.IAwsQueue;
  new() {
    let queue = new cloud.Queue();
    if let awsQueue = aws.Queue.from(queue) {
      this.queue = awsQueue;
    } else {
      throw "only AWS targets supported";
    }
  }
  pub inflight push(item: Json) {
    CustomQueue._push(this.queue.queueUrl, item);
  }
  extern "./queue.js" inflight static _push(queueUrl: str, item: Json);
  pub onLift(host: std.IInflightHost, ops: Array<str>) {
    if let awsFn = aws.Function.from(host) {
      let actions = MutArray<str>[];
      if ops.contains("push") {
        actions.push("sqs:SendMessage");
      }
      awsFn.addPolicyStatements({
        actions: actions.copy(),
        effect: aws.Effect.ALLOW,
        resources: [this.queue.queueArn]
      });
    } else {
      throw "only AWS targets supported";
    }
  }
}

let q = new CustomQueue();

new cloud.Function(inflight () => {
  q.push({ "key": "value" });
});
```

There seems to be a runtime error caused by queueUrl not getting lifted properly - I've opened a separate issue for this (https://github.com/winglang/wing/issues/6960).
