### ISSUE TITLE
Playground "You are running an incompatible node.js version v16.14.2. Compatible engine is: >=v18.0.0."

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2261]
### I tried this

Use the playground

### I expected this:

Not to show this error

### Instead, this happened

```
WARNING: You are running an incompatible node.js version v16.14.2. Compatible engine is: >=v18.0.0.
```

### Component

Other

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment]
@eladcon can you take a look?

**Comment by ShaiBer** [comment]
OK, better than nothing I guess :)

**Comment by ekeren** [comment]
@eladcon, I think this was removed... right?
