### ISSUE TITLE
Confusing errors when @winglang/sdk is installed separately

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#2280]
### I tried this

1. Install a recent version of Wing globally as recommended in the docs (`npm i -g winglang`)
2. Install an old version of the SDK separately (e.g. `npm i @winglang/sdk@0.8.43`)
3. Run `wing compile hello.w` on a basic Wing app

### Instead, this happened

A confusing preflight error

```
preflight error: $stdlib.core.App.for is not a function

  note: intermediate javascript code (/Users/chrisr/dev/wing-demo/target/hello.wsim.691358.tmp/.wing/preflight.js):
   const $outdir = process.env.WING_SYNTH_DIR ?? ".";
   const $wing_is_test = process.env.WING_IS_TEST === "true";
>> const $AppBase = $stdlib.core.App.for(process.env.WING_TARGET);
   const cloud = require('@winglang/sdk').cloud;
   class $Root extends $stdlib.std.Resource {
  note: run with `NODE_STACKTRACE=1` environment variable to display a stack trace
```

### I expected this:

Either:
* No error (winglang should use the version of the SDK bundled with it, and not the version installed in my current directory)
* A warning saying that there is a version mismatch between the version number of `winglang` and the runtime `@winglang/sdk` being used, with link troubleshooting information

### Component

CLI

### Wing Version

0.13.25

### Node.js Version

18.14.1

### Platform(s)

MacOS

### Anything else?

In this case the error was very up-front (it prevented the app from compiling), but if the version of Wing SDK installed locally is only slightly outdated, the errors or problems could be more subtle.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
@Chriscbr - since the getting started guide doesn't have a section for testing programmatically - do you think we should close this issue as the use case is expected to be very rare?

**Comment by Chriscbr** [comment]
@staycoolcall911 Sounds good
