### ISSUE TITLE
`cloud.Table.update()` accepts any `Json` object without throwing any error

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#2283]
### I tried this

```
bring cloud;

let table = new cloud.Table(
  primary_key: "id",
  name: "test-table",
  columns: {
    name: cloud.ColumnType.STRING,
  }) as "table";

let file1 = Json { id: "1", name: "Three 3" };
let file2 = Json { id: "1", name: "Three Ⅲ" };
let file3 = Json { id: "☁", name: "uʍop ǝpısdn" };

new cloud.Function(inflight(msg:str): str => {
  table.insert(file1);
  table.insert(file3);
  log(table.list());
  let lista: Map<Json> = table.list();
  table.update(Json "[{random thing}]");
  log(table.list());
}) as "test:update";

```
I run this test expecting it to fail.

### Instead, this happened

Test passed and it added an `undefined` object to my `cloud.Table`.

### I expected this:

I expected test to fail and throw an error.

### Component

SDK

### Wing Version

0.13.31

### Node.js Version

v18.12.1

### Platform(s)

Linux

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by marciocadev** [comment]
@garysassano When using the table, you need define a valid Json object to update or insert

this line `table.update(Json "[{random thing}]");` doesn't make sense, as the valid data must have `id` and `name` properties as defined in the table.

a valid update was `table.update(Json { id: 1, name: "something" });`

you cannot insert a list in this table

**Comment by garysassano** [comment]
@marciocadev I agree with you, and the problem is that it doesn't throw any error. On the other hand, if I try to update an item that doesn't exist, you do indeed get an error.

Trying to update an item with id 3: `table.update(Json { "id": "3", "name": "something" });`
If you add this code, you get the following error:

```
 TypeError: Cannot set properties of undefined (setting 'name')
     │     at Object.activity (/home/user/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-sim/table.inflight.js:40:35)
     └     at async Object.withTrace (/home/user/.volta/tools/image/packages/winglang/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/testing/simulator.js:71:38)
```
