### ISSUE TITLE
Return optional on Queue.pop

### ISSUE THREAD

**Issue by flyingImer** [winglang/wing#2284]
### Feature Spec

In current spec, `inflight pop(): Json;`, however, this assumes messages exist in the queue, or it throws runtime exception otherwise. Cloud implies being distributed. Even `peek` ahead of `pop` does not guarantee the message existence. Hence, runtime exception handling is inevitable. 

From developer standpoint, it would be smoother to have `inflight pop(): Json?;`. Instead of dealing with `try...catch`, it can be as simple as:
```
if let msg = myQueue.pop() {
  // process my message
} else {
  log("no message");
}
```

### Use Cases

This allows blind queue polling without worrying out runtime exceptions on an empty queue.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by fynnfluegge** [comment]
@flyingImer Guess this can be closed right? Seems that github does not recognize Closes #issues concatenized with *and* in PR description.
