### ISSUE TITLE
vscode: missing error when initializing two buckets 

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#2287]
### I tried this

```ts (wing)
bring cloud;

let a = new cloud.Bucket();
let b = new cloud.Bucket();

```

### Instead, this happened

vscode extension didn't show any errors, although this doesn't compiel

### I expected this:

to show the compilation error

### Component

IDE Extension

### Wing Version

0.13.33

### Anything else?

After talking to @MarkMcCulloh  I understand that the root cause here is that our compiler only runs into that during execution of preflight. the lsp does not do this part

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Related to #2623

**Comment by Chriscbr** [comment]
Construct IDs can be dynamically generated so it's not possible to know this information until the compiler executes your preflight code. 

For example:

```js
bring cloud;

let calculateNum = (): num => {
  // perform complex calculation...
  return 5;
};
let n = calculateNum();
new cloud.Bucket() as "foo-${n}";
```

This second phase of compilation (where wing runs some generated JS code) can take an unbounded amount of time, so I'm not sure if it would be practical to expose this to the LSP.

**Comment by Chriscbr** [comment]
Closing as unactionable.
