### ISSUE TITLE
handling relative paths in wing files

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#2290]
### Feature Spec

Right now we pass the absolute directory of the executed wing file as an env var, upon compilation. This approach may be ok for now, when we compile a single wing file at a time, but will probably fail in the future when we'll support multiple files and directories within a wing project.

We need a more robust approach for the compiler to be able to inject the wing source file path into the resource constructor so it will be possible to resolve it.

Here's a "simple" idea: we can have the wing compiler always pass a special prop into all resources called `$wing` which will include stuff like the source file path that initialized this resource.

This is only a hidden runtime thing, so basically it won't be part of the public api but resource implementors can use it.

_Posted originally by @eladb in https://github.com/winglang/wing/pull/2164#discussion_r1176409031_

### Use Cases

Reading a directory, serving a static website, uploading a file to a bucket, etc...

### Component

Compiler, SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment]
P3

**Comment by MarkMcCulloh** [comment]
Resolved by https://github.com/winglang/wing/pull/6443 with `@dirname` which can be used to create paths relative to the current sourcefile
