### ISSUE TITLE
Terraform apply sometimes spits an error "unrecognized remote plugin message"

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#2293]
### I tried this:

Compiled a non-trivial wing app (e.g. [the WhereToEat app](https://github.com/winglang/research/tree/main/dogfooding/where-to-eat)) multiple times, making changes to the wing code, then recompiling. Also witnessed the same behavior when making changes to a static website code.

1. Making code-changes
2. Compiling for target tf-aws
3. Running `terraform apply`

### This happened:

Sometimes (but not every time - once in 5 attempts) an error shows:
```sh
╷
│ Error: Unrecognized remote plugin message: 
│ 
│ This usually means that the plugin is either invalid or simply
│ needs to be recompiled to support the latest protocol.
│ 
│ 
╵
```
<img width="603" alt="image" src="https://user-images.githubusercontent.com/106860404/234863525-cc3d5ceb-0513-4d2e-bee3-c3cbf89ef686.png">

### I expected this:

`terraform apply` should always work

### Is there a workaround?

Recompiling to tf-aws target solves the issue

### Component

SDK

### Wing Version

0.13.34

### Node.js Version

19.3.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skorfmann** [comment]
> Sometimes (but not every time - once in 5 attempts) an error shows:

Was the `terraform apply` done in parallel or sequentially?

**Comment by staycoolcall911** [comment]
Haven't seen that in a while - closing for now
