### ISSUE TITLE
wing console: consider removing the cloud.Functions inside the api view

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#2341]
### I tried this:

I would consider hiding the cloud.Function inside the api. 
Although it does bring value to see them, this information is also available in the cloud.Api view  

```ts (wing)
bring cloud;
let api = new cloud.Api();

api.get("/test-get", inflight (req: cloud.ApiRequest): cloud.ApiResponse => {
  return cloud.ApiResponse {
    status: 200,
    body: {
      query: Json (Json req).get("query"),
    }
  };
});
api.post("/test-post", inflight (req: cloud.ApiRequest): cloud.ApiResponse => {
  return cloud.ApiResponse {
    status: 200,
    body: "Hello, POST!"
  };
});

```

```sh
wing it app.w
```

### This happened:

![image](https://user-images.githubusercontent.com/1727147/235458283-19961938-85aa-4230-b08c-647ed50c0ee0.png)

### I expected this:

![image](https://user-images.githubusercontent.com/1727147/235458356-21060f44-fae6-4489-905c-9185730e27ef.png)

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
We can hide this in the SDK pretty easily. Should we also have a way to show all `hidden` resources in the Wing console?

**Comment by ekeren** [comment]
> Should we also have a way to show all hidden resources in the Wing console?

In the future we will allow people to see even more then that, like the aws resources and such

**Comment by ekeren** [comment]
Keep

**Comment by ainvoner** [comment]
see [The Console API resource should display the route path#4383](https://github.com/winglang/wing/issues/4383)
