### ISSUE TITLE
Playground doesn't work well on Mobile (also when switching to desktop mode) and doesn't display a message to use a computer

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2348]
### I tried this:

I tried the playground on mobile (both regular and desktop mode)

### This happened:

There are many issues there that make it unusable.
- Cannot edit the code
- Cannot resize the editor/map view
- Visual artifacts with misalignment of buttons and other components
- Cannot interact with items on the map view

### I expected this:

To be able to work with it, or get a message telling me it only works on desktop

### Is there a workaround?

Working on desktop

### Component

Playground

### Platform(s)

Other

### Anything else?

I think we should display a message saying that the playground only works on desktop for now.
Then we need to see what amount of work needs to be put in to make it work on mobile and whether it makes sense to invest it.
I think that if its not a lot of work it might make sense since we want to direct developers from social platforms to the playground, and most people consume these from their phones.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
duplicate [#2499](https://github.com/winglang/wing/issues/2499)
