### ISSUE TITLE
cloud.Schedule support sub-minute schedules

### ISSUE THREAD

**Issue by hasanaburayyan** [winglang/wing#2350]
### Feature Spec

Support creating schedules with sub-minute intervals. 
```ts
bring cloud;

let s = new cloud.Schedule(rate: 30s);

```

### Use Cases

enables sub-minute scheduled events. 

### Implementation Notes

See CDK implementation here: https://constructs.dev/packages/cdk-lambda-subminute/v/2.0.109?lang=typescript

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
duplicates #1551
