### ISSUE TITLE
Bucket on console with events view

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#2356]
```ts (wing)
bring cloud;

let bucket = new cloud.Bucket();
bucket.on_create(inflight (m:str, type: cloud.BucketEventType) => {});
bucket.on_create(inflight (m:str, type: cloud.BucketEventType) => {});
bucket.on_create(inflight (m:str, type: cloud.BucketEventType) => {});
bucket.on_create(inflight (m:str, type: cloud.BucketEventType) => {});
bucket.on_delete(inflight (m:str, type: cloud.BucketEventType) => {});

```

The result in the console is:
![image](https://user-images.githubusercontent.com/1727147/235611576-7edd9078-2064-4a68-a419-ba49c5c606dd.png)

Which is pretty cool, but we are basically seeing the internal implementation of a bucket. Similar to #2341, there might be an opportunity here to have a smaller representation of this view that will  present the same amount of information

**Comment by marciocadev** [comment]
I understand what you mean, Eyal, and I agree for two reasons.

The first is that this representation allows you to send messages through the Topic in the console, which does not reflect the code.

And the second is that by displaying the internal construction of the Bucket, the focus seems to shift to the infrastructure and not to the practical result.

An example is in creating the same type of events for the Table. While in the simulator we can use a Topic connected to an inflight function, in AWS we have to emit an event through DynamoDB directly to Lambda. Or if we want to use the Topic, we have to emit the DynamoDB event to EventBridge Pipes, which sends it to the Topic to deliver to Lambda. This way, the representation in the console exposes too much information, making it different from what exists in AWS, but it can also be different from any other cloud.
