### ISSUE TITLE
Update console Api view to retrieve routes from openapi spec

### ISSUE THREAD

**Issue by hasanaburayyan** [winglang/wing#2363]
### Feature Spec

With the new dependency inversion that was added to api resource this introduces a breaking change in the console that requires the console to aggregate the routes from event mappings rather than just on the api `schema.props.routes`

### Use Cases

It unbreaks the api resource in the console

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by polamoros** [comment]
related to https://github.com/winglang/wing/pull/2389
