### ISSUE TITLE
Avoid overriding the primary key when inserting into a table resource

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#2372]
### I tried this:

```
bring cloud;
let table = new cloud.Table(cloud.TableProps{
  name: "simple-table",
  primary_key: "id",
  columns: {
    id: cloud.ColumnType.STRING,
    name: cloud.ColumnType.STRING,
  },
});

new cloud.Function(inflight (message: str): str => {
   table.insert("1", {
    id: "2",
    name: "John",
  });
});
```

### This happened:

<img width="351" alt="image" src="https://user-images.githubusercontent.com/5547636/235878725-78e6c848-8fea-4f58-b9e0-ca6b0f321e1f.png">

### I expected this:

The primary key should override the column value.

### Is there a workaround?

Avoid passing a different value for the primary_key inside the row data.

### Component

SDK

### Anything else?

It was introduced by [this PR](https://github.com/winglang/wing/pull/2307).

Moving the primar_key setter under the loop [here](https://github.com/winglang/wing/blob/main/libs/wingsdk/src/target-sim/table.inflight.ts#L43-L46) should do the trick (same for the other inflights).

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
I was able to reproduce this after modernizing the code to:
```ts
bring cloud;
bring ex;
let table = new ex.Table(ex.TableProps{
  name: "simple-table",
  primaryKey: "id",
  columns: {
    id: ex.ColumnType.STRING,
    name: ex.ColumnType.STRING,
  },
});

new cloud.Function(inflight () => {
   table.insert("1", {
    id: "2",
    name: "John",
  });
});
```

**Comment by Chriscbr** [comment]
`cloud.Table` / `ex.Table` is no longer in the SDK - we recommend using the `postgres` or `dynamodb` winglibs instead. Closing
