### ISSUE TITLE
compiler complains about void but void doesn't exists the language

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#2378]
### I tried this:

```ts (wing)
bring cloud;

new cloud.Function(()=>{});
```

### This happened:

```
Error: Command failed: wing compile ./test.w -t sim
error: Expected type to be "IFunctionHandler (inflight (str): void)", but got "preflight (): void" instead
  --> .[/test.w:6:20](vscode://file//test.w:6:20)
  |
6 | new cloud.Function(()=>{});
  |                    ^^^^^^ Expected type to be "IFunctionHandler (inflight (str): void)", but got "preflight (): void" instead
```

### I expected this:

Notice that the requested handler is `inflight (str): void` while `: void` is not legal in the code

### Component

Compiler

### Wing Version

0.15.0

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
> May be a duplicate of https://github.com/winglang/wing/issues/2234

Right, but in my opinion this is not the same urgency .

**Comment by staycoolcall911** [comment]
Solve this issue by adding `void` as return type - see issue #2234

**Comment by staycoolcall911** [comment]
Duplicate #2234
