### ISSUE TITLE
Playground: code blocks are not automatically created

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2381]
### I tried this:

Type `class Foo {` and press ENTER.

### This happened:

https://user-images.githubusercontent.com/598796/235913305-1bb84c70-8310-413d-ac32-4ee5c6796184.mov

The `}` was not added automatically and the indentation did not happen.

### I expected this:

https://user-images.githubusercontent.com/598796/235912921-a2ecfd90-0c58-40db-b060-e59d7e0fd336.mov

### Is there a workaround?

Just type this stuff like in the 90s

### Component

Playground

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
Monaco should support the use of the same language config file we have for the vscode extension https://github.com/winglang/wing/blob/main/apps/vscode-wing/language-configuration.json

This is where the auto-closing (and some other stuff) comes from.
