### ISSUE TITLE
why a language awscdk code is funky

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#2395]
![image](https://user-images.githubusercontent.com/1727147/236136638-a5e0c85e-3929-4ab3-b121-3bc983fb9312.png)

**Comment by ShaiBer** [comment]
@ekeren 
Looks like for some reason it displays it all in one line.
There is a button there to unwrap it, do you see it?
I wonder why it wrapped it into one line for you?
You have an idea?

**Comment by ekeren** [comment]
I don't see the button to unrwap, where is it?

**Comment by ekeren** [comment]
I had the button to unwrap on CDKTF, and it worked, but it disappeared

**Comment by ekeren** [comment]
even when I unwrap, it doesn't make complete sense 
![image](https://user-images.githubusercontent.com/1727147/236142673-875f0525-9f90-4f31-bc6f-6c39615bc405.png)

**Comment by ShaiBer** [comment]
Yes, it doesn't return it to the original state.
I'm trying to find out when it decides to wrap it on its own

**Comment by ShaiBer** [comment]
Fixed a while back
