### ISSUE TITLE
compatibility matrix improvements

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#2399]
### Feature Spec

a list of improvements to the compatibility matrix

### Use Cases

improving our beloved matrix 😊 

### Component

Documentation

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by tsuf239** [comment]
- [ ]  light mode version issue link color might be too pale

**Comment by garysassano** [comment]
Two things I would change: 1) The `Resource` column should be renamed to `Class` to reflect the recent changes introduced by #2270, and then maybe call the other column `Method`? 2) The table as it is now is quite bulky and hard to navigate, so I'd try to make it lighter to scroll. Possibly I would like to have a compressed view showing just the names of the classes, and when you click on each name you can expand it to show all related methods.
