### ISSUE TITLE
Queue.purge test needs to be able to reflect the real size of the queue

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#2402]
### I tried this:

run this code in `wing test -t tf-aws`:
```
bring cloud;

let q = new cloud.Queue();

new cloud.Function(inflight () => {
  q.push("foo");
  q.push("bar");
  q.push("baz");
  assert(q.approx_size() == 3);
  q.purge();
  assert(q.approx_size() == 0);
}) as "test";
```

### This happened:

<img width="923" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/39455181/234845500-4eed5982-64b0-4704-a70e-5afd01fbd9e5.png">

### I expected this:

to run without problems

### Component

SDK

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by revitalbarletz** [comment]
The test uses approx_size which is problematic as the size is probably not reflecting the accurate size at this stage of the test. If you look at the error - the first call to approx_size is the one that is failing, not the one called after purge, therefore I suspect that the test needs to be re-written.
