### ISSUE TITLE
As a contributor I want to make changes to the documentation even faster by avoiding running all tests when merging to main

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#2428]
### Feature Spec

We would like to avoid running all tests when a PR is created against the documentation under https://github.com/winglang/wing/tree/main/docs

Followup for #1088. 

After the work done in PR #2346 for doc changes - we're skipping tests on the dev branch.
We want to also avoid unnecessary steps when the dev branch merges to `main`.

This allows very quick iterations on the docs.

CC: @MarkMcCulloh, @WeepingClown13, @ShaiBer 

### Use Cases

See #1088

### Component

Documentation, Contributor Experience

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by WeepingClown13** [comment]
@MarkMcCulloh do you think this was the solution?
 https://github.com/winglang/wing/pull/2346#discussion_r1181709828

I believe this would skip the release altogether on pure docs changes, which was how I intended it. Instead it'd be just released in the next non docs-only release. Well, as I understand it anyway😅

**Comment by WeepingClown13** [comment]
While we are on the topic, how necessary is the _needs.build_ in the _publish_ job? As I see it, the job also needs _quality gate_ which in turn _needs build_. So when quality gate is needed, I can't help but feel the seperate need for build is simply redundant.

**Comment by MarkMcCulloh** [comment]
> I believe this would skip the release altogether on pure docs changes, which was how I intended it. Instead, it'd be just released in the next non docs-only release. Well, as I understand it anyway

[This workflow](https://github.com/winglang/wing/blob/main/.github/workflows/update-docsite.yml) relies on published release to update the docsite. Definitely open to changes on that, but disabling doc changes from releasing is not enough on it's.

> While we are on the topic, how necessary is the needs.build in the publish job? As I see it, the job also needs quality gate which in turn needs build. So when quality gate is needed, I can't help but feel the seperate need for build is simply redundant.

I see what you mean, but there is a quirk of github actions here. When it comes to getting outputs from previous jobs, `need` is not transitive. If `A` `need`s `B`, and `B` `need`s `C`, The final execution order will be as expected (C>B>A) but A will not be able to directly reference output values from C without `A` `need`ing `B`. The publish job needs to directly reference output from `build`, so it needs to explicitly `need`.

**Comment by staycoolcall911** [comment]
This is done
