### ISSUE TITLE
`cloud.Bucket` can only have one event notification at a time when compiled to `tf-aws`

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#2439]
### I tried this:

`wing compile --target tf-aws file.w`

### file.w
```
bring cloud;

let b = new cloud.Bucket() as "Bucket";

b.on_delete(inflight(e:str) => {
  log("delete ${Json.stringify(e)}");
});
```
`terraform apply`

`wing compile --target tf-aws file.w`

### file.w
```
bring cloud;

let b = new cloud.Bucket() as "Bucket";

b.on_delete(inflight(e:str) => {
  log("delete ${Json.stringify(e)}");
});

b.on_create(inflight(e:str) => {
  log("update ${Json.stringify(e)}");
});
```
`terraform apply`

### This happened:

I played around with this `file.w` for several hours and I noticed that if you deploy the S3 Bucket with one Event Notification it works just fine. But then, once you add a second Event Notification and do a `terraform apply` to update the configuration, it will delete the first Event Notification and overwrite it with the second one.

There seems to be an issue in the way Wing generates the Terraform template when there are more than one Event Notification for an S3 Bucket.

This issue is related to #2308

### I expected this:

I expected the S3 Bucket to be created with multiple Event Notifications.

### Component

SDK

### Wing Version

0.15.23

### Node.js Version

18.16.0

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Duplicates #2308
