### ISSUE TITLE
Set up PagerDuty and rotations for wing maintainers

### ISSUE THREAD

**Issue by MarkMcCulloh** [winglang/wing#2447]
See https://github.com/winglang/wing/blob/main/docs/06-contributors/99-maintainers/050-operations.md#on-call for details. If an alternative to pagerduty is desired, that doc should be updated as well.

**Comment by tsuf239** [comment]
Due to a limitation of PagerDuty, docs were updated in this PR. https://github.com/winglang/wing/pull/2646

**Comment by tsuf239** [comment]
PagerDuty accounts are set,  betterUptime alerts are connected, and documentation is up to date :)
