### ISSUE TITLE
Winglang cheatsheet

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2449]
inspired by [Go cheatsheet](https://devhints.io/go)

We want to have the same type of page, and use it also in the winglang tour

**Comment by skorfmann** [comment]
This would be super helpful! In the best case somehow tested / verified against the latest version of Wing

**Comment by ShaiBer** [comment]
> This would be super helpful! In the best case somehow tested / verified against the latest version of Wing

Yes, and there is already a PR for this: #2469 that was closed recently, but it might be revived by @Chriscbr as part of his work on the documentation

**Comment by ekeren** [comment]
opened other issues (see user-story:"docs: examples")
