### ISSUE TITLE
Container Types: Array

### ISSUE THREAD

**Issue by yoav-steinberg** [winglang/wing#246]
https://github.com/winglang/wing/blob/main/docs/04-reference/winglang-spec.md#112-container-types

Basically see what was done for map and struct literals and adopt it accordingly.

```
let y: Array<num> = [1,2,3];
let w = [1,2,3]; // And inference too
let z: Array<MyStruct> = [MyStruct {f1: 2;}, MyStruct {f1: 3;}]
```

**Comment by staycoolcall911** [comment]
This was done in #1045
