### ISSUE TITLE
Doc and Blog headers should be the same as our Website, with links and CTAs

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2477]
### Feature Spec

The doc and blog headers are not like the website header, with relevant links and CTAs (docs/blog, community, getting started, Github, Slack, or whatever else we'll add to the website)

### Use Cases

When users explore our docs/blog they don't have links to the homepage or to Github, and not CTA to star us or join our slack

### Implementation Notes

Need to see how to do this in Docusaurus.
We can either use implementation from the website or from the playground

### Component

Other

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
Done
