### ISSUE TITLE
Provide Feedback if the Wing Console is missing for CLI commands

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#2488]
### Feature Spec

When installing the wing CLI without having the wing Console installed, the commands `wing run / it` will do nothing without any feedback to the user. It might appear like something is broken in the codebase.

Would be nice to have a little info message suggesting to download the console from https://docs.winglang.io/getting-started/installation#wing-console 

### Use Cases

In particular for cases where people will just explore wing code bases and only skimming through docs, this will be quite helpful.

### Component

CLI

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Thanks for reporting.
This duplicates another issue on our repository: #407
