### ISSUE TITLE
Improve compilation artifacts display in playground/tutorial

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2494]
### Feature Spec

When compiling in the playground/tutorial to a real cloud, the compilation artifacts are clearly displayed

### Use Cases

So users understand what they get

### Implementation Notes

I think that as first step, clicking a compile button should open a modal like in the playground for the tutorial too.
But in this view, we should show the folder/file structure of the output and open the Terraform file by default so users see the structure of the app and all the code.
While the compilation takes place, we can display an explenation in the modal saying that we compile to Terraform and Javascript and generate least Privilage IAM policies, network topologies and other cloud mechanics.

### Component

Playground, Tutorial

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
already done
