### ISSUE TITLE
Playground/Tutorial don't bounce back after LSP crash

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2496]
### I tried this:

Typed code in the tutorial instead of pasting

### This happened:

LSP crashes and did not rebound for the reminder of the tutorial

### I expected this:

The crash to be detected and the LSP restarted

### Component

Playground, Tutorial

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
We need to check if there is a way to see if the LSP has crashed

**Comment by ekeren** [comment]
it does bounce back
