### ISSUE TITLE
Improve map-view hover state in Console/Tutorial/Playground

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2497]
### I tried this:

Hovered elements in the map view of the console/playground/tutorial

### This happened:

Hover state is weird
### I expected this:

Good hover state

### Component

Playground, Tutorial, Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
Hover states exists, closing

**Comment by ShaiBer** [comment]
Re-opening and changing the phrasing to improve it :)

**Comment by polamoros** [comment]
Hi @ShaiBer. Any suggestion on what would you expect for the hover state? What do you think it feels wired, the ring of the hovered resource or all the other resources fading out?

@ekeren FYI

**Comment by ShaiBer** [comment]
> Hi @ShaiBer. Any suggestion on what would you expect for the hover state? What do you think it feels wired, the ring of the hovered resource or all the other resources fading out?
> 
> @ekeren FYI

Actually I think @ainvoner can better explain exactly what he expects to see there
