### ISSUE TITLE
Add message if device is not supported in playground/tutorial

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2499]
### Feature Spec

Users who try to use the Playground/Tutorial from mobile get a clear message that it is not supported and are directed to desktop

### Use Cases

So users don't get frustrated that it is not working well for them on mobile

### Implementation Notes

We can possibly also make it work well on mobile, but there are multiple issues to solve for this, so easier at first to explicitly not support mobile

### Component

Wing Console, Playground, Tutorial

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by polamoros** [comment]
uncomment this code
https://github.com/winglang/playground/blob/12650b7002108608c900c936e3e6af7365120293/apps/playground/src/App.tsx#L12-L18

**Comment by ekeren** [comment]
@polamoros the message is not good there. 

**for playground**: Winglang playground experience works only on chrome on desktops, please open this page in chrome or try our [getting started guide](https://winglang.io/docs)

**for learn**: Winglang learn experience works only on chrome on desktops, please open this page in chrome or try our [getting started guide](https://winglang.io/docs)

**Comment by ShaiBer** [comment]
I would add there that it is because our use of webcontainers to get some sympathy :)
