### ISSUE TITLE
Remove instructions from comments in Playground

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2504]
### Feature Spec

Playground is now self-explanatory enough that instructions are no longer needed inside the code comments

### Use Cases

Reduce the amount of text in the examples.
Users don't need to read the instructions in the comments to understand how the playground works.

### Component

Playground

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
The Playground itself is actually not that self explanatory.... If someone lands there before the learn experience he will know very little
