### ISSUE TITLE
Update supported browsers for Playgorund/Tutorial

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2513]
### Feature Spec

Users on supported browsers by WebContainers can access the Tutorial/Playground. Those who don't, get a clear message to use one of the supported ones

### Use Cases

Users of supported browsers now get a message to use Chrome

### Component

Playground, Tutorial

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
duplicate [#2499](https://github.com/winglang/wing/issues/2499)
