### ISSUE TITLE
Remove root and/or default layer from the map view of the console/tutorial/playground

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2514]
### Feature Spec

Remove unnecessary layers from the map view of the console (and playground/tutorial)

### Use Cases

These layers that are not in the code are confusing users

### Component

Wing Console, Playground, Tutorial

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skyrpex** [comment]
https://github.com/winglang/console/pull/546#issuecomment-1550904905

I think the Root node should also be removed from the Console (both in the tree and the map view) as it doesn't really exist in Wing code.

**Comment by ainvoner** [comment]
perhaps we can change its' name to App instead?
