### ISSUE TITLE
Find a better way to display arrows when an inflight class method accesses class resources

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2515]
### Feature Spec

Clean up map view when there are inflight class members are accessed

### Use Cases

The multiple arrows we display now are confusing

### Implementation Notes

Right now we show an error to the object, and also arrows to it resources.
We should probably just have one arrow to the class method, and maybe arrows from the method to the resources 

### Component

Wing Console, Playground, Tutorial

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ShaiBer** [comment]
Keep

**Comment by skyrpex** [comment]
Yes, one of my early proposal was to render nodes along with their inputs (inflights) and outputs. Like in the following image:

![image](https://github.com/winglang/wing/assets/1077520/a56c53da-ce4e-486e-adb9-b4cc0e0d7afd)

I believe it looks cleaner like this.

**Comment by skyrpex** [comment]
This concept of node inputs/outputs is usually called ports. The ELK algorithm that we use to compute the map layout also supports some kind of ports.

**Comment by ainvoner** [comment]
as part of map V2
