### ISSUE TITLE
Don't debounce before compiling in the Playground/Tutorial if LSP doesn't return an error

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2524]
### Feature Spec

Playground and Simulator are more responsive. As soon as you write code that compiles without error, you see the result in the Console view

### Use Cases

Right now most of the time that uses wait between finishing to type and seeing the result in the console is spent waiting on debounce. This is good to avoid displaying compilation errors when typing, but is bad when the user finishes typing and is expecting to see the app updated in the simulator.

### Implementation Notes

Assuming we can tell that there are no errors reported by the LSP, avoiding the debounce should be easy

### Component

Playground, Tutorial

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
We tried it briefly the the offsite, it produces poor results because of something else that was happening... I can't recall what.

We should try harder, but just removing the debounce didn't work well

**Comment by ShaiBer** [comment]
Did we try to not debounce only when language server reported no errors, or on every key stroke?
I think that removing all together will not work, but only when there are no errors from the LSP has a bigger chance of working well.
