### ISSUE TITLE
Explain test isolation in docs

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#2526]
### Feature Spec

Explain how tests are isolated by creating a copy of the environment for each test

### Use Cases

Explaining how current unit testing system works / why many resources are created with you run `wing test` on the cloud

### Implementation Notes

https://docs.winglang.io/reference/cli#test-wing-test

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
should be covered in #2192
