### ISSUE TITLE
improve wing compile time in playground

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#2539]
### Feature Spec

Faster compile time in wing playground and wing tutorials.

### Use Cases

compile wing files to tf-aws target in the playground takes too much time.

### Implementation Notes

try to have wing and wing-cli in the web container in order to make things faster.

### Component

Playground

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
We are in an ok state for now
