### ISSUE TITLE
Add copy button on code blocks in the instructions panel 

### ISSUE THREAD

**Issue by shaiber01** [winglang/wing#2545]
### Feature Spec

It is now easier to copy code in the Tutorial

### Use Cases

Users expect code blocks to have a 'copy' button to copy them instead of marking the code and copying.
In some setups marking the code for copy is not easy

### Component

Tutorial

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
might be related to #3073
