### ISSUE TITLE
move all diagnostics out of jsification so they appear in the LSP

### ISSUE THREAD

**Issue by yoav-steinberg** [winglang/wing#2548]
Move all diagnostics out of jsification so they appear in the LSP.
Currently the LSP (and I think rightfully so) doesn't perform the compiler's output (jsify) phase. So diagnostics added at this point aren't available in the vs code extension. These are some of the coolest diagnostics we have (can't reference a preflight mutable array inflight, for example). Ideally we should have a phase that "prepares" all the info we need for output before running the output phase (similar to the capture pahse we use to have). It'll also generate diags and we can run it in the LSP.

note here: https://github.com/winglang/wing/pull/2411#discussion_r1194155812

**Comment by staycoolcall911** [comment]
I think this comes down to 1 diagnostic - FYI @yoav-steinberg

**Comment by yoav-steinberg** [comment]
The capturing phase moved to be pre-jsify and also the jsify is now being run in the LSP as well. I think we can safely close this issue.
