### ISSUE TITLE
Boilerplate Templates 

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#2557]
### Feature Spec

- a template consisting of a recommended folder layout, and some files to not start with a blank page
- perhaps these templates could be configurable with some sort of wizard workflow
- could be something like `npm create` or a `projen` template

### Use Cases

For users who don't want to think about a good project structure, it could be quite helpful to have some basic boilerplate. Could be very simple like: 
- src
- tests

Later on, there could be starters for framework specific solutions (e.g. nextjs, generic api, ...)

### Component

CLI

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
For now, Wing is extremely non ceremonial. It simply needs a single entrypoint file + perhaps an external js file. Tests usually go within the same entrypoint file (like Rust), so I'm not sure we have a real use case for templates. Of course this may change in the future. 
Anyone has other thoughts on this?

**Comment by staycoolcall911** [comment]
`wing new` provides this functionality - closing.
