### ISSUE TITLE
"Update" Menu Item in Unexpected Position

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#2560]
### Feature Spec

- the update menu item is easy to find (in the main menu)

### Use Cases

As described in this [slack thread](https://winglang.slack.com/archives/C04BBDQUWQP/p1682340470707739), the "update" menu item is in a somewhat unexpected location. 
![Screenshot 2023-05-16 at 17 38 26](https://github.com/winglang/wing/assets/136789/88fe7bd0-0e8b-4149-9fb5-c7f043f866c3)

## Other apps
Other tools seem to put these type of functionality in the main menu, which is the place I was looking for it at least. 

![Screenshot 2023-05-16 at 15 12 27](https://github.com/winglang/wing/assets/136789/91646db8-df3c-42e6-bcc2-3a7f3bf81fee)
![Screenshot 2023-05-16 at 15 12 49](https://github.com/winglang/wing/assets/136789/21242614-1726-4105-8119-8c7416dc3850)
![Screenshot 2023-05-16 at 15 13 09](https://github.com/winglang/wing/assets/136789/651553ac-32e8-4aea-bbf1-99fec0d09c44)

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
NA
