### ISSUE TITLE
Error when trying to use non-string columns for the Table resource

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#2572]
### I tried this:

Trying to insert a row with non-string value fail.

```js
bring cloud;

let table = new cloud.Table(cloud.TableProps{
  name: "simple-table",
  primaryKey: "id",
  columns: {
    id: cloud.ColumnType.STRING,
    age: cloud.ColumnType.NUMBER,
    active: cloud.ColumnType.BOOLEAN,
  },
});
new cloud.Function(inflight (message: str) => {
  let id = message;
  let age = 0;
  let active = true;
  
  table.insert(id, {
    id,
    age,
    active
  });
}) as "Insert numeric value into table";
```

### This happened:

<img width="441" alt="image" src="https://github.com/winglang/wing/assets/5547636/b674d313-8fd1-467e-b786-c57ac9069b7b">
<img width="864" alt="image" src="https://github.com/winglang/wing/assets/5547636/d73988a4-879f-4a13-a836-18a5b60f2891">

### I expected this:

The file is compiled without errors.

### Is there a workaround?

No

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
keep
