### ISSUE TITLE
Table resource: cannot update value to be false, 0, etc.

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#2573]
### I tried this:

Tried to update numeric and boolean columns.

```js
let table = new cloud.Table(cloud.TableProps{
  name: "simple-table",
  primaryKey: "id",
  columns: {
    id: cloud.ColumnType.STRING,
    name: cloud.ColumnType.STRING,
    age: cloud.ColumnType.NUMBER,
    active: cloud.ColumnType.BOOLEAN,
  },
});
```

### This happened:

```js
const simulator = await ctx.simulator();
const client = simulator.getResource(
  input.resourcePath,
) as ITableClient;

// Inserting a row
await client.insert("id", {
  id: "id",
  name: "name",
  age: 1,
  active: true,
} as any);
console.log(await client.get("id"));
// { id: 'id', name: 'name', age: 1, active: true }

// Updating a numeric column with a "0" doesn't work
await client.update("id", {
  id: "id",
  name: "update age to 0",
  age: 0,
  active: true,
} as any);
console.log(await client.get("id"));
// { id: 'id', name: 'update age to 0', age: 1, active: true }

// Updating a numeric column with a number greater than 0 works
await client.update("id", {
  id: "id",
  name: "update age to 10",
  age: 10,
  active: true,
} as any);
console.log(await client.get("id"));
// { id: 'id', name: 'update age to 10', age: 10, active: true }

// Updating a boolean column with a "false" doesn't work
await client.update("id", {
  id: "id",
  name: "update active to false",
  age: 1,
  active: false,
} as any);
console.log(await client.get("id"));
// { id: 'id', name: 'update active to false', age: 1, active: true }

```

### I expected this:

The boolean and numeric columns to be updated

### Is there a workaround?

no

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
@polamoros - I'm updating the title of this issue to reflect this is related to non-string columns. 
I'm assuming it is related to the second issue you reported #2572
Or am I wrong and if you update a numerical value to be above 0 (say 5) the update succeeds?

**Comment by polamoros** [comment]
@staycoolcall911 - Updating non-string columns works.
Only when trying to set a numeric to `0` or a boolean to `false` is when the value for that specific column is not updated (other columns of the same updated do).

I would say that everything that evaluates to true doing `!value` will not be updated 🤔

**Comment by ekeren** [comment]
keep
