### ISSUE TITLE
Improve table resource interaction view

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#2578]
### Feature Spec

* Type errors are shown as tooltips instead of notifications.
* Edited rows are saved when focusin out the table instead of when focusing out each input
* Add pagination

Related to [this PR](https://github.com/winglang/console/pull/542)

### Use Cases

To be defined

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
@polamoros I have two issues with the result:

1. I don't like how the Table ui looks like - but we can improve it later if other users will have the same feedback
2. Whenever a new row is added, the whole table is being reloaded which cause a flickering.
