### ISSUE TITLE
RFC: CLI design

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#258]
Goal: communicate a vision / end-goal for what the Wing CLI user experience should feel like.

We can organize this as a RFC that works backwards from different user scenarios. (e.g. "When Mona Lisa runs XYZ, she sees the following appear on her terminal..."). Take a look at the existing RFCs within the repo [here](https://github.com/monadahq/winglang/tree/main/rfcs) for inspiration.

Some questions to serve as inspiration (it's ok if the RFC doesn't answer all of them):

- What does the help screen or manpage look like? (`wing --help`)
- What are all of the available commands and subcommands?
- When the `compile` command is run, what gets printed out? Which parts are printed to stdout vs stderr?
- How will we show the user progress between the different compilation stages? (In case a program takes multiple seconds to compile)
- Where are compiler artifacts placed?
- How should error messages look?
  - ...when they are produced by the parser?
  - ...when they are produced by the type checker?
  - ...when they occur at runtime? (e.g. a preflight method is called that returns an error)
- How does the user update the version of Wing they're using? Is it tied to the project, or to the CLI, etc.?

Useful resources:
- https://clig.dev/

**Comment by staycoolcall911** [comment]
At some point, we should consider improving the CLI based on the guidelines in this issue. Added to long-term backlog as p3

**Comment by Chriscbr** [comment]
Closing for housekeeping
