### ISSUE TITLE
cannot use enum value in a string literal

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#2607]
### I tried this:

```
 other.put("last_${cloud.bucketEventType.CREATE}_key", "n/a");
```

### This happened:

<img width="793" alt="image" src="https://github.com/winglang/wing/assets/39455181/9143a811-b16d-4793-bd40-7b6ef1a3e7fc">

### I expected this:

to be compiled :) 

### Is there a workaround?

replacing the use of an enum with a plain string (i.e "last_${cloud.bucketEventType.CREATE}_key" -> "last_create_key")

### Component

Compiler

### Wing Version

0.17.4

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
It's worth mentioning that the [current version of the spec](https://docs.winglang.io/reference/spec#38-enumeration) mentions a global utility function called `nameof` for converting enums into strings at compile time, but this could be something we want to revisit.

**Comment by staycoolcall911** [comment]
This code worked for me:
```ts
bring cloud;

let a = "pref_${cloud.BucketEventType.CREATE}";

test "log enum" {
  log(a);
}
```
Closing the issue.
