### ISSUE TITLE
Cannot assign `cloud` enums to variables on inflight

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#2608]
### I tried this:

if for some reason we'll want to do that: 
```
    let create = "${cloud.BucketEventType.CREATE}";
```
OR:
```
    let create = cloud.BucketEventType.CREATE;
```

note: this isn't working either (same error):
```
 if (event == loud.BucketEventType.CREATE) {
        counter.inc();
    } 
```

### This happened:

we'll get a very unclear error when compiling:
<img width="719" alt="image" src="https://github.com/winglang/wing/assets/39455181/96e3a8a3-5827-4c4c-98cc-ac66d46d9f26">
`Missing initializer in const declaration`

### I expected this:

get a clearer error

### Component

Compiler

### Wing Version

0.17.4

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
@tsuf239 I'm not sure if I understand the bug. We have a test [here](https://github.com/winglang/wing/blob/main/examples/tests/valid/enums.w) validating that you can assign enums to variables. Can you share the full Wing file that is causing the error you saw?

**Comment by tsuf239** [comment]
After a few trials and errors I found what reproduce the error:
this code breaks:
```
test "test inflight" {
    let c = cloud.BucketEventType.CREATE;
}
```
this doesn't: 
```
// preflight
    let c = cloud.BucketEventType.CREATE;
```
and this doesn't: 
```
enum SomeEnum {
    ONE, TWO, THREE
}

test "test inflight" {
    let one = SomeEnum.ONE;
}
```

**Comment by staycoolcall911** [comment]
This now works. Closing.
