### ISSUE TITLE
unable to assign a variable in condition to other variable's value

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#2609]
### I tried this:

I wanted to write a piece of code that does that:
  ` log("other bucket event called!: key=${key}, value=${event ==  cloud.BucketEventType.DELETE ? "n/a" :  other.get(key) }");`

I couldn't write it the way above since we're not supporting ternaries yet (#221)
The syntax below also failed to compile...

```
other.onEvent(inflight (key: str, event: cloud.BucketEventType) => {
    let var value;
    if (event == cloud.BucketEventType.DELETE) {
    value = other.get(key);
    } else {
    value = "n/a";
    }
    
    log("other bucket event called!: key=${key}, value=${value}");
});
```

### This happened:

<img width="866" alt="image" src="https://github.com/winglang/wing/assets/39455181/1cfb2aaa-2b2e-4e33-b9c5-f71121465bc7">

### I expected this:

`value` to be either `other.get(key)` or `n/a` according to `event` value...

### Is there a workaround?

for this specific case- using `tryGet` may work

### Component

Compiler

### Wing Version

0.17.4

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
On line 2 of your code (or 23 on the screenshot you added), you should assign a value to `value`, so it'll be: 
```ts
let var value = "n/a";
```
Closing for now, please reopen if I missed anything about this issue
