### ISSUE TITLE
Support cloud.Output resource

### ISSUE THREAD

**Issue by hasanaburayyan** [winglang/wing#2622]
Support post deployment output artifacts, which is a feature provided by infra provisioners (TF, CF, pulumi, etc..)

Examples:
- (Terraform) https://developer.hashicorp.com/terraform/language/values/outputs
- (CloudFormation) https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
- (Pulumi) https://www.pulumi.com/docs/concepts/inputs-outputs/

TODO:
- [ ] RFC a spec for the resource
- [ ] Add to SDK spec

**Comment by Chriscbr** [comment]
@hasanaburayyan It looks like this is a duplicate of #2430. Closing this issue

**Comment by hasanaburayyan** [comment]
@Chriscbr jeez how did I not find that 🤦 thanks for the catch
