### ISSUE TITLE
The Simulator doesn't work in the Console because of a wrong assumption with `process.argv[0]`

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#2647]
https://github.com/winglang/wing/blob/3943e01430ba12e02dc283e93c8cd44961c67a82/libs/wingsdk/src/utils/bundling.ts#L34-L44

The Simulator, at some point, spawns a node process (using `process.argv[0]` to find the path to node). This causes problems in environments that aren't node, such as electron (which is what the Console uses).

When running the Simulator in the Console, `process.argv[0]` is the electron executable rather than the node executable, thus failing the whole process.

In order to fix this, maybe we can discuss why is it necessary to spawn another node process to run esbuild-wasm? Why not running it directly from the main process?

**Comment by staycoolcall911** [comment]
Thanks for digging into the problem @skyrpex. Not commenting on your suggested solution - I wanted to ask if you know why it started failing now? From a fast look it seems this change was done 2 months ago.

**Comment by ainvoner** [comment]
@staycoolcall911 it seems like you started to use this method 2 days ago as part of the VM2 refactor:
https://github.com/winglang/wing/blame/3943e01430ba12e02dc283e93c8cd44961c67a82/libs/wingsdk/src/target-sim/function.inflight.ts#L40

**Comment by Chriscbr** [comment]
> In order to fix this, maybe we can discuss why is it necessary to spawn another node process to run esbuild-wasm? Why not running it directly from the main process?

This was a workaround for a bug in esbuild that we discovered in esbuild when we tried calling it directly 😕. See the comment above:

https://github.com/winglang/wing/blob/39ad1d569ee65d00d4bc3b03fed498dfe512a71c/libs/wingsdk/src/utils/bundling.ts#L29-L32

@skyrpex Can you try to see if assuming "node" is on the PATH and invoking it directly, and see if that will work for the console?

```js
const result = spawnSync("node", ["-e", esbuildScript]);

// or

const nodePath = execSync("which node").toString(); // wrap this in try/catch
const result = spawnSync(nodePath, ["-e", esbuildScript]);
```

**Comment by skyrpex** [comment]
Assuming `node` on the path works for me:

```ts
const result = spawnSync("node", ["-e", esbuildScript]);
```

Assuming that `node` is globally available seems like a fair assumption to me, especially if the console is bundled along with wing via npm.

Also added a question to the issue in esbuild: https://github.com/evanw/esbuild/issues/2927#issuecomment-1564011644

**Comment by skyrpex** [comment]
BTW Pol and I just tried a hack in the Console to make it work for now: we can modify our electron app's `process.argv[0]` to point to the globally installed `node`. Pol's preparing a PR.

**Comment by skyrpex** [comment]
@staycoolcall911 @ainvoner have a look when you have some time, please 🙏🏻

**Comment by ainvoner** [comment]
I understand the easy workaround. But I think this should be fixed in the sdk and not the console.
@Chriscbr what do you think?

**Comment by staycoolcall911** [comment]
I believe this was addressed, right? Closing, but please reopen if this is still relevant
