### ISSUE TITLE
`bucket.delete` optional parameter `mustExist` may be redundant

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#2681]
### Feature Spec

There's already a `bucket.tryDelete` method that checks if an object exists before trying to delete it, so I think the `mustExist` optional paramter of `bucket.delete` may be redundant in functionality.

### Use Cases

Avoid redundancy.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
I think this makes sense, what do you think @hasanaburayyan @tsuf239 ?

**Comment by hasanaburayyan** [comment]
@Chriscbr Thinking out loud but I believe its different behaviors no? `tryDelete` is a graceful delete attempt whereas delete with the `mustExist` option is a throwable operation.

**Comment by Chriscbr** [comment]
I'm wondering say, between these three usages:

```
myBucket.delete("file.txt", mustExist: true); // 1
myBucket.delete("file.txt", mustExist: false); // 2
myBucket.tryDelete("file.txt"); // 3
```

What's the difference between 2 and 3? I was thinking they might behave the same

**Comment by tsuf239** [comment]
It depends on the `tryDelete` implementation, unless it catches any error,  2 and 3 behave the same.
I believe that different users will favor one over the other, I agree with Hasan,
(but we should remember that adding is easier than removing, once will be on beta, as a side note )

**Comment by staycoolcall911** [comment]
Based on this discussion I think we can keep the behavior as is. Closing for now
