### ISSUE TITLE
Add support for `bucket.exists` in VS Code extension

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#2682]
### I tried this:

Called `bucket.exists` method inside a `.w`file.

### This happened:

Got `unknown symbol "exists"` error.

### I expected this:

I expected `Wing [Alpha]` extension for VS Code to recognize the `bucket.exists` method.

### Component

IDE Extension

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
@garysassano - thanks for reporting. Same as my remark for ##2683 - what code did you use? What wing version?
I used the following code on wing 0.17.37 and it compiled successfully with no errors + no errors on the vscode extension:
```ts
bring cloud;

let b = new cloud.Bucket();

new cloud.Function(inflight(s: str) => {
  b.exists("foo");
});
```
Perhaps your global wing installation is outdated and precedes 0.17.23 (when `Bucket.exists` was added)?

**Comment by garysassano** [comment]
@staycoolcall911 I got a request from VS Code to update the `Wing [Alpha]` extension  to v0.17.40 released 1 hour ago and that fixed the issue.
