### ISSUE TITLE
Add support for `nil` in VS Code extension

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#2683]
### I tried this:

Wrote some code in a `.w` file with an if statement checking if a method was returning `nil`.

### This happened:

Got `unknown symbol "nil"` error.

### I expected this:

I expected `Wing [Alpha]` extension for VS Code to recognize the `nil` type.

### Component

IDE Extension

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
@garysassano - what code did you use? What wing version?
I used `let a: str? = nil;` on wing 0.17.37 and it compiled successfully with no errors + no errors on the vscode extension.
Perhaps your global wing installation is outdated and precedes 0.17.24 (when `nil` was added)?

**Comment by garysassano** [comment]
@staycoolcall911 I got a request from VS Code to update the `Wing [Alpha]` extension  to v0.17.40 released 1 hour ago and that fixed the issue.
