### ISSUE TITLE
Add preflight logs to the playground/tutorial

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2693]
### Feature Spec

When developers use the log in preflight they can now see it in the logs area

### Use Cases

Right now these logs get lost, leaving users confused

### Implementation Notes

When using VCS, terminal and console, these logs are outputted to the terminal at compile time. There is no terminal in the playground. I think we should collect these logs from stdout somehow and display in the console window if possible, I wouldn't add a separate terminal window for it.

### Component

Playground, Tutorial

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
duplicated with #3012
