### ISSUE TITLE
can't use the same inflight function instance - There is already a Construct with name 'cloud.Topic-OnMessageHandler-16f2c72f' in $Root

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2694]
### I tried this:

```ts (wing)
bring cloud;

let h = inflight() => {
};
let t = new cloud.Topic();
t.onMessage(h);
t.onMessage(h);
```
### This happened:

Got this error:
```
ERROR: There is already a Construct with name 'cloud.Topic-OnMessageHandler-de95ec56' in $Root [Default]

target/b.wsim.019590.tmp/.wing/preflight.js:43
       const t = this.node.root.newAbstract("@winglang/sdk.cloud.Topic",this,"cloud.Topic");
       (t.onMessage(h));
>>     (t.onMessage(h));
     }
   }
```
### I expected this:

To not get an error

### Is there a workaround?

create two different inflights

### Component

Compiler

### Anything else?

This is related to #2623 .
It is even worse in a way since there is no place that we can use the `as` keyword here to mitigate this.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
Yes I think @eladb @ekeren mentioned this API may need to be changed to `setConsumer` or some other name. My understanding is that when you have a `cloud.Function` or `cloud.Service` or any other cloud compute resource that automatically scales to the demand of its callers, it does not a valid use case to add multiple consumers.

We can also improve the error message given by the SDK here.

**Comment by ShaiBer** [comment]
Even if this will fix it for the queue, we'll still have a problem with the topic. It should always allow for multiple consumers, right?

**Comment by eladb** [comment]
Queues can only have a single consumer. Topics can have multiple consumers. That's in a sense the main difference between them.

**Comment by ekeren** [comment]
I see, changing description and issue name.

I hope I get it right, I am aware of the rumors that it is not my forte (@eladb)

**Comment by ekeren** [comment]
I'll create  a PR with the edits

**Comment by ekeren** [comment]
@staycoolcall911 , is this better ? https://github.com/winglang/wing/pull/2705/files

**Comment by staycoolcall911** [comment]
Duplicates #4925
