### ISSUE TITLE
The header of the learn.winglang.io page is missing

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2697]
### I tried this:

browsed to learn.winglang.io

### This happened:

There was no header with link to GitHub, etc. like in the playground

### I expected this:

To have a header like in the playground

### Component

Tutorial

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
the new design includes the header
