### ISSUE TITLE
Cannot find APIs through docs search bar

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#2710]
### I tried this:

Trying to find docs for the Wing [stdlib](https://github.com/winglang/wing/tree/main/libs/wingsdk/src/std) on the [docs page](https://docs.winglang.io/). e.g. trying to find `String#lowercase`.

### This happened:

The search for methods / types of the stdlib leads to zero results on docs

e.g. [lowercase](https://github.com/winglang/wing/blob/dafc385402d3c35f66e5d0fb4205deb98bb3742b/libs/wingsdk/src/std/string.ts#L92-L101C4) is present, but not discoverable / findable.

![Screenshot 2023-05-30 at 17 18 30](https://github.com/winglang/wing/assets/136789/4656f9b6-5b39-4b3f-8e45-adee1f15ba0d)

### I expected this:

- being able to find docs about stdlib and available functions

### Is there a workaround?

- read the code [implementation](https://github.com/winglang/wing/blob/dafc385402d3c35f66e5d0fb4205deb98bb3742b/libs/wingsdk/src/std)

### Component

SDK, IDE Extension

### Wing Version

0.17.32

### Wing Console Version

0.17.32

### Node.js Version

v18.16.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
I can reproduce this (I searched for "lowercase" and didn't find the API page listed). after playing with the search a bit I think there may be an issue where the "API reference" page is not being indexed. I wonder if it's due to the page size?

**Comment by ainvoner** [comment]
Algolia crawler returns `Extractors returned too many records` error for the [API reference page](https://docs.winglang.io/standard-library/sdk).
we can reduce the number of records at the content level of the extractor using [aggregatecontent](https://docsearch.algolia.com/docs/record-extractor/#aggregatecontent),

**Comment by Chriscbr** [comment]
I see. I'll look into splitting the API reference into subpages as part of the docs work. I'm not sure if this would work as an intermediate solution but if there is a way to tell the extractor to skip low-level headings (H4, H5, H6) then that could be another option. Related: https://github.com/algolia/docsearch/issues/1658

**Comment by ainvoner** [comment]
@Chriscbr yes, there is an easy way to configure the crawler. However, by doing it we are losing search capabilities.
Another downside is that the api reference page is going to have much more records in the future.
In my opinion the best solution would be to split the api reference page.

**Comment by ainvoner** [comment]
@tsuf239 thanks!
we can now resolve it
