### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by fchughes** [winglang/wing#2715]
### I tried this:

Typos in step 3. of the Compile for AWS portion of the tutorial.

### This happened:

Step 3. of the Compile for AWS portion of the tutorial reads, "You can browse through the different terraform resources that where generate by the code." 

### I expected this:

Presumably, it should read "You can browse through the different Terraform resources that were generated by the code."

### Component

Tutorial

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by fchughes** [comment]
<img width="929" alt="Screenshot 2023-05-30 at 11 26 42 AM" src="https://github.com/winglang/wing/assets/129426794/6a3e4ccb-bd40-42d0-ac5a-12928d1c95ac">

**Comment by stejin-stephen** [comment]
Okay, this typo is in the 'learn wing' website. I cannot find its source files in this repo. Could you please guide me where to find those? @Chriscbr

**Comment by Chriscbr** [comment]
Hey @fchughes, thanks for catching the typo. 🙂

@stejin-stephen It looks like at the moment the source code for the "learn wing" website is currently private - I'll let the team know so they can fix the instructions

**Comment by ekeren** [comment]
fixed:
> Feel free to browse through the different Terraform resources that were generated by the code, and observe the generated inflight JavaScript functions.
