### ISSUE TITLE
Flakey test `file-counter.test.ts`

### ISSUE THREAD

**Issue by hasanaburayyan** [winglang/wing#2716]
### I tried this:

`npm run build` OR (from withing libs/wingsdk run `npx vitest counter`)

### This happened:

<img width="717" alt="image" src="https://github.com/winglang/wing/assets/45375125/966d36d4-2545-4da0-b251-9c9c122ad06c">

### I expected this:

Test to pass

### Component

SDK

### Anything else?

Here is a video of the flakey behavior 
https://www.loom.com/share/6b8784b61f484a9cb24d55c7c9555b46

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by garysassano** [comment]
I'm glad to know that I'm not the only one who constantly has issues with this test.
