### ISSUE TITLE
Playground: Let me select error messages

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#2720]
### Feature Spec

- A user can select compiler error messages in the playground.

### Use Cases

If errors occur, users likely want to copy & paste the error messages
![Screenshot 2023-05-30 at 23 22 35](https://github.com/winglang/wing/assets/136789/81b05ae4-5f9b-4624-a326-bbb543a8bc2d)

### Implementation Notes

- Chrome Version 113.0.5672.126 (Official Build) (x86_64)

### Component

Wing Playground

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
The text is already selectable, @skorfmann can you verify on your end?

**Comment by skorfmann** [comment]
> he text is already selectable, @skorfmann can you verify on your end?

Yes, works now 👍
