### ISSUE TITLE
Cannot access 'x' before initialization

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2753]
### I tried this:

```js
let x = "hi";
if true {
  log(x);
  let x = "world";
}
```

### This happened:

```
ERROR: Cannot access 'x' before initialization

../../examples/tests/invalid/target/test/capture_redefinition.wsim.755953.tmp/.wing/preflight.js:10
       const x = "hi";
       if (true) {
>>       {console.log(x)};
         const x = "world";
       }
```

### I expected this:

To emit a compilation error, not a preflight error.

### Is there a workaround?

This shouldn't be supported by the language.

### Component

Language Design

### Anything else?

This is not really considered a "capture" because we are still within the same function scope, so the capture scanner doesn't find it.

It is also hard to identify this case in the type checker because when `x` is referenced the symbol environment of the `if` scope still doesn't contain the later defined `x` (because the `let` is after the `x` reference).

Uncomment the test `invalid/capture_redefinition.w` (included with PR #2677).

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
This is already fixed.
