### ISSUE TITLE
It shouldn't be possible to capture reassignable variable with inflight closures

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2757]
### I tried this:

```js
test "t" {
  let var x = "foo";

  class C1 {
    f() {
      x = "bar";
    }
  }

  new C1().f();
  log(x);
}
```

### This happened:

It compiled and printed "foo".

### I expected this:

Not to compile and tell me that I can't capture a reassignable variable within an inflight class.

### Component

Compiler

### Anything else?

The reason it is hard to support capturing reassignable variables within inflight classes is that our classes are emitted into a separate javascript file, so the variable is not really captured, just it's reference (which is why it's possible to capture mutable variables).

I really don't think we need to support capturing reassignable variables within inflight classes declared inside inflight closures because it's a confusing feature anyway.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
Will it still compile if we aren't introducing a `class` in between where the reassignable variable is declared and where the reassignment happens?

For example, this compiles in Wing 0.18.7:

```js
let fib = inflight(n: num): num => {
  let var a = 0;
  let var b = 1;
  let next = inflight (): num => {
    let c = a + b;
    a = b;
    b = c;
  };
  for _ in 0..n {
    next();
  }
  return a;
};

test "fib(10) = 55" {
  assert(fib(10) == 55);
}
```

**Comment by staycoolcall911** [comment]
Related to #1908, but this is more of an edge case. p3 for now

**Comment by Chriscbr** [comment]
@eladb The example you gave compiles in Wing 0.24.41 and now prints "bar" (instead of "foo" when you originally reported it). The behavior seems reasonable / maybe we can close this - WDYT?

**Comment by eladb** [comment]
yes, I think we can close for now.
