### ISSUE TITLE
Support calling async methods from initializers of inflight classes

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2765]
> We have a a problem with our async programming model in inflight classes because there is no way to indicate that a method is async. For now, all methods are async (since they are tagged inflight), but that means we cannot call them from within the constructor. We need to decide how to deal with it.

If inflight scopes are always async (and inflight classes can only be instantiated in inflight scopes), then couldn't we emit code like this each time an inflight class is constructed?

```js
let a = new A();
await a.$inflight_init(); // allowed to call async methods
```

_Originally posted by @Chriscbr in https://github.com/winglang/wing/issues/2677#issuecomment-1570564765_

**Comment by staycoolcall911** [comment]
@yoav-steinberg - I believe this issue duplicates #4290 - please reopen in case you disagree
