### ISSUE TITLE
Completion inside function/variable declaration after colon - show all types

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#2787]
When I have a complete function declaration, this works: (notice there is a `=> {  } ` in this example )
<img width="705" alt="image" src="https://github.com/winglang/wing/assets/1727147/88fdb35f-db76-4f11-a7f0-54448ab08f74">

But when I am implementing it, it doesn't:
<img width="578" alt="image" src="https://github.com/winglang/wing/assets/1727147/4aebd148-9b8f-41ee-bc7d-0194e82ce2e4">

```ts (wing)
let f = inflight (req: cloud.
//                           ^ should autocomplete 
````

**Comment by MarkMcCulloh** [comment]
Solving this problem generically (e.g. making sure tree-sitter can parse incomplete closures) will likely be very difficult.
To make this problem hopefully less noticeable in vscode, we can add a closure snippet that'll automatically insert `() => {}`.
