### ISSUE TITLE
`x?` syntax is not valid

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#2791]
### I tried this:

[Testing using x?](https://docs.winglang.io/reference/spec#172-testing-using-x) and `let x? = 1;`

### This happened:

`Unknown parser error` or other errors

### I expected this:

I expected the `x?` special syntax to work.

### Component

SDK

### Wing Version

0.18.12

### Node.js Version

18.12.1

### Platform(s)

Linux

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Hey @garysassano, thanks for reporting - can you please write the full code that didn't work for you? It'll help us track down the issue

**Comment by garysassano** [comment]
@staycoolcall911 The code is the one provided in the link. Besides that, using `let x? = 1;` anywhere in your code also throws an error. If you confirm that `x?` special syntax got abandoned, I could update the docs to reflect the change.

**Comment by staycoolcall911** [comment]
Thanks for the elaborate answer @Chriscbr. 
@garysassano - optionality could be a tricky & confusing topic. I don't have a good reading material to reference, but if you can't find anything on your own, you're welcome to bring it up on office hours and we'll give you the TL:DR;

Closing for now.
