### ISSUE TITLE
tf-aws assets inside the console

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#2795]
Similar to the work that was done in learn.winglang.io, we would like to provide TF information in the context of a wing resource inside the console.

Here is a proposed view :
![image](https://github.com/winglang/wing/assets/1727147/d7639f30-dac7-4e13-a682-c61d93f0dd1c)

And some proposed suggestions:
- [ ] show this view only for terminal resources (for now) 
- [ ]  show the `open` icon on hover 
- [ ] on click open the file in full screen 
- [ ] leave the assets out of this view

**Comment by ekeren** [comment]
Let's do it

**Comment by ekeren** [comment]
don't give an option to download them

**Comment by ainvoner** [comment]
@polamoros lets also increase the initial width of the resource view (right panel). - not the minimal.
the reason we haven't done it until now was that we only had a table resource that needed a wider panel, now each terminal resource will need it.

**Comment by ekeren** [comment]
The issue was identified when we noticed that resources like `root/Default/cloud.Queue-AddConsumer-90af6456` does not have any terraform assets associated with them: (notice no files)
![image](https://github.com/winglang/wing/assets/1727147/9968fd71-2006-4052-aa63-4bac07f7481a)

@Chriscbr also noted that discrepancy can also happen with something like the following code:
```ts (wing)
bring cloud;
bring util;

if util.env("WING_TARGET") == "tf-aws" {
  new cloud.Bucket();
} else {
  new cloud.Counter();
}
```

I wonder if we should wait to move forward with some of the work that is related in regards to the map view (inflight method, events subscribers) and see a more "correct" layout solves some of these issues
