### ISSUE TITLE
Default behavior of CLI progress output

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2800]
@Chriscbr wrote:

> Curious if the default here open for discussion -- for operations that deploy to the cloud, IMO it really helps built user trust when we show what's happening under hood (this is the experience users expect with `terraform apply`, `cdk deploy`, `sst deploy`, etc.) If the first time I ran `cdk deploy` I got no feedback, I would have probably felt less trusting of the tool.

I'm curious what part was most annoying about them. Maybe we could:
- Disable progress by default if the user is using a TTY (this will remove the progress from logs), or
- Disable progress by default only for `wing test -sim`, or
- Disable all progress spinners for the "compile" step

Also:

Consider renaming `PROGRESS` to `WING_PROGRESS`.

_Originally posted by @Chriscbr in https://github.com/winglang/wing/pull/2783#discussion_r1218357973_

**Comment by staycoolcall911** [comment]
Duplicates #2903
