### ISSUE TITLE
Rename `Json.cloneMut` to `Json.deepCopyMut` and add `MutJson.deepCopy`

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#2822]
### Feature Spec

Changes to Json type:
- Rename `Json.cloneMut` to `Json.deepCopyMut` to make the method more self-explanatory
- Remove `Json.clone` since there's no actual use case for it

Changes to MutJson type:
- Add `MutJson.deepCopy` to follow the same standard as `MutArray`, `MutSet` and `MutMap`

### Use Cases

Make the word `copy` mainstream across the entire API SDK, both for shallow and deep copies.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Thanks for picking it up @garysassano!
