### ISSUE TITLE
Rename ImmutableClass to Class and MutableClass to MutClass

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#2824]
### Feature Spec

Some classes within the [API Reference](https://github.com/winglang/wing/blob/main/docs/05-reference/wingsdk-api.md) don't follow the actual naming they have in Wing so the two things need to be aligned:

ImmutableArray 🡆 Array
ImmutableMap 🡆 Map
ImmutableSet 🡆 Set
MutableArray 🡆 MutArray
MutableMap 🡆 MutMap
MutableSet 🡆 MutSet

### Use Cases

Aligning the documentation.

### Component

Documentation

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
This is also mentioned in #2165 and is not trivial

**Comment by Chriscbr** [comment]
@staycoolcall911 What's the limitation? I couldn't find an explanation in the other issue

**Comment by staycoolcall911** [comment]
I vaguely remember :)
I think it has to do with our infamous baby macros types interfering with our compiler builtin types. 
@MarkMcCulloh do you have a better memory of this issue? If not, no worries, I'll look into it tomorrow.

**Comment by MamathaKarapanahalli** [comment]
Hi, 

I would like to work on this issue. 
From my understanding, in the documentation inside the markdown file: https://github.com/winglang/wing/blob/main/docs/05-reference/wingsdk-api.md 

the following replacements need to be done: 
ImmutableArray 🡆 Array
ImmutableMap 🡆 Map
ImmutableSet 🡆 Set
MutableArray 🡆 MutArray
MutableMap 🡆 MutMap
MutableSet 🡆 MutSet

Kindly confirm if my understanding is correct and I will make the change and create a PR. 

Thanks,
Mamatha

**Comment by staycoolcall911** [comment]
This was done in #3036

**Comment by revitalbarletz** [comment]
@MamathaKarapanahalli We can find similar issue if you would like ! feel free to join our slack https://winglang.slack.com/join/shared_invite/zt-1mw74uvra-fHXIKNQ9BorWuIMRG7oQDw
