### ISSUE TITLE
Query compilation target

### ISSUE THREAD

**Issue by eladb** [winglang/wing#283]
I can totally see a use case where, for local simulation, I'd want some initial messages to be in a queue while, for production, I want the queue to be empty.

Something like:

```ts
bring cloud;

new cloud.Queue(
  initialMessages: app.get_target()
    ? [ "foo", "bar", "baz" ]
    : nil,
);
```

`app.get_target()` is just pseudo API. We need to think about it...

**Comment by Chriscbr** [comment]
@eladb Would you like to propose a syntax for this? One straightforward way to implement this could be a new global function named `get_target()` or `target_eq(str)` etc. but there could be other options

**Comment by eladb** [comment]
Ha ha love it that we basically had the same conversation 6 months ago, and finally we are picking this up.

I believe this is already set in an environment variable, and we need a way to access env variables anyway, so how about something like this:

```
bring env;

let s: str = env.get("WING_TARGET");
```

* `env.try_get()` returns `str?`

And kill two birds with one stone?

**Comment by Chriscbr** [comment]
> I believe this is already set in an environment variable, and we need a way to access env variables anyway, so how about something like this:
> 
> ```
> bring env;
> 
> let s: str = env.get("WING_TARGET");
> ```
> 
> * `env.get()` throws if not empty
> * `env.try_get()` returns `str?`
> 
> (I think we don't have global functions...) 
> 
> And kill two birds with one stone?
> 

Definitely an approach we can try -- note that we will need to inject WING_TARGET as an environment variable to every cloud function for it to work inflight.

**Comment by staycoolcall911** [comment]
This was already done
