### ISSUE TITLE
No autocomplete for bucket preflight if we're adding a blank line between bucket definition and usage

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#2830]
### I tried this:

Wrote this simple code on the vscode extension:
```ts
bring cloud;

let bucket = new cloud.Bucket();

bucket.
```
Notice I have added a blank line on line 4. If I remove it then autocomplete works as expected.

### This happened:

No autocomplete suggestions for `cloud.Bucket`'s preflight methods on the `bucket` variable.

### I expected this:

To see autocomplete suggestions for `cloud.Bucket`'s preflight methods.

### Is there a workaround?

Delete the blank line:
```ts
bring cloud;

let bucket = new cloud.Bucket();
bucket.
```

### Component

IDE Extension

### Wing Version

0.19.2

### Node.js Version

19.3.0

### Platform(s)

MacOS

### Anything else?

This works (autocomplete on primitive type `str` with a blank line before parameter usage):
```ts
let text = "hola mundo";

text.
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
I'm not able to replicate this. Similar to https://github.com/winglang/wing/issues/2832#issuecomment-1580740061, is it possible copilot is blocking suggestions?

**Comment by staycoolcall911** [comment]
This all works if I disable github copilot for Wing... we'll discuss that sync, but moving to p2 for now.
