### ISSUE TITLE
Autocomplete doesn't show up if I chose to autocomplete the previous expression

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#2832]
### I tried this:

Wrote this wing code on the vscode extension:
```ts
bring cloud;

let bucket = new cloud.Bucket();
```
Now if on the next line I type `bucket.` by hand, autocomplete works.
However if I just type `b` and select the autocomplete suggestion of `bucket`, then type `.` then no autocomplete suggestions are shown.

### This happened:

No autocomplete suggestions popped up when I typed `.` after selecting the autocomplete suggestion `bucket`.

### I expected this:

Autocomplete to show bucket preflight method suggestions.

### Is there a workaround?

Delete the `bucket.` parameter name and retype it manually.

### Component

IDE Extension

### Wing Version

0.19.2

### Node.js Version

19.3.0

### Platform(s)

MacOS

### Anything else?

Activating the autocomplete suggestions using the keyboard combo for autocomplete (option+esc on my Mac) did work, so perhaps we should somehow let the vscode extension know it should show it whenever `.` is typed.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
This seems to be due to copilot, which kinda takes over autocomplete.
<img width="380" alt="image" src="https://github.com/winglang/wing/assets/1237390/b91ff397-7742-42fa-934a-8c4d281360ff">

language server completion won't show while the copilot suggestion is showing.

**Comment by staycoolcall911** [comment]
This all works if I disable github copilot for Wing... we'll discuss that sync, but moving to p2 for now.
