### ISSUE TITLE
Accessing invalid value in array does not throw an error

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#2856]
### I tried this:

```js
let a = ["hello", "world"];
log(a.at(42));
```

### This happened:

It prints "undefined"

### I expected this:

It should throw a runtime error. This is the typical behavior in most languages -- throwing an error prevents the program from continuing execution since it may start performing calculations based on an invalid result.

If you aren't sure if an array index is valid, you can guard your access using an if statement:

```js
let a = ["hello", "world"];
if a.length < 43 {
  log("no element at index 42");
} else {
  log(a.at(42));
}
```

Another option is to use `tryAt` to return an optional (`tryAt` is not implemented yet):

```js
let a = ["hello", "world"];
let b = a.tryAt(42); // returns a `str?`
if let word = b {
  log(word);
}
```

### Component

Compiler

### Wing Version

0.19.4

### Node.js Version

18.14.1

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
keep

**Comment by staycoolcall911** [comment]
Hey @revitalbarletz - do you know the status of this? `tryAt` was added, but `at` still doesn't throw an exception when retrieving an out-of-bounds element.

**Comment by Lancear** [comment]
Why is throwing an error prefered over returning nil or an option type?

To me for preflight code this might make sense as its a quick feedback loop to fix the infra configuration code. But during inflight I would say returning nil or an option type makes it easier to recover than throwing an error. Errors often come with verbose try-catching and thrown errors aren't typed in the function signature in TS for example leading to cumbersome to work with types.

**Comment by Chriscbr** [comment]
@Lancear I think we want to basically support both cases - a way to access an array element that gives you an option value (`T?`), and a way to access an array element that gives you a non-option value (`T`) or throws. The convention we have in the standard library is call these methods `tryXxx` and `xxx` - for an example, see `Map.get` and `Map.tryGet`:

```js
let m = Map<str> { "key" => "value" };

let a = m.tryGet("key");
log("${a ?? "nil"}"); // prints "value"
let b = m.tryGet("not-a-key");
log("${b ?? "nil"}"); // prints "nil"

let c = m.get("key");
log("${c}"); // prints "value"
let d = m.get("not-a-key");
log("${d}"); // throws an error
```

`Array.tryAt` has already been implemented, it seems like we just haven't fixed the behavior for `Array.at` 🙂

**Comment by Chriscbr** [comment]
Fixed by https://github.com/winglang/wing/pull/4704
