### ISSUE TITLE
Bad for loop causes language server crash

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#2857]
### I tried this:

```js
for _ 0..3 {
  let x = inflight () => {
  };
}
```

### This happened:

An error "Wing language server crashed and will resume when changes are made".

If I run `wing compile hello.w` then I do get a list of parse errors:

```js
error: Unexpected 'identifier'
  --> misc.w:1:5
  |
1 | for _ 0..3 {
  |     ^ Unexpected 'identifier'


error: Unexpected 'identifier'
  --> misc.w:2:3
  |
2 |   let x = inflight () => {
  |   ^^^ Unexpected 'identifier'


error: Unexpected 'identifier'
  --> misc.w:2:7
  |
2 |   let x = inflight () => {
  |       ^ Unexpected 'identifier'


error: Unknown parser error
  --> misc.w:3:4
  |
3 |   };
  |    ^ Unknown parser error


error: Expected ';'
  --> misc.w:4:2
  |
4 | }
  |  ^ Expected ';'
```

### I expected this:

A syntax error telling me that there is a missing "in" in my for loop

### Component

Compiler

### Wing Version

0.19.4

### Node.js Version

18.14.1

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
This doesn't panic anymore, but we should still provide the suggested meaningful error message, so keeping it open

**Comment by staycoolcall911** [comment]
This is now showing a proper error message.
![image](https://github.com/winglang/wing/assets/106860404/6f80b1b8-490f-4bd8-abf1-67f69e60a3e5)
