### ISSUE TITLE
`Json.stringify` not suggested by the IDE

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#2872]
### I tried this:

```
bring cloud;

Json.stringify
```

### This happened:

After typing `Json.` , Intellisense doesn't suggest me that a `stringify` static method exists for `Json`.

### I expected this:

I expected VS Code to suggest and autocomplete the method name.

### Component

IDE Extension

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Good catch. This applies to all of `Json`'s static methods both preflight and inflight.
