### ISSUE TITLE
`wing test --no-clean`

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#2884]
### Feature Spec

It's easy to debug test issues for various targets. e.g. being able to inspect provisioned resources is possible after the `wing test` command has finished 

### Use Cases

Right now `wing test ...` will [cleanup](https://github.com/winglang/wing/blob/479d6cc0441c1eb3228f367200abc779f06fdbe9/apps/wing/src/commands/test.ts#L346-L349) in most of the cases. For debugging purposes it can be fundamental to being able to inspect the provisioned resources. As a user, I'd love to have a way to express something like `wing test --skip-cleanup` or provide an env like `WING_TEST_SKIP_CLEANUP`.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment]
I think `--no-clean`

**Comment by skorfmann** [comment]
Just for reference, setting `TF_CLI_ARGS_destroy=-target=does_not.exist` will effectively skip all destroy actions in Terraform.

**Comment by tsuf239** [comment]
related to #2689 (point 4)
