### ISSUE TITLE
Tests: Inflight Test Function Names Potentially Conflicting across Stacks

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#2887]
### I tried this:

I have two Wing files:

- `foo.w`
- `bar.w`

Both files have a test defined as follows

```
test "fetch issues" {
// ...
}
```

which synthesizes to the following in both cases.

```json
"root_testfetchissues_Handler_7DA88EB6": {
        "//": {
          "metadata": {
            "path": "root/Default/Default/test:fetch issues/Handler/Default",
            "uniqueId": "root_testfetchissues_Handler_7DA88EB6"
          }
        },
```

### This happened:

When testing both in parallel for the `tf-aws` target, either via `wing test -t tf-aws ...`  or for some manually debugging deploying the by hand there's a resource conflict in AWS

```
aws_lambda_function.root_cloudApi_cloudApiOnRequestcdafee6e_582EA655: Still creating... [5m0s elapsed]
╷
│ Error: creating Lambda Function (cloud-Api-OnRequest-cdafee6e-c8147384): operation error Lambda: CreateFunction, https response error StatusCode: 409, RequestID: c11e324c-c455-4970-93c2-ab2840cb928b, ResourceConflictException: Function already exist: cloud-Api-OnRequest-cdafee6e-c8147384
│
│   with aws_lambda_function.root_cloudApi_cloudApiOnRequestcdafee6e_582EA655,
│   on main.tf.json line 176, in resource.aws_lambda_function.root_cloudApi_cloudApiOnRequestcdafee6e_582EA655:
│  176:       },
│
```

### I expected this:

- (somewhat) globally uniquely named test handlers 

### Is there a workaround?

Manually define unique names for tests

### Component

CLI

### Wing Version

0.19.11

### Node.js Version

v18.16.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by tsuf239** [comment]
Fixed
