### ISSUE TITLE
util.sleep compiles in preflight

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#2907]
### I tried this:

```ts (wing)
bring util;
util.sleep(1s);
```

### This happened:

it worked

### I expected this:

to complain that sleep is not an inflight api

### Is there a workaround?

flight  boarding has started, don't sleep during preflight 

### Component

Compiler

### Wing Version

0.20.0

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by tsuf239** [comment]
seems to be fixed now :) 

![Image](https://github.com/winglang/wing/assets/39455181/8455a188-d363-4cd3-8fdb-20ec6e27ca3e)
