### ISSUE TITLE
Some weirdness with simulator tokens and `website.url`

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2919]
### I tried this:

```js
bring cloud;

let w = new cloud.Website(path: "./website");
let url = w.url;

test "show me" {
  log(url);
}
```

### This happened:

```
Tried to resolve token "${root/env0/cloud.Website#attrs.url}" but resource root/env0/cloud.Website has no attribute url defined yet. Is it possible root/env0/test:show me/Handler needs to take a dependency on root/env0/cloud.Website?
```

### I expected this:

To print the URL

### Component

Compiler, SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skorfmann** [comment]
Related to this https://github.com/winglang/wing/issues/2919 (duplicate?)

**Comment by staycoolcall911** [comment]
Works
