### ISSUE TITLE
Unable to see the `url` of a website in the Wing Console

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2920]
### I tried this:

```js
bring cloud;

let w = new cloud.Website(path: "./website");

test "test" {
  log(w.url);
}
```

### This happened:

```
Unknown error: Cannot read properties of null (reading 'toString')
```

### I expected this:

To print the URL of the website so I can open with my browser.

### Is there a workaround?

When running through `wing test` I get a good output:

```
pass ┌ website.wsim » root/env0/test:test
     └ http://127.0.0.1:53996
```

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
resolved, was related to a different issue we had in the console

![Screenshot 2023-06-18 at 11 25 17](https://github.com/winglang/wing/assets/2538825/81c9dac8-32dd-4f4c-9e18-2212cbe35d71)

**Comment by eladb** [comment]
Cool beans!
