### ISSUE TITLE
Error when invoking a cloud.Function in the console

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2922]
### I tried this:

Wrote this code:
```ts
bring cloud;

new cloud.Function(inflight () => {});
```

Tried to invoke the function (with or without payload)

### This happened:

Invocation failed and this error appeared in the log:
> Unknown error: Cannot read properties of null (reading 'toString')

### I expected this:

Everything to go smoothly

### Component

Wing Console

### Wing Version

0.21.5

### Wing Console Version

0.2.183

### Platform(s)

MacOS

### Anything else?

Anything with a function generated this (bucket events, queue consumers, etc.)

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
resolved.
update to the new console version 0.2.184 
(will be downloaded automatically by our console auto updater).
