### ISSUE TITLE
Learn: empty state of console/code is confusing

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2927]
### I tried this:

Go into learn.winglang.io

### This happened:

The right hand side showed an empty state view of the the code and console. 

### I expected this:

I waited for it to load but it never did.

I think that the initial view should not include the right hand side at all. Maybe some nice graphics?

### Component

Tutorial

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
The current ui for an empty state looks like a loading state skeletons.

@polamoros i remember we have several types of empty state visuals. Can you take it Amiel?

**Comment by amielpb** [comment]
@polamoros and I spoke about this, we think the best option is to keep it blank so as to not take attention away from the welcome message, a graphic or animation would be eye catching and also nto solve the problem of the user waiting for something to happen when they need to press the start button. Can I close the issue?

**Comment by polamoros** [comment]
I already removed the empty state images and merged the PR. We can close this issue
