### ISSUE TITLE
cdktf Terraform iterators are not working

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#2930]
### I tried this:

Use Terraform iterators as described in the [cdktf docs](https://developer.hashicorp.com/terraform/cdktf/concepts/iterators#define-iterators)

```
bring cloud;
bring "cdktf" as cdktf;
bring "@cdktf/provider-dnsimple" as dnsimple;

new dnsimple.provider.DnsimpleProvider();

let simpleIterator = cdktf.TerraformIterator.fromList(cdktf.Fn.toset([
  "nameserver1.",
  "nameserver2",
  "nameserver3",
  "nameserver4"
]));

let record = new dnsimple.zoneRecord.ZoneRecord(
  forEach: simpleIterator,
  zoneName: "mydomain.org",
  name: "test",
  type: "NS",
  ttl: 3600,
  value: simpleIterator.value
);
```

### This happened:

```
Expected type to be "ITerraformIterator?", but got "ListTerraformIterator" instead
preflight simpleIterator: ListTerraformIterator
class ListTerraformIterator extends TerraformIterator
```

![Screenshot 2023-06-15 at 15 48 27](https://github.com/winglang/wing/assets/136789/27d9861a-3fcc-444c-9017-d6565f17dba1)

### I expected this:

No compiler / type error

### Is there a workaround?

Use escape hatches:

```
record.addOverride("for_each", cdktf.Fn.toset([
  "nameserver1.",
  "nameserver2",
  "nameserver3",
  "nameserver4"
]))
```

### Component

Compiler

### Wing Version

0.21.4

### Node.js Version

v18.16.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skorfmann** [comment]
Also: I can't provide string to forEach because of the type expected by cdktf. Any other workaround in Wing? (something like any type?)

**Comment by Chriscbr** [comment]
Tested with Wing 0.59.12, the error doesn't seem to be present anymore. Closing
