### ISSUE TITLE
Generic Terraform Target

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#2931]
### Feature Spec

With `wing compile -t tf-generic main.w` it's now possible to compile pure non SDK applications. This omits wing sdk specific config such as the automatically added aws provider and the function output.

### Use Cases

For cases where the wing application contains only providers other than `aws`, it could be nice to produce a clean stack output and be clearer in terms of usage.

I know this is a stretch in terms of use-cases, in particular since there are no real downsides in the current implementation (except for the unnecessary download of the aws provider). Created this issue to collect feedback if that's a desired / supported use-case.

### Component

CLI

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
> Created this issue to collect feedback if that's a desired / supported use-case.

Totally a desired use case - I found an issue we already have for it 😄 (I just updated its title to make it a bit clearer) https://github.com/winglang/wing/issues/2365

Closing as duplicate
