### ISSUE TITLE
`==` has higher precedence in grammar than `Json value` expression

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#2937]
### I tried this:

```js
assert(Json true == Json true);
```

### This happened:

```
error: Expected type to be "bool", but got "Json" instead
  --> equality.w:1:13
  |
1 | assert(Json true == Json true);
  |             ^^^^^^^^^^^^^^^^^ Expected type to be "bool", but got "Json" instead


error: Expected type to be "bool", but got "Json" instead
  --> equality.w:1:8
  |
1 | assert(Json true == Json true);
  |        ^^^^^^^^^^^^^^^^^^^^^^ Expected type to be "bool", but got "Json" instead
```

### I expected this:

It compiles

### Is there a workaround?

Wrap `Json true` in parentheses:

```js
assert((Json true) == Json true);
```

### Component

Compiler

### Wing Version

0.19.14

### Node.js Version

18.14.1

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by hasanaburayyan** [comment]
This is no longer an issue, the example provided works. I think the inference changes fixed it
