### ISSUE TITLE
Wrong Test Count

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#2946]
### I tried this:

run `wing test` for a file with multiple tests

### This happened:

```
pass ─ main.wsim » root/env0/test:GET --project--:project
pass ┌ main.wsim » root/env1/test:GET --project--:project (unauthorized, missing header)
     │ auth failed
     └ Error fetching http://127.0.0.1:64097/project/test-project: 403 Forbidden
pass ┌ main.wsim » root/env2/test:GET --project--:project (unauthorized, wrong header)
     │ user not found
     │ auth failed
     └ Error fetching http://127.0.0.1:64098/project/test-project: 403 Forbidden
pass ┌ main.wsim » root/env3/test:GET --project--:project (project does not exist)
     │ project not found
     └ Error fetching http://127.0.0.1:64099/project/other-project: 404 Not Found





Tests 1 passed (1)
Duration 0m8.44s
```

Test count is displayed as 1

### I expected this:

`Tests 4 passed (4)`

### Component

CLI

### Wing Version

0.21.4

### Node.js Version

v18.16.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by tsuf239** [comment]
closed by https://github.com/winglang/wing/pull/3054
