### ISSUE TITLE
Add compiler error types and codes

### ISSUE THREAD

**Issue by MarkMcCulloh** [winglang/wing#295]
wingc errors are currently adhoc. We should have errors for specific situations. This issue can cover some basic ones for now, with the addition that the Diagnostics system can consume these errors and any `Result` types use them. These errors should have info like spans, error codes, etc.

- [ ] CompileError
- [ ] TypeError
- [ ] CaptureError
- [ ] UnimplementedError
- [ ] JsifyError (maybe a better name :) )

**Comment by staycoolcall911** [comment]
Duplicates #1746
