### ISSUE TITLE
learn and playground analytics is broken

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#2958]

**Comment by ainvoner** [comment]
few notes:
1. report analytics from a single location (either host or container but not from both)
2. remove segment.identify (segment should handle it for us)

**Comment by skyrpex** [comment]
> few notes:
> 
> 1. report analytics from a single location (either host or container but not from both)
> 2. remove segment.identify (segment should handle it for us)

Okay, given these restrictions, I believe the simplest way to achieve this is to send the traces via post message, the same way it was before.

**Comment by skyrpex** [comment]
After merging and publishing https://github.com/winglang/console/pull/626, we'll need to update the `@wingconsole/app` version in the playground repo.
