### ISSUE TITLE
Map view animation into view looks like a bug

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2968]
### I tried this:

Open Wing Console with `wing it`.

### This happened:

The map view animated into view from 0,0 to the center:

https://github.com/winglang/wing/assets/598796/5253edaa-312e-4763-8c04-af99c77d096b

### I expected this:

Just appear in the center

### Is there a workaround?

N/A

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
fixed
