### ISSUE TITLE
Compiler not showing error when `path` is not provided to `new cloud.Website()`

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2970]
### I tried this:

```js
bring cloud;
new cloud.Website();
```

Another example:

```js
bring cloud;

struct FooProps {
    required: str;
}

class Foo {
    init(props: FooProps) { }
}

new Foo();
```

### This happened:

```
ERROR: Cannot read properties of undefined (reading 'path')

target/test.wsim.268992.tmp/.wing/preflight.js:9
     constructor(scope, id) {
       super(scope, id);
>>     this.node.root.newAbstract("@winglang/sdk.cloud.Website",this,"cloud.Website");
     }
   }
```

### I expected this:

Compiler error should tell me that `path` is required.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by tsuf239** [comment]
@eladb how did you run the code, 
Both examples were throwing the correct errors for me:
ran with `wing test`
<img width="574" alt="image" src="https://github.com/winglang/wing/assets/39455181/74fc002f-c26b-4d15-9e2e-53d1918fd933">
<img width="534" alt="image" src="https://github.com/winglang/wing/assets/39455181/2c4fa236-f255-4219-9dae-be41ed114535">
