### ISSUE TITLE
monaco suggest widget is cropped

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#3003]
![Image](https://user-images.githubusercontent.com/1727147/247485987-5166bcfd-344c-4f6b-ae67-585be25a5099.png)

**Comment by ekeren** [comment]
@ainvoner FYI

**Comment by ainvoner** [comment]
@polamoros it seems like the suggestion widget auto layout is working for everyone else.
for example: https://codesandbox.io/s/editor-instance-354cr?file=/src/App.js

**Comment by ekeren** [comment]
@ainvoner , as far as I can see the link you've shared also has the same problem
![image](https://github.com/winglang/wing/assets/1727147/41b8507e-a542-49f8-8adb-17fcaf1e7a0b)


Am I missing anything?

**Comment by polamoros** [comment]
@ekeren I guess you have the same issue because the console panel is not part of the viewport.

check this example from the @ainvoner's link
<img width="602" alt="image" src="https://github.com/winglang/wing/assets/5547636/34304878-d5fb-403f-96be-948be8482114">
