### ISSUE TITLE
No intellisense for function signatures in the playground

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#3033]
### I tried this:

Wrote this code in the playground:

```ts
bring cloud;

let bucket = new cloud.Bucket();
bucket.addObject(
```

### This happened:

No intellisense for the function was displayed

### I expected this:

To have intellisense displayed like it is displayed in VSC

### Is there a workaround?

Hover on the function

### Component

Compiler

### Wing Version

0.22.8

### Anything else?

It does work in VSC, and also hovering on the function shows the contract, but users don't know they can do it and expect to get it when writing the opening parethesis.

Also, I put the component as the compiler since there is no option to select LSP.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ShaiBer** [comment]
I put the component as the compiler since there is no option to select LSP.

**Comment by ekeren** [comment]
It does show when you put the cursor on the function. 
![Image](https://github.com/winglang/wing/assets/1727147/bae78211-6c02-4499-ae20-e1e10b9483e5)
