### ISSUE TITLE
Unable to define MutArray<cloud.Bucket>

### ISSUE THREAD

**Issue by revitalbarletz** [winglang/wing#3043]
### I tried this:

test "pushAndPopBucket()" {
  let b1 = firstBucket;
  let firstBucketStr = firstBucket.node.id;
  let secondBucketStr = secondBucket.node.id;
  let a = MutArray<cloud.Bucket>[firstBucket];
}

### This happened:

Compiler yells: 

- Unable to qualify which operations are performed on 'firstBucket' of type 'Bucket'. This is not supported 
- Cannot capture field 'node' with non-capturable type 'Node'

### I expected this:

No errors are expected.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Discussed it with @revitalbarletz - we currently don't support this code - the compiler errors make sense to me.
Closing for now.
