### ISSUE TITLE
TS enums (i.e cloud.HttpMethod) value is different between inflight and preflight

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#3049]
### I tried this:

Testing this code on local via `wing test -t sim <file>` command
![image](https://github.com/winglang/wing/assets/39455181/e28fbea5-1062-41e9-8273-b62f4494d3cd)

### This happened:

The enums' value is a number on inflight and string on preflight

### I expected this:

to equal their TS string value

### Is there a workaround?

yes, we can bypass it by assigning the enum's value into a variable on the preflight, and then use the variable inflight

### Component

Compiler

### Anything else?

please refer to this Slack thread for more information: https://winglang.slack.com/archives/C048QCN2XLJ/p1687425563136599

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Hey @tsuf239 - thanks for reporting. Could you please edit the issue to have a clear code sample that could be copy-pasted to show what's not working as expected? As it is now, it seems perhaps you just need to change from `HttpMethods` to `HttpMethod`, but I'm guessing I'm missing something...
This code works:
```ts
bring cloud;
bring http;

let a = http.HttpMethod.PATCH;
log("${http.HttpMethod.GET}");

test "test" {
  log("${http.HttpMethod.GET}");
}
```

**Comment by staycoolcall911** [comment]
Ok I see what this issue is about... the error messages on the screenshot were misleading. The code runs correctly, except that it prints `GET` on preflight and `0` on inflight. The sample above shows that.

**Comment by staycoolcall911** [comment]
Fixed
