### ISSUE TITLE
Panic: `encountered unresolved type during jsification`

### ISSUE THREAD

**Issue by eladb** [winglang/wing#3059]
### I tried this:

```js
class Foo { }

inflight () => {
  arr.at(y);
};
```

### This happened:

```
Compiler bug (panicked at 'Encountered unresolved type during jsification', libs/wingc/src/jsify.rs:1801:33) during jsifying, please report at https://docs.winglang.io/contributors/bugs
```

### I expected this:

No bug

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
This was resolved in #3128
