### ISSUE TITLE
The Redis resource's `help` command doesn't open the link for you

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#3066]
When typing the `help` command in a Redis resource, it should open the URL for you (but it doesn't).

So, either display a clickable link or open it automatically.

**Comment by ainvoner** [comment]
@skyrpex works for me... can you provide more details?

**Comment by skyrpex** [comment]
Typing `help` prints the following output (as expected) 
<img width="306" alt="image" src="https://github.com/winglang/wing/assets/1077520/18f43572-a511-4e78-b08b-040c720c7ccb">

But the link is not open automatically (as the message suggests).

**Comment by ainvoner** [comment]
just to clarify: it worked properly when used by Wing cli.
Didn't work in dev.
fixed
