### ISSUE TITLE
Simulate resource permissions

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#3082]
### Feature Spec

Wing's `sim` target today allows applications to be tested using simulated versions of cloud services. The simulation accurately reflects some of the limitations of deploying cloud applications today (for example, the fact that a resource must be deployed after any resources its configuration depends on), but not others. One noticeable difference is that permissions are not simulated. This means that if the Wing compiler generates classes with incorrect permissions, in many cases the only way to catch them is if you try to deploy and run the application on AWS.

### Use Cases

Discover permission bugs sooner and as part of our end-to-end testing of the Wing language. Most users and contributors assume "if it works on the simulator, then it will work on the cloud", and simulating permissions will make this gap smaller (at a small runtime cost).

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by garysassano** [comment]
Maybe a possible solution could be to use [Cedar Agent](https://github.com/permitio/cedar-agent) to manage permissions in the simulator?

**Comment by garysassano** [comment]
Maybe a possible solution could be to use [OPA](https://github.com/open-policy-agent/opa) or [Cedar Agent](https://github.com/permitio/cedar-agent) to manage permissions in the simulator?

**Comment by Chriscbr** [comment]
This has been implemented
