### ISSUE TITLE
Standard library: utility functions

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#3096]
### Feature Spec

A number of simple utility functions are added to Wing's standard library as described in [the RFC](https://www.winglang.io/contributing/rfcs/stdlib).
This includes the following modules:
- [x] `math`
- [x] `fs`
- [x] `util`

`http` module was already previously added.
- [x] http 

### Use Cases

Support simple programming needs such as performing math or file-system operations.

### Implementation Notes

`util` module: `env`, `tryEnv` and `sleep` were done previously (see the source under https://github.com/winglang/wing/blob/main/libs/wingsdk/src/util/util.ts). Still need to add the rest of the methods defined in the RFC.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by revitalbarletz** [comment]
@marciocadev is working on the math module.

**Comment by staycoolcall911** [comment]
The only thing left to close this one is adding a simple `fs` module as defined in the RFC [here](https://www.winglang.io/contributing/rfcs/stdlib).

**Comment by staycoolcall911** [comment]
@marciocadev - took you off this issue, because you already added the `math` and `util` modules, but if you want to implement the `fs` module as well please reassign this to yourself. Thanks!

**Comment by jianzs** [comment]
Hey, there. I am working on the `fs` module.
