### ISSUE TITLE
Failed to bundle function: [object Object] when passing map from preflight to inflight

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#3119]
### I tried this:

test on sim: 
```
bring cloud;

// NOT WORKING
let m1 = Map<str> {
    "a a": "b", 
  };

test "test 1" {
  log(m1.get("a a"));
}

// WORKING
let m2 = Map<str> {
    "a": "b", 
  };

test "test 2" {
  log(m2.get("a"));
}


// WORKING
test "test 3" {
  let m3 = Map<str> {
    "a a": "b", 
  };

  log(m3.get("a a"));
}
```

### This happened:

when a map has a key that includes a space, it throws this error when the map is in the preflight:
<img width="1135" alt="image" src="https://github.com/winglang/wing/assets/39455181/9ddf8120-ea52-43bf-b2c0-ec81e43636e5">
 Error: Failed to bundle function: [object Object]

when it doesn't include space or is found within the inflight scope it's working.

### I expected this:

to work with no errors

### Is there a workaround?

placing the map in the inflight scope

### Component

Compiler

### Wing Version

0.22.31

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
I encountered this as well. It looks like the examples originally posted are working for me (after updating them to the latest map syntax with "=>"), but here is a new example where it fails to bundle when I run `wing compile -t tf-aws main.w`:

```js
bring cloud;

let headers = {
  "my-fancy-header" => "my-fancy-value"
};

let api = new cloud.Api();
api.get("/hello", inflight (req: cloud.ApiRequest): cloud.ApiResponse => {
  return cloud.ApiResponse {
    status: 200,
    headers: headers,
    body: "Hello, world!"
  };
});
```
