### ISSUE TITLE
Class declaration: overloading constructor and methods

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#3123]
Allow class methods (including `init`)to be overloaded with many signatures only varying in the number of arguments and their unique type order.

**Comment by eladb** [comment]
Let's close this for now. I am not sure we need it.

**Comment by staycoolcall911** [comment]
hmmm... it makes sense for an OOP-like language to have this feature - users would try to override methods and constructors. If we decide not to support it, at the very least we should give a reasonable error message. I'm fine just leaving it in our backlog

**Comment by eladb** [comment]
Not all OOP languages have support for overloading (e.g. TypeScript/JavaScript). 

The current error is `error: Symbol "bar" already defined in this scope` which is reasonable to me, no?

**Comment by staycoolcall911** [comment]
Ok, I'm fine closing this for now.
