### ISSUE TITLE
Links in the docs lead to 404

### ISSUE THREAD

**Issue by revitalbarletz** [winglang/wing#3130]
### I tried this:

https://www.winglang.io/docs/concepts/compiler-targets
Portability section, found [here](https://www.winglang.io/docs/concepts/docs/docs/04-standard-library/03-winglang-support-matrix) link leads to 404. 

Same for https://www.winglang.io/docs/language-guide/equality - Equality section, ([preflight or inflight)](https://www.winglang.io/docs/02-core-concepts/01-preflight-and-inflight.md) link.

### This happened:

404 page

### I expected this:

Lead to the right doc.

### Component

Documentation

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by garysassano** [comment]
Fixed in #3171
