### ISSUE TITLE
Json.entries()

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#3142]
Json static method `.entries()`

**Comment by staycoolcall911** [comment]
> I was running into this issue earlier (I had no way to iterate over a JSON value's keys). 

Have you tried using the `Json.keys` static method?

> I wonder what should the behavior of the function be when the Json value isn't an object? Throw? Return an empty map?

Empty map makes sense to me.

**Comment by Chriscbr** [comment]
> Have you tried using the Json.keys static method?

I think I missed that one - thanks!
