### ISSUE TITLE
verify no broken links in our onboarding sites

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#3150]
We have two types of problems 
- [x] broken links 
  - [ ] from webflow winglang.io - current [data](https://docs.google.com/spreadsheets/d/1M3aqmyShq2Xw33eHFcS-6DOvO-9shyjpzOkeNtFHd9c/edit?usp=drive-slack&ts=64a53431), @RoniWDS will update with more relevant data
  - [ ]  from docs
- [x] wrong links 
for example :
in the footer -> Language Specification ->  https://www.winglang.io/contributing/rfcs/language-spec ( instead of https://www.winglang.io/docs/language-guide/language-reference)

**Comment by ekeren** [comment]
@ShaiBer is this description correct?

**Comment by ekeren** [comment]
fixed footer in https://github.com/winglang/docsite/pull/504

**Comment by ekeren** [comment]
fixed footer in webflow

**Comment by ekeren** [comment]
Fixed all, waiting for @RoniWDS to verify

**Comment by ekeren** [comment]
And we are done !
