### ISSUE TITLE
Add provider specific identifier to wing resources

### ISSUE THREAD

**Issue by fynnfluegge** [winglang/wing#3152]
### Feature Spec

With a provider specific wing resource identifier it is possible to wire wing resources with higher level `aws-cdk` or `terraform-cdk` constructs by creating cdk references from that identifier.

For example, we have a wing bucket and an aws-cdk `DockerImageFunction`. By using the identifier from the wing bucket it is possible to create a aws-cdk `S3EventSource` and attach it to the `DockerImageFunction`.
```javascript
let bucket = new cloud.Bucket();

class CdkDockerImageFunction {
  function: awscdk.aws_lambda.DockerImageFunction;

  init() {
    this.function = new awscdk.aws_lambda.DockerImageFunction(awscdk.aws_lambda.DockerImageFunctionProps{
      code: awscdk.aws_lambda.DockerImageCode.fromImageAsset("./docker.assets"),
    }) as "DockerImageFunction";

    let wingBucketIdentifier = bucket.providerIdentifier() // <-- ARN if compiled with target AWS

    // Create an S3 bucket, referencing the previously created wing bucket
    let s3BucketRef = aws_cdk.aws_S3.fromBucketArn('ExistingBucket', wingBucketIdentifier);

    // Attach an S3 event source mapping for the Lambda function
    this.function.addEventSource(new aws_cdk.aws_lambda_event_sources.S3EventSource(s3BucketRef, {
      events: [s3.EventType.OBJECT_CREATED]
    }));
  }
}
```

### Use Cases

Sometimes it might be necessary to create cloud resources from cdk constructs, e.g. if a user wants to use python libraries in a function and hence, this function needs to be bundled with Docker. For these specific kind of use cases a cdk construct can be used.
But to let these constructs interact with wing resources in a wing application, there needs to be an interface for that. CDKs provide handy methods to create references from identifier. With these references, logical objects like event mappings can be created and attached to cdk constructs.
There might be many other use cases where the wing sdk is not sufficient yet and hence a cdk construct needs to step in.
Currently it is not possible to let these constructs interact with wing resources without doing some tweaks outside of the wing source code.

### Implementation Notes

The provider identifiers should be derived from the compile target, e.g. it should be the ARN for AWS and the resource ID for Azure.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Great suggestion @fynnfluegge! Adding this to our plans.
In the meantime you can use `let target = util.tryEnv("WING_TARGET");` and add a target specific behavior.

**Comment by fynnfluegge** [comment]
Thanks for the hint @staycoolcall911! I didnt know that env vars are helpful in this situation. What is `WING_TARGET` in that case? The name of the resource?

**Comment by fynnfluegge** [comment]
Alright, got it! An example would be great 👍

**Comment by revitalbarletz** [comment]
@staycoolcall911 I think we can close this one, as it was already implemented by Marcio https://github.com/winglang/wing/pull/5002
