### ISSUE TITLE
docs: Update title & description metadata of top pages for SEO

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#3164]
@dannac2 has details:

https://docs.google.com/spreadsheets/d/1M3aqmyShq2Xw33eHFcS-6DOvO-9shyjpzOkeNtFHd9c/edit?usp=sharing

**Comment by ekeren** [comment]
@ainvoner are you familiar with this?

**Comment by ekeren** [comment]
@dannac2 , lets talk about this

**Comment by dannac2** [comment]
@ekeren replied on slack
