### ISSUE TITLE
No way to denote optional function type

### ISSUE THREAD

**Issue by MarkMcCulloh** [winglang/wing#3183]
### I tried this:

Let's set I want to declare a type to be an function:

```ts
let x: (): num
```

There is no way to make x (the function sig) optional. The following makes the return type optional:

```ts
let x: (): num?
```

### This happened:

Nothing

### I expected this:

To have some way to denote this.

### Is there a workaround?

No

### Component

Language Design, Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Duplicates #3115
