### ISSUE TITLE
(Ops) Monitoring auto-resolve causes false alarm for maintainer

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#3186]
Sometimes, a monitoring incident on BetterUptime getting auto-resolved results in a new PagerDuty incident getting created, resulting in a maintainer getting paged.

Example: https://uptime.betterstack.com/team/48207/incidents/416200671
(screenshot from BetterUptime)
<img width="1031" alt="Screenshot 2023-06-30 at 2 26 03 PM" src="https://github.com/winglang/wing/assets/5008987/ee128505-de9e-4fd1-81a9-27e777bbeb07">

**Comment by staycoolcall911** [comment]
Thanks for reporting - we have plans to switch from BetterUptime to Sentry, so marking this as p3 for now

**Comment by staycoolcall911** [comment]
@Chriscbr did you see that lately? I'm not sure if we should keep it

**Comment by staycoolcall911** [comment]
Closing for now
