### ISSUE TITLE
remove display and node from cloud.* public api

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#3211]
I've been wondering about this for a while, can these 2 api be removed from the public api of the cloud.resources?

![image](https://github.com/winglang/wing/assets/1727147/18d896be-1fdc-489d-91b1-4b4253b37788)

**Comment by staycoolcall911** [comment]
Not sure what's `display` for, but we use `node` to get the resource id and path. See for example: https://github.com/winglang/wing/blob/main/examples/tests/sdk_tests/std/array.w

**Comment by staycoolcall911** [comment]
Closing - we decided it is not needed
