### ISSUE TITLE
Difficult to figure out http.get response.body is optional

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#3221]
### I tried this:

```ts
bring http;

let response = http.get("some/url", { headers: { "content-type": "application/json" }});
let b = response.body;
```

### This happened:

Hovering over `response.body` shows no doc, so I can't know the type is `str?`. 
Also if I delete `body`, `response.` shows `body` as a completion option (which is great), but no indication that it is an optional.
<img width="855" alt="image" src="https://github.com/winglang/wing/assets/106860404/b7c6539e-80ef-4299-9531-e73bde529574">

### I expected this:

To be able to to know `response.body` is optional without having to check the [reference documentation](https://www.winglang.io/docs/standard-library/http/api-reference#@winglang/sdk.http.Response.property.body).

### Is there a workaround?

Use the [reference documentation](https://www.winglang.io/docs/standard-library/http/api-reference#@winglang/sdk.http.Response.property.body).

### Component

IDE Extension

### Wing Version

0.23.11

### Node.js Version

18.15.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Let's add a `?` next to `body` to indicate it is optional

**Comment by staycoolcall911** [comment]
But of course, @naorpeled :) You got it

**Comment by naorpeled** [comment]
@staycoolcall911 
this seems to already be working as you expected atm 🙏 
Not sure if I'm missing anything.

<img width="1486" alt="image" src="https://github.com/winglang/wing/assets/6171622/98e4cfae-0757-4070-826c-713b3b1b6a6a">

**Comment by staycoolcall911** [comment]
You're correct @naorpeled - it must have been fixed recently by an anonymous contributor :)
If you'd like to find an alternative `good first issue` issue to work on I'm happy to suggest a few for you to choose from.
You can contact me via Slack (@Uri Bar).
