### ISSUE TITLE
SDK Simple HTTP check resource

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#3226]
### Feature Spec

With the new SimpleHttpCheck SDK resource it's now possible to perform HTTP check for provisioned resources as part of the the deployment configuration. 

Before this, one had to build a check by adding the [Http Data source](https://registry.terraform.io/providers/hashicorp/http/latest/docs/data-sources/http) with a [custom condition](https://developer.hashicorp.com/terraform/language/expressions/custom-conditions) like this:

```
bring "@cdktf/provider-http" as httpProvider;
new httpProvider.provider.HttpProvider();

let check = new httpProvider.dataHttp.DataHttp(
  url: "https://www.winglang.io",
  lifecycle: cdktf.TerraformResourceLifecycle {
    postcondition: [cdktf.Postcondition {
      condition: "\${contains([200], self.status_code)}",
      errorMessage: "Expected status code 200"
    }]
  }
);

// pseudo code
check.addDependency(myDistribution)
```

Now:

```
new util.HttpCheck(
  url: "https://www.winglang.io",
  expectedStatusCodes: [200], 
)

check.addDependency(myDistribution)
```

### Use Cases

A simple check as part of the deployment configuration. This is not replacing proper monitoring, but serves as a quick check that the provisioned resources are behaving as expected and are up and running.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skorfmann** [comment]
That's how an error looks like 

```
│   on main.tf.json line 83, in data.http.root_httpProviderdataHttpDataHttp_3A6839DC.lifecycle.postcondition[0]:
│   83:               "condition": "${contains([400], self.status_code)}",
│     ├────────────────
│     │ self.status_code is 200
│ 
│ Expected status code 200
```

**Comment by staycoolcall911** [comment]
I think this can be implemented with the OnDeploy resource as @Chriscbr pointed out or using a Winglib [Check](https://github.com/winglang/winglibs/tree/main/checks).
Closing, please reopen if I'm missing a use case.
