### ISSUE TITLE
Compiler doesn't error if I am trying to assign into a captured variable

### ISSUE THREAD

**Issue by eladb** [winglang/wing#3249]
### I tried this:

```js
let var x = 12;
inflight () => {
  x = 44;
};
```

Same as inflight and any other "capture" case.

### This happened:

Compilation was successful

### I expected this:

Should fail

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
@eladb In your example, is the closure supposed to be inflight? i.e. `inflight () => { ... }`

**Comment by eladb** [comment]
I think we can close this for now. Across phases it is forbidden and I think we have an error. No?

**Comment by ekeren** [comment]
updated description (added `inflight`)

verified fix
![image](https://github.com/winglang/wing/assets/1727147/917dd0af-25f0-4d1a-801c-052d043c845c)


see it here
https://www.winglang.io/play/?code=bABlAHQAIAB2AGEAcgAgAHgAIAA9ACAAMQAyADsACgBpAG4AZgBsAGkAZwBoAHQAIAAoACkAIAA9AD4AIAB7AAoAIAAgAHgAIAA9ACAANAA0ADsACgB9ADsA
