### ISSUE TITLE
Console log says test succeeded even though it failed

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#3264]
### I tried this:

`wing it` for this simple wing system:
```ts
test "doomed to fail" {
    assert(false);
}
```
Then ran the test on the console

### This happened:

Console log says the assertion failed (which is correct).
Nevertheless, the log says the test succeeded (see screenshot).
![image](https://github.com/winglang/wing/assets/106860404/40e26d3f-7dac-4fef-9842-400951da6c62)

### I expected this:

Test to show as failing.

### Component

Wing Console

### Wing Version

0.23.21

### Platform(s)

MacOS

### Anything else?

@ShaiBer pointed out correctly that wing tests recently changed behavior and are now returning 0 on failure. See #3176
This might be related.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
due to sdk test runner returned object changes
