### ISSUE TITLE
Some methods from `aws-cdk-lib` are not available with wing

### ISSUE THREAD

**Issue by fynnfluegge** [winglang/wing#3265]
### I tried this:

I tried to call `addEventNotification` on `IBucket`. 

### This happened:

`addEventNotification` is unknown in VS Code extension. 
<img width="1029" alt="Screenshot 2023-07-05 at 16 18 18" src="https://github.com/winglang/wing/assets/16321871/5f2c25f3-2484-4b03-8010-66e5953fea0f">

`wing compile` also threw
```
Unknown symbol "addEventNotification"
```

### I expected this:

`addEventNotification` should be available in wing as:

![Screenshot 2023-07-04 at 18 05 22](https://github.com/winglang/wing/assets/16321871/abb8b4d1-80d9-4b3d-aef6-b9865c2d23cc)

### Component

Compiler

### Wing Version

0.23.22

### Node.js Version

18.12.1

### Platform(s)

MacOS

### Anything else?

As in the screenshot from **This happened** section `addToResourcePolicy` is available. `addToResourcePolicy` is similar defined as `addEventNotification` in `IBucket`. There are more methods from `IBucket` like `onCloudTrailEvent` that are unknown in wing. Currently I don't see a pattern why some methods are unknown and some not.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment]
Mmm interesting... JSII importer is skipping those for some reason I persome.

**Comment by Chriscbr** [comment]
Yep this is due to https://github.com/winglang/wing/issues/397
