### ISSUE TITLE
Align typography of the tutorial to match our docs

### ISSUE THREAD

**Issue by eladb** [winglang/wing#3274]
Our typography for how the markdown is presented needs to align between docs and learn. The tutorial is basically part of our documentation.

I think we need to make sure we use the exact same CSS if possible.

As an example, the paragraph font in the docsite is:
- font-family: IBM Plex Sans
- font-weight: 400
- font-size: 1rem
- line-height 26.4px

And in learn:
- font-weight not defined
- font-size: 17.5px 
- line height: 21px

This also applies to any other elements in the markdown such as headings, block quotes, code blocks, etc.

**Comment by ekeren** [comment]
👍 

@ShaiBer is working on https://github.com/winglang/playground/pull/218 

Might want to incorporate these changes there

**Comment by ainvoner** [comment]
docs site is the base guideline for the style.
- adjust learn text (the new markdown) with the docs site.
- add an underline in both learn and play sites headers (as in docs)

**Comment by ShaiBer** [comment]
From what I can gather, the styles in the markdown are mainly taken from the classes that are defined on the div that wraps the 'MarkdownRender' component
