### ISSUE TITLE
Adding a built-in way to manage configurations in wing

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#3288]
### Feature Spec

When I developed a Slack bot, I had to hard-code Slack channel Ids, user Ids, and full names, since I didn't have a better way. 
We should think of a convenient and safe way to keep and use those "almost-sensitive" data pieces.

### Use Cases

writing a real-life wing code containing sensitive data, that isn't considered a secret 

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
A possible inspiration: See ballerina's `configurable` keyword https://ballerina.io/learn/distinctive-language-features/data/#configurable-variables

**Comment by staycoolcall911** [comment]
@tsuf239 - I think [platform parameters](https://www.winglang.io/docs/concepts/platforms#platform-parameters) is what you wanted, so I'm closing this issue. Please reopen if I'm wrong
