### ISSUE TITLE
SDK missing type information about inflights

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#329]
An important area of Wing standard library's API are the points where preflight and inflight meet.

Currently there are at least two APIs we have where a preflight function accepts an inflight function as an argument:

```ts
// 1.
new cloud.Function((event: any) ~> {
  print(event);
});

// 2.
let queue = new cloud.Queue();
queue.onMessage((event: any) ~> {
  print(event);
});
```

Inflight functions can have any number of arguments, but in the two above examples, it only makes sense to allow functions with a single argument to be passed. In the future, there may also be cases where we only want to allow functions with certain function signatures, like:

```ts
// 3.
let bucket = new cloud.Bucket();
bucket.onUpload((filename: num) ~> { // compile error: Inflight must have signature (filename: str) ~> void
  print(filename);
});
```

However, the Wing SDK is written in JSII, and here the API is modeled using the type `Inflight` (a class representing a piece of code). When those types are imported into the Wing compiler, it does not know what kind of inflights can be passed, so it assumes any are allowed. This information needs to be provided to the SDK, perhaps with a type annotation of some kind. The SDK should also have a linter rule to enforce that these type annotations are always included.

**Comment by staycoolcall911** [comment]
Related to #542

**Comment by staycoolcall911** [comment]
This is already done
