### ISSUE TITLE
Wing console emits random logs to STDIO

### ISSUE THREAD

**Issue by eladb** [winglang/wing#3291]
### I tried this:

Run:

```sh
wing it
```

### This happened:

![Screenshot 2023-07-06 at 15 04 09](https://github.com/winglang/wing/assets/598796/6525844d-a7ba-460e-a0e3-4e7a7dcfdf68)

### I expected this:

Quiet

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
fixed
