### ISSUE TITLE
tutorial - Improve copy button in markdown code blocks

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#3292]
What are the chance to use the copy icon similar to the one on docusaurus 
![image](https://github.com/winglang/playground/assets/1727147/58fead4d-aea9-45c2-bd84-e075af37b3ff)

```
<svg class="copyButtonIcon_y97N" viewBox="0 0 24 24" style="
    color: red;
"><path d="M19,21H8V7H19M19,5H8A2,2 0 0,0 6,7V21A2,2 0 0,0 8,23H19A2,2 0 0,0 21,21V7A2,2 0 0,0 19,5M16,1H4A2,2 0 0,0 2,3V17H4V3H16V1Z"></path></svg>
```

and the success indicator:
```
<svg class="copyButtonSuccessIcon_LjdS" viewBox="0 0 24 24"><path d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg>
```

_Originally posted by @ekeren in https://github.com/winglang/playground/pull/218#discussion_r1254059482_

**Comment by ekeren** [comment]
done by @polamoros #3274
