### ISSUE TITLE
Wing Console in VSCode does not always match theme

### ISSUE THREAD

**Issue by MarkMcCulloh** [winglang/wing#3309]
### I tried this:

1. System is configured for dark mode.
1. Open vscode code with a light mode theme.
1. Open console inside vscode

### This happened:

Wing console starts with dark theme (matching system theme)

### I expected this:

Wing console starts with light theme (matching vscode theme)

### Is there a workaround?

change the theme yourself

### Component

Wing Console, IDE Extension

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by polamoros** [comment]
fixed by https://github.com/winglang/wing/issues/3514
