### ISSUE TITLE
small improvements to the docs snippets

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#3340]
### Feature Spec

1. This: 
![image](https://github.com/winglang/wing/assets/39455181/482ab8b9-f1a0-4877-9f9d-3d98f5502126)
should become: 
`inflight start(): void`
with no `inflight client:true` line below 

2. this:
```
bring http;

http.Util.delete(url: str, options?: RequestOptions);
```

should become: 
```
bring http;

http.delete(url: str, options?: RequestOptions);
```

### Use Cases

improving documentation

### Component

Documentation

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
💯 

Number 1 and 2 are different issues, I would love to see number 1
