### ISSUE TITLE
`queue.timeout` doesn't seem to work in AWS

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#3354]
### I tried this:

Setting up a queue with a timeout,
inserting 2 messages that exceeded the timeout,
check what is the `approxSize`

### This happened:

The `approxSize` was different than 2

### I expected this:

Since timed-out messages should return to the queue the `approxSize` should be 2.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by revitalbarletz** [comment]
@ekeren I am not sure it is the timeout issue, could be that approx size is not returning the accurate size.

**Comment by tsuf239** [comment]
it could indeed be the approx size, (as it takes up to 1 minute to be updated) https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueAttributes.html

**Comment by marciocadev** [comment]
The `approxSize` on AWS only filters `ApproximateNumberOfMessages`, but this should not be the only filter.

* `ApproximateNumberOfMessages`: Returns the approximate number of messages available for retrieval from the queue.

* `ApproximateNumberOfMessagesDelayed`: Returns the approximate number of messages in the queue that are delayed and not available for reading immediately. This can happen when the queue is configured as a delay queue or when a message has been sent with a delay parameter.

* `ApproximateNumberOfMessagesNotVisible`: Returns the approximate number of messages that are in flight. Messages are considered to be in flight if they have been sent to a client but have not yet been deleted or have not yet reached the end of their visibility window.

However, the `ApproximateNumberOfMessagesDelayed`, `ApproximateNumberOfMessagesNotVisible`, and `ApproximateNumberOfMessagesVisible` metrics may not achieve consistency until at least 1 minute after the producers stop sending messages. This period is required for the queue metadata to reach eventual consistency.
