### ISSUE TITLE
Implicitly convert from mutable collections to immutable collections in return positions

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#3397]
### Feature Spec

The current behavior in Wing is if you write a function that expects to return a immutable collection type, but the implementation returns a mutable collection type, you will get a type checking error:

```js
let f = (): Array<str> => {
  let m = MutArray<str>[];
  m.push("a");
  return m;
};
```

```
error: Expected type to be "Array<str>", but got "MutArray<str>" instead
  --> example.w:4:10
  |
4 |   return m;
  |          ^ Expected type to be "Array<str>", but got "MutArray<str>" instead
```

The reason the compiler produces the error today is that when it's type checking the `return` statement, it simply looks to see if the value is a subtype of the return type annotation. In general, `MutArray<T>` is not a subtype of `Array<T>` in Wing because it breaks the API contract that a `Array<T>` cannot be mutated. If we allowed this subtyping relationship, the following errors would be left uncaught:

```js
let mutable_array = MutArray<num> [1, 2, 3];

// If MutArray is allowed to be assigned like this without cloning, due to the subtyping relationship
let immutable_array: Array<num> = mutable_array;

// immutable_array has changed, thus defeating the point of it being immutable
mutable_array.push(4)
```

In practice, however, it's not possible for the function in the first example to result in runtime errors, since the function's callers will always "see" the output as an immutable `Array<str>` (and hence, those are the only operations that will ever be used on it). To work around this today, it's necessary to call `.copy()` to convert the `MutArray<str>` to an `Array<str>`, but it can result in worse application performance.

I'd like to propose that the type checker implicitly converts from `MutArray<T>` to `Array<T>` (and likewise for all other collection types) in applicable `return` statements to support this kind of safe collection usage.

If my understanding's correct, I believe the rule works even recursively, so even these functions ought to be valid as well:

```js
let f1 = (): Array<MutArray<str>> => {
  let m = MutArray<MutArray<str>>[];
  m.push(MutArray<str>[]);
  return m;
};

let f2 = (): MutArray<Array<str>> => {
  let m = MutArray<MutArray<str>>[];
  m.push(MutArray<str>[]);
  return m;
};

let f3 = (): Array<Array<str>> => {
  let m = MutArray<MutArray<str>>[];
  m.push(MutArray<str>[]);
  return m;
};
```

### Use Cases

See examples above. Creating a mutable collection within a function and then providing an immutable version to the caller is a common use case.

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
This seems unsound without sufficient static analysis. What about this case?

```rust
let m = MutArray<str>[];

let f = (): Array<str> => {
  m.push("a");
  return m;
};

let iHopeThisIsImmutable = f();

m.push("oops");
```

So we'd have to check that no references exist outside the closure it's returning from, and I'm not sure how difficult that is (considering we basically don't have any static analysis yet)

**Comment by Chriscbr** [comment]
Ahhh you're right...  thanks for the sanity check.

I suppose we would have to somehow verify that `m` was initialized within the function and isn't otherwise reassigned to. Definitely on the tricky side.

(what if you had some "fix(value: T): Fixed<T>" function/operator which enforced that the value inside can't be moved between scopes? or can't be re-aliased? idk)

I'll close this since I don't see a clear path to implementation at the moment.
