### ISSUE TITLE
waitUntil options are confusing 

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#3406]
### I tried this:

```
bring cloud;
bring util;

let bucket = new cloud.Bucket();
let queue = new cloud.Queue();

queue.setConsumer(inflight (message: str) => {
  bucket.put("wing.txt", "Hello, ${message}");
}, timeout: 1s);

test "Hello, world!" {
  queue.push("world!");

  let found = util.waitUntil((): bool => {
    log("Checking if wing.txt exists");
    return bucket.exists("wing.txt");
  }, { 
    timeout: 1s,
    interval: 1ms
  });

  assert("Hello, world!" == bucket.get("wing.txt"));
}
```

[playground](https://www.winglang.io/play/?code=YgByAGkAbgBnACAAYwBsAG8AdQBkADsACgBiAHIAaQBuAGcAIAB1AHQAaQBsADsACgAKAGwAZQB0ACAAYgB1AGMAawBlAHQAIAA9ACAAbgBlAHcAIABjAGwAbwB1AGQALgBCAHUAYwBrAGUAdAAoACkAOwAKAGwAZQB0ACAAcQB1AGUAdQBlACAAPQAgAG4AZQB3ACAAYwBsAG8AdQBkAC4AUQB1AGUAdQBlACgAKQA7AAoACgBxAHUAZQB1AGUALgBzAGUAdABDAG8AbgBzAHUAbQBlAHIAKABpAG4AZgBsAGkAZwBoAHQAIAAoAG0AZQBzAHMAYQBnAGUAOgAgAHMAdAByACkAIAA9AD4AIAB7AAoAIAAgAGIAdQBjAGsAZQB0AC4AcAB1AHQAKAAiAHcAaQBuAGcALgB0AHgAdAAiACwAIAAiAEgAZQBsAGwAbwAsACAAJAB7AG0AZQBzAHMAYQBnAGUAfQAiACkAOwAKAH0ALAAgAHQAaQBtAGUAbwB1AHQAOgAgADEAcwApADsACgAKAHQAZQBzAHQAIAAiAEgAZQBsAGwAbwAsACAAdwBvAHIAbABkACEAIgAgAHsACgAgACAAcQB1AGUAdQBlAC4AcAB1AHMAaAAoACIAdwBvAHIAbABkACEAIgApADsACgAKACAAIABsAGUAdAAgAGYAbwB1AG4AZAAgAD0AIAB1AHQAaQBsAC4AdwBhAGkAdABVAG4AdABpAGwAKAAoACkAOgAgAGIAbwBvAGwAIAA9AD4AIAB7AAoAIAAgACAAIABsAG8AZwAoACIAQwBoAGUAYwBrAGkAbgBnACAAaQBmACAAdwBpAG4AZwAuAHQAeAB0ACAAZQB4AGkAcwB0AHMAIgApADsACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAYgB1AGMAawBlAHQALgBlAHgAaQBzAHQAcwAoACIAdwBpAG4AZwAuAHQAeAB0ACIAKQA7AAoAIAAgAH0ALAAgAHsACgAgACAAIAAgAHQAaQBtAGUAbwB1AHQAOgAgADEAcwAsAAoAIAAgACAAIABpAG4AdABlAHIAdgBhAGwAOgAgADEAbQBzAAoAIAAgAH0AKQA7AAoACgAgACAAYQBzAHMAZQByAHQAKAAiAEgAZQBsAGwAbwAsACAAdwBvAHIAbABkACEAIgAgAD0APQAgAGIAdQBjAGsAZQB0AC4AZwBlAHQAKAAiAHcAaQBuAGcALgB0AHgAdAAiACkAKQA7AAoAfQA%3D)

### This happened:

```
error: Expected "Json" elements to be Json values (https://www.json.org/json-en.html), but got "duration" which is not a Json value
   --> test.w:18:14
   |
18 |     timeout: 1s,
   |              ^^ Expected "Json" elements to be Json values (https://www.json.org/json-en.html), but got "duration" which is not a Json value

```

### I expected this:

- An error that the options should be a Map, rather than Json.

changing this to 

```
{
    "timeout" => 1s,
    "interval" => 1ms
  }
```

does work, while 

```
{
    timeout: 1,
    interval: 1
  }
```

compiles and executes, but does not have any effect.

### Is there a workaround?

Use a Map, as it was probably intended 

### Component

Compiler

### Wing Version

0.24.17

### Node.js Version

v18.16.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
The timeout and interval are struct fields, this would work:
```ts 
util.waitUntil((): bool => {
    return bucket.exists("wing.txt");
  }, timeout: 1s, interval: 1ms);
```



It seems that we have a DX problem here, of [struct expansion](https://www.winglang.io/docs/examples/structs#struct-expansion-in-function-calls) Json and Map. All three are similar and different, and the developer is tasked with understanding the difference. It will be even more of an issue when other developers will release api that don't always use struct as the optional last parameter.

**Comment by skorfmann** [comment]
interesting :D - yes, these are very subtle differences which are hard to grasp. 

Looking at the potential options makes me 🤯 

```
foo("arg", timeout: 1s, interval: 1ms ) // works
foo("arg", { "timeout" => 1s, "interval" => 1ms }) // works
foo("arg", { timeout: 1, interval: 1 }) // doesn't work, but compiles
foo("arg", { timeout: 1s, interval: 1ms }) // doesn't work, doesn't compile
```

It's certainly not intuitive at the moment. Perhaps compiler warnings which are pointing me as a user into the right direction would be helpful. But I think the underlying issue is really the dev ergonomics of having to fully understand the differences as @ekeren said.

**Comment by marciocadev** [comment]
Hey @skorfmann 

if you follow the IntelliSense your last line works if you put the `util.WaitUntilProps`
```ts (wing)
foo("arg", util.WaitUntilProps { timeout: 1s, interval: 1ms }) // works
```

All of this works
```ts (wing)
// If you follow the IntelliSense this is work
let found = util.waitUntil((): bool => {
    log("Checking if wing.txt exists");
    return bucket.exists("wing.txt");
  }, util.WaitUntilProps { 
    timeout: 1s,
    interval: 1ms
  }); 
// works too
let found = util.waitUntil((): bool => {
    log("Checking if wing.txt exists");
    return bucket.exists("wing.txt");
  }, { 
    "timeout" => 1s,
    "interval" => 1ms
});
// works again  
let found = util.waitUntil((): bool => {
    log("Checking if wing.txt exists");
    return bucket.exists("wing.txt");
}, timeout: 1s, interval: 1ms );
```

> There's too many options, too many alternatives
> Making too many problems
> And there's not much love to go around
> Can't you see this is the land of confusion?
>
> I couldn't resist, I love this song by Genesis.

![image](https://github.com/winglang/wing/assets/67694075/aed995d9-2346-49e4-83ec-f02772e21afc)

**Comment by ekeren** [comment]
Map shouldn't work , I wonder why it does?

All but struct explicit and struct expansion should result in a compilation error

**Comment by skorfmann** [comment]
Just to put some more colour to this, when defining the return type of an inflight function as a struct, it's a bit fiddly as well.

```
bring cloud;

struct MyStruct {
    a: str;
}

// works
let foo = inflight (): MyStruct => {
    return MyStruct {
        a: "hello"
    };
};

// doesn't
let bar = inflight (): MyStruct => {
    return {
        a: "hello"
    };
};

// doesn't
let baz = inflight (): MyStruct => {
    return {
        "a" => "hello"
    };
};

// doesn't
let bak = inflight (): MyStruct => {
    return MyStruct {
        "a" => "hello"
    };
};
```

see [playground](https://www.winglang.io/play/?code=YgByAGkAbgBnACAAYwBsAG8AdQBkADsACgAKAHMAdAByAHUAYwB0ACAATQB5AFMAdAByAHUAYwB0ACAAewAKACAAIAAgACAAYQA6ACAAcwB0AHIAOwAKAH0ACgAKAGwAZQB0ACAAZgBvAG8AIAA9ACAAaQBuAGYAbABpAGcAaAB0ACAAKAApADoAIABNAHkAUwB0AHIAdQBjAHQAIAA9AD4AIAB7AAoAIAAgACAAIAByAGUAdAB1AHIAbgAgAE0AeQBTAHQAcgB1AGMAdAAgAHsACgAgACAAIAAgACAAIAAgACAAYQA6ACAAIgBoAGUAbABsAG8AIgAKACAAIAAgACAAfQA7AAoAfQA7AAoACgBsAGUAdAAgAGIAYQByACAAPQAgAGkAbgBmAGwAaQBnAGgAdAAgACgAKQA6ACAATQB5AFMAdAByAHUAYwB0ACAAPQA%2BACAAewAKACAAIAAgACAAcgBlAHQAdQByAG4AIAB7AAoAIAAgACAAIAAgACAAIAAgAGEAOgAgACIAaABlAGwAbABvACIACgAgACAAIAAgAH0AOwAKAH0AOwAKAAoAbABlAHQAIABiAGEAegAgAD0AIABpAG4AZgBsAGkAZwBoAHQAIAAoACkAOgAgAE0AeQBTAHQAcgB1AGMAdAAgAD0APgAgAHsACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAewAKACAAIAAgACAAIAAgACAAIAAiAGEAIgAgAD0APgAgACIAaABlAGwAbABvACIACgAgACAAIAAgAH0AOwAKAH0AOwAKAAoAbABlAHQAIABiAGEAegAgAD0AIABpAG4AZgBsAGkAZwBoAHQAIAAoACkAOgAgAE0AeQBTAHQAcgB1AGMAdAAgAD0APgAgAHsACgAgACAAIAAgAHIAZQB0AHUAcgBuACAATQB5AFMAdAByAHUAYwB0ACAAewAKACAAIAAgACAAIAAgACAAIAAiAGEAIgAgAD0APgAgACIAaABlAGwAbABvACIACgAgACAAIAAgAH0AOwAKAH0AOwA%3D)

And yes, there are probably good reasons why this doesn't work. The point is confusing DX - "don't make me think" :)

**Comment by skorfmann** [comment]
I think there are multiple issues where this could be added. Just put it here to illustrate the potential confusion, in particular in combination with unhelpful compiler error messages like in these screenshots.

```
let api = new cloud.Api();

api.get("/hello", inflight (req: cloud.ApiRequest): cloud.ApiResponse => {
  return cloud.ApiResponse {
    status: 200,
    headers: Map<str> {
      "Content-Type": "text/plain" // works with =>
    },
    body: "Hello, world!"
  };
});
```
![Screenshot 2023-07-17 at 20 42 08](https://github.com/winglang/wing/assets/136789/65764359-c7b0-4416-bf93-a3f53056c77b)

![Screenshot 2023-07-17 at 20 42 20](https://github.com/winglang/wing/assets/136789/5d4adce4-3d49-47b2-9489-70aa9281ec80)

![Screenshot 2023-07-17 at 20 42 30](https://github.com/winglang/wing/assets/136789/a2f568c6-7cfe-47e5-b10f-09a077c43b5a)

**Comment by staycoolcall911** [comment]
This works now (compiles and the test runs). Closing.
