### ISSUE TITLE
Unable to copy text from Wing Console logs in VSCode extension

### ISSUE THREAD

**Issue by eladb** [winglang/wing#3408]
### I tried this:

Copy some text from the Wing Console logs (when opened through the VSCode pane)

### This happened:

Didn't work

### I expected this:

To work.
I also expected right-click to show me a menu with "Copy"

### Is there a workaround?

If I run `wing it` it works (from the browser).

### Component

IDE Extension

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by polamoros** [comment]
fixed by https://github.com/winglang/wing/issues/3514
