### ISSUE TITLE
Main build is failing

### ISSUE THREAD

**Issue by revitalbarletz** [winglang/wing#3418]
### Incident description

Build is failing on publish: https://github.com/winglang/wing/actions/runs/5542451480

### Incident Response Checklist

- [X] CREATE this issue (fill up the title, description and submit), then follow the next steps.
- [x] PIN the incident issue.
- [x] ACKNOWLEDGE the incident on [PagerDuty](https://monada.pagerduty.com/incidents).
- [x] ACKNOWLEDGE the incident on [BetterStack](https://uptime.betterstack.com/team/48207/incidents).
- [ ] WORKAROUND - if there is one, make sure it is documented in the section above.
- [x] PRIORITIZE (P0/P1/P2 - see the definitions [here](https://www.winglang.io/contributing/maintainers/operations#severity-levels)).
- [ ] (optional) CONTACT a relevant person who has more information about the incident.
- [ ] (optional) ANNOUNCE major incidents on Slack \#dev or \#general channels. "NOTICE - P0 incident started. {incident-description}. Track on {link to issue}".
- [ ] HANDLE by reverting or forward fixing.
- [x] UPDATE the team on your actions in the created \#alert Slack thread throughout the incident.
- [x] RESOLVE the incident on [PagerDuty](https://monada.pagerduty.com/incidents) (BetterStack resolves automatically).
- [x] UPDATE the team on the issue closure.
- [x] (optional) ANNOUNCE closure of major incidents on Slack \#dev or \#general channels. "NOTICE - P0 incident ended. {incident-resolution-description}. Track on {link to issue}".
- [x] UNPIN the incident issue.
- [ ] LESSONS LEARNED should be shared via the "post-mortem" workflow on \#dev Slack channel.
- [x] CLOSE the incident issue.

**Comment by staycoolcall911** [comment]
The incident is done. Closing.
