### ISSUE TITLE
vscode publisher is still Monada

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#3422]
See https://github.com/winglang/wing/pull/3421/files/9deb83c6e04d86c247b0f25427c8c71c08eab72f#r1262495574

**Comment by garysassano** [comment]
I think this could be closed?

**Comment by ekeren** [comment]
not sure if @MarkMcCulloh committed his changes (he wanted to set Display Name to "Wing Cloud" )

**Comment by MarkMcCulloh** [comment]
The publisher display name has been changed to Wing Cloud https://marketplace.visualstudio.com/items?itemName=Monada.vscode-wing
