### ISSUE TITLE
Update versions of the contribution license, console EULA and the NPM package EULA

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#3475]
### Feature Spec

Versions are updated to the latest one

### Use Cases

We need the updates to better refer to the contribution to the console, also to chane Monada to Wing Cloud everywhere

### Component

Documentation

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
@ShaiBer can we close this one?

**Comment by ShaiBer** [comment]
> @ShaiBer can we close this one?

After we meet with Alon and finish everything for good :)
