### ISSUE TITLE
`bring ex;` is missing in REST API exaple

### ISSUE THREAD

**Issue by haimrait** [winglang/wing#3477]
### I tried this:

`bring ex;` is missing in the published docs in https://www.winglang.io/docs/standard-library/cloud/api
in the rest api example despite of that the simulator does not work properly.

### This happened:

<img width="859" alt="image" src="https://github.com/winglang/wing/assets/21267310/98126ae7-d8c6-4f2f-b2c1-2455ed0288e5">

### I expected this:

<img width="500" alt="image" src="https://github.com/winglang/wing/assets/21267310/00d778a4-7044-40e7-a7dc-6048c1115fa1">

### Component

Documentation

**Comment by staycoolcall911** [comment]
Thanks @haimrait - I fixed it yesterday in `dev` branch, but somehow it didn't get into `main` branch. I'll look into that now

**Comment by staycoolcall911** [comment]
Fixed in #3498
