### ISSUE TITLE
Type casting / unwrapping

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#3506]
### Feature Spec

Optional types are easy to cast / unwrap without having to create a sub scope.  

```js
bring cloud;

let foo = inflight (): str => {
  let var bar: str? = nil;

  if (bar == nil) {
    bar = "hello";
  }

  // this would make typescript happy
  if (bar == nil) {
    throw("bar is nil");
  }
  
  return bar; // how to cast to str natively?

  // the following would work, but is awkward
  // 
  // force casting
  // return "${bar}"
  // 
  // // unwrapping
  // if let baz = bar {    
  //   return baz;
  // } else {
  //   throw("bar is nil");
  // }

};
```

[playground](https://www.winglang.io/play/?code=YgByAGkAbgBnACAAYwBsAG8AdQBkADsACgAKAGwAZQB0ACAAZgBvAG8AIAA9ACAAaQBuAGYAbABpAGcAaAB0ACAAKAApADoAIABzAHQAcgAgAD0APgAgAHsACgAgACAAbABlAHQAIAB2AGEAcgAgAGIAYQByADoAIABzAHQAcgA%2FACAAPQAgAG4AaQBsADsACgAKACAAIABpAGYAIAAoAGIAYQByACAAPQA9ACAAbgBpAGwAKQAgAHsACgAgACAAIAAgAGIAYQByACAAPQAgACIAaABlAGwAbABvACIAOwAKACAAIAB9AAoACgAgACAALwAvACAAdABoAGkAcwAgAHcAbwB1AGwAZAAgAG0AYQBrAGUAIAB0AHkAcABlAHMAYwByAGkAcAB0ACAAaABhAHAAcAB5AAoAIAAgAGkAZgAgACgAYgBhAHIAIAA9AD0AIABuAGkAbAApACAAewAKACAAIAAgACAAdABoAHIAbwB3ACgAIgBiAGEAcgAgAGkAcwAgAG4AaQBsACIAKQA7AAoAIAAgAH0ACgAgACAACgAgACAAcgBlAHQAdQByAG4AIABiAGEAcgA7ACAALwAvACAAaABvAHcAIAB0AG8AIABjAGEAcwB0ACAAdABvACAAcwB0AHIAIABuAGEAdABpAHYAZQBsAHkAPwAKAAoAIAAgAC8ALwAgAHQAaABlACAAZgBvAGwAbABvAHcAaQBuAGcAIAB3AG8AdQBsAGQAIAB3AG8AcgBrACwAIABiAHUAdAAgAGkAcwAgAGEAdwBrAHcAYQByAGQACgAgACAALwAvACAACgAgACAALwAvACAAZgBvAHIAYwBlACAAYwBhAHMAdABpAG4AZwAKACAAIAAvAC8AIAByAGUAdAB1AHIAbgAgACIAJAB7AGIAYQByAH0AIgAKACAAIAAvAC8AIAAKACAAIAAvAC8AIAAvAC8AIAB1AG4AdwByAGEAcABwAGkAbgBnAAoAIAAgAC8ALwAgAGkAZgAgAGwAZQB0ACAAYgBhAHoAIAA9ACAAYgBhAHIAIAB7ACAAIAAgACAACgAgACAALwAvACAAIAAgAHIAZQB0AHUAcgBuACAAYgBhAHoAOwAKACAAIAAvAC8AIAB9ACAAZQBsAHMAZQAgAHsACgAgACAALwAvACAAIAAgAHQAaAByAG8AdwAoACIAYgBhAHIAIABpAHMAIABuAGkAbAAiACkAOwAKACAAIAAvAC8AIAB9AAoACgB9ADsA)

### Use Cases

- simple and straightforward unwrapping of optional values without having to branch out in sub scopes or force casting by interpolating 

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skyrpex** [comment]
Wrong reference 🔝 My bad.

**Comment by eladb** [comment]
The first case can be addressed with `??`:

```js
let foo = inflight (): str => {
  let var bar: str? = nil;
  return bar ?? "hello";
}
```

The second case can be address with [`let/else`](https://github.com/winglang/wing/issues/3860) which is still not implemented.

```js
bring cloud;

let foo = inflight (): str => {
  let var bar: str? = nil;

  let baz = bar else {
    throw("bar is nil");
  };

  return baz;
}
```

@skorfmann doe these address your need?

**Comment by staycoolcall911** [comment]
I'm closing this issue as a duplicate since #3860 should cover it (see Elad's last comment).
