### ISSUE TITLE
Wing console as vs-code extension

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#3514]
### Feature Spec

Having the console integrated in vs-code as an extension, using the integrated output/file-tree, etc.

### Use Cases

TBD

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
see this slack thread: https://winglang.slack.com/archives/C04BBDQUWQP/p1689853000118739
