### ISSUE TITLE
More helpful compiler error message for wrong struct instantiation 

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#3525]
### I tried this:

```
let api = new cloud.Api();

api.post("/hello", inflight (request: cloud.ApiRequest): cloud.ApiResponse => {
  return cloud.ApiResponse( // should be {
    status: 200,
    body: "Hello, Wing",
  );
});
```

[playground](https://www.winglang.io/play/?code=LwAvACAAVABoAGkAcwAgAGkAcwAgAHQAaABlACAAaQBtAHAAbwByAHQAIABzAHQAYQB0AGUAbQBlAG4AdAAgAGkAbgAgAFcAaQBuAGcALgAKAC8ALwAgAEgAZQByAGUAIAB3AGUAIABiAHIAaQBuAGcAIAB0AGgAZQAgAFcAaQBuAGcAIABzAHQAYQBuAGQAYQByAGQAIABsAGkAYgByAGEAcgB5ACAAdABoAGEAdAAgAAoALwAvACAAYwBvAG4AdABhAGkAbgBzACAAYQBiAHMAdAByAGEAYwB0AGkAbwBuAHMAIABvAGYAIABwAG8AcAB1AGwAYQByACAAYwBsAG8AdQBkACAAcwBlAHIAdgBpAGMAZQBzAC4ACgBiAHIAaQBuAGcAIABjAGwAbwB1AGQAOwAKAAoAbABlAHQAIABhAHAAaQAgAD0AIABuAGUAdwAgAGMAbABvAHUAZAAuAEEAcABpACgAKQA7AAoACgBhAHAAaQAuAHAAbwBzAHQAKAAiAC8AaABlAGwAbABvACIALAAgAGkAbgBmAGwAaQBnAGgAdAAgACgAcgBlAHEAdQBlAHMAdAA6ACAAYwBsAG8AdQBkAC4AQQBwAGkAUgBlAHEAdQBlAHMAdAApADoAIABjAGwAbwB1AGQALgBBAHAAaQBSAGUAcwBwAG8AbgBzAGUAIAA9AD4AIAB7AAoAIAAgAHIAZQB0AHUAcgBuACAAYwBsAG8AdQBkAC4AQQBwAGkAUgBlAHMAcABvAG4AcwBlACgAIAAvAC8AIABzAGgAbwB1AGwAZAAgAGIAZQAgAHsACgAgACAAIAAgAHMAdABhAHQAdQBzADoAIAAyADAAMAAsAAoAIAAgACAAIABiAG8AZAB5ADoAIAAiAEgAZQBsAGwAbwAsACAAVwBpAG4AZwAiACwACgAgACAAKQA7AAoAfQApADsA)

### This happened:

```
Expected identifier "cloud" to be a variable, but it's a namespace
```

![Screenshot 2023-07-18 at 22 00 21](https://github.com/winglang/wing/assets/136789/2f17f3ce-aecc-41aa-934b-d6ce9bc8b82c)

### I expected this:

A more helpful error message, which makes it clear what the problem could be and is actionable.

For example, when changing the code to 

```
let api = new cloud.Api();

api.post("/hello", inflight (request: cloud.ApiRequest): cloud.ApiResponse => {
  return new cloud.ApiResponse( 
    status: 200,
    body: "Hello, Wing",
  );
});
```

The error message is actionable 

```
Cannot instantiate type "ApiResponse" because it is a struct and not a class. Use struct instantiation instead.
```
![Screenshot 2023-07-18 at 22 04 07](https://github.com/winglang/wing/assets/136789/60a78374-158a-4289-8645-c9c6b7dfa0c8)

### Component

Compiler

### Wing Version

0.24.31

### Node.js Version

v18.16.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Duplicates #2876
