### ISSUE TITLE
Website: Cloudfront should authorize with Origin Access Identity against the Website Bucket 

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#3538]
### Feature Spec

Now the Website SDK is using Cloudfront [origin access identity](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_origin_access_identity) to authenticate against the S3 bucket which holds the assets for the website. 

Up until now, the website bucket had to be made public for everyone, which is unnecessary in this case and could lead to nagging security warnings in security scanning tools.

### Use Cases

- follow best practices for setting up AWS resources
- Avoid unneccessary `*` principal
- Avoid security warnings from infra security tools (e.g. AWS Config) or even teams

 

### Implementation Notes

Stumbled upon this while troubleshooting https://github.com/winglang/wing/pull/3536 - which is a short term fix for the existing implementation. If we had this one here implemented, the other fix wouldn't be necessary for the Website. It still makes sense for the cases where a user actually want's to have just a public bucket.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by garysassano** [comment]
Any reason to prefer the older OAI vs the [newer OAC](https://aws.amazon.com/blogs/networking-and-content-delivery/amazon-cloudfront-introduces-origin-access-control-oac/) authentiation method?

**Comment by skorfmann** [comment]
> Any reason to prefer the older OAI vs the [newer OAC](https://aws.amazon.com/blogs/networking-and-content-delivery/amazon-cloudfront-introduces-origin-access-control-oac/) authentiation method?

No, not all - thanks for bringing it up 👍
