### ISSUE TITLE
Adding meat to the 'Hello, wing!' app on docs

### ISSUE THREAD

**Issue by Eitansl** [winglang/wing#3541]
### Feature Spec

It seems like the current hello-wing wing [app](https://www.winglang.io/docs/start-here/hello#the-entrypoint-file) lacks some meat. (With others, as discussed on Slack) I was thinking of adding some extra meat.
Firstly, more meat can be added by using a counter (as in the first page of the [docs](https://www.winglang.io/docs#what-is-a-cloud-oriented-language) rather than overwriting the current wing.txt file.
Also, an API resource was mentioned, which will make the app much more robust.

### Use Cases

Winglang's capabilities will be better demonstrated with a more robust app. As well as showing how well different services can be tied together with only a few lines of code.
The user experience is better when a new file is created in the bucket each time a message is pushed, instead of the file being overridden.
Also, after reading the first docs page, it'll be nice to run the first wing code you've ever seen (but can be changed upon other additions to the getting-started app)

### Implementation Notes

Working on a PR, a counter wouldn't take me long time, but API will require me some more work 🙂 

### Component

Documentation

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
Great Idea. 

@Eitansl , what would you like to see with the api gateway?

**Comment by Eitansl** [comment]
> Great Idea.
> 
> @Eitansl , what would you like to see with the api gateway?

I'm not sure, as we probably want to keep the example app simple. 
Maybe accessing interfaces from the bucket/queue? i.e.:

- /get/objects_count - print the number of objects in the bucket (`bucket.list()`)
- get/object/{key} - maybe by using the counter for it - print the object's content (`bucket.get()`)
- delete/object/{key} - - delete an object's (`bucket.delete()`)

or for the queue:
- /post/message - push a message to the queue, will also add a file to the bucket, as defined by the first inflight (`queue.push()`)

WDYT?

**Comment by Eitansl** [comment]
Actually, even just for the counter I think there's more work needed to be done (mainly on the wing console page), so I'll reopen and continue to work on it. 
Amazing to see my changes already on the docsite 😃

**Comment by Eitansl** [comment]
> Actually, even just for the counter I think there's more work needed to be done (mainly on the wing console page), so I'll reopen and continue to work on it. Amazing to see my changes already on the docsite 😃

Added a new PR with the relevant changes

**Comment by Eitansl** [comment]
@hasanaburayyan Any thoughts regarding the API resource? I admit I don't have something specific on my mind besides what I've written above
