### ISSUE TITLE
Failing to download winglang 

### ISSUE THREAD

**Issue by Eitansl** [winglang/wing#3542]
### I tried this:

I've tried to install winglang on various folders using `npm install -g winglang`

### This happened:

I failed to download winglang, npm complains about the compiler package 
```
eitansegel-lion@Eitan-Segel-Lion wing % npm install -g winglang
  npm ERR! code E404
  npm ERR! 404 Not Found - GET https://npm.pkg.github.com/@winglang%2fcompiler - npm package "compiler" does not exist under owner "winglang"
  npm ERR! 404
  npm ERR! 404  '@winglang/compiler@0.24.37' is not in this registry.
  
  eitansegel-lion@Eitan-Segel-Lion wing % npm install @winglang/compiler
  npm ERR! code EUNSUPPORTEDPROTOCOL
  npm ERR! Unsupported URL Type "workspace:": workspace:^
```

### I expected this:

Winglang will be installed fluently 

### Is there a workaround?

Haven't tried with an older version of wing

### Component

CLI

### Wing Version

0.24.37

### Node.js Version

V18.17.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Eitansl** [comment]
> Did you use Wing during the private alpha? If so, we used to host it in github packages and required login. Try this and then installing again:
> 
> ```shell
> npm logout --scope=@winglang
> ```

Indeed, I thought it might be related but wasn't sure. Will try

**Comment by skyrpex** [comment]
Maybe try looking for a `.npmrc` file (in your home or in your project directory).

**Comment by Eitansl** [comment]
> Maybe try looking for a `.npmrc` file (in your home or in your project directory).

Removed its content, downloaded successfully 🙂 Thanks all!

**Comment by staycoolcall911** [comment]
Great to hear, thanks for updating @Eitansl
