### ISSUE TITLE
http module doesn't work in the playground

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#3558]
### I tried this:

Run the test in the [playground](https://www.winglang.io/play/?code=YgByAGkAbgBnACAAYwBsAG8AdQBkADsACgBiAHIAaQBuAGcAIAB1AHQAaQBsADsACgBiAHIAaQBuAGcAIABoAHQAdABwADsACgAKAGwAZQB0ACAAdwBlAGIAcwBpAHQAZQAgAD0AIABuAGUAdwAgAGMAbABvAHUAZAAuAFcAZQBiAHMAaQB0AGUAKAAKACAAIABwAGEAdABoADoAIAAiAC4ALwBzAHQAYQB0AGkAYwAiACwAIAAgAAoAKQA7AAoACgBsAGUAdAAgAGEAcABpACAAPQAgAG4AZQB3ACAAYwBsAG8AdQBkAC4AQQBwAGkAKAApADsACgB3AGUAYgBzAGkAdABlAC4AYQBkAGQASgBzAG8AbgAoACIAYwBvAG4AZgBpAGcALgBqAHMAbwBuACIALAAgAHsAIABhAHAAaQA6ACAAYQBwAGkALgB1AHIAbAAgAH0AKQA7AAoACgBsAGUAdAAgAGMAbwB1AG4AdABlAHIAIAA9ACAAbgBlAHcAIABjAGwAbwB1AGQALgBDAG8AdQBuAHQAZQByACgAKQA7AAoACgBsAGUAdAAgAGMAbwByAHMASABhAG4AZABsAGUAcgAgAD0AIABpAG4AZgBsAGkAZwBoAHQAKAByAGUAcQA6ACAAYwBsAG8AdQBkAC4AQQBwAGkAUgBlAHEAdQBlAHMAdAApADoAIABjAGwAbwB1AGQALgBBAHAAaQBSAGUAcwBwAG8AbgBzAGUAIAA9AD4AIAB7AAoAIAAgAHIAZQB0AHUAcgBuACAAYwBsAG8AdQBkAC4AQQBwAGkAUgBlAHMAcABvAG4AcwBlACAAewAKACAAIAAgACAAaABlAGEAZABlAHIAcwA6ACAAewAKACAAIAAgACAAIAAgACIAQQBjAGMAZQBzAHMALQBDAG8AbgB0AHIAbwBsAC0AQQBsAGwAbwB3AC0ASABlAGEAZABlAHIAcwAiACAAPQA%2BACAAIgAqACIALAAKACAAIAAgACAAIAAgACIAQQBjAGMAZQBzAHMALQBDAG8AbgB0AHIAbwBsAC0AQQBsAGwAbwB3AC0ATwByAGkAZwBpAG4AIgAgAD0APgAgACIAKgAiACwACgAgACAAIAAgACAAIAAiAEEAYwBjAGUAcwBzAC0AQwBvAG4AdAByAG8AbAAtAEEAbABsAG8AdwAtAE0AZQB0AGgAbwBkAHMAIgAgAD0APgAgACAAIgBPAFAAVABJAE8ATgBTACwAUABPAFMAVAAiACwACgAgACAAIAAgAH0ALAAKACAAIAAgACAAcwB0AGEAdAB1AHMAOgAgADIAMAA0AAoAIAAgAH0AOwAKAH0AOwAKAGEAcABpAC4AbwBwAHQAaQBvAG4AcwAoACIALwBoAGUAbABsAG8AIgAsACAAYwBvAHIAcwBIAGEAbgBkAGwAZQByACkAOwAKAGEAcABpAC4AcABvAHMAdAAoACIALwBoAGUAbABsAG8AIgAsACAAaQBuAGYAbABpAGcAaAB0ACAAKAByAGUAcQB1AGUAcwB0ADoAIABjAGwAbwB1AGQALgBBAHAAaQBSAGUAcQB1AGUAcwB0ACkAOgAgAGMAbABvAHUAZAAuAEEAcABpAFIAZQBzAHAAbwBuAHMAZQAgAD0APgAgAHsACgAgACAAcgBlAHQAdQByAG4AIABjAGwAbwB1AGQALgBBAHAAaQBSAGUAcwBwAG8AbgBzAGUAIAB7AAoAIAAgACAAIABzAHQAYQB0AHUAcwA6ACAAMgAwADAALAAKACAAIAAgACAAaABlAGEAZABlAHIAcwA6ACAAewAKACAAIAAgACAAIAAgACIAQwBvAG4AdABlAG4AdAAtAFQAeQBwAGUAIgAgAD0APgAgACIAdABlAHgAdAAvAGgAdABtAGwAIgAsAAoAIAAgACAAIAAgACAAIgBBAGMAYwBlAHMAcwAtAEMAbwBuAHQAcgBvAGwALQBBAGwAbABvAHcALQBPAHIAaQBnAGkAbgAiACAAPQA%2BACAAIgAqACIALAAKACAAIAAgACAAfQAsAAoAIAAgACAAIABiAG8AZAB5ADoAIAAiACAAPABkAGkAdgAgAGkAZAA9AFwAIgBoAGUAbABsAG8AXAAiACAAYwBsAGEAcwBzAD0AXAAiAG0AdAAtADQAXAAiAD4ASABlAGwAbABvACAAJAB7AGMAbwB1AG4AdABlAHIALgBpAG4AYwAoACkAfQA8AC8AZABpAHYAPgAiACwACgAgACAAfQA7AAoAfQApADsACgAKAC8ALwAgAHcAbwByAGsAYQByAG8AdQBuAGQAIABmAG8AcgAgAGgAdAB0AHAAcwA6AC8ALwBnAGkAdABoAHUAYgAuAGMAbwBtAC8AdwBpAG4AZwBsAGEAbgBnAC8AdwBpAG4AZwAvAGkAcwBzAHUAZQBzAC8AMwAyADgAOQAKAC8ALwAgAHQAaABpAHMAIABzAGgAbwB1AGwAZABuACcAdAAgAGIAZQAgAG4AZQBjAGUAcwBzAGEAcgB5ACwAIABzAGkAbgBjAGUAIABhAHAAaQAuAHUAcgBsACAAcwBoAG8AdQBsAGQACgAvAC8AIABiAGUAIABkAGkAcgBlAGMAdABsAHkAIABhAGMAYwBlAHMAcwBpAGIAbABlACAAIABpAG4AIAB0AGgAZQAgAHQAZQBzAHQACgBsAGUAdAAgAGEAcABpAFUAcgBsACAAPQAgAGEAcABpAC4AdQByAGwAOwAKAAoALwAvACAASABvAHcAZQB2AGUAcgAsACAAdwBoAGkAbABlACAAdABoAGkAcwAgAHcAbwByAGsAZQBkACAAZgBvAHIAIABBAFAASQAsACAAaQB0ACAAZABvAGUAcwBuACcAdAAgAHcAbwByAGsAIABmAG8AcgAKAC8ALwAgAHQAaABlACAAdwBlAGIAcwBpAHQAZQAuAHUAcgBsACAAcAByAG8AcABlAHIAdAB5ACAAOgAvAAoAbABlAHQAIAB3AGUAYgBzAGkAdABlAFUAcgBsACAAPQAgAHcAZQBiAHMAaQB0AGUALgB1AHIAbAA7AAoACgBsAGUAdAAgAGkAbgB2AG8AawBlAEEAbgBkAEEAcwBzAGUAcgB0ACAAPQAgAGkAbgBmAGwAaQBnAGgAdAAoAHIAZQBzAHAAbwBuAHMAZQA6ACAAaAB0AHQAcAAuAFIAZQBzAHAAbwBuAHMAZQAsACAAZQB4AHAAZQBjAHQAZQBkADoAIABzAHQAcgApACAAPQA%2BACAAewAKACAAIABsAG8AZwAoACIAcgBlAHMAcABvAG4AcwBlADoAIAAkAHsAcgBlAHMAcABvAG4AcwBlAC4AcwB0AGEAdAB1AHMAfQAgACIAKQA7AAoAIAAgAGEAcwBzAGUAcgB0ACgAcgBlAHMAcABvAG4AcwBlAC4AcwB0AGEAdAB1AHMAIAA9AD0AIAAyADAAMAApADsACgAgACAAYQBzAHMAZQByAHQAKAByAGUAcwBwAG8AbgBzAGUALgBiAG8AZAB5AD8ALgBjAG8AbgB0AGEAaQBuAHMAKABlAHgAcABlAGMAdABlAGQAKQAgAD0APQAgAHQAcgB1AGUAKQA7AAoAfQA7AAoACgAvAC8AIABEAG8AZQBzAG4AJwB0ACAAdwBvAHIAawAgAHIAaQBnAGgAdAAgAG4AbwB3AAoALwAvACAAdABlAHMAdAAgACIAcgBlAG4AZABlAHIAcwAgAHQAaABlACAAaQBuAGQAZQB4ACAAcABhAGcAZQAiACAAewAKAC8ALwAgACAAIABpAG4AdgBvAGsAZQBBAG4AZABBAHMAcwBlAHIAdAAoAGgAdAB0AHAALgBnAGUAdAAoAHcAZQBiAHMAaQB0AGUAVQByAGwAKQAsACAAIgBIAGUAbABsAG8ALAAgAFcAaQBuAGcAIgApADsACgAvAC8AIAB9AAoACgB0AGUAcwB0ACAAIgBhAHAAaQAgAHIAZQB0AHUAcgBuAHMAIAB0AGgAZQAgAGMAbwByAHIAZQBjAHQAIAByAGUAcwBwAG8AbgBzAGUAIgAgAHsACgAgACAAaQBuAHYAbwBrAGUAQQBuAGQAQQBzAHMAZQByAHQAKABoAHQAdABwAC4AcABvAHMAdAAoACIAJAB7AGEAcABpAFUAcgBsAH0ALwBoAGUAbABsAG8AIgApACwAIAAiAEgAZQBsAGwAbwAgADAAIgApADsACgB9AAoA)

### This happened:

![Screenshot 2023-07-21 at 10 57 35](https://github.com/winglang/wing/assets/136789/46abe7c9-9658-4e90-b5c7-40499ac6b5a1)

```
Unknown error: fetch is not a function
Test "api returns the correct response" failed (1524ms)
```

### I expected this:

It works

### Component

Playground

### Wing Version

0.24.38

### Node.js Version

18

### Platform(s)

Other

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
@ainvoner  - here is another motivation to move to fly.io

**Comment by ekeren** [comment]
@skorfmann  - you can try this in Safari and it will work

**Comment by ekeren** [comment]
Following the discussion with @ainvoner we are probably going to move all the traffic to fly.io and see how conversions are working. Lets wait on taking any action on this issue till we decide

**Comment by ekeren** [comment]
Playground is working with fly.io, which means that the solution is working. 


[playground](https://www.winglang.io/play/?code=YgByAGkAbgBnACAAYwBsAG8AdQBkADsACgBiAHIAaQBuAGcAIABoAHQAdABwADsACgAKAAoAbABlAHQAIABhAHAAaQAgAD0AIABuAGUAdwAgAGMAbABvAHUAZAAuAEEAcABpACgAKQA7AAoAYQBwAGkALgBnAGUAdAAoACIALwAiACwAIABpAG4AZgBsAGkAZwBoAHQAIAAoAHIAZQBxADoAIABjAGwAbwB1AGQALgBBAHAAaQBSAGUAcQB1AGUAcwB0ACkAOgAgAGMAbABvAHUAZAAuAEEAcABpAFIAZQBzAHAAbwBuAHMAZQAgAD0APgAgAHsACgAgACAAcgBlAHQAdQByAG4AIABjAGwAbwB1AGQALgBBAHAAaQBSAGUAcwBwAG8AbgBzAGUAIAB7ACAAcwB0AGEAdAB1AHMAOgAgADIAMAAwACAALAAgAGIAbwBkAHkAOgAgACIASABlAGwAbABvACIAIAB9ADsACgAKAH0AKQA7AAoACgBsAGUAdAAgAHUAcgBsACAAPQAgAGEAcABpAC4AdQByAGwAOwAKAAoAdABlAHMAdAAgACIAbQBhAGkAbgAiACAAewAKACAAIABsAGUAdAAgAHIAZQBzACAAPQAgAGgAdAB0AHAALgBnAGUAdAAoACIAJAB7AHUAcgBsAH0ALwAiACkAOwAgAAoAIAAgAGEAcwBzAGUAcgB0ACAAKAByAGUAcwAuAGIAbwBkAHkAIAAgAD0APQAgACIASABlAGwAbABvACIAKQA7AAoAfQAKAA%3D%3D)
