### ISSUE TITLE
`wing it` not reacting to `kill` command

### ISSUE THREAD

**Issue by olivernybroe** [winglang/wing#3559]
### I tried this:

Run kill command on PID from `wing it`

### This happened:

Nothing

### I expected this:

The process to execute

### Is there a workaround?

ctrl+c in the window or force quit

### Component

Wing Console, CLI

### Wing Version

0.24.37

### Node.js Version

v18.17.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

from @ekeren:

### Reproduce

1.

```ts 
bring cloud;

new cloud.Function(inflight (m: str) => {
  while true {
  }
});

```

2. 

```sh
wing it
```

3. 

from console invoke the function 

Try running `Ctrl-C` which sends a SIGINT signal 

### workaround 

If in a unix/linux shell  you can `Ctrl-Z` which puts the process in the background and then `kill -9 <pid>` or if this is your only process in the background `kill -9 %1`

**Comment by eladb** [comment]
I am not sure it's related, but anecdotally after working quite a lot with the Wing Console inside the VSCode extension, I see lots of `wing` processes running.

**Comment by olivernybroe** [comment]
@eladb sounds pretty related. At least for the IntelliJ work I am doing, it sends a kill command to all subprocess when exiting.

I am guessing vscode does the same

**Comment by skyrpex** [comment]
I can't reproduce the problem. My steps:

```sh
wing it index.w
```

On a different terminal:

```sh
ps
# Find 29856 ttys037    0:01.31 node /.../Library/pnpm/global/5/node_modules/winglang/bin/wing it /...
kill 29856
```

The process was correctly stopped and killed ```[1]    29856 terminated  wing it```


Am I missing something? Using `0.24.46`.

**Comment by ekeren** [comment]
I've notice it also - basically it doesn't react to Ctrl-C, which is super annoying 

It happens when you are running a 100% CPU (no io) loops

Adding how to reproduce to the description

**Comment by olivernybroe** [comment]
Alright so I just tested on my mac and `kill` works when starting wing via `wing it` command and killing the `node` process. 
![image](https://github.com/winglang/wing/assets/5870441/6e676182-df7f-4f74-8a35-8d51fbfdea78)

However when running `npx wing it`, it starts a new process for node. 
![image](https://github.com/winglang/wing/assets/5870441/5ff312b9-3a8e-48bf-861d-e111526e2185)
The PID after running my command is the `npx wing it` PID, but sending `kill` command to that one, will not actually end up killing the `node` process. 

Force killing that actually ends up leaving a hidden `wing it` process around. 
![image](https://github.com/winglang/wing/assets/5870441/8e77f395-cad7-4046-8b12-3f6ae52df927)

**Comment by MarkMcCulloh** [comment]
> Force killing that actually ends up leaving a hidden wing it process around.

This is an issue with npx rather than wing it seems, I can replicate the same behavior for npx nodemon as well.

> I am not sure it's related, but anecdotally after working quite a lot with the Wing Console inside the VSCode extension, I see lots of wing processes running.

This should have been addressed in https://github.com/winglang/wing/pull/4124

@olivernybroe That PR also improved handling for SIGINT and SIGTERM in the wing cli which may have addressed the original reason you created this issue.
Additionally, I added [this change](https://github.com/winglang/wing/pull/4124/files#diff-44a6c883669ff29807c4596b689c0a11642bd15e50c515e4f65ee27996321029R84-R100) to the vscode extension in that PR to make sure vscode cleans up the entire process tree. May or may not be useful in the IntelliJ plugin.

**Comment by olivernybroe** [comment]
@MarkMcCulloh thanks for sharing :) I do have something like that which will soft kill first and then force quit if timeout from soft kill

**Comment by MarkMcCulloh** [comment]
@olivernybroe Is your original issue still present? Now that SIGTERM/SIGINT are handled better I'm hoping things should work more as expected. And force killing will definitely leave resources behind, but that's expected with force killing.
