### ISSUE TITLE
Example: Stock polling example

### ISSUE THREAD

**Issue by moralesl** [winglang/wing#3563]
### Feature Spec

This is a Wing example for a stock polling application, that stores the latest stock price in DynamoDB and publishes the update to an SQS queue.

### Use Cases

I recently took some time to explore more of Wing capabilities and came across the issue https://github.com/winglang/wing/issues/360. I started implementing it for Twitter, but based on the recent API pricing changes, you [can't poll or search for tweets in the free API tier](https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#item0) anymore.

As I liked the example of interacting with an external API to showcase the capabilites of Wing, I decided to rather go for an stock update poller that retrieves the API key from secrets manager, fetches the freely available [twelve data Time Series API](https://twelvedata.com/docs#time-series), stores the latest price in DynamoDB and send all stock updates to an SQS queue.

### Implementation Notes

Implementation is based on this sequence diagramm

![Winglang AWS Stock Update Sequence Diagramm](https://github.com/winglang/wing/assets/17140951/3cdff9d5-dc89-4684-afcc-83d5247ac9ed)

### Component

Tutorial, Other

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by revitalbarletz** [comment]
@moralesl I want to share this example in our slack and probably introduce it in one of our community meetings, do you mind joining our slack channel so that we can proceed the discussion there? https://winglang.slack.com/join/shared_invite/zt-1mw74uvra-fHXIKNQ9BorWuIMRG7oQDw

**Comment by staycoolcall911** [comment]
This is absolutely great @moralesl! I'm wondering - with your current knowledge of wing - is there any part of the implementation that seems more complex or is it all quite straight forward?

**Comment by moralesl** [comment]
Will close this issue, as it was implemented as part of https://github.com/winglang/examples/pull/12.
