### ISSUE TITLE
Broken HyperLink in the Docs section of the website.

### ISSUE THREAD

**Issue by harsh9607** [winglang/wing#3589]
// **wing version:** 0.24.44 

Hi there. Just noticed that the **Website's Documentation section has a broken Link**. A 404 error is generated when you click on - inflight and preflight code. 

**BROKEN LINK** 
------------------------
https://www.winglang.io/concepts/inflights

Please Fix this.
 
**LINK TO DOCS**
--------------------------------------
https://www.winglang.io/docs

Scroll to the bottom and you will  find preflight and inflight code  hyperlinked.

**Comment by ekeren** [comment]
merged
