### ISSUE TITLE
[ Wing console issue ] The Block diagram inside the simulator doesnot resize back when...

### ISSUE THREAD

**Issue by harsh9607** [winglang/wing#3591]
### I tried this:

Ran hello.w    
So in the Wing console at the center of the screen we have a **block diagram**.
Wing Console was running on Firefox. 

### This happened:

When you click on the resize button ( square box next to the close button on top right ) the Wing console resizes to half which is fine. BUT  when I click on resize button again to maximize the screen. The rest of the window resizes but the the **block diagram** inside the simulator **remains** **shrunken**.  [screenshots attached]

### I expected this:

I expected that the Block diagram would also resize itself automatically when the entire browser sceen was made Fullscreen.
**This may spoil** **the UI/UX as they would have to click on zoom to fit everytime this happens** . 
 Shouldnt it maximize automatically as well ? 

### Is there a workaround?

If some way we could trigger zoom to fit button automatically whenever we resize the screen then the problem will be solved ! 

### Component

Wing Console

### Wing Version

0.24.44

### Node.js Version

v18.16.0

### Platform(s)

Windows

### Anything else?

![1a](https://github.com/winglang/wing/assets/29411800/f8bfe05f-891f-40d4-87b6-027e2d868092)
![2a](https://github.com/winglang/wing/assets/29411800/f5285980-e01f-491f-9b89-18342e988729)
![3a](https://github.com/winglang/wing/assets/29411800/64bebb49-1733-413f-aeda-8b7ef86a81c2)

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
I think that the zoom-to-screen button should be a stateful button that has on/off. 

The button should automatically be turned off when the use zoom in/out or scroll on the screen

**Comment by harsh9607** [comment]
Also if you look at the second image in the screenshots. [ resized once.] .. We can observe that the **center pane** that contains the block diagram is **resized the most**. The **left** (explorer) and the **right** (Node info) panes and the **bottom** pane(that contains logs) remain more or less of the **same size**. It looks almost as if they **sandwich** the center simulator screen on resizing. Probably we should also try to resize everything in proportion.

**Comment by skyrpex** [comment]
The solution I thought for this problem is the following:

- Use the [Resize Observer API](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) to track whenever the Map Pane changes size
- When it does resize, zoom in/out accordingly using best effort to keep the same nodes visible, same aspect ratio, etc

I bet it's not too complicated math-wise but not trivial either.

**Comment by ainvoner** [comment]
cant reproduce
