### ISSUE TITLE
Refactor the Console to Panels and allow configuring it

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#3596]
- Redesign the UI to use tabbed panels. Will make it easier to read, and modular
![image](https://github.com/winglang/wing/assets/1077520/f34f3530-671c-4d5b-80d6-6e86088c4667)

- Use [react-resizable-panels](https://github.com/bvaughn/react-resizable-panels) to implement the resizing. It will simplify our codebase

- Allow passing a configuration to specify the layout. Something like:
```ts
/**
 * @see https://github.com/bvaughn/react-resizable-panels/blob/a87cdb65282b4f12550aca1b0f20bfdcfe6786fa/packages/react-resizable-panels/README.md#panel
 */
interface Panel<PanelIds extends string[]> {
    id: PanelIds;
    minSize?: number;
    maxSize?: number;
    defaultSize?: number;
    order?: number;
}

/**
 * @see https://github.com/bvaughn/react-resizable-panels/blob/a87cdb65282b4f12550aca1b0f20bfdcfe6786fa/packages/react-resizable-panels/README.md#panelgroup
 */
interface PanelGroup<PanelIds extends string[]> {
    autoSaveId?: string;
    direction: 'horizontal' | 'vertical';
    items: Array<PanelGroup<PanelIds> | Panel<PanelIds>>;
}


// Our code:
type PanelId = "hierarchy" | "explorer" | "traces" | "inspector" | "logs" | "project";
interface MyOptions {
    layout: PanelGroup<PanelId>;
}
```

- Provide a storage medium (react-resizable-panels supports it) to save the layout sizes and settings

**Comment by skyrpex** [comment]
BTW I'd like to rename our components to the names that appear above:

- Hierarchy: the tree of nodes (aka tree view)
- Explorer: the visual representation of the nodes (aka map view)
- Inspector: the list of properties of the node (aka metadata panel)

**Comment by ainvoner** [comment]
@skyrpex if still relevant, please reopen.
