### ISSUE TITLE
Hide the Root node references from the Console

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#3611]
The Root node is a container construct that holds all of the application resources. It doesn't hold any useful properties or serve any other purpose. It doesn't exist in user code either.

The proposal is to remove any reference to the Root node from the Console Tree View and the Map View so there's less visual clutter and there's no references to ghost resources.

The Map View should still display a background that holds all nodes, like:

<img width="393" alt="image" src="https://github.com/winglang/wing/assets/1077520/ff524a05-d669-4939-a94a-00926478275d">

**Comment by ainvoner** [comment]
done
