### ISSUE TITLE
Add Vercel Deployment Environments for the Console

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#3614]
We could add some Vercel Deployment Environments to our Pull Requests so we can preview our changes to the Console.

The following Console packages that are eligible:

- `@wingconsole/app`: Using a webcontainer and maybe a Monaco editor, we can run the Console live
- `@wingconsole/ui`: We can deploy the Storybook that shows the UI components and the Design System

Food for thought: we could have environments for the docs, the cli (using a webcontainer and a terminal interface), the tree sitter playground...

**Comment by skyrpex** [comment]
BTW, if we merge the [Refactor to Turbo PR](https://github.com/winglang/wing/pull/3447), the Vercel Deployments will become faster since the build assets will benefit from the cache.

**Comment by MarkMcCulloh** [comment]
If we can bring the docs and playground into this repo, I love love love the idea of PRs basically have preview URL(s) for the entire toolchain (i.e. new compiler features can be tested in the browser)
