### ISSUE TITLE
Improve our learn site success rate by not using WebContainers

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#3629]
### Feature Spec

We observed a significant difference in the number of users progressing from our initial tutorial page to the second one, depending on the website backend technology we used.
Specifically, we noticed a drop in users who landed on a site using web containers, with many of them not waiting for the page to fully load. 
See the image below, which illustrates the significant decline at the initial step of the tutorial.
![Screenshot 2023-07-27 at 10 48 34](https://github.com/winglang/wing/assets/2538825/c8bf2a15-14c8-40bc-82c2-025ed13ae0d7)

Our assumption is that migrating all browsers to use fly.io as a backend solution, will improve the conversion rate, which will lead to more users completing our tutorial.

### Use Cases

improve learn site conversion rate which will lead to more users completing our tutorials

### Implementation Notes

use fly.io for all browsers

### Component

Playground

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ShaiBer** [comment]
I'm in favor of doing it

**Comment by ekeren** [comment]
👍
