### ISSUE TITLE
compile the same code twice generates different archive.zip files

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#3647]
### I tried this:

I recompiled the same codebase twice and got a diff in the main.tf.json file

```ts
bring cloud;
bring util;


let b = new cloud.Bucket();
b.onCreate(inflight (name: str) => {
  log("file was created with name ${name}");
});

let  f = new cloud.Function(inflight (m: str) => {
  b.put("file.txt", m);
});

```

### This happened:

The `assets/cloudFunction_Asset_*/*.zip` files are different

See this diff output comparing  `index.js` file from multiple compilations
```sh  
<   "target/simple.tfaws.300228.tmp/.wing/inflight.$Closure2.js"(exports2, module2) {
---
>   "target/simple.tfaws.342499.tmp/.wing/inflight.$Closure2.js"(exports2, module2) {
```

### I expected this:

Although this issue doesn't create a correctness issue. It does create a lot of clatter in a single `terraform plan` command output after doing some minimal change 

### Component

Compiler

### Wing Version

0.24.55

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skyrpex** [comment]
Looks like the cause is the temporary path used to build the javascript assets:

![image](https://github.com/winglang/wing/assets/1077520/ed590e56-5b9b-4fce-9130-c549a8e28d99)

**Comment by skyrpex** [comment]
Maybe this `target/main.*.*.tmp/` path can be removed from all generated code?

**Comment by skorfmann** [comment]
To add some colour to this:

![Screenshot 2023-11-07 at 11 15 47](https://github.com/winglang/wing/assets/136789/cd5c4bd9-7a88-4e6c-85a6-1e6ee43a5f96)

Out of ~ 700 lines there are actually 10 relevant ones in a relatively small wing application with a static website and a few api handlers

**Comment by skorfmann** [comment]
Yes, much better! 🎉
