### ISSUE TITLE
adding how to install and complete pre-requirements for `tf-azure`, `tf-gcp` and `awscdk`

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#3649]
### Feature Spec

I was trying to check if I broke something in the `awscdk` during development to `tf-aws` and I couldn't find anywhere how to run it for the first time, at the end I could find some information in Marcio's PR: https://github.com/winglang/wing/pull/1576
I really think we should put it on the docs somewhere (the same apply to the other targets).

### Use Cases

Start working with Wing, deploying to different targets 

### Implementation Notes

We should check if we should move the tf-aws tutorial to be next to the rest

### Component

Documentation

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
This is done:
https://www.winglang.io/docs/tools/cli#awscdk-platform
