### ISSUE TITLE
ENOENT: no such file or directory, stat '/initrd.img'

### ISSUE THREAD

**Issue by giovanni-orciuolo** [winglang/wing#3665]
### I tried this:

I'm trying to build the project on my machine. Below are my OS details:

OS: Ubuntu 20.04.6 LTS x86_64 
Kernel: 5.4.0-155-generic
CPU: Intel i5-4460 (4) @ 3.400GHz 
GPU: Intel HD Graphics

Node version: 19.0.0
pnpm version: 8.6.11

The command I run is `pnpm build`, but the error happens when I run any test command (for example `pnpm nx wing -- test ../../examples/tests/valid/captures.w`)

### This happened:

Many tests do not pass due to this error:

`ENOENT: no such file or directory, stat '/initrd.img'`

So the build fails.

### I expected this:

I expected all the tests to pass and the build to work.

### Is there a workaround?

Not to my knowledge

### Component

Development Environment

### Node.js Version

19.0.0

### Platform(s)

Linux

### Anything else?

Full logs of the `pnpm nx wing -- test ../../examples/tests/valid/captures.w` command:

<details>
<summary>Logs</summary>

```
pnpm nx wing -- test ../../examples/tests/valid/captures.w


   ✔    10/10 dependent project tasks succeeded [10 read from cache]

   Hint: you can run the command with --verbose to see the full dependent project outputs

 ——————————————————————————————————————————————————————————————————————————————


> nx run winglang:build  [existing outputs match the cache, left as is]


> winglang@0.0.0 build /home/giovanni/Projects/wing/apps/wing
> tsc && pnpm copy-root-readme


> winglang@0.0.0 copy-root-readme /home/giovanni/Projects/wing/apps/wing
> cp ../../README.md ./README.md && pnpm copy-root-assets


> winglang@0.0.0 copy-root-assets /home/giovanni/Projects/wing/apps/wing
> cp ../../logo/demo.gif ./logo/demo.gif


> nx run winglang:wing test ../../examples/tests/valid/captures.w

ENOENT: no such file or directory, stat '/initrd.img'
 
 
Tests 1 failed (1)
Test Files 1 failed (1)
Duration 0m0.01s
Warning: run-commands command "./bin/wing test ../../examples/tests/valid/captures.w" exited with non-zero status code

 ——————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target wing for project winglang and 11 task(s) they depend on (701ms)
 
         With additional flags:
           test ../../examples/tests/valid/captures.w
 
    ✖    1/12 failed
    ✔    11/12 succeeded [11 read from cache]
```

</details>

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by giovanni-orciuolo** [comment]
Turns out I had some broken links I had to remove in order to make it work.

If you are in the same situation as me, check if you have broken links by running `ls -la /initrd.img /initrd.img.old /vmlinuz /vmlinuz.old` and checking if it links to actual file. If it doesn't, remove the link.

**Comment by ekeren** [comment]
Credit to https://github.com/marmelab/react-admin/issues/5417#issuecomment-716099254
