### ISSUE TITLE
Playground: Handle Backend Shutdown Gracefully

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#3668]
### I tried this:

Open a [playground](https://www.winglang.io/play/?code=LwAvACAAVABoAGkAcwAgAGkAcwAgAHQAaABlACAAaQBtAHAAbwByAHQAIABzAHQAYQB0AGUAbQBlAG4AdAAgAGkAbgAgAFcAaQBuAGcALgAKAC8ALwAgAEgAZQByAGUAIAB3AGUAIABiAHIAaQBuAGcAIAB0AGgAZQAgAFcAaQBuAGcAIABzAHQAYQBuAGQAYQByAGQAIABsAGkAYgByAGEAcgB5ACAAdABoAGEAdAAgAAoALwAvACAAYwBvAG4AdABhAGkAbgBzACAAYQBiAHMAdAByAGEAYwB0AGkAbwBuAHMAIABvAGYAIABwAG8AcAB1AGwAYQByACAAYwBsAG8AdQBkACAAcwBlAHIAdgBpAGMAZQBzAC4ACgBiAHIAaQBuAGcAIABjAGwAbwB1AGQAOwAKAAoALwAvACAAVABoAGkAcwAgAGMAbwBkAGUAIABkAGUAZgBpAG4AZQBzACAAYQAgAGIAdQBjAGsAZQB0ACAAYQBzACAAcABhAHIAdAAgAG8AZgAgAHkAbwB1AHIAIABhAHAAcAAuAAoALwAvACAAVwBoAGUAbgAgAGMAbwBtAHAAaQBsAGkAbgBnACAAdABvACAAYQAgAHMAcABlAGMAaQBmAGkAYwAgAGMAbABvAHUAZAAgAHAAcgBvAHYAaQBkAGUAcgAKAC8ALwAgAGkAdAAgAHcAaQBsAGwAIABiAGUAIABzAHUAYgBzAHQAaQB0AHUAdABlAGQAIABiAHkAIABhAG4AIABpAG0AcABsAGUAbQBlAG4AdABhAHQAaQBvAG4AIABmAG8AcgAKAC8ALwAgAHQAaABhAHQAIABjAGwAbwB1AGQALgAgAEkALgBlACwAIABmAG8AcgAgAEEAVwBTACAAaQB0ACAAdwBpAGwAbAAgAGIAZQAgAGEAbgAgAFMAMwAgAEIAdQBjAGsAZQB0AC4ACgBsAGUAdAAgAGIAdQBjAGsAZQB0ACAAPQAgAG4AZQB3ACAAYwBsAG8AdQBkAC4AQgB1AGMAawBlAHQAKAApADsACgBsAGUAdAAgAGIAdQBjAGsAZQB0ADEAIAA9ACAAbgBlAHcAIABjAGwAbwB1AGQALgBCAHUAYwBrAGUAdAAoACkAIABhAHMAIAAiAGYAbwBvACIAOwAKAAoALwAvACAAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhAAoALwAvACAAWQBvAHUAIABjAGEAbgAgAGkAbgB0AGUAcgBhAGMAdAAgAHcAaQB0AGgAIAB0AGgAZQAgAGEAcABwACAAaQBuACAAdABoAGUAIABjAG8AbgBzAG8AbABlACAALQAtAD4ACgAvAC8AIAAKAC8ALwAgAEMAbABpAGMAawAgAG8AbgAgAHQAaABlACAARgB1AG4AYwB0AGkAbwBuACwAIABhAG4AZAAgAHQAaABlAG4AIABpAG4AdgBvAGsAZQAgAGkAdAAgAGkAbgAgAHQAaABlAAoALwAvACAAbABvAHcAZQByACAAcgBpAGcAaAB0ACAAcABhAG4AZQBsACwAIABvAHIAIABjAGwAaQBjAGsAIABvAG4AIAB0AGgAZQAgAEIAdQBjAGsAZQB0AAoALwAvACAAdABvACAAcwBlAGUAIABpAHQAcwAgAGMAbwBuAHQAZQBuAHQAcwAgAGkAbgAgAHQAaABlACAAcABhAG4AZQBsACwAIABlAHQAYwAuAAoALwAvACAAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhAAoACgAvAC8AIABgAGkAbgBmAGwAaQBnAGgAdABzAGAAIAByAGUAcAByAGUAcwBlAG4AdAAgAGMAbwBkAGUAIAB0AGgAYQB0ACAAcgB1AG4AcwAgAGwAYQB0AGUAcgAsACAAbwBuAAoALwAvACAAbwB0AGgAZQByACAAbQBhAGMAaABpAG4AZQBzACwAIABpAG4AdABlAHIAYQBjAHQAaQBuAGcAIAB3AGkAdABoACAAYwBhAHAAdAB1AHIAZQBkACAAZABhAHQAYQAgAGEAbgBkAAoALwAvACAAcgBlAHMAbwB1AHIAYwBlAHMAIABmAHIAbwBtACAAdABoAGUAIABwAHIAZQAtAGYAbABpAGcAaAB0ACAAcABoAGEAcwBlAC4ACgBsAGUAdAAgAGgAZQBsAGwAbwBfAHcAbwByAGwAZAAgAD0AIABpAG4AZgBsAGkAZwBoAHQAIAAoACkAIAA9AD4AIAB7AAoAIAAgAGIAdQBjAGsAZQB0AC4AcAB1AHQAKAAiAGgAZQBsAGwAbwAuAHQAeAB0ACIALAAgACIASABlAGwAbABvACwAIABXAG8AcgBsAGQAIQAiACkAOwAKAH0AOwAKAAoALwAvACAASQBuAGYAbABpAGcAaAB0AHMAIABjAGEAbgAgAGIAZQAgAGQAZQBwAGwAbwB5AGUAZAAgAGEAcwAgAHMAZQByAHYAZQByAGwAZQBzAHMAIABmAHUAbgBjAHQAaQBvAG4AcwAKAG4AZQB3ACAAYwBsAG8AdQBkAC4ARgB1AG4AYwB0AGkAbwBuACgAaABlAGwAbABvAF8AdwBvAHIAbABkACkAOwAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAKAC8ALwAgAJEhIABTAHcAaQB0AGMAaAAgAGYAaQBsAGUAcwAgAGEAbgBkACAAcwBlAGUAIABvAHQAaABlAHIAIABlAHgAYQBtAHAAbABlAHMAIAB3AGkAdABoACAAbQBvAHIAZQAKAC8ALwAgAGUAeABwAGwAZQBuAGEAdABpAG8AbgBzACAAYQBiAG8AdgBlAC4A) and let the opened page idle for a while. Don't really know how long, but probably something like 30 - 60 minutes (?).

### This happened:

![Screenshot 2023-08-01 at 13 19 56](https://github.com/winglang/wing/assets/136789/382b0887-2074-4107-8f7c-cbf1c51e65f0)

### I expected this:

In the best case a user wouldn't notice a backend that's offline at all, it'd just be auto-started whenever needed. In any case, the UI feedback shouldn't make the impression that some unexpected error happened.

### Is there a workaround?

Just reload the page

### Component

Playground

### Wing Version

not relevant

### Node.js Version

not relevant

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by amielpb** [comment]
@ainvoner  we took care of this, no?

**Comment by ainvoner** [comment]
This is how we handled it at a time. I don't think we want to add additional logic here. At least not now.
we can leave the issue open and address it in the future
![Screenshot 2024-01-02 at 10 21 50](https://github.com/winglang/wing/assets/2538825/a3a890ac-63e6-48e7-adb5-8b0f455be70e)
