### ISSUE TITLE
resource is hidden if it is called "test"

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#3670]
### I tried this:

```
bring cloud;

let bucket = new cloud.Bucket() as "test";
```

### This happened:

<img width="1182" alt="image" src="https://github.com/winglang/wing/assets/5547636/9468ea87-4fc9-49c7-8131-9e34143698f5">

### I expected this:

<img width="1228" alt="image" src="https://github.com/winglang/wing/assets/5547636/73b7a9c6-9de4-4523-82c1-34afc25eefad">

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
fixed
