### ISSUE TITLE
Wing Cloud Preview Environment

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#3679]
The Wing Cloud Preview Environments will allow developers to preview their Wing applications using GitHub Pull Requests. 

A GitHub App will be necessary. Once installed on a repository, the GitHub App will be able to create a preview environment for each Pull Request. The preview environment will be accessible via a unique URL. The preview environment will be deleted once the Pull Request is closed.

## Features

- Add a comment to PRs with information about the Preview Environment (build status, preview URL, etc)
- The Preview URL will open the Console App
- Delete the Preview Environment automatically when the PR is closed
- Delete the Preview Environment automatically if it becomes stale and unused

## Architecture

The Wing Cloud Preview Environment will be built using the following technologies:

- https://www.winglang.io
- https://github.com/probot/probot for the GitHub App
- https://fly.io for the preview environment hosting

## Implementation

- Create a Wing Cloud Preview Environment GitHub App
- Create a Wing application with:
    - A Cloud.Function to process the GitHub App webhook
    - A Cloud.Api that exposes the GitHub App webhook
    - A Cloud.Table to store the preview environment state
    - A Cloud.Scheduler to manage stale machines

In order to manage the flyio machines, we will need to:
- Create flyio for cdktf (so we can use it in wing)
    - There's a terraform module for flyio we can use
- Create a wing interface for flyio, similar to the following:
    ```ts
    struct FlyioMachine {}
    struct FlyioOptions {}
    interface Flyio {
        init(options: FlyioOptions): void;
        inflight createMachine(): FlyioMachine;
        inflight deleteMachine(machineId: str): void;
    }
    ```

Some resources may not be necessary, such as the table. The flyio interface for Wing may also be different. @eladcon has a better understanding of these parts.

**Comment by ainvoner** [comment]
some addition that I think worth mentioning (still not 100% sure all my assumptions are correct):

**GitHub application**
1. Authentication is being done by GitHub
2. GitHub application backend will manage all machines lifecycle and authentication for all repositories
3. Github application backend will create and update the PR comment with the preview environment details
4. Github application backend won’t have any state, which means that it can be a simple `cloud.Function`. GH PR holds the relation between the `PR/branch` name and the `vm` url, while `fly.io` has the connection between the `url` and the actual `vm` instance.
5. Add analytics and datadog

**VMs management**
1. `fly.io` will manage all preview environment machines contain a predefined image (see below).
2. `redeploy` action will redeploy the whole machine and won't restart the console server only.
3. create/destroy vms as described in the PR description

**VM image**

the image should:
1. clone a git repo
6. install npm deps
7. run wing console
8. run docker?
9. export logs
10. expose server for health check and state updates

**Important note**
Beside building a new product, our goal is also to use **wing** and enrich the language where needed.

**Open questions**
1. What would be the best way to add a `fly.io` library to wing? following `redis` lib pattern in `wing`, should we add `ex/vm-manager.ts` and a `target-tf-fly.io`? @Chriscbr we would love your input here

**Comment by skyrpex** [comment]
> **Open questions**
> 
> 1. What would be the best way to add a `fly.io` library to wing? following `redis` lib pattern in `wing`, should we add `ex/vm-manager.ts` and a `target-tf-fly.io`? @Chriscbr we would love your input here

I think we can do it in userland if we just had the flyio for cdktf, but I'm not sure.

**Comment by ainvoner** [comment]
@skyrpex try to describe the way users will use this external library published in userland.
for example, how to compile it? `wing compile -t ????`

**Comment by skyrpex** [comment]
> @skyrpex try to describe the way users will use this external library published in userland.
> for example, how to compile it? `wing compile -t ????`

I didn't think of any users compiling it, just us. But to answer your question, when I mean userland I mean writing our wing code like this:

```ts
bring "./cdktf-flyio.js" as cdktfFlyio;

class FlyioClient {  
  extern "./flyio-client.js" inflight createMachine(appId: str): str;
}

class Flyio {
  _app: cdktfFlyio.App;
  _client: FlyioClient;

  init() {
     this._app = new cdktfFlyio.App(this);
     this._client = new FlyioClient();
  }

  inflight createMachine() {
    this._client.createMachine(...);
  }
}
```

Not even sure how doable is this...

**Comment by skyrpex** [comment]
> i think we need to support a `wing.config.json` to handle custom install/build requirements. something lilke
> 
> ```
> {
>   "version": "1.0",
>   "entryfile": "something.w" //default: main.w
>   "installScript": "./install" //default: npm install
>   "buildScript": "npm run build" //default ""
> }
> ```
> 
> and for each config file we would create a preview env

- Do we want to support multiple apps in one repo (as of now?)
- Maybe the filename should be something like `wingpreview.config.json` (or similar) so users aren't confused. They may think this file can be consumed by `wing compile`, `wing it`, etc.

**Comment by skorfmann** [comment]
for the fly.io stuff - wouldn't this be a great opportunity to think about inflight provisioning? 

So far there are two approaches in this issue (if I understand them correctly):

1. Build the bindings for the fly tf provider and have dedicated, parameterized builds (the default way of using wing)
2. Build an inflight client with a JS sdk (or just by hand) and use it inflight 

It's probably stretching the boundaries within Wing, but wouldn't it be cool to have the option to do ad-hoc, inflight provisioning of Terraform resources? In contrast to build / use a custom SDK, one could just use an existing provider and let it handle all the complexity and make sure the state is persisted properly. Something like an inflight provider backed by a bucket / table for state handling.

**Comment by eladb** [comment]
@skorfmann do you think the right way to provision new flyio machines is through terraform...

**Comment by eladb** [comment]
@ainvoner @skyrpex @ekeren let's consolidate everything related to the preview environment planning work (spec and design) into a single RFC document. It should include the user story and the proposed solution, architecture, etc.

It's a big enough project not to plan inside a GitHub issue 🤷🏻‍♀️

**Comment by skorfmann** [comment]
> @skorfmann do you think the right way to provision new flyio machines is through terraform...

Depends on the complexity, but probably not, since it's likely a single resource. 

When initially talking about the fly provisioning for the playground, I had a workflow based on durable objects of Cloudflare in my mind. I still think that could be quite useful as a general concept, with or without terraform being baked in :)

**Comment by ekeren** [comment]
> @ainvoner @eladcon @skyrpex @ekeren let's consolidate everything related to the preview environment planning work (spec and design) into a single RFC document. It should include the user story and the proposed solution, architecture, etc.
> 
> It's a big enough project not to plan inside a GitHub issue 🤷🏻‍♀️

I agree, @ainvoner do you mind owning this?

**Comment by ainvoner** [comment]
@eladb @ekeren sure. we thought about starting the initial conversation in an issue and to create an RFC when we will have more clue.
I'll create one soon

**Comment by ainvoner** [comment]
duplication of https://github.com/winglang/wing/issues/3689
