### ISSUE TITLE
`wing watch` or `wing compile --watch` command

### ISSUE THREAD

**Issue by 3p3r** [winglang/wing#370]
@eladb mentioned `wing run` should also accept an entry point and do the watch/compile/sim cycle. This ticket tracks it. #322 should reflect this change as well.

**Comment by staycoolcall911** [comment]
@eladb - since the Console now provides this functionality, I'm closing this issue. Please reopen if you feel differently.

**Comment by Chriscbr** [comment]
@staycoolcall911 I feel like it makes sense to have some kind of `wing watch` or `wing compile --watch` command, at least until the Wing console is available on Linux or Windows. Should I create a new issue?

**Comment by staycoolcall911** [comment]
You're absolutely right, @Chriscbr - I'm reopening this issue
