### ISSUE TITLE
Icons via console API

### ISSUE THREAD

**Issue by olivernybroe** [winglang/wing#3708]
### Feature Spec

Each resource in the console API **may** (optinally) have a `icon` field. 

This field **must** contains a unique name for the icon, it does not contain the icon data itself. For fetching the icon refer to the `app.fetchIcon` query. 

**Fetch Icon Query**
The `app.fetchIcon` query takes two arguments
- `name` (required): The unique name of the icon to fetch
- `color` (optional): The color of the icon. If no color provided a variable named `chosenColor` will be the value of the color instead. (Client can replace this with their color scheme later) 

The query **shall** always return the icon as SVG, if other format is needed. The client may convert it itself.

All SVGs **must** always be square, e.g. 16x16, 32x32, 256x256.

The reason why fetch icon is it's own query and not part of the resource directly is to reduce bandwidth. No reason the send a full SVG for every single resource when the client already received it once and likely cached it. The bandwidth matters more when talking about the web socket. 

### Use Cases

This solves the need for the clients to keep a list of all icons available and updating this list when updates happens. 

It also solves the coloring issues of icons to match the clients own theme. 

Lastly it allows for later on having custom resources provide their own icons. E.g. creating a third party library for A.I, the resources in there can actually have it's own icons instead of only the default icon.

### Implementation Notes

This can and probably should be split into two pr's, one for adding the icon field to the api and resources and another one for fetching the icons. 

### Component

Wing Console, Development Environment

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

```[tasklist]
### Tasks
```

**Comment by ainvoner** [comment]
handled in a different issue. support heroicons string for custom resources using node.display object
