### ISSUE TITLE
Customize App root id on sim

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#3749]
### Feature Spec

Following this comment: https://github.com/winglang/wing/pull/3723#discussion_r1286225467 
This issue is to make root id customizable on all cloud targets. 

### Use Cases

User customization

### Implementation Notes

There are places in the code in which the sim root id is hardcoded, and it's preventing us from being able to allow customization as well.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
@tsuf239 I edited the title and description of this issue.

**Comment by tsuf239** [comment]
that's actually a duplicate of the one Mark opened recently- #6598

**Comment by eladb** [comment]
So perhaps we can close this?
