### ISSUE TITLE
Mobile support error message in playground/learn site

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#3751]
### Feature Spec

Add a new and designed error message when our playground and learn sites open in mobile

### Use Cases

see a nice error message incase of an ugly one when opening the sites in mobile

### Component

Playground

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
this is the current text:

"This app is intend to be used on desktops
            Please open this app on a device with a wider screen."

**Comment by ainvoner** [comment]
![Screenshot 2023-08-09 at 14 47 16](https://github.com/winglang/wing/assets/2538825/49045c7a-1e72-4f94-a51c-510441f3fc59)

**Comment by amielpb** [comment]
![image](https://github.com/winglang/wing/assets/95175829/02e355eb-7c30-4b84-80a1-00119097e1eb)

**Comment by amielpb** [comment]
Device Not Supported
This app is for desktop use only.

**Comment by amielpb** [comment]
#660000
HEX for the color
