### ISSUE TITLE
CLI flags are sensitive to ordering

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#3766]
### I tried this:

`wing compile -t tf-aws --plugins my-plugin.js website.w`

### This happened:

error: missing required argument 'entrypoint'

### I expected this:

It works

### Is there a workaround?

Put the plugins first
`wing compile --plugins plugin.s3-etags.js -t tf-aws website.w`
or after the entrypoint
`wing compile -t tf-aws website.w --plugins plugin.s3-etags.js`

### Component

CLI

### Wing Version

0.24.89

### Node.js Version

18.14.1

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
An alternative could be to separate each plugin with its own (repeatable) flag:

```
wing compile -t tf-aws --plugin p1.js --plugin p2.js website.w
```

(esbuild is another example of a CLI that handles flags like this: `esbuild app.js --bundle --loader:.png=dataurl --loader:.svg=text`)

**Comment by staycoolcall911** [comment]
@Chriscbr - I couldn't reproduce this since `--plugins` has been deprecated. Closing. Please reopen if you can reproduce this.
