### ISSUE TITLE
feat(console): change elk depending on screen size

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#3774]
### Feature Spec

Change the ELK configuration depending on things like screen size.

### Use Cases

When a user opens the Console inside vs-code, they usually use it side by side with the wing file.

<img width="1512" alt="image" src="https://github.com/winglang/wing/assets/5547636/be374248-7d6a-4b7d-9602-b7fc03a2ba1d">

But when a user opens the Console in the browser, there is more room to open it more widely.
<img width="1512" alt="image" src="https://github.com/winglang/wing/assets/5547636/6c585c0b-d56b-45b6-972e-07a41e8c5ccf">

### Implementation Notes

changing `elk.layered.layering.strategy` should do almost all the work.

_No response_

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
not relevant
