### ISSUE TITLE
cloud.OnDeploy - `awscdk` implementation

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#3782]

**Comment by marciocadev** [comment]
The problem is that this issue also occurs in the CDK.

This code works:

```ts
    const tri = new NodejsFunction(this, "Tri", {
      handler: "handler",
      entry: join(__dirname, 'lmb/tri.ts'),
      functionName: "tri",
    });

    const goodbye = new NodejsFunction(this, "Goodbye", {
      handler: "handler",
      entry: join(__dirname, 'lmb/index3.ts'),
      functionName: "goodbye",
    });

    const triggerGoodbye = new Trigger(this, "TriggerGoodbye", { handler: goodbye });

    new Trigger(this, "F3Tri", {
      handler: tri,
      executeBefore: [triggerGoodbye],
    });
```

However, this code doesn't work because the Function is created within the trigger's own class:

```ts
    const tri = new NodejsFunction(this, "Tri", {
      handler: "handler",
      entry: join(__dirname, 'lmb/tri.ts'),
      functionName: "tri",
    });

    const triggerGoodbye = new TriggerFunction(this, 'TriggerGoodbye', {
      handler: "index3.handler",
      code: Code.fromAsset(__dirname + "/lmb"),
      runtime: Runtime.NODEJS_18_X
    });

    new Trigger(this, "F3Tri", {
      handler: tri,
      executeBefore: [triggerGoodbye],
    });
```

**Comment by marciocadev** [comment]
I believe that just like in the OnDeploy class, as in the CDK TriggerFunction class, the function is present within the class's hierarchy, and this adds the dependency.

In the case of the Trigger class in the CDK, the function is not within the same hierarchy as the class, so it's not included, and that's why the error doesn't occur.

**Comment by Chriscbr** [comment]
Hey @marciocadev, thanks for raising the issue. This sounds like a tricky cyclic dependency problem. 🤔

I'm not sure if it solves it, but what if we exposed the `cloud.Function` that is created to `cloud.OnDeploy` as a public property? For example:

```js
new cloud.OnDeploy(inflight () => {
    log("trigger");
  },
  executeAfter: [triggerHello.fn, triggerWorld.fn],
  executeBefore: [triggerGoodbye.fn]
) as "init";
```
