### ISSUE TITLE
unexpected lifting value for mutable arrays

### ISSUE THREAD

**Issue by eladcon** [winglang/wing#3798]
### I tried this:

`wing test` this code: 
```
let arr = MutArray<str>[];
test "arr" {
  log("${arr}");
  arr.push("abc");  
  log("${arr}");
}
```

### This happened:

got this output:
```
pass ┌ test.wsim » root/env0/test:arr
     │ abc,abc
     └ abc,abc
```

### I expected this:

this output:
```
pass ┌ test.wsim » root/env0/test:arr
     │ 
     └ abc
```

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
That is a surprising output indeed 🤔

**Comment by staycoolcall911** [comment]
Might be related to changes from #3622?

**Comment by staycoolcall911** [comment]
Duplicates #3064
