### ISSUE TITLE
RFC: Preview Environments Implementation Details

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#3803]
# RFC | Preview Environments Implementation Details

### Introduction
Defines some of the technical implementation details for [Wing Cloud Preview Environments](https://github.com/winglang/wing/issues/3689).

### GitHub App

A GitHub App will be created for the integration between GitHub and Wing Cloud ([docs](https://docs.github.com/en/developers/apps/creating-a-github-app)).

The configuration of the GitHub App will require the following steps:

#### Configuring permissions

The GitHub App will need specific permissions to be able to perform the required actions with repositories.

- **Repository Permissions**
  - [Contents](https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-contents) - **Read**
    - This permission is essential for accessing the `.main.w` entry points within PRs.
  - [Pull Requests](https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-pull-requests) - **Read and Write**
    - This permission is required to create comments containing the fly.io link.

#### Webhook Configuration

The GitHub App will need to subscribe to specific events through webhook URLs. The following configurations will be applied:

- **Webhook URL:**
  - `https://wing.cloud/api/v1/github/webhook`
- **Events:**
  - [Pull Request](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request)

The GitHub App will be installed at the organization level. Upon installation, all PRs within the repositories accessible by the GitHub App will automatically have Preview Environments enabled.

### GitHub Sign Up / Log In

The GitHub App will be used for the user sign-up and log-in processes. [docs](https://docs.github.com/en/apps/creating-github-apps/writing-code-for-a-github-app/building-a-login-with-github-button-with-a-github-app).

The login flow is defined further in the documentation, available [here](https://github.com/winglang/wing/blob/rfc-preview-environment/docs/docs/09-rfcs/2023-03-08-wing-preview-environment.md#sign-up-and-sign-in).

To generate a user access token, a callback URL must be added to the GitHub App's configuration:

- **Callback URL:** `https://wing.cloud/github/callback`
- An example about how to generate a user access token is provided [here](https://docs.github.com/en/apps/creating-github-apps/writing-code-for-a-github-app/building-a-login-with-github-button-with-a-github-app#add-code-to-generate-a-user-access-token).

### Storage of users
TBD

### Storage of fly.io links
TBD

### Storage of Environment Variables
TBD

### DNS Resource
TBD

**Comment by ainvoner** [comment]
@polamoros what do you want to do with this issue?

**Comment by polamoros** [comment]
> @polamoros what do you want to do with this issue?

We can close it
