### ISSUE TITLE
MutArray.remove(item), MutArray.removeAt(index)

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#3833]
### Feature Spec

```js
let arr = MutArray<num>[5, 10, 15];
assert(arr.at(0) == 5);
arr.removeAt(0);
assert(arr.at(0) == 10);
arr.remove(10);
assert(arr.at(0) == 15);

let arr2 = MutArray<num>[3, 6, 9];
let r1 = arr2.remove(3);
assert(r1 == true);
assert(arr2.length == 2);
let r2 = arr2.remove(-42);
assert(r2 == false);
assert(arr2.length == 2);
```

### Use Cases

Removing elements from arrays

### Implementation Notes

Index must be valid (0 <= index < array.length) otherwise `removeAt` should throw an error

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by garysassano** [comment]
@Chriscbr I guess `r == true` was meant to be either `r1` or `r2`?

So, from what I could infer, `array.remove()` returns a boolean with `true` if at least one occurence of the given value was found, while `array.removeAt()` returns `void` but throws an error if the index doesn't exist. Is that correct?

**Comment by garysassano** [comment]
@Chriscbr I guess `r == true` and `r == false` were meant to be either `r1` or `r2`?

So, from what I could infer, `MutArray.remove()` returns a boolean with `true` if at least one occurence of the given value was found, while `MutArray.removeAt()` returns `void` but throws an error if the index doesn't exist. Is that correct?

**Comment by Chriscbr** [comment]
> @Chriscbr I guess `r == true` and `r == false` were meant to be either `r1` or `r2`?

You're right - I've fixed the examples now.

> So, from what I could infer, `MutArray.remove()` returns a boolean with `true` if at least one occurence of the given value was found, while `MutArray.removeAt()` returns `void` but throws an error if the index doesn't exist. Is that correct?

That's right - though I forgot to include an example with the return type of `removeAt`. It probably makes sense for `removeAt` to return the item that was removed.

If an element in an array appears multiple times, `remove` only removes the first occurrence.

**Comment by garysassano** [comment]
>That's right - though I forgot to include an example with the return type of `removeAt`. It probably makes sense for `removeAt` to return the item that was removed.

So, wouldn't it make more sense to call the method `popAt()`, since it behaves like `MutArray.pop()` but with an index?

**Comment by WeepingClown13** [comment]
Similarly if `remove()` only removes the first occurence of the element, it'd be better to have a more intuitive name like `removeFirst()` because I initially thought this method was supposed to remove all occurences. Unless of course if this can be used to remove either one, or all or even a specific number of occurences.
