### ISSUE TITLE
`elif let` statements

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#3835]
### Feature Spec

Support `if let` in the "elif" position:

```js
let x = Json { ghost: "spooky" };
if let y = x.tryAsBool() {
  log("it's a boolean!");
} elif let y = x.tryAsNum() {
  log("it's a number!");
} else {
  log("it's something else!");
}
```

### Use Cases

Checking and unwrapping values without separate if statements

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by marciocadev** [comment]
🤣🤣🤣🤣 I just finished implementing a branch for this, and now I'm not sure if I should push it.

**Comment by staycoolcall911** [comment]
Done in #3888
