### ISSUE TITLE
Compiler panic on recursive function without type annotations

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#3846]
### I tried this:

```js
let fact = (n) => {
  if (n == 0) {
    return 1;
  } else {
    return n * fact(n - 1);
  }
};
```

### This happened:

Compiler bug (panicked at 'Inference id already has a type', libs/wingc/src/type_check.rs:1321:9

### I expected this:

It compiles, or expects a type annotation

### Is there a workaround?

Add return type annotation

### Component

Compiler

### Wing Version

0.25.14

### Platform(s)

MacOS

### Anything else?

If you add a type annotation to the parameter it yields the same error:
```
let fact = (n: num) => {
  if (n == 0) {
    return 1;
  } else {
    return n * fact(n - 1);
  }
};
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
Fixed in https://github.com/winglang/wing/pull/3729
