### ISSUE TITLE
Inconsistent type inference in if statements

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#3847]
### I tried this:

When I "return x" in the first part of an if branch, the type of `x` is inferred:

```js
let g = (flag: bool, x) => {
  if flag {
    return x;
  } else {
    return 5;
  }
};
```

But if "return x" is in the second part of an if branch, it gives compiler errors:

```js
let g = (flag: bool, x) => {
  if flag {
    return 5;
  } else {
    return x;
  }
};
```

### This happened:

```
error: Expected type to be "unknown", but got "unknown" instead
  --> inference.w:5:12
  |
5 |     return x;
  |            ^ Expected type to be "unknown", but got "unknown" instead


error: Unable to infer type
  --> inference.w:1:22
  |
1 | let g = (flag: bool, x) => {
  |                      ^ Unable to infer type


error: Unable to infer type
  --> inference.w:1:5
  |
1 | let g = (flag: bool, x) => {
  |     ^ Unable to infer type
```

### I expected this:

It compiles

### Is there a workaround?

Add type annotation for `x`

### Component

Compiler

### Wing Version

0.25.14

### Node.js Version

18.14.1

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
Fixed in https://github.com/winglang/wing/pull/3729
