### ISSUE TITLE
`Unexpected variadic` error

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#3874]
### I tried this:

```
bring cloud;

let q = new cloud.Queue();

test "foobar" {
  let msgs = ["Foo", "Bar"];
  q.push(...msgs);
  let popped = q.pop();
  log(popped ?? "NIL");
}
```

### This happened:

```sh
error: Unexpected 'variadic'
  --> examples/tests/sdk_tests/queue/pop.w:7:10
  |
7 |   q.push(...msgs);
  |          ^^^ Unexpected 'variadic'

```

### I expected this:

I expected it to work the same way as:

```
bring cloud;

let q = new cloud.Queue();

test "foo" {
  q.push("Foo", "Bar");
  let popped = q.pop();
  log(popped ?? "NIL");
}
```

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by marciocadev** [comment]
@garysassano try this

```ts (wing)
bring cloud;

let q = new cloud.Queue();

test "foobar" {
  q.push("Foo", "Bar");
  let popped = q.pop();
  log(popped ?? "NIL");
}
```

**Comment by garysassano** [comment]
@marciocadev That's the same code I wrote in the original post under "I expected this".

**Comment by eladb** [comment]
I don't think we support the spread (`...`) operator yet.

**Comment by staycoolcall911** [comment]
Duplicates #3855
