### ISSUE TITLE
Wrong connections when using custom resources

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#3880]
### I tried this:

```
bring cloud;

let bucket = new cloud.Bucket();

class MyBucketManager {
  inflight managerPut() {
    bucket.put("file.txt", "Hello World");
  }
}

let manager = new MyBucketManager();

let func = new cloud.Function(inflight () => {
  manager.managerPut();
});
```

### This happened:

There is a connection `Function -> Bucket`

<img width="546" alt="image" src="https://github.com/winglang/wing/assets/5547636/563bcb9f-3a3f-4ef0-b077-e3cab9300f97">

```
{
  "version": "connections-0.1",
  "connections": [
    {
      "source": "root/Default/cloud.Function",
      "target": "root/Default/cloud.Bucket",
      "name": "put()"
    },
    {
      "source": "root/Default/cloud.Function",
      "target": "root/Default/MyBucketManager",
      "name": "managerPut()"
    },
  ]
}
```

### I expected this:

A connection `Function -> MyBucketManager`
Another connection `MyBucketManager -> Bucket`

```
{
  "version": "connections-0.1",
  "connections": [
   {
      "source": "root/Default/MyBucketManager",
      "target": "root/Default/cloud.Bucket",
      "name": "put()"
    },
    {
      "source": "root/Default/cloud.Function",
      "target": "root/Default/MyBucketManager",
      "name": "managerPut()"
    },
  ]
}
```

### Component

SDK

### Anything else?

Without custom resources

```
bring cloud;

let bucket = new cloud.Bucket();

let manager = new cloud.Function(inflight () => {
  bucket.put("file.txt", "Hello World");
}) as "manager";

let func = new cloud.Function(inflight () => {
  manager.invoke("");
}) as "func";
```

<img width="658" alt="image" src="https://github.com/winglang/wing/assets/5547636/44f15c82-0b82-41a3-987a-10455006ac7b">

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
Related: https://github.com/winglang/wing/issues/2629
