### ISSUE TITLE
Console logs don't show when invoking cloud.Function

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#3893]
### I tried this:

While trying to look into #1843 I tried this code on the Wing Console:
```ts
bring cloud;

let my_func = new cloud.Function(inflight (m: str) => {
  // do nothing
});

new cloud.Function(inflight () => {
  log("whatevah");
  let x = my_func.invoke("message");
  log(x);
}) as "test";
```
I then tried to invoke the function on the Console.

### This happened:

Nothing was printed to the log.

### I expected this:

Log to show:
```sh
whatevah
undefined
```

### Is there a workaround?

Use a test, instead of a cloud.Function.

### Component

Wing Console

### Wing Version

0.25.27

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment]
Has this been fixed?

**Comment by ainvoner** [comment]
already fixed
