### ISSUE TITLE
Add `assertThrows` for testing errors

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#3901]
### Feature Spec

Throughout the [sdk_tests](https://github.com/winglang/wing/tree/main/examples/tests/sdk_tests), I've noticed that this code snippet gets used over and over:

```
let assertThrows = (expected: str, block: (): void) => {
  let var error = false;
  try {
    block();
  } catch actual {
    assert(actual == expected);
    error = true;
  }
  assert(error);
};
```

So I was wondering if it wouldn't be simpler to add a native way for testing errors in Wing.

### Use Cases

Avoid repeating the same function dozens of times.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by WeepingClown13** [comment]
+1 to this. Last time I had to use this and I thought the same thing. It'd be a very useful method to have.

**Comment by staycoolcall911** [comment]
Duplicates #1977
