### ISSUE TITLE
Add a Testing guide to the docs

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#3906]
### Feature Spec

The guides section has explanations with examples of how to conduct tests in Wing for different scenarios.
https://www.winglang.io/docs/category/guides

### Use Cases

When developers want to know how to test their specific use case

### Implementation Notes

We have a tests section in the concepts part of the docs (https://www.winglang.io/docs/concepts/tests). But it is not a guide and not enough to really answer specific questions we get asked, like how do I test event driven architectures with Wing? where can I see examples for this? etc.

### Component

Documentation

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by boyney123** [comment]
I think there is some great value here. Going to bring this back to life.
