### ISSUE TITLE
Add `testing` submodule to Wing SDK

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#3918]
### Feature Spec

Now you can import `testing` submodule.
```
bring testing;
```

Methods to add:
- [ ] `testing.assertThrows()` (see #3901)
- [ ] `testing.assertEq()`
- [ ] `testing.assertNotEq()`

### Use Cases

Improve testing DevEx in Wing.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skorfmann** [comment]
Perhaps this is something which could live in an external npm module for now and maybe a first class external wing module at some point. Something like https://github.com/winglang/examples/pull/16

**Comment by skorfmann** [comment]
Related to https://github.com/winglang/wing/issues/2859 / https://github.com/winglang/wing/issues/1977

@garysassano are you working on this? Could use this as well :)

**Comment by eladb** [comment]
I think this should be in the sdk.

**Comment by garysassano** [comment]
@skorfmann I checked if I could add it now, but I saw that it actually [already exists](https://github.com/winglang/wing/tree/main/libs/wingsdk/src/testing), despite not being included in the [exported submodules](https://github.com/winglang/wing/blob/main/libs/wingc/src/lib.rs#L75-L82). I think it was used in the past for the inflight test functions, before Wing had the `test` blocks.

**Comment by eladb** [comment]
I think we should change the name of the existing `testing` module to `simulator`...

**Comment by skorfmann** [comment]
Looked into it to see how difficult it would be, turned out it's not that complicated (except for the renaming part in this case). So, here's an initial version to get things going https://github.com/winglang/wing/pull/3976 - feel free to edit / add things.

**Comment by garysassano** [comment]
Keep.
