### ISSUE TITLE
Preserve state inside resource interaction views

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#3928]
### I tried this:

1. Created a `cloud.Api`:
```ts
bring cloud;

let api = new cloud.Api();
```
2. Clicked the Api resource in the Wing Console and edited the request body (added "hello").
3. Clicked the Root panel.
4. Clicked the Api resource again.

### This happened:

The request body text field is cleared (does not contain "hello").

### I expected this:

The request body text field to still contain "hello".
A "clear all fields" button could be added to quickly get a clean slate, but in many cases I'd prefer to keep the panel's state longer.

### Component

Wing Console

### Wing Version

0.25.33

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by polamoros** [comment]
I've updated the issue title as it's affecting all resources
