### ISSUE TITLE
Add SDK tests for `http` submodule

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#3945]
### Feature Spec

I don't see any testing for the `http` submodule in [sdk_tests](https://github.com/winglang/wing/tree/main/examples/tests/sdk_tests).

### Use Cases

Reduce unwanted errors from untested library.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by BITOCTA** [comment]
@garysassano API resource tests [sdk_tests/api](https://github.com/winglang/wing/tree/main/examples/tests/sdk_tests/api) include some tests for the `http` submodule. Do we need any other tests?

**Comment by garysassano** [comment]
@BITOCTA Ok, I didn't check there actually. I think test for `HEAD` may be missing? I see it's in the available methods [HERE](https://www.winglang.io/docs/standard-library/http/api-reference#enums-).

**Comment by BITOCTA** [comment]
> @BITOCTA Ok, I didn't check there actually. I think test for `HEAD` may be missing? I see it's in the available methods [HERE](https://www.winglang.io/docs/standard-library/http/api-reference#enums-).

it's also there in [options.w](https://github.com/winglang/wing/blob/main/examples/tests/sdk_tests/api/options.w)

**Comment by garysassano** [comment]
> it's also there in [options.w](https://github.com/winglang/wing/blob/main/examples/tests/sdk_tests/api/options.w?rgh-link-date=2023-08-26T17%3A56%3A42Z)

I don't see `http.head` in that file.

**Comment by garysassano** [comment]
Tested within `cloud.Api` tests.
