### ISSUE TITLE
Making "wing it" watcher ignore website folders

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#3956]
### Feature Spec

Assuming we have a folder containing our client-side application in one subfolder, and the wing file in another/at the root, 
we want to prevent the wing watcher from watching the client-side files. 
one way to do it is "knowing" what files to ignore (detect the website paths), and another, is "knowing" what files to include- only the wing file and its imports.

### Use Cases

Real life wing app

### Component

Compiler, Wing Console, Development Environment

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skyrpex** [comment]
This shouldn't be necessary if https://github.com/winglang/wing/issues/3730 gets implemented, right?

**Comment by tsuf239** [comment]
> This shouldn't be necessary if #3730 gets implemented, right?

right!

**Comment by garysassano** [comment]
So there's no need to complete this? It's not clear for me what is the "`wing it`'s watcher". All I can see [HERE](https://github.com/winglang/wing/blob/main/apps/wing/src/commands/run.ts) is that it looks for a `.w` file, not for any subfolders.

**Comment by tsuf239** [comment]
closing as a duplication (specific case) of #3730
