### ISSUE TITLE
Can't access base class's inflight fields

### ISSUE THREAD

**Issue by yoav-steinberg** [winglang/wing#3977]
### I tried this:

```wing
class FooBase {
  inflight baseInflightField: str;

  inflight init() {
    this.baseInflightField = "base inflight field";
  }
}

class Foo extends FooBase {}

let foo = new Foo();

test "a test" {
  log(foo.baseInflightField);
}
```

### This happened:

```
3:27 $ apps/wing/bin/wing test temp/bla.w 
ERROR: Resource root/env0/Foo does not support inflight operation baseInflightField (requested by root/env0/test:a test/Handler)

temp/target/test/bla.wsim.164393.tmp/.wing/preflight.js:87
         _registerBind(host, ops) {
           if (ops.includes("handle")) {
>>           $Closure1._registerBindObject(foo, host, ["baseInflightField"]);
           }
           super._registerBind(host, ops);

 
 
Tests 1 failed (1)
Test Files 1 failed (1)
```

### I expected this:

to work (print the base class's inflight field's value)

### Component

Compiler

### Anything else?

I was attempting to prove there's a bug where we don't call the base class's inflight `init` method. So base class fields don't get initialized, for example. But then this happened.
I guess we now need to fix both..

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
This could be a regression from my PR https://github.com/winglang/wing/pull/3884 (sorry 😬)

**Comment by staycoolcall911** [comment]
Had to modernize the code a bit (`init` -> `new`, exposed the inflight field as `pub`), but then this works - closing.
