### ISSUE TITLE
wingc test fixtures for JSII importer testing

### ISSUE THREAD

**Issue by MarkMcCulloh** [winglang/wing#3984]
### Feature Spec

In a similar vein to the [jsify unit testing](https://github.com/winglang/wing/blob/main/libs/wingc/src/jsify/tests.rs), we have a similar system for the JSII importer. In a test you can define a JSII manifest (inline or a separate file) and assert against the resulting type system state.

### Use Cases

Fast and easy testing for the JSII importer

### Implementation Notes

Might be nice to also use the defined JSII manifest in a wing program as well, but may not be a necessary feature

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Duplicates #1414
