### ISSUE TITLE
vscode missing debugging information

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#3992]
### I tried this:

![image](https://github.com/winglang/wing/assets/1727147/3752d9ee-d9bb-4d01-a6b9-6d04147483b2)

### This happened:

see image

### I expected this:

missing information about what is expected - I would expect to have a the api.post signature here and to know that there is a str path as the first argument 

### Component

IDE Extension

### Wing Version

0.26.5

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
This is much better and useful IMO:
This is the error message:
![image](https://github.com/winglang/wing/assets/106860404/75b717bd-a9cc-40f3-b4cb-13fa59eeb311)
If you hover over the method name you see the signature:
![image](https://github.com/winglang/wing/assets/106860404/26656d09-b7a6-4c78-a322-629cd45c0d86)
Code to reproduce:
```ts
bring cloud;

let api = new cloud.Api();

api.post(inflight(req) => {

});
```
