### ISSUE TITLE
vscode after if completion is broken

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#3999]
### I tried this:

![image](https://github.com/winglang/wing/assets/1727147/20f74cb4-7cc6-4a02-9000-8e044cada9ed)

### This happened:

It didn't complete string methods

### I expected this:

to complete string methods

### Component

IDE Extension

### Wing Version

0.25.6

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
This is resolved.
