### ISSUE TITLE
Operators: increment (`++`) and decrement (`--`)

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#4004]
We'd like to support the increment and decrement operators and add them to the [language reference](https://www.winglang.io/docs/language-reference#643-mathematics-operators).

```ts
test "increase/decrease" {
  let var i = 5;
  let var j = 5;
  let var k = 5;
  let var m = 5;

  // 5 is logged
  // Then, i is increased to 6
  log("${i++}");

  // j is increased to 6
  // Then, j is logged
  log("${++j}");

  // 5 is logged
  // Then, k is decreased to 4
  log("${k--}");

  // m is decreased to 4
  // Then, m is logged
  log("${--m}");
}
```
For reference: see a former PR that added the `power` operator to the language #1654
Small note: the operator was named `exponent` in this PR, but later renamed to `power`.

**Comment by Chriscbr** [comment]
https://github.com/apple/swift-evolution/blob/main/proposals/0004-remove-pre-post-inc-decrement.md

**Comment by staycoolcall911** [comment]
> [apple/swift-evolution@main/proposals/0004-remove-pre-post-inc-decrement.md](https://github.com/apple/swift-evolution/blob/main/proposals/0004-remove-pre-post-inc-decrement.md?rgh-link-date=2023-08-29T21%3A18%3A24Z)

Very interesting, thanks! 
I'd love to see what others think - should we add `++` to the language or not?

**Comment by wzslr321** [comment]
> https://github.com/apple/swift-evolution/blob/main/proposals/0004-remove-pre-post-inc-decrement.md

Quite an interesting proposal. I have coded in C++ and I have to admit that even though these operators are not, in fact, complicated, they can still cause some issues - simply because it is easy to automatically write them as pre/post fix without giving it much thought. Good luck debugging in such a case.

Personally, I believe that cloud-native aspects of Wing are enough - no need to complicate things just to save a few chars.

**Comment by WeepingClown13** [comment]
It is definitely convenient but not like x++ and x+=1 are worlds apart. If there are problems it could introduce then better not have it since fundamentally wing looks at solving the pains of cloud and not exactly programming itself😅 I mean, we can always add it later if necessary.

**Comment by staycoolcall911** [comment]
Ok, I'm closing this issue for now.
