### ISSUE TITLE
can't alias util sdk resources

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#4032]
### I tried this:

```
bring cloud as c;
bring http as h;

let bucket = new c.Bucket();

let hello_world = inflight () => {
  bucket.put("hello.txt", "Hello, World!");
  h.get("/mypath");
};

new c.Function(hello_world);
```

[playground](https://www.winglang.io/play/?code=YgByAGkAbgBnACAAYwBsAG8AdQBkACAAYQBzACAAYwA7AAoAYgByAGkAbgBnACAAaAB0AHQAcAAgAGEAcwAgAGgAOwAKAAoAbABlAHQAIABiAHUAYwBrAGUAdAAgAD0AIABuAGUAdwAgAGMALgBCAHUAYwBrAGUAdAAoACkAOwAKAAoAbABlAHQAIABoAGUAbABsAG8AXwB3AG8AcgBsAGQAIAA9ACAAaQBuAGYAbABpAGcAaAB0ACAAKAApACAAPQA%2BACAAewAKACAAIABiAHUAYwBrAGUAdAAuAHAAdQB0ACgAIgBoAGUAbABsAG8ALgB0AHgAdAAiACwAIAAiAEgAZQBsAGwAbwAsACAAVwBvAHIAbABkACEAIgApADsACgAgACAAaAAuAGcAZQB0ACgAIgAvAG0AeQBwAGEAdABoACIAKQA7AAoAfQA7AAoACgBuAGUAdwAgAGMALgBGAHUAbgBjAHQAaQBvAG4AKABoAGUAbABsAG8AXwB3AG8AcgBsAGQAKQA7AA%3D%3D)

### This happened:

```
Failed to compile.

ERROR: h is not defined

wing/target/test.wsim.785931.tmp/.wing/preflight.js:19
             require("./inflight.$Closure1-1.js")({
               $bucket: ${context._lift(bucket)},
>>             $h_Util: ${context._lift(h.Util)},
             })
           `;
```

### I expected this:

It compiles, since `bring cloud as c` works as properly 

### Is there a workaround?

don't alias

### Component

Compiler, SDK

### Wing Version

0.27.7

### Node.js Version

18.6.0

### Platform(s)

MacOS

### Anything else?

the http resource is [exporting](https://github.com/winglang/wing/blob/33165cf561269a57a6d77e22709287abee1f97f7/libs/wingsdk/src/http/http.ts#L164) a `Util` class, which allows calling static functions on that class directly on the namespace (e.g. `http.fetch` rather than `http.http.fetch`). Learned that the other day, thanks to @Chriscbr  :) 

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skorfmann** [comment]
also had this for normal classes in https://github.com/winglang/wing/pull/3976/

**Comment by eladb** [comment]
+1 I think we should support this.

Copying @yoav-steinberg

**Comment by staycoolcall911** [comment]
This works now.
