### ISSUE TITLE
Confusing error when $ is used in strings

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#4038]
### I tried this:

```js
log("hello$");
log("cool${} stuff");
```

### This happened:

```
error: Unexpected 'identifier'
  --> api.w:1:11
  |
1 | log("hello$");
  |           ^ Unexpected 'identifier'


error: Expected 'reference_identifier'
  --> api.w:2:12
  |
2 | log("cool${} stuff");
  |            ^ Expected 'reference_identifier'


error: Unknown symbol ""
  --> api.w:2:12
  |
2 | log("cool${} stuff");
  |            ^ Unknown symbol ""
```

### I expected this:

For the first line, I expected no error, since there is no set of braces following it like `log("hello${}")`.
For the second line, I expected a single error, probably with a friendly message like `Expected an expression inside of the braces, like "${2 + 2}"`

### Component

Compiler

### Wing Version

0.27.7

### Node.js Version

18.14.1

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by garysassano** [comment]
I also experienced this, and saw there was already an open issue: #1071

**Comment by Chriscbr** [comment]
@garysassano ah, yeah you're right. I'll close this one
