### ISSUE TITLE
Do not allow ambiguous api paths

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#4052]
### I tried this:

```
api.get("/{param}/{something}", handler);
api.get("/path/{something}", handler)
```

Those paths are ambiguous- since for the call `${api.url}/path/xxx` I can be directed to both of them.

### This happened:

The app failed only when tried to access one of the paths- during a test, and after deploying to aws...

### I expected this:

To throw a compilation error

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by garysassano** [comment]
Would it be possible to have the full code so that I can replicate it on my side?

**Comment by garysassano** [comment]
Would it be possible to have the full code so that I can replicate the issue on my side?

**Comment by tsuf239** [comment]
```
bring cloud;
let api = new cloud.Api();
let handler = inflight (req: cloud.ApiRequest): cloud.ApiResponse => {
  return cloud.ApiResponse {
    status: 200,
    body: body
  };
});

api.get("/{param}/{something}", handler);
api.get("/path/{something}", handler)
```

**Comment by tsuf239** [comment]
this is resolved by https://github.com/winglang/wing/pull/4352
