### ISSUE TITLE
winglang.io/play and winglang.io/learn are down

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#4068]
### I tried this:

load to play and learn are down

### This happened:

They are stuck on loading

See also https://uptime.betterstack.com/team/48207/incidents/447916447

### I expected this:

to work

### Component

Playground, Tutorial

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skyrpex** [comment]
Seems like flyio is having problems:

<img width="920" alt="image" src="https://github.com/winglang/wing/assets/1077520/ec669c52-ea20-41bb-9f0e-72bdac6c7dbd">

**Comment by ainvoner** [comment]
login to their site doesn't work as well

**Comment by ainvoner** [comment]
![Screenshot 2023-09-04 at 10 58 01](https://github.com/winglang/wing/assets/2538825/883f046b-059f-4841-99bb-af855c4c96d0)
 getting worse... hopefully their alerts got triggered as well...

**Comment by ainvoner** [comment]
they acknowledged the issue 
![Uploading Screenshot 2023-09-04 at 12.21.16.png…]()

**Comment by ekeren** [comment]
Lets change /learn /play to present the following message until this issue is resolved:

![image](https://github.com/winglang/wing/assets/1727147/e32965a5-f5ff-4e9d-bbb7-143db4907e09)

**Comment by ekeren** [comment]
FYI - The service is getting better (slow but working)

**Comment by ainvoner** [comment]
https://github.com/winglang/playground/pull/413

**Comment by ainvoner** [comment]
resolved
