### ISSUE TITLE
`wing run` invalid exit code when console is not installed

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#407]
**I tried this:**
I was running `wing run` command without installing the console before

0. before installing wing console
1. run `wing run /tmp/sim-tests/app.wx`
2. Command exited without any error (exit status error) 

**I expected to see this happen:**
Something like
`couldn't run console: command  /Applications/wing-console.app not found`
command exit status is 0

I would go ever further and let the user know how he can download the console  
**Instead, this happened:**
```
wing run /tmp/sim-tests/app.wx
eyalkeren@eyals-MacBook-Pro sim-tests %
eyalkeren@eyals-MacBook-Pro sim-tests % echo $?
0
```

no indication of an issue
### Component

Select one or more:

- [ ] Language Design
- [ ] Compiler
- [ ] SDK
- [ ] IDE Extension
- [ ] Documentation
- [x] Development Environment

### Environment

**Platform**: MacOS | Windows | Linux
MacOS 
**Version (`wing --version`)**: <0.0.0>
0.2.90

**Comment by staycoolcall911** [comment]
Since wing and the wing console are now installed together, this issue is no longer relevant.
Closing.
