### ISSUE TITLE
Function with infinite loop keeps on spewing logs even after hot reloading a change of code that deletes it

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#4087]
### I tried this:

Wrote this code:
```ts
bring cloud;
bring util;

new cloud.Function(inflight () => {
  while true {
    log("Weeeeee");
    util.sleep(1s);
  }
});
```

Then invoked the function and saw the logs starting to appear.

Then I deleted the function, so my code is this:

```ts
bring cloud;
bring util;
```

### This happened:

After the console hot reloaded the new code, the Function was removed from the map view, but the "Weeee" logs kept appearing every second

### I expected this:

The logs to stop coming in

### Component

SDK

### Anything else?

I was doing this test in the playground.

Also, if I changed the sleep time to 1ms the playground crashed after a short time..

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skyrpex** [comment]
I think this belongs to the simulator.

@Chriscbr

**Comment by Chriscbr** [comment]
This bug has since been fixed (the inflight code now runs in an external process which can be killed - see https://github.com/winglang/wing/pull/5554)
