### ISSUE TITLE
Replace REST API Gateway with HTTP API for tf-aws target

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#4097]
### Feature Spec

Using the [HTTP API](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api.html) rather than the [REST API](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-rest-api.html) for the `tf-aws` target will simplify the implementation and gets rid of some custom plumbing around 404 handlers and CORS. On top of that, it'll be [cheaper](https://cloudonaut.io/review-api-gateway-http-apis/) per request.

The HTTP API lacks a few things, most notably (see here for more [details](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html)):

- X-Ray
- Edge endpoints

X-Ray is probably the one which might be missed in the future, however it's not being used at the moment. Edge endpoints are just baked in Cloudfront capabilities which could be easily added.

### Use Cases

Generally I think, the HTTP should be the default choice, primarily for the ease of use and the more attractive pricing model. This would get rid of https://github.com/winglang/wing/issues/4091 and most of the follow up tasks of https://github.com/winglang/wing/pull/2904 by using baked in capabilities of the HTTP API.

### Implementation Notes

In [Slack](https://winglang.slack.com/archives/C048QCN2XLJ/p1693943660561259), the option of "implementations" for SDK resources was brought up - where there might be multiple implementations per resource / target. Don't have any details on this, perhaps someone else could elaborate on this.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by garysassano** [comment]
Was the current `cloud.Api` interface validated as compatible or there could be some things that need to be changed?

**Comment by skorfmann** [comment]
the current implementation is very straightforward. The only thing which will not work from the current implementation is the mock integration - which is not an issue, since the things which is being used for a are natively supported in the http api gateway (cors / 404 handling).

It's more a question if one of these points (or something else from the feature [differences]([details](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html))) will be a roadblock in the near future.

> - X-Ray
> - Edge endpoints

**Comment by skorfmann** [comment]
All in all the HTTP API Gateway feels pretty half baked and is missing core features like X Ray which would lead into dead ends pretty quickly. Closing and gonna create follow up issues for https://github.com/winglang/wing/pull/2904
