### ISSUE TITLE
console preview environment tweaks

### ISSUE THREAD

**Issue by eladcon** [winglang/wing#4114]
### Feature Spec

- [ ] Use our own DNS record above the fly.dev one
- [ ] Update the preview comment when the environment is closed
- [ ] Leave the environment alive for some time after the PR was closed

### Use Cases

better DX

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
One we will finish Wing Cloud preview environments feature, we will be able to use it instead of the current solution
