### ISSUE TITLE
Wing workshop

### ISSUE THREAD

**Issue by eladb** [winglang/wing#412]
The Wing Tutorial is a primary documentation artifact that helps developers learn Wing from the ground up.

## Feature Spec

Welcome to the Wing Tutorial!

Go make a cup of coffee, lean back and enjoy the ride...

The goal of this tutorial is to teach everything you need to know about Wing so you can start building awesome cloud applications in no time. To do that, we will build together a real cloud application step-by-step, and with every step, we will take a second to give you some background about the various language features.

## Use Cases

* I want to learn Wing

## Component

Select one or more:

- [ ] Language Design
- [ ] Compiler
- [ ] SDK
- [ ] IDE Extension
- [x] Documentation
- [ ] Development Environment
- [ ] Contributor Experience

**Comment by eladb** [comment]
Keep

**Comment by staycoolcall911** [comment]
One idea we had was to build the URL Shortener example step by step

**Comment by staycoolcall911** [comment]
This is very stale. Closing
