### ISSUE TITLE
Console: cannot copy error message text

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#4132]
### I tried this:

Ran some code that yields a compilation error (e.g. just write `blabla` in the playground or vscode Wing Console extension).
[Playground](https://www.winglang.io/play/?code=YgBsAGEAYgBsAGEA)

### This happened:

Couldn't copy the error message (so I could put it into an issue description, for example).

Text on the BSOD is not copy-able:
![image](https://github.com/winglang/wing/assets/106860404/898dd33a-7447-4d30-8fa3-76ddba7a8276)

### I expected this:

To be able to copy the error message

### Component

Wing Console, Playground

### Wing Version

0.29.11

### Node.js Version

18.15

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by exoego** [comment]
I think the culprit is `select-none` in default layout.
The `select-none` class prevents users from selecting content in the div.
https://github.com/winglang/wing/blob/d37d83f4045f8d817424f2df4c045dd7c9e08221/apps/wing-console/console/ui/src/layout/default-layout.tsx#L257-L260

**Comment by staycoolcall911** [comment]
Reopening as this is still a disturbing issue

**Comment by ainvoner** [comment]
resolved by https://github.com/winglang/wing/pull/5839
