### ISSUE TITLE
Embedded vscode console not rendering in windows

### ISSUE THREAD

**Issue by MarkMcCulloh** [winglang/wing#4150]
Originally posted in https://github.com/winglang/wing/issues/4022#issuecomment-1711881016

### I tried this:

I created a `hello.w` file and added the following:

```wing
bring cloud;
```

### This happened:

Nothing is rendered in vscode:

![image](https://github.com/winglang/wing/assets/50240570/4cad386d-a32c-4f34-a8fd-15cfa4054b9c)

### I expected this:

To work.

Again running `wing it hello.w` works as expected

![image](https://github.com/winglang/wing/assets/50240570/c294f7b5-547d-4324-858b-790dadce0812)

### Is there a workaround?

The CLI works just fine and the browser shows what's expected.

### Component

IDE Extension

### Wing Version

0.27.4

### Node.js Version

v19.6.0

### Platform(s)

Windows

---

This is a followup issue from https://github.com/winglang/wing/issues/4022

**Comment by staycoolcall911** [comment]
We removed the embedded console. Closing
