### ISSUE TITLE
Simplify JavaScript code generated by wing

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#4158]
### Feature Spec

We would like to improve the readability of JavaScript code emitted by the Wing compiler so that inflight code is easier to debug in production.

### Use Cases

Making it easier to debug Wing applications in production

### Implementation Notes

For example, the following Wing code

```js
let x = 2;
assert(x == 2);
```

currently generates
```js
const x = 2;
{((cond) => {if (!cond) throw new Error("assertion failed: x == 2")})((((a,b) => { try { return require('assert').deepStrictEqual(a,b) === undefined; } catch { return false; } })(x,2)))};
```

Instead, it should generate

```js
const x = 2;
$stdlib.assert($stdlib.equals(x, 2), "assertion failed: x == 2"));
```

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by marciocadev** [comment]
I started working on this, and I wanted to provide an update on the progress.

In the preflight, it's working, but in the inflight, it's necessary to import the `@winglang/sdk`.

I'm going to try importing the library and check the impact on the size of the `cloud.Function` and whether it would have any impact on execution speed

**Comment by marciocadev** [comment]
@Chriscbr 

I was thinking about which parts of the code we should make more readable, and I believe that the assert, range, equal, and notEqual parts can be improved. There might be more areas to enhance, but if we can improve these, it's a good start.

I was also thinking that when we create a class in the Cloud (like a Queue, for example), there's the "inflight" part associated with the function if a push is performed. I thought about creating a specific class for this with "inflight" methods like assert, range, equal, and notEqual. This way, the compiler itself would take care of importing these functionalities into the inflight part.

The only issue is that the generated code would be different depending on the phase, and we would need to check the phase when generating the code. 

In this way, this code:
```ts (wing)
bring cloud;
let x = 2;
assert(x == 2);
assert(x != 3);
new cloud.Function(inflight () => {
  assert(x == 2);
});
```
Would transform into this code during the preflight phase:
```ts
const x = 2;
{$stdlib.util.assert($stdlib.util.equal(x, 2), x == 2)};
{$stdlib.util.assert($stdlib.util.notEqual(x, 3), x != 3)};
// I know, it's a stupid name
const q = this.node.root.newAbstract("@winglang/sdk.cloud.CleanUp",this,"cloud.CleanUp"); 
```
But in the inflight phase, it could be like this:
```ts
module.exports = function({ $q, $x }) {
   ...
   (await $q.assert($q.equal($x, 2)));
   ...
}
```

**Comment by revitalbarletz** [comment]
@marciocadev are you still looking at this issue?

**Comment by marciocadev** [comment]
No @revitalbarletz 

I'm busy with other stuffs right now, sorry

**Comment by Chriscbr** [comment]
Implemented in https://github.com/winglang/wing/pull/5306
