### ISSUE TITLE
Missing API documentation in struct/keyword completions

### ISSUE THREAD

**Issue by eladb** [winglang/wing#4184]
### I tried this:

<img width="579" alt="Screenshot 2023-09-14 at 16 18 21" src="https://github.com/winglang/wing/assets/598796/0ea02f12-79a4-4c5d-90c5-0d9cdaf30c43">

### This happened:

No API documentation

### I expected this:

To see API documentation for each field

### Component

IDE Extension

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
The docs are available, although hidden sometimes by the ide and needs to be manually expanded. I'm not sure when it decides to automatically show it, may be based on screen size.

<img width="963" alt="image" src="https://github.com/winglang/wing/assets/1237390/29c817e8-2fdc-4e1a-a801-dbbec8ee01d9">

**Comment by eladb** [comment]
Is there a way to show them by default or at least show the description
next to the symbol?

**Comment by staycoolcall911** [comment]
Closing as not planned for now
