### ISSUE TITLE
Show breaking change descriptions in changelog

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#4189]
### Feature Spec

(working backwards) Starting in Wing 0.x, whenever there is a breaking change made in the Winglang toolchain, the full description of the breaking changes will be listed in the GitHub release notes, so Wing users don't have to navigate to the pull request for extra context about how to migrate their code based on the breaking change.

Whenever a commit as designated as a breaking change (it has a "!" after the commit type, like `feat(sdk)!: bucket has been removed`), extra notes can be specified through the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard of including a paragraph in the commit description starting with `BREAKING CHANGE:`. Typically this description explains what API changed and how users need to update their code, assuming there's a way to do so. These notes will be included in GitHub release notes.

### Use Cases

Make it easier for users to migrate between Wing versions as we incubate the language and standard libraries. Provide a standard / well-defined way for contributors and maintainers to follow for including extra content in the release notes when there is a breaking change.

### Implementation Notes

Example of current release notes for breaking changes: https://github.com/winglang/wing/releases/tag/v0.30.0

### Component

Documentation

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
This should already work since we use https://github.com/unjs/changelogen to generate the note. So the change here would just be to document and possibly enforce that breaking changes should have an extra note.

Note: It didn't work for https://github.com/winglang/wing/releases/tag/v0.30.0 because the PR for it was merged manually and didn't have the PR description in the commit.

**Comment by Chriscbr** [comment]
@MarkMcCulloh I found a change from a while back that seems to have a valid description in its commit, and the release doesn't seem to include it. https://github.com/winglang/wing/releases/tag/v0.27.0 Maybe it needs to be formatted differently? 

I've got another breaking change open that we can use to try test things https://github.com/winglang/wing/pull/4190

**Comment by MarkMcCulloh** [comment]
Yeah looks like changelogen actually doesn't do this. We'll see if they take this https://github.com/unjs/changelogen/pull/148
