### ISSUE TITLE
Getting occasional "Unknown symbol cloud" on https://www.winglang.io/learn/

### ISSUE THREAD

**Issue by Retamogordo** [winglang/wing#4193]
Hi,
I'm getting occasional "Unknown symbol cloud"  issues starting from the page 5 of the tutorial.
While the simulator renders components normally, the editor complains on the ```bring cloud;``` line.
The guide starts normally, however when the page 5 is reached, the above message appears and then it repeats when I move to the next or previous pages.
Refreshing the page helps but only until the fifth page is reached.

**Comment by ekeren** [comment]
Seeing this also 

![image](https://github.com/winglang/wing/assets/1727147/f271c2b5-3ba1-4218-a6e9-e423df18ae30)

**Comment by ekeren** [comment]
@ShaiBer 

I think this is related to your implementation of syntax highlighting 

Notice that If I go to page four that shows this:
![image](https://github.com/winglang/wing/assets/1727147/9c0e6de0-19cc-4917-8610-fde2a3b88f2c)

And then go back to page 3, it reproduces this issue (there is some race condition there, you can retry it a couple of times)

**Comment by ShaiBer** [comment]
I'm innocent :) I did lion in the desert on the PRs to the playground repo, and looks like this is the first PR in which the bug appears - https://github.com/winglang/playground/pull/336
The PR before it doesn't have the bug, and all the ones after it do have it.
So it's either the bump in the wing version of the console server, or something else..
Adding @ainvoner to see how to proceed
