### ISSUE TITLE
cannot invoke inherited Function in sim`

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#4201]
### I tried this:

```ts
bring cloud;

class FunctionA extends cloud.Function  {
  
  init(f: inflight (str):void) {
    super(f);
  }
  
}
new FunctionA(inflight (s: str) => {
  log("heeelloo");
});


```

### This happened:

![image](https://github.com/winglang/wing/assets/1727147/28b822dc-7ec8-4819-ae57-ae4e2941e519)

### I expected this:

To be able to invoke `FunctionA`

### Is there a workaround?

No

### Component

Wing Console

### Wing Version

0.31.1

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
@ekeren the code is not valid anymore

**Comment by ekeren** [comment]
Probably just because of the init keyword, right ?
