### ISSUE TITLE
inheritance: api.get is not a function

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#4205]
### I tried this:

```
bring cloud;

class AnApi extends cloud.Api {

}

let api = new AnApi();
api.get("/", inflight () => {
  return  {
    status: 200
  };
});

```

### This happened:

```
wing compile main.w
```
```
ERROR: api.get is not a function

target/api.main.wsim.640250.tmp/.wing/preflight.js:63
       }
       const api = new AnApi(this,"AnApi");
>>     (api.get("/",new $Closure1(this,"$Closure1")));
     }
   }


```

### I expected this:

to work

### Component

Compiler

### Wing Version

0.31.1

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
duplicates #3585
