### ISSUE TITLE
Simulator crash when creating cloud.Secret with missing /.wing/secrets.json file

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#4237]
### I tried this:

create a cloud.Secret
```
let secret = new cloud.Secret(name: "my-secret");
```
with no secret.json file in `/.wing/secrets.json file`

and run `wing it`

### This happened:

Error in the Console:

No secrets file found at /Users/ainvoner/.wing/secrets.json while looking for secret my-secret

Internal error: An internal compiler error occurred. Please report this bug by creating an issue on GitHub (github.com/winglang/wing/issues) with your code and this trace.

### I expected this:

to not throw an error

### Component

Compiler, SDK

### Wing Version

0.31.12

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
@ainvoner - why shouldn't it throw in that case? The developer defined a `cloud.Secret` in the code, but forgot to add the local `secrets.json` - the compiler should surface that error or am I missing anything?

**Comment by ainvoner** [comment]
@staycoolcall911 you don't get an error when compiling the app, only when running it.
I think it is depends how it behave when running terraform apply (on tf-aws compiled code)
will check it out

**Comment by staycoolcall911** [comment]
We decided to close this issue - the error message is sufficient for now.
