### ISSUE TITLE
ex.Redis doesn't work in our playground

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#4279]
### I tried this:

in winglang.io/play:
```
bring ex;
new ex.Redis();
```

### This happened:

![Screenshot 2023-09-26 at 11 32 41](https://github.com/winglang/wing/assets/2538825/84cd4993-0857-499e-bfb0-5bc9eedc93ec)

### I expected this:

to work

### Is there a workaround?

NO

### Component

Playground

### Wing Version

0.13.35

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
Do we expect container based solutions to work in the playground?

@eladcon what will it take?
