### ISSUE TITLE
Primitive Types: void

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#432]
https://github.com/winglang/wing/blob/main/docs/04-reference/winglang-spec.md#111-primitive-types

@yoav-steinberg :
- [x] We should support this internally in our type system for functions that have no return value.
- [ ] Adding void as a primitive type or even as a keyword in the syntax is something I'd like to avoid as much as possible.

**Comment by Chriscbr** [comment]
Part 1 is done (implemented in #1122)

**Comment by staycoolcall911** [comment]
Thanks @Chriscbr - I have updated the description with sub-tasks to reflect that.

**Comment by staycoolcall911** [comment]
@eladb will consider the use cases for `void` and either remove it from the spec or introduce the gaps.

**Comment by staycoolcall911** [comment]
Closed in #2733
