### ISSUE TITLE
long log messages are truncated in the console

### ISSUE THREAD

**Issue by eladcon** [winglang/wing#4353]
### I tried this:

log a long message in the console:

```ts
test "ss" {
  log("a very very very very very very very very very very long msg");
}
```

### This happened:

message is truncated

<img width="525" alt="Screenshot 2023-10-01 at 15 48 12" src="https://github.com/winglang/wing/assets/16601535/59df3138-b254-4e2c-88f0-cb73772ee9cd">

### I expected this:

see the whole message

### Is there a workaround?

double click and copy the message

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skyrpex** [comment]
This has been solved already 👍
