### ISSUE TITLE
`std.Json` static methods suggested thrice by IntelliSense

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#4367]
### I tried this:

I typed `Json.` inside a Wing file in VS Code.

### This happened:

IntelliSense presented me a list of all static methods with each one appearing thrice.

![json-triple-intellisense](https://github.com/winglang/wing/assets/10464497/848d2749-1357-4779-bc97-7c80259636ca)

### I expected this:

I expected each static method to appear only once.

### Component

IDE Extension

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
Are you able to post more from the file here? Or a replication in the [playground](https://www.winglang.io/play/)?

I think I've seen this issue but I'm not able to replicate it.

**Comment by staycoolcall911** [comment]
Hey @garysassano - I wasn't able to reproduce this as well. Could you please try to see if you can reproduce this?

**Comment by garysassano** [comment]
I tryed yesterday but I couldn't reproduce it. It looks like it's a flaky issue.

**Comment by staycoolcall911** [comment]
Closing for now, until someone is able to replicate it.

**Comment by subh-cs** [comment]
Hi @staycoolcall911 @MarkMcCulloh , I think it is similar. 

I'm not doing anything new. It is happening with me by default. 

### This is for cloud module
![image](https://github.com/winglang/wing/assets/75121304/0ba51bcb-4b6c-49ee-ad2f-7f6e0729b0b9)

### And this is ex module
![image](https://github.com/winglang/wing/assets/75121304/f9c9d2b6-ec32-4156-9ef8-4ad79edb5f26)
