### ISSUE TITLE
Rethink Console relationships between nodes

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#4384]
In the following example, the API resource displays a relationship to all of it's routes. IMO it's unnecessary.

Also, every route node shows a relationship to the Projects resource, and its inner DynamoDB table. I'm missing here the inflight nodes for Projects: every route should be connected to a Projects inflight, and the inflight node should be connected to the DynamoDB table node.

<img width="1089" alt="image" src="https://github.com/winglang/wing/assets/1077520/d2c483ef-225f-4bab-96f0-0786b7a5b0e1">

**Comment by ekeren** [comment]
repoen

**Comment by ainvoner** [comment]
was handled as part of Map V2, @skyrpex is need to reopen, remove `stale` and reopen please
