### ISSUE TITLE
Can't parse a string as Json

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#4386]
### I tried this:

```
test "parse()" {
  assert(Json.parse("foo") == "foo");
}
```

### This happened:

```sh
 │ SyntaxError: Unexpected token o in JSON at position 1
 │     at JSON.parse (<anonymous>)
 │     at $Closure8.handle (/tmp/wing-bundles-RWbtVF/index.js:26:21)
 └     at exports.handler (/tmp/wing-bundles-RWbtVF/index.js:5337:9)
```

### I expected this:

I expected it to work like shown in [MDN examples](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#examples).

### Is there a workaround?

```
test "parse()" {
  assert(Json.parse("\"foo\"") == "foo");
}
```

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
> I expected it to work like shown in [MDN examples](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#examples).

Here's a [playground link](https://www.winglang.io/play/?code=SgBzAG8AbgAuAHAAYQByAHMAZQAoACIAewB9ACIAKQA7ACAALwAvACAAewB9AAoASgBzAG8AbgAuAHAAYQByAHMAZQAoACIAdAByAHUAZQAiACkAOwAgAC8ALwAgAHQAcgB1AGUACgBKAHMAbwBuAC4AcABhAHIAcwBlACgAIgBcACIAZgBvAG8AXAAiACIAKQA7ACAALwAvACAAIgBmAG8AbwAiAAoASgBzAG8AbgAuAHAAYQByAHMAZQAoACIAWwAxACwAIAA1ACwAIABcACIAZgBhAGwAcwBlAFwAIgBdACIAKQA7ACAALwAvACAAWwAxACwAIAA1ACwAIAAiAGYAYQBsAHMAZQAiAF0ACgBKAHMAbwBuAC4AcABhAHIAcwBlACgAIgBuAHUAbABsACIAKQA7ACAALwAvACAAbgB1AGwAbAA%3D#) showing all the examples working. The example with foo here is `JSON.parse('"foo"');`, notice the inner quotes.

Json.parse (and JSON.parse in JS) takes a string that is valid json.
In your example `assert(Json.parse("foo") == "foo");`, `foo` is not valid json while `"foo"` is valid json.

If you want to represent a string as json, you can do:

```js
let j: Json = "foo";
```

**Comment by garysassano** [comment]
The point here was to test the `Json.parse()` method tho, which expects a string.

Then you need to use the workaround I put in the original post.
