### ISSUE TITLE
Clean up the example folder

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#4405]
### Feature Spec

There are some js methods and hardcoded helpers that we used in the examples folder before writing a solution in wing
those are:
1. `examples/tests/sdk_tests/util/sleep-helper.js` that can be swapped with the `datetime` module
2. `examples/tests/sdk_tests/external/http.js` that can be swapped with the `http` module
3.  the `Predicate` class or method that can be swapped with our native `waitUntil`

please refactor the examples to use the latest solution

### Use Cases

Updating our examples- so the readers will get to know the latest solution

### Component

SDK, Documentation, Contributor Experience

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec
  has not been finalized yet. Please reach out on the #dev channel
  in the [Wing Slack](https://t.winglang.io/slack).

**Comment by tsuf239** [comment]
@revitalbarletz that's the task that you asked earlier today, please feel free to assign it/ split and assign it to a contributor

**Comment by staycoolcall911** [comment]
Renamed the issue "Clean up the example repo" => "Clean up the example folder" because the examples repo is https://github.com/winglang/examples while the examples folder is https://github.com/winglang/wing/tree/main/examples

**Comment by mnik7044** [comment]
Hey @tsuf239 @revitalbarletz I want to work on this issue

**Comment by revitalbarletz** [comment]
Its all yours!

**Comment by garysassano** [comment]
Point 3 was addressed in #5296

**Comment by garysassano** [comment]
All points were addressed.
