### ISSUE TITLE
Adding documentation to the Ex module's resources

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#4407]
### Feature Spec

adding md files for `ex.Table`, `ex.Redis`, `ex.DynamoDb`

### Use Cases

documentation

### Component

Documentation

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec
  has not been finalized yet. Please reach out on the #dev channel
  in the [Wing Slack](https://t.winglang.io/slack).

**Comment by eladb** [comment]
All of these are going to be moved to external libraries soon. Not sure this is worth the effort.

(We would want to automatically render docs for libraries but that's a different story)

**Comment by staycoolcall911** [comment]
Closing - since we're migrating the ex module to winglibs
