### ISSUE TITLE
class field declaration and assignment is not respected

### ISSUE THREAD

**Issue by eladcon** [winglang/wing#4474]
### I tried this:

```js
class C {
  s: str = "123";
  init() {
  }
}
```

### This happened:

```
eladcohen@Elads-w-MacBook-Pro a2 % wing test main.w
error: Preflight field "s" is not initialized
  --> main.w:2:7
  |
2 |   pub s: str = "123";
  |       ^ Preflight field "s" is not initialized
```

### I expected this:

i wont have to explicitly assign to `s` again in `init` (or at least a compiler error on the declaration line)

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
I don't believe this syntax is supported yet (see https://github.com/winglang/wing/issues/3121). Perhaps it should have produced a syntax error instead?

**Comment by staycoolcall911** [comment]
I don't think we should keep an issue for adding an error message for this case, since #3121 is p1.
I think we can close this for now.

Semi-related: #3121 will be split to 3 issues for default values in structs, classes and function signatures.
