### ISSUE TITLE
Compiler should narrow types after simple guard clauses

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#4495]
### I tried this:

```
test "infer after throw" {
  let cookies: str? = "value";
  // Guard clause: if no cookies, throw.
  if cookies == nil {
    throw "no cookies";
  }
  cookies;
  // ^^^^ The compiler should know that `cookies` is `str`, not `str?`.
}
```

### This happened:

The compiler still believes that `cookies` is `str?` and requires additional boilerplate code to handle.

### I expected this:

The compiler should be able to narrow optional types after some guard clauses.

### Component

Compiler

### Wing Version

0.36.7

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
An enhancement suggestion :)

**Comment by ekeren** [comment]
I am not sure I understand the `let else` syntax @eladb would that be

```
test "infer after throw with let esle" {
  let cookies: str? = "value";
  // Guard clause: if no cookies, throw.
  let realCookies = cookies else return;  // relacookie is from type str
}
```
