### ISSUE TITLE
Create a wing slack library

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#4507]
### Feature Spec

Since Wing is an awesome way to write slack bots (see [Guy's article](https://levelup.gitconnected.com/cloud-first-programming-how-i-built-a-notification-bucket-with-wing-in-under-5-minutes-f70fd9a21ca7))
Let's embrace that and build a Slack library (and then another article or a few, making Wing the preferable way to write Slackbots 💪 )
Also, it will be good to test a real-life usage of the library feature

### Use Cases

great things that can be built with Wing, 
testing real-life use of the library feature

### Implementation Notes

I'll do it in my spare time, after getting more urgent work done :) 
Where should we put "library request" issues? 

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by ekeren** [comment]
keep

**Comment by hasanaburayyan** [comment]
We missed this issue and created: https://github.com/winglang/wing/issues/5733

Since the other issue already has some api proposals and comments we can just use that one for now.
