### ISSUE TITLE
RFC: Wing Playground

### ISSUE THREAD

**Issue by eladb** [winglang/wing#451]
The Wing Playground is a web-based experience that can be used to play with the Wing language.

## Feature Spec

Home: https://playground.winglang.io

(TODO ux wireframe)

The playground includes two sub-components:
1. The code editor
2. The output view

### Editor

The code editor is single-file, fully fledged IDE-like editing tool, with syntax highlighting, code completion, diagnostics, etc.

* P0: syntax highlighting
* P1: Wing VSCode extension behavior (code completion, compiler diagnostics, etc)

### Output

The output view will show the compilation output of the program. It will be possible to switch between the following views:

* P1: Terraform AWS: shows the terraform output (what about inflight javascript?)
* P1: Preflight: shows the intermediate preflight code generated by the compiler (for compiler diagnostics).
* P1.5: Console map view: shows only the console map and you can navigate it (but no simulator backend)
* P2: Interactive Wing Console: shows a fully fledged interactive wing console (with simulator backend)
* P1: Terraform GCP (when supported)
* P1: Terraform Azure (when supported)

### Other Requirements

* P2: It should be possible to select which version of the toolchain they are using (one version for compiler, sdk, etc).
* P2: The playground should be highly embeddedable in other websites. We should distribute it in the most portable way possible (web component? react component?)
* P2: It should be possible to position the code editor and the output view separately inside a host website to have maximum control over layout etc.
* P1: Simple and minimalistic visual design that will fit as-is inside other experiences.

### Roadmap (future ideas)

* Support installing 3rd party dependencies
* Support downloading the Terraform+JS output
* Support deployment from within the browser
* Support showing an infrastructure architecture diagram in the output view instead of the Terraform output
* Support interaction with the wing console app in console mode

## Use Cases

* Take Wing for a spin (hello, world).
* Share snippets of Wing code (send a link to a pre-populated playground).
* Embed inside documentation and blogs (e.g. inside the wing tutorial)

**Comment by staycoolcall911** [comment]
@ekeren - can we close this issue? It seems to be stale
