### ISSUE TITLE
Improve the file preview of the bucket interaction view

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#4531]
### Feature Spec

Text files should always be displayed (e.g., wing files, yaml, etc are now shown as base64).
<img width="290" alt="image" src="https://github.com/winglang/wing/assets/5547636/8a071686-fe43-4604-9668-37274165e12f">

Should be shown like:
<img width="277" alt="image" src="https://github.com/winglang/wing/assets/5547636/27c0107a-7b7f-4af0-873b-723078ee88da">

It shows a warning if there is no preview:
<img width="286" alt="image" src="https://github.com/winglang/wing/assets/5547636/f2415e02-a21a-4bf3-a616-817415fa7584">

### Use Cases

The user might assume that the files are corrupted when text files are displayed as base64.

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by ekeren** [comment]
qualifies as good first issue
