### ISSUE TITLE
Allow filtering secrets in the Console map

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#4553]
### Feature Spec

The Wing Console now allows filtering secrets from the map view.

Instead of the `Show tests / Hide tests` tool button, there's now a filter button that opens a small popup which allows toggling whether the tests and the secrets are visible.

### Use Cases

Hiding the secrets from the map is something users may want to do since they may be used in many different places at once, which may add unnecessary noise.

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by ainvoner** [comment]
@skyrpex not sure this is relevant anymore. if relevant - reopen please
