### ISSUE TITLE
Support calling inflight methods from different processes

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#4560]
### Feature Spec

Allow compute resources (like `cloud.Service`, `cloud.Function`, etc.) in separate processes to interact with simulated resources

### Use Cases

Today, the resources in the Wing Cloud Library are constrained to being part of the same Node.js process as the simulator. Each resource (like an a `cloud.Bucket` instance) maps to a single object in Node.js, and references to these objects are shared and passed around by inflight code. But this architecture won't work if the inflight code is running in a separate process, such as a Docker container. Instead, information about the resource and the method that needs to be called would have to be communicated through some form of [IPC](https://en.wikipedia.org/wiki/Inter-process_communication), like sockets, pipes, etc.

### Implementation Notes

An initial version of this was implemented in https://github.com/winglang/wing/pull/4105 using an express server, but it was reverted in #4557 since it resulted in many flakey tests for contributors and in CI.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by staycoolcall911** [comment]
@Chriscbr - is there anything in this issue not done in #4697? Can we close?
