### ISSUE TITLE
Can not use id nor scope inside init function

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#4577]
### I tried this:

```
class Main {
  init() {
    let id = "id";
  }
}
```

### This happened:

<img width="772" alt="image" src="https://github.com/winglang/wing/assets/5547636/3ddf0ea5-7848-47d1-8b76-a0ebb314507c">

The error is not clear when using an extern:
<img width="775" alt="image" src="https://github.com/winglang/wing/assets/5547636/f5ea9c9a-4a42-4287-9edc-47cc1bc905e3">

### I expected this:

to be able to use `id` and `scope` inside the init function.

### Is there a workaround?

nope

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Duplicates #3026
