### ISSUE TITLE
Investigate better technologies for the Console map

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#4582]
The map gets slow real quick when the app grows. We need something better for rendering the map, like WebGL, canvas or similar.

SolidJS may be able to provide the performance we're looking for while keeping most of our code intact.

**Comment by eladb** [comment]
I would also try to collapse everything by default (eg only show one layer deep) and allow users to expand only a single node at a time.

This way, the map will usually stay pretty lean and you also just focus on one thing.

Worth experimenting with a few modes, maybe even allow the users to select the view mode until we decide which is the one we love.

**Comment by Chriscbr** [comment]
I wonder if it's possible to let users expand or minimize each node without making it too visually distracting (maybe you can double click on a node, or maybe it's a single button that only appears when you mouse over the node, etc)

**Comment by eladb** [comment]
Maybe hovering on a node will start to expand it and if you linger it will expand

**Comment by ainvoner** [comment]
handled
