### ISSUE TITLE
A browser extension that adds syntax highlighting to `.w` files on GitHub

### ISSUE THREAD

**Issue by eladb** [winglang/wing#4594]
### Feature Spec

The **Winglang GitHub Syntax Highlighting** browser extension will add syntax highlighting to GitHub files and markdown for Winglang.

This is needed as long as GitHub's [linguist](https://github.com/github-linguist/linguist) doesn't support Winglang as a language ([tracking](https://github.com/winglang/wing/issues/1038)).

### Use Cases

Read Wing code on the GitHub website.

### Component

Other

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by ekeren** [comment]
I think that  @ShaiBer  have dome something similar in the [winglang.io/learn](https://winglang.io/learn)
In the attached image:
![image](https://github.com/winglang/wing/assets/1727147/629cca4c-2752-4ef5-85c3-8fb407cb1c98)

The syntax highlight for the wing code is done using `@monaco-editor/react` and `monaco-editor`
It might be possible to use the same method and inject into the github webpage https://www.plasmo.com/blog/posts/how-to-inject-a-react-component-onto-a-web-page-using-a-chrome-extension

**Comment by marciocadev** [comment]
Maybe we can add the language on Syntaxtic! extension

https://chrome.google.com/webstore/detail/syntaxtic/cgjalgdhmbpaacnnejmodfinclbdgaci

https://github.com/ajmath/Syntaxtic

**Comment by Lancear** [comment]
Sounds like an awesome improvement for DX! Would be interested to assist.

We want to replace the rendered file on GitHub with a highlighted one if it ends with .w? Or where/how do we want to show the highlighted code?

**Comment by eladb** [comment]
> We want to replace the rendered file on GitHub with a highlighted one if it ends with .w?

Yes! Basically until GitHub supports Winglang format, people will be able to install this extension and it would work as if there's built-in support.

**Comment by Chriscbr** [comment]
Thanks to @eladcon there's now a Chrome extension you can download that adds syntax highlighting: https://chromewebstore.google.com/detail/winglang-syntax-hightligh/gjnleleianfjpmckmmdeahlklhcdlakj

**Comment by Lancear** [comment]
AWESOME 🥳
