### ISSUE TITLE
It is not possible to run tests in different folders

### ISSUE THREAD

**Issue by marciocadev** [winglang/wing#4658]
### I tried this:

When running `wing test *`, the tests in the folder are not found.

![277644134-a24c5c33-9f6a-4d65-bd36-8ccb421add5b](https://github.com/winglang/wing/assets/67694075/43e604f7-5099-409e-8365-df95d90f32c4)

### This happened:

```bash
$ wing test *
log preflight
Invalid Wing app (target/test/folder.wsim) - simulator.json not found.
pass ┌ invoke.test.wsim » root/env0/test:invoke
     │ log inside test
     └ log inside function
contains 2 lines

Results:
    ✓ invoke.test.w
    × folder

Errors:
At folder
Invalid Wing app (target/test/folder.wsim) - simulator.json not found.

Tests 1 failed | 1 passed (2)
Test Files 1 failed | 1 passed (2)
Duration 0m0.89s
```

### I expected this:

Works

### Component

SDK

### Wing Version

0.41.5

### Node.js Version

v18.17.1

### Platform(s)

Linux

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by tsuf239** [comment]
what about `wing test **/*.w`?

**Comment by marciocadev** [comment]
> what about `wing test **/*.w`?

only execute the current folder file

```bash
$ wing test **/*.w
pass ─ env.test.wsim » root/env0/test:addEnvironment


Tests 1 passed (1)
Test Files 1 passed (1)
Duration 0m0.89s
```

**Comment by garysassano** [comment]
@marciocadev That's normal since `wing test` takes an array of glob patterns as an input. If you want to test all files in the current directory and in any subdirectory, you would use `wing test *.w **/*.w`.

**Comment by staycoolcall911** [comment]
@garysassano is correct - the path argument to `wing test` is a regular expression, so the behavior makes sense.
Closing for now, but if anyone disagrees, feel free to reopen.

**Comment by tsuf239** [comment]
I tested it on my machine and it's working for me, what terminal and machine are you using @marciocadev?

**Comment by marciocadev** [comment]
Hi @tsuf239 

We can close this

I was using the wrong command
