### ISSUE TITLE
Strings: sizeof

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#468]
https://github.com/winglang/wing/blob/main/docs/04-reference/winglang-spec.md#61-strings

Support sizeof to get the length of the string

**Comment by staycoolcall911** [comment]
We're not doing that. Instead we have `str.len`

**Comment by Chriscbr** [comment]
@staycoolcall911 Shouldn't we update the spec then?

**Comment by staycoolcall911** [comment]
@Chriscbr - you're absolutely correct - I'll do that!
