### ISSUE TITLE
Publish `awscdk` Platform as a Custom Platform Provider

### ISSUE THREAD

**Issue by hasanaburayyan** [winglang/wing#4693]
### Feature Spec

The `awscdk` platform should be published as its own custom platform rather than as a builtin one.

### Use Cases

Slims up the builtin shipped packages, and also will serve as a guide to others on how to build and publish custom platforms

### Implementation Notes

Gonna need to play around with what `wingsdk` exposes since `awscdk` platform makes use of some internal methods for bundling and other things

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by hasanaburayyan** [comment]
Should not that this requires https://github.com/winglang/wing/pull/4669 merging first

**Comment by marciocadev** [comment]
@hasanaburayyan if you need some help with that, please let me know
