### ISSUE TITLE
Operators: advanced behavior

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#470]
https://github.com/winglang/wing/blob/main/docs/04-reference/winglang-spec.md#63-operators

Missing the following functionality:
- [x] Floor Division `\`
- [x] Power `^`
- [x] Equality https://github.com/monadahq/winglang-spec/blob/rev1.3/README.md#636-equality

**Comment by mortax** [comment]
ah ha. so this actually explains why using floor division (or exponents) don't compile:

```
$ cat wing.w         
let floor = 10 \ 5;

print("${floor}");
$ wing compile wing.w
Compilation failed with 2 errors
Error at wing.w:1:16 | Unknown parser error.
Error at wing.w:1:16 | Unknown parser error.
{1} $ 
```

is there an ETA when floor division and exponent support will exist? it was confusing since they are [documented](https://docs.winglang.io/reference/spec#632-logical-operators).

**Comment by staycoolcall911** [comment]
Hi @mortax, thank you for your question.

Wing is still in alpha. The [language spec](https://docs.winglang.io/reference/spec) defines our beta, where Wing could be used to build some real world apps.
You can see the progress on our spec implementation and the roadmap [here](https://github.com/orgs/winglang/projects/1/views/1).
I'll also frankly add that as an early alpha project, we still don't have an ETA for our beta.

I'm actually going to speak about that and other aspects of how-we-work on Wing today on our Twitch show, "The Wingly Update Name TBD".
Click [here](https://t.winglang.io/wingly02) on Sunday Jan 8th, 1:30pm ET to view the show and ask us questions live!

**Comment by mortax** [comment]
perfect. that answers all of my current questions. i'll watch the roadmap and have another look once the aspects i need are implemented. cheers!

**Comment by staycoolcall911** [comment]
Both operators were implemented (thanks @flyingImer) and equality is detailed in a different issue. Closing this issue.
