### ISSUE TITLE
Console error links not working

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#4716]
### I tried this:

```
bring cloud;
let bucket = new cloud.Bucket()
```

### This happened:

<img width="866" alt="image" src="https://github.com/winglang/wing/assets/5547636/e3b7637e-9fb8-4ca5-a51e-1083210987b6">

### I expected this:

The file path 
`Users/polamoros/Projects/WingCloud/wing/apps/wing-console/console/app/demo/main.w:4:32`

to be a clickable link

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
fixed
