### ISSUE TITLE
Monitor fly.io status

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#4721]
### Feature Spec

We need to monitor fly.io status and send alerts on downtime

### Use Cases

we are deploying our playground / learn / wing.cloud on fly.io machines.
we need to make sure we are aware of any downtime or issues with the fly.io service

### Component

Wing Console, Playground, Other

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by skyrpex** [comment]
We can subscribe using https://status.flyio.net/. They can send messages to a Slack channel, but they also support a webhook URL

**Comment by ainvoner** [comment]
duplication of https://github.com/winglang/wing.cloud/issues/387
