### ISSUE TITLE
an excessive await is added when jsifying macro 

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#4727]
### I tried this:

checked out to this branch: `revitalb/array-at-fix`
in this branch, Revital fixed the macro `array.at` to throw an error in the case of invalid input
run `pnpm wing test examples/tests/sdk_tests/std/string.test.w --no-clean`

### This happened:

the following error appears: 
```
fail ┌ string.test.wsim » root/env8/test:split()     
     │ Error: Failed to bundle function: Error: Build failed with 1 error:
     │ examples/tests/sdk_tests/std/target/test/string.test.wsim/.wing/inflight.$Closure9-1.js:10:274: ERROR: "await" can only be used inside an "async" function
     │     at ....
```
this code:
```
test "split()" {
  assert("hello;wing".split(";").at(0) == "hello");
....
}
```
is jsified wrongly to 
```
      {((cond) => {if (!cond) throw new Error("assertion failed: \"hello;wing\".split(\";\").at(0) == \"hello\"")})((((a,b) => { try { return require('assert').deepStrictEqual(a,b) === undefined; } catch { return false; } })(((obj, args) => { if (args[0] < 0 || args[0] >= (await "hello;wing".split(";")).length) throw new Error("Index out of bounds"); return obj[args[0]]; })((await "hello;wing".split(";")), [0]),"hello")))};
```

### I expected this:

To pass with no errors.

The await is coming from here:
https://github.com/winglang/wing/blob/main/libs/wingc/src/jsify.rs#L421-L424

(verified by removing it- and the issue resolved)

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
Closed by #4704
