### ISSUE TITLE
Typo error and grammatical error in contributing.md

### ISSUE THREAD

**Issue by HimanshuMahto** [winglang/wing#4728]
### Feature Spec

Grammatical error in contributing.md

### Use Cases

Error

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by HimanshuMahto** [comment]
@subh-cs please review the PR generated #4726 .

**Comment by staycoolcall911** [comment]
Closed in #4726
For next time: there's no need to create an issue for a minor change in docs, especially if you already created the PR with the fix
