### ISSUE TITLE
Cannot inspect test function in Wing Console

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#4730]
### I tried this:

I tried clicking "Show tests", and then clicking on one of the Function nodes (the ones with the lightning icon)

https://github.com/winglang/wing/assets/5008987/f4d30d92-5869-4977-b369-3dc3b1760125

### This happened:

The UI automatically takes me back to the parent resource

### I expected this:

It stays on the resource I clicked on.

I also encountered this bug in the Wing playground (https://www.winglang.io/play/).

### Component

Wing Console, Playground

### Wing Version

0.41.39

### Node.js Version

18.14.1

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
fixed nodes selection
