### ISSUE TITLE
Function Types: independent phase functions

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#474]
https://github.com/winglang/wing/blob/main/docs/04-reference/winglang-spec.md#113-function-types

We should add support for functions that can run both preflight and inflight. Phase independent closure literal is `=>` (where for inflight it is `~>` and for preflight it is `->`).

**Comment by Chriscbr** [comment]
Duplicate of #435 (I think one of the issues was just meant to be about the syntax vs the feature design itself, but it makes sense to group them together for now)
