### ISSUE TITLE
token replace doesn't actually replace in inflight

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#4749]
### I tried this:

```ts
bring cloud;

let api = new cloud.Api();

test "main" {  
  let withHttps = api.url.replace("http", "https");
  assert(withHttps.contains("https"));
}
```

```sh
wing test main.test.w
```

### This happened:

test failed

### I expected this:

test to pass

### Component

Compiler

### Wing Version

0.41.42

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skyrpex** [comment]
Related https://github.com/winglang/wing/issues/4688
