### ISSUE TITLE
Pending Tests

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#4761]
### Feature Spec

Wing allows tests to be marked as pending / not implemented yet and reports them. 

### Use Cases

This increases the visibility of yet to be implemented / fixed tests when running `wing test`.

### Component

CLI

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by tsuf239** [comment]
added here: https://github.com/winglang/wing/pull/4602
