### ISSUE TITLE
Add more assertions to the expect module

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#4785]
### Feature Spec

More capabilities for the expect module are making it easier to express test expectations for wing applications.

- `expect.toThrow` / `expect.doesNotThrow` // functions
- `expect.contains` / `expect.doesNotContain` // array, set, string, range
- `expect.match` / `expect.doesNotMatch` // string
- `expect.fail("message")` // always fails
- `expect.ok(condition[, "message"])`

Follow up for https://github.com/winglang/wing/pull/3976

### Use Cases

testing capabilites which are not expressable right now but pretty standard in other testing frameworks 

one use case from examples:

```
assert(response.body?.contains(expected) == true);
```

### Implementation Notes

So far the `expect` module is mirroring https://nodejs.org/api/assert.html - this will still be possible for `throw` and `match`. However, `includes` is not supported there. So this needs to be either implemented manually or we'll need to reach for another library.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by staycoolcall911** [comment]
Added `fail` and `ok` from #4789

**Comment by revitalbarletz** [comment]
Srinu Madhav is trying to look at this one.

**Comment by srinumadhavv** [comment]
Hey @skorfmann  as far as my understanding is this correct ?
```
expect.toThrow -> (fn: () => void, expected: string)  should accept the parameters and throws the expected error 
expect.doesNotThrow ->  doesNotThrow(fn: () => void) should accept the parameters and doesn't throw error
expect.match // string -> match(actual: string, expected: RegExp)  should accept the parameters and check if the string matches regex expression 
expect.doesNotMatch -> doesNotMatch(actual: string, expected: RegExp) should accept the parameters and check if the string doesn't match regex expression 
```
and also need some clarification on these methods 
```
expect.contains / expect.doesNotContain // array, set, string, range
expect.ok(condition[, "message"])
```

**Comment by staycoolcall911** [comment]
Hi @srinumadhavv you seem to be correct. 
If you have doubts stick to Node's implementation, for example: https://www.geeksforgeeks.org/node-js-assert-throws-function/

In a similar manner `expect.contains` should succeed if the first argument is contained in the container type passed as the second argument: 
```ts
let a = [1, 2];
expect.contains(1, a); //succeeds
expect.contains(8, a); //fails
```

And also:
```ts
expect.ok(3>2, "this succeeds");
expect.ok(2>3, "this fails");
```

**Comment by srinumadhavv** [comment]
Hi @staycoolcall911 , and `contains` should work for  `array, set, string` , and also there was `range` thats mentioned , whats `range` by the way ?

**Comment by staycoolcall911** [comment]
We don't have a `range` type in Winglang yet, so you can drop the requirement to support `range`.

>and for string are we expecting a string contains a substring

Yes, let's support string contains as well 👆 
>set should be similar to array

Yes 👆
>and is it only about array or set containing an element or array contains a sub array

First level of depth only - this is not a graph crawl method

**Comment by srinumadhavv** [comment]
@staycoolcall911  I have added a pr for this https://github.com/winglang/wing/pull/6450
