### ISSUE TITLE
str implicitly converts to Json

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#4793]
### I tried this:

```js
let x = "{\"name\": \"Alice\"}";

struct Person {
  name: str;
}

let parsed = Person.fromJson(x);
```

### This happened:

Runtime error

```
ERROR: unable to parse Person:
- instance is not of a type(s) object

target/from-json.test.wsim.708157.tmp/.wing/preflight.js:11
       const Person = $stdlib.std.Struct._createJsonSchema({id:"/Person",type:"object",properties:{name:{type:"string"},},required:["name",]});
       const x = "{\"name\": \"Alice\"}";
>>     const parsed = ((json, validateOptions) => (Person._fromJson(json, validateOptions)))(x);
     }
   }
```

### I expected this:

I might have expected to get a compile time error saying that `x` is a `str`, not `Json`.

### Is there a workaround?

Use `Json.parse`:

```js
let parsed = Person.fromJson(Json.parse(x));
```

### Component

SDK

### Wing Version

0.41.44

### Node.js Version

18.14.1

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
I don't think it is a problem, but I do agree that implicit conversion is confusing in many cases. 


```ts
bring expect;
let x = "{\"name\":\"Alice\"}";
let j: Json = x;

test "x is a str Json Value" {
 expect.equal(j, Json "{\"name\":\"Alice\"}");
}

test "x is a a parsed Json" {
 expect.equal(j, Json.parse("{\"name\":\"Alice\"}"));
}
```
[playground](https://www.winglang.io/play/?code=YgByAGkAbgBnACAAZQB4AHAAZQBjAHQAOwAKAGwAZQB0ACAAeAAgAD0AIAAiAHsAXAAiAG4AYQBtAGUAXAAiADoAXAAiAEEAbABpAGMAZQBcACIAfQAiADsACgBsAGUAdAAgAGoAOgAgAEoAcwBvAG4AIAA9ACAAeAA7AAoACgB0AGUAcwB0ACAAIgB4ACAAaQBzACAAYQAgAHMAdAByACAASgBzAG8AbgAgAFYAYQBsAHUAZQAiACAAewAKACAAZQB4AHAAZQBjAHQALgBlAHEAdQBhAGwAKABqACwAIABKAHMAbwBuACAAIgB7AFwAIgBuAGEAbQBlAFwAIgA6AFwAIgBBAGwAaQBjAGUAXAAiAH0AIgApADsACgB9AAoACgAKAHQAZQBzAHQAIAAiAHgAIABpAHMAIABhACAAYQAgAHAAYQByAHMAZQBkACAASgBzAG8AbgAiACAAewAKACAAZQB4AHAAZQBjAHQALgBlAHEAdQBhAGwAKABqACwAIABKAHMAbwBuAC4AcABhAHIAcwBlACgAIgB7AFwAIgBuAGEAbQBlAFwAIgA6AFwAIgBBAGwAaQBjAGUAXAAiAH0AIgApACkAOwAKAH0ACgAKAA%3D%3D)

<img width="431" alt="image" src="https://github.com/winglang/wing/assets/1727147/1fa2a7b9-8a92-4ab1-a95c-49fd2d5e3fbc">

**Comment by ekeren** [comment]
I would love to have a compiler experimental flag that doesn't allow implicit conversion in the language so I can "feel" what it is like to not have this functionality, how often I use implicit conversions and enjoy it without knowing

**Comment by MarkMcCulloh** [comment]
I like the implicit casting because it's safe and constant with what is happening (the data is just being reinterpreted). I do see how it's confusing though.
What if we just get rid of the `fromJson` methods from all types (since the same confusion came from `str.fromJson`) and work on supporting `.as<TType>` for json instances instead? I feel like it does a better job of emphasizing that no "parsing" is happening.

**Comment by eladb** [comment]
I think this is the same issue raised by @eladcon https://github.com/winglang/wing/issues/4771

**Comment by staycoolcall911** [comment]
> I think this is the same issue raised by @eladcon #4771

I agree. Closing as a duplicate
