### ISSUE TITLE
struct with only optional fields must be constructed

### ISSUE THREAD

**Issue by eladcon** [winglang/wing#4814]
### I tried this:

```js
struct A {
  x: str?;
}

class C {
  pub func(a: A) {

  }
}

new C().func();
```

### This happened:

Compiler expects the struct argument to be constructed (with `{}`) although all fields are optional

```
error: Expected 1 positional argument(s) or named arguments for the last parameter but got 0
   --> main.w:11:1
   |
11 | new C().func();
   | ^^^^^^^^^^^^^^ Expected 1 positional argument(s) or named arguments for the last parameter but got 0
```

### I expected this:

to compile

### Is there a workaround?

```js
new C().func({});
```

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
This also applies to constructors:

```
struct BucketProps {
  public: bool?;
}

class Bucket {
  public: bool;
  new(props: BucketProps) {
    this.public = props.public ?? true;
  }
}

new Bucket();
```

**Comment by eladb** [comment]
Yes, let's fix this!

**Comment by tsuf239** [comment]
looks like it already working (maybe it's the spread operator?)
checked both compiling form a file and on the playground
https://www.winglang.io/play/?code=cwB0AHIAdQBjAHQAIABBACAAewAKACAAIAB4ADoAIABzAHQAcgA%2FADsACgB9AAoACgBjAGwAYQBzAHMAIABDACAAewAKACAAIABwAHUAYgAgAGYAdQBuAGMAKABhADoAIABBACkAIAB7AAoACgAgACAAfQAKAH0ACgAKAG4AZQB3ACAAQwAoACkALgBmAHUAbgBjACgAKQA7AAoACgBzAHQAcgB1AGMAdAAgAEIAdQBjAGsAZQB0AFAAcgBvAHAAcwAgAHsACgAgACAAcAB1AGIAbABpAGMAOgAgAGIAbwBvAGwAPwA7AAoAfQAKAAoAYwBsAGEAcwBzACAAQgB1AGMAawBlAHQAIAB7AAoAIAAgAHAAdQBiAGwAaQBjADoAIABiAG8AbwBsADsACgAgACAAbgBlAHcAKABwAHIAbwBwAHMAOgAgAEIAdQBjAGsAZQB0AFAAcgBvAHAAcwApACAAewAKACAAIAAgACAAdABoAGkAcwAuAHAAdQBiAGwAaQBjACAAPQAgAHAAcgBvAHAAcwAuAHAAdQBiAGwAaQBjACAAPwA%2FACAAdAByAHUAZQA7AAoAIAAgAH0ACgB9AAoACgBuAGUAdwAgAEIAdQBjAGsAZQB0ACgAKQA7AA%3D%3D
