### ISSUE TITLE
Add HTTP request methods `CONNECT` and `TRACE` to `http` submodule

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#4818]
### Feature Spec

The Wing SDK `http` submodule now supports [CONNECT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT) and [TRACE](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/TRACE) among its HTTP request methods.

### Use Cases

Support all HTTP request methods in Wing standard library.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by DoronV** [comment]
@BITOCTA are you working on this? If yes, I'd like to help out (if that's okay).

**Comment by DoronV** [comment]
@garysassano @staycoolcall911 is it okay if I start on this (because it looks like @BITOCTA isn't responding)

**Comment by BITOCTA** [comment]
@DoronV  you could take it, I'm not working on it.

**Comment by staycoolcall911** [comment]
Thank you @BITOCTA 🙏 

@DoronV - I assigned you on this issue - please let us know if you have any questions (either here or on Discord)

**Comment by DoronV** [comment]
@staycoolcall911 should I close this/mark it done?

**Comment by staycoolcall911** [comment]
Yes please @DoronV, thanks
We usually add "Fixes #4818" in the PR description and then github automatically closes the issue once the PR has merged.

**Comment by DoronV** [comment]
Alright, I'll remember that for next time.
