### ISSUE TITLE
Implicit cast from structs to `Json`

### ISSUE THREAD

**Issue by eladb** [winglang/wing#4845]
### Feature Spec

If a struct is serializable (i.e. has only fields of serializable types), then it should be possible to implicitly cast it to `Json`, similarly to how all other serializable primitive types are implicitly castable to `Json`:

```js
struct FooBar {
  a: num;
  b: str;
}

let jang: Json = FooBar { a: 12, b: "hello" };
```

### Use Cases

```js
struct User { ... };

let myUser: User = ...
bucket.putJson("user.json", myUser);
```

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by Chriscbr** [comment]
It looks like this is working today - [link to playground](https://www.winglang.io/play/?code=YgByAGkAbgBnACAAYwBsAG8AdQBkADsACgAKAHMAdAByAHUAYwB0ACAARgBvAG8AQgBhAHIAIAB7AAoAIAAgAGEAOgAgAG4AdQBtADsACgAgACAAYgA6ACAAcwB0AHIAOwAKAH0ACgAKAGwAZQB0ACAAagBhAG4AZwA6ACAARgBvAG8AQgBhAHIAIAA9ACAAewAgAGEAOgAgADEALAAgAGIAOgAgACIAaABlAGwAbABvACIAIAB9ADsACgAKAGwAZQB0ACAAYgB1AGMAawBlAHQAIAA9ACAAbgBlAHcAIABjAGwAbwB1AGQALgBCAHUAYwBrAGUAdAAoACkAOwAKAAoAdABlAHMAdAAgACIAcAB1AHQAIgAgAHsACgAgACAAYgB1AGMAawBlAHQALgBwAHUAdABKAHMAbwBuACgAIgB1AHMAZQByAC4AagBzAG8AbgAiACwAIABqAGEAbgBnACkAOwAKAH0A)
