### ISSUE TITLE
Improve API of `function.invoke()`

### ISSUE THREAD

**Issue by eladb** [winglang/wing#4847]
### Feature Spec

The signature of:

```js
function.invoke(payload: str): void
```

Should change to:

```js
function.invoke(payload: Json?): Json?
```

### Use Cases

* `Json` offers the ability to pass in and out structured data.
* Optionality improves ergonomics. If the inflight handler doesn't call `return` the value is `nil`.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by Chriscbr** [comment]
Done
