### ISSUE TITLE
No error when missing `super()` call

### ISSUE THREAD

**Issue by eladb** [winglang/wing#4851]
### I tried this:

```js

class Base {
  init(hello: num) {}
}

class Derived extends Base {
  init() {
    // no super() call
  }
}

new Derived();
```

### This happened:

No errors

### I expected this:

A compiler error telling me that I don't have a `super(num)` call in my derived class.

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
Duplicate of #4277
