### ISSUE TITLE
Docsite readability

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#4877]
I was browsing the Winglang docsite and it the text felt less readable compared to other documentation websites, mostly in dark mode IMO. Some comparisons taken on my phone:

| | | |
| - | - | - |
| ![IMG_4265](https://github.com/winglang/wing/assets/5008987/ef3e4b0c-8b21-431b-89f5-42d978dc3813)  | ![IMG_4267](https://github.com/winglang/wing/assets/5008987/df16f1a7-19ff-4669-966c-f999c320639d)  | ![IMG_4266](https://github.com/winglang/wing/assets/5008987/59011601-6bf3-4743-bc28-2187ab58dd6d) |
| ![IMG_4268](https://github.com/winglang/wing/assets/5008987/455ddb80-4f5f-4767-8cad-05f5fb017fb2) | ![IMG_4270](https://github.com/winglang/wing/assets/5008987/922faf78-a6f3-401d-96e8-1204eb6acbd5) | ![IMG_4269](https://github.com/winglang/wing/assets/5008987/af990d84-a99b-45e7-91b9-cff8d6d96415) |

**Comment by eladb** [comment]
I agree. @amielpb can you take a look

**Comment by amielpb** [comment]
![image](https://github.com/winglang/wing/assets/95175829/f0ed1616-8aea-44d9-93c0-e8b8f68db9c5)

Something strange is going on! The image on the left is Chris's screenshot, and the image on the right is what the docsite looks to me. Is there any reason the docsite would use a different font on your phone?

**Comment by Chriscbr** [comment]
It looks like it could be a difference in how the browsers render these fonts - I was able to reproduce the same difference with Chrome and Safari on my desktop:

<img width="1153" alt="Screenshot 2023-11-10 at 2 50 13 PM" src="https://github.com/winglang/wing/assets/5008987/3b81d786-7a64-405f-8a69-84a63a31e4a3">

Maybe @skyrpex @polamoros would have suggestions on the best ways to handle this?

**Comment by skyrpex** [comment]
I'll check it out Monday

**Comment by skyrpex** [comment]
Not 100% sure but it may be due to including only the `General Sans` font with weight `400`. We should either include more font weights, or use the variable font version.

I'll prepare a PR to use the variable version of `General Sans`.

**Comment by skyrpex** [comment]
@Chriscbr can you check again? I think it looks identical between browsers now.

**Comment by Chriscbr** [comment]
Thanks @skyrpex, yeah it's the same in both browsers now.

I noticed that words specifically marked bold look very similar to the regular text, and some paragraphs are not the same font weight. Maybe it's a bug? I've added some screenshots

![IMG_4337](https://github.com/winglang/wing/assets/5008987/9df6fc08-333a-47a9-acb3-2bcbfedbe3a1)

Here the words "address" and "path" are meant to be bold I think:
![IMG_4338](https://github.com/winglang/wing/assets/5008987/e1750fd5-5a14-4506-86ad-3fc45dd36a87)

**Comment by skyrpex** [comment]
@Chriscbr 

The problem here is the resulting HTML from the markdown. All paragraphs (`<p>` elements) are configured with weight 600, while bold words (`<strong>` elements`) are configured with weight 700.

The font is correct now, but we may want to alter the weights of some elements such as `<p>`'s.

**Comment by skyrpex** [comment]
I think this makes more sense:

<img width="743" alt="image" src="https://github.com/winglang/wing/assets/1077520/ed11c806-feba-4adb-b149-2c06554df10f">

Paragraphs are 400, strong are 600.

**Comment by skyrpex** [comment]
Refer to https://github.com/winglang/wing/issues/4943 for the weird font weights.
