### ISSUE TITLE
sdk: expose api domain

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#4887]
### Feature Spec

besides from `api.url` the Wing SDK Api resource provides the domain part of the url easily accessible with `api.domain` 

url: `https://${this.api.id}.execute-api.${this.region}.amazonaws.com/${this.stage.stageName}`
domain: `${this.api.id}.execute-api.${this.region}.amazonaws.com`

### Use Cases

e.g. when using this in cloudfront just the domain is needed

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by Chriscbr** [comment]
@skorfmann Is it possible to get the domain using the built-in `util.parseUrl()` API?

**Comment by staycoolcall911** [comment]
@Chriscbr, @skorfmann - Chris is right. You can use `http.parseUrl()` to get the domain. Here's the code snippet:
```ts (wing)
bring http;
bring cloud;

let api = new cloud.Api();

api.get("/bla", inflight (req) => {
  return {
    status: 200,
  };
});

test "print domain" {
  log(http.parseUrl(api.url).hostname);
}
```
Closing this issue for now.
