### ISSUE TITLE
Story: Using terraform resources in Wing code

### ISSUE THREAD

**Issue by eladb** [winglang/wing#489]
### Summary

Seamlessly use arbitrary Terraform resources in Wing

### Feature Spec

You can use any resource from the vast [Terraform Registry] in your Wing applications.

[Terraform Registry]: https://registry.terraform.io/

Let's walk through an example. We will use the pre-built CDKTF provider for GitHub called [@cdktf/provider-github](https://www.npmjs.com/package/@cdktf/provider-github).

First, let's install the provider module:

```sh
$ npm i @cdktf/provider-github
```

Now, `bring` this into your code and define a `Repository` resource:

```js
bring cloud;
bring git;
bring fs;
bring "@cdktf/provider-github" as github;

let filename = "message.txt";
let repo = new github.repository.Repository(
  name: "my-repo",
  description: "My new github repository",
  visibility: "public",
);

let update_message = (req: cloud.ApiRequest, res: cloud.ApiResponse) => {
  let repo = new git.Repository(fs.mkdtemp());
  repo.clone(repo.git_clone_url, depth: 0);
  fs.File.write(fs.Path.join(repo.dir, filename), req.body));
  repo.commit("update message", add: true);
  repo.push(remote: "origin", branch: "main");
};

let api = cloud.Api();
api.on_put("/messages", update_message);
```

This is all dandy. If we compile our code to a Terraform target (such as `tfaws`), this should Just Work™️:

```sh
$ wing compile -t tf-aws my-repo.w
```

The Terraform output will includes:

```hcl
resource "github_repository" "Repository" {
  name        = "example"
  description = "An awesome example"
  visibility  = "public"
}
```

But what happens when we try to compile this to the `sim` target?

```sh
$ wing compile -t sim my-repo.w
ERROR: Unable to resolve "sim:@cdktf/provider-github.repository.Repository".
Add a "--resolve sim:@cdktf/provider-github.repository.Repository=./factory.ts"
```

> **Implementation note**: we will need the simulator synthesizer to proactively look for `TerraformResource` constructs in the tree in order to produce this error. Impure albeit pragmatic (good catch @Chriscbr).

This error indicates that I need to inject a `sim` backend for this resource through a TypeScript factory:

OK, let's create one:

```ts
// TO BE CONTINUNED
```

[Terraform ecosystem]: https://registry.terraform.io/
[`cdktf get`]: https://developer.hashicorp.com/terraform/cdktf/cli-reference/commands#get
[GitHub terraform provider]: https://registry.terraform.io/providers/integrations/github

### Use Cases

P0 is to simply support terraform resources when compiling to terraform (perhaps this is already supported? Worth adding a test/example...

Next, we should figure out what happens when we set the target to `sim`. I suspect that this will simply cause the `TerraformResource` to emit an error saying it couldn't find the `TerraformStack` scope, isn't it?

So now, what do we do?

Users may want different solutions to this situation:

1. Be able to supply a simulated version of the resource. That's not trivial at the moment because the terraform construct is not a polycon, which means that we don't get to inject a different object upon construction. I am wondering if the Wing compiler can help here by basically shimming every construct with a polycon (some kind of implicit polyconization).
2. Hybrid output - both sim and terraform. To me this seems like a very nice general purpose default solution. Meaning - if I add a terraform resource that is not supported by `sim`, my output will include a terraform output which the Wing Console (??) will be able to apply when it's starting and the local resources will be wired into the cloud resources. This is a holy grail worth perusing because its the reality of the cloud...
3. Treat as external - in this case we treat the unsupported sim resource as external to the application (meaning - it is already provisioned) and all we need to do is to give the user a way to supply the relevant attributes that will allow inflight code to reach this external resource.

**Comment by eladb** [comment]
@Chriscbr I believe this is done, right?

**Comment by Chriscbr** [comment]
Yep, I think the rest of the use cases (like how to override a terraform resource with a simulator implementation) is addressed by https://github.com/winglang/wing/issues/1365

**Comment by mingfang** [comment]
You can’t just any Terraform provider. 
You must use provides that have a CDK binding. 
Perhaps this obvious to others but the description above wasn’t clear about this.
