### ISSUE TITLE
Referencing API url in other handlers will cause cyclic dependency

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#4906]
### I tried this:

For a scenario like the following

```
bring cloud;
bring http;

let api = new cloud.Api();
let queue = new cloud.Queue();

api.get("/api/v1/xxx", inflight (req) => {    
    return {
        body: "hello world",
        status: 200
    };
});

api.get("/api/v2/xxx", inflight (req) => {    
    return {
        body: "hello world",
        status: 200
    };
});

queue.setConsumer(inflight (msg) => {
    http.get("${api.url}/api/v2/xxx");
});
```

[see in playground](https://www.winglang.io/play/?code=YgByAGkAbgBnACAAYwBsAG8AdQBkADsACgBiAHIAaQBuAGcAIABoAHQAdABwADsACgAKAGwAZQB0ACAAYQBwAGkAIAA9ACAAbgBlAHcAIABjAGwAbwB1AGQALgBBAHAAaQAoACkAOwAKAGwAZQB0ACAAcQB1AGUAdQBlACAAPQAgAG4AZQB3ACAAYwBsAG8AdQBkAC4AUQB1AGUAdQBlACgAKQA7AAoACgBhAHAAaQAuAGcAZQB0ACgAIgAvAGEAcABpAC8AdgAxAC8AeAB4AHgAIgAsACAAaQBuAGYAbABpAGcAaAB0ACAAKAByAGUAcQApACAAPQA%2BACAAewAgACAAIAAgAAoAIAAgACAAIAByAGUAdAB1AHIAbgAgAHsACgAgACAAIAAgACAAIAAgACAAYgBvAGQAeQA6ACAAIgBoAGUAbABsAG8AIAB3AG8AcgBsAGQAIgAsAAoAIAAgACAAIAAgACAAIAAgAHMAdABhAHQAdQBzADoAIAAyADAAMAAKACAAIAAgACAAfQA7AAoAfQApADsACgAKAGEAcABpAC4AZwBlAHQAKAAiAC8AYQBwAGkALwB2ADIALwB4AHgAeAAiACwAIABpAG4AZgBsAGkAZwBoAHQAIAAoAHIAZQBxACkAIAA9AD4AIAB7ACAAIAAgACAACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAewAKACAAIAAgACAAIAAgACAAIABiAG8AZAB5ADoAIAAiAGgAZQBsAGwAbwAgAHcAbwByAGwAZAAiACwACgAgACAAIAAgACAAIAAgACAAcwB0AGEAdAB1AHMAOgAgADIAMAAwAAoAIAAgACAAIAB9ADsACgB9ACkAOwAKAAoAcQB1AGUAdQBlAC4AcwBlAHQAQwBvAG4AcwB1AG0AZQByACgAaQBuAGYAbABpAGcAaAB0ACAAKABtAHMAZwApACAAPQA%2BACAAewAKACAAIAAgACAAaAB0AHQAcAAuAGcAZQB0ACgAIgAkAHsAYQBwAGkALgB1AHIAbAB9AC8AYQBwAGkALwB2ADIALwB4AHgAeAAiACkAOwAKAH0AKQA7AA%3D%3D)

the preflight value of the api gets referenced in the inflight consumer of the queue. This is slimmed down example extracted from a real application. 

### This happened:

Trying to remove one the handlers causes issues for the `tf-aws` target, for an iterative deployment with existing state. Terraform generates a cyclic dependency as described here https://github.com/hashicorp/terraform-provider-aws/issues/11344#issuecomment-1521831630

### I expected this:

Being able to deploy the api without manual interaction 

### Is there a workaround?

see https://github.com/hashicorp/terraform-provider-aws/issues/11344#issuecomment-1521831630

### Component

SDK

### Wing Version

0.45

### Node.js Version

18.17

### Platform(s)

MacOS

### Anything else?

The value lifting for inflight handlers is done via env, e.g. for the queue consumer above that's like

```
  "environment": {
    "variables": {
      "WING_FUNCTION_NAME": "cloud-Queue-SetConsumer-3fc9280c-c8180aab",
      "WING_TARGET": "tf-aws",
      "WING_TOKEN_HTTPS_TFTOKEN_TOKEN_8_EXECUTE_API_TFTOKEN_TOKEN_1_AMAZONAWS_COM_TFTOKEN_TOKEN_9": "${jsonencode(\"https://${aws_api_gateway_rest_api.cloudApi_api_2B334D75.id}.execute-api.${data.aws_region.Region.name}.amazonaws.com/${aws_api_gateway_stage.cloudApi_api_stage_BBB283E4.stage_name}\")}"
    }
  },
```

And this beautifully named env `WING_TOKEN_HTTPS_TFTOKEN_TOKEN_8_EXECUTE_API_TFTOKEN_TOKEN_1_AMAZONAWS_COM_TFTOKEN_TOKEN_9` is the offender in this case. 

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skorfmann** [comment]
On thing I thought about, perhaps it would be worthwhile thinking about other ways of value lifting. Something based on SSM parameters for example. Values could be written to an SSM key path based on some convention. When these values are only read at the inflight stage, this would effectively decouple the resources in the preflight stage. 

As a first step, doing this manually would be good enough already. Perhaps this could helpful here as well https://github.com/winglang/wing/issues/2726

**Comment by Chriscbr** [comment]
Was this fixed by https://github.com/winglang/wing/pull/4879? The example seems to compile in the playground now

**Comment by skorfmann** [comment]
No, not really. It's essentially this case described over here https://github.com/hashicorp/terraform-provider-aws/issues/11344#issuecomment-1521831630

Just built a simple Parameter (along the lines of https://github.com/winglang/wing/issues/2726) resource internally to decouple the API url from other consumers, which then really fixes it

**Comment by ekeren** [comment]
> On thing I thought about, perhaps it would be worthwhile thinking about other ways of value lifting. Something based on SSM parameters for example. Values could be written to an SSM key path based on some convention. When these values are only read at the inflight stage, this would effectively decouple the resources in the preflight stage.

> As a first step, doing this manually would be good enough already. Perhaps this could helpful here as well https://github.com/winglang/wing/issues/2726

@skorfmann this is only relevant for tokens, right?

**Comment by Chriscbr** [comment]
Closing as I believe this was fixed by https://github.com/winglang/wing/pull/5637. Please feel free to re-open if I'm mistaken.
