### ISSUE TITLE
Bang (!) operator

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#4923]
### Feature Spec

The bang operator can be used to tersely unwrap an optional value, throwing an error if it is nil. This is notably _different_ from TypeScript's bang operator (`!`), which silently allows code to continue running if is undefined or null.

For example:

```js
struct Person {
  name: str;
  age: num;
}

let person = Person.tryParseJson(req.body)!;
log("${person.name} is ${person.age} years old.");
```

In the example above, `Person.tryParseJson` returns `Person?` because parsing the string as Json and converting the Json to Person may fail. If it fails, the "!" indicates that the code will automatically throw an error.

`foo!` is syntax sugar for `foo ?? throws "Unexpected nil"` (tracking issue: https://github.com/winglang/wing/issues/3858).

### Use Cases

See example above

### Component

Language Design, Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by eladb** [comment]
I think the example should use `tryParseJson()` no?

**Comment by Chriscbr** [comment]
Fixed - thanks

**Comment by meirdev** [comment]
I think I can implement it, is it ok to send PR?

**Comment by eladb** [comment]
This is implemented, no?

**Comment by Chriscbr** [comment]
I believe so - closing
