### ISSUE TITLE
No enforcement of `super()` call

### ISSUE THREAD

**Issue by eladb** [winglang/wing#4924]
### I tried this:

```js
class Base { }

class Derived extends Base {
  new() {
    // <- no super()
  }
}

new Derived();

class Base2 {
  new(x: str) {}
}

class Derived2 extends Base2 {
  new() {
    // <- no super(str) ccall
  }
}
```

### This happened:

No errors

### I expected this:

I would have expected errors to enforce the call to `super()` and `super(str)` from the derived classes.

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Duplicates #4277
