### ISSUE TITLE
There's no way to configure Secondary Indexes in DynamoDB tables

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#4928]
### I tried this:

I tried using Secondary Indexes in DynamoDB tables.

### This happened:

There's no way to do so.

### I expected this:

I expected to be able to configure GSIs: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_dynamodb-readme.html#secondary-indexes.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skyrpex** [comment]
@staycoolcall911 I created this issue in the name of a Slack user but I guess it doesn't hurt to add the dogfood label anyway :)

**Comment by staycoolcall911** [comment]
@skyrpex - got it. I'll take off the label.

**Comment by thoroc** [comment]
Is that still an issue? I am seeing the prop for the GSI: https://github.com/winglang/winglibs/blob/23d298a87242f793eaa2203f3e39fe1c3048dcc5/dynamodb/dynamodb-types.w#L180

Or am I misunderstanding the issue?

**Comment by staycoolcall911** [comment]
Thanks @thoroc - seems to me this was indeed implemented a few months ago. Closing.
