### ISSUE TITLE
`ex.DynamodbTable` is missing DynamoDB Streams

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#4949]
### I tried this:

I tried using DynamoDB Streams with the `ex.DynamoDBTable`

### This happened:

It wasn't possible since they aren't implemented

### I expected this:

To be able to run code like the following:

```ts
bring ex;

let users = new ex.DynamodbTable();

user.onStream(inflight (event) => {
  log("${event.records.length} events changed");
});
```

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
This will make for a better DX, but is not a must for wing cloud 1.0

**Comment by marciocadev** [comment]
I don't think it's possible to implement DynamoDB streams in the simulator the way it's currently built.

Currently, the DynamoDBTable uses `amazon/dynamodb-local`, causing the simulator to use a real DynamoDB container. However, DynamoDB streams need to connect to real Amazon resources, such as a Lambda function. The way it's currently done, I don't think it's possible to create streams in the simulator.

One possibility could be for the simulator to cease using Docker and instead create an implementation similar to what was done for `cloud.Table`, essentially a `Map<string, any>`.
Events could then be mapped in a manner similar to what was done for `cloud.Bucket`.

On the other hand, in tf-aws and aws-cdk, it's quite simple.

**Comment by ekeren** [comment]
@marciocadev , I've notice this https://stackoverflow.com/a/42185707

Is it relevant?

**Comment by eladb** [comment]
From the [aws docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.UsageNotes.html) it seems like it is supposed to be supported.

**Comment by skyrpex** [comment]
> I saw this @ekeren
> 
> Creating the Dynamo Stream wouldn't be the problem in the simulator. The issue is that, to consume it, a lambda would have to be used. Currently, the `cloud.Function` in the simulator doesn't create an AWS resource, as the DynamoDB simulator does.
> 
> I don't think it's possible to create the stream in the simulator the way it's currently built

During this weekend, I recreated the DynamoDB Table resource in pure Wing to enable streams for the Simulator (it uses the dynamodb-local docker image, too). In order to fetch the records from the local stream, a long running `cloud.Service` can be used.

My code isn't ready to share just now but maybe I can create a small playground repository with what I have.
