### ISSUE TITLE
Wing Console doesn't respect `node.title`

### ISSUE THREAD

**Issue by eladb** [winglang/wing#4985]
### I tried this:

```js
class Foo {
  new() {
    std.Node.of(this).title = "My Foofoo";
  }
}

new Foo();
```

### This happened:

<img width="284" alt="image" src="https://github.com/winglang/wing/assets/598796/c3f102a0-1a09-4ea9-a5a0-90d1b2a95245">

### I expected this:

The node should say "My Foofoo"

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
fixed
