### ISSUE TITLE
Can't implement a resource that requires external compilation

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#4989]
### I tried this:

Resources such as websites usually require a compilation step that generates the website files. Currently, it's impossible to implement in Wing unless you use the `ex.ReactApp` resource, which is implemented in the SDK and is able to run a CLI command.

Ideally, we should be able to run such a command from any other resource of our choice.

### This happened:

It's impossible to run commands or external JS APIs during preflight.

### I expected this:

I should be able to build my own class (eg, `Vite`) that runs `vite build` during preflight for the `tf-aws` target.

### Is there a workaround?

No.

### Anything else?

Having a `child_process` standard package that allows us doing something like this would be enough to unblock me:

```ts
bring child_process;

// Equivalent to `execSync` in Node:
child_process.exec("pnpm", ["vite", "build"]);
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skyrpex** [comment]
We have more use cases:

- At Wing Cloud, we have to generate a Docker image. We currently generate it as a step previous to the wing compilation. Ideally, we should be able to have a `DockerImage` resource that builds the image during preflight

**Comment by skyrpex** [comment]
It would be interesting to be able to gather the logs of these processes. Also, it'd be interesting if we could parallelize resource creation.

**Comment by eladb** [comment]
i don't see us supporting async calls in preflight in the near future.

you can exec a child process using `spawnSync()` during preflight. we have a plan to support this through something like `util.shell()`, but in the meantime, an extern that runs this is easy to write.

see https://github.com/winglang/winglibs/tree/main/containers for an example of building a docker image during preflight.

i suggest to close for now.

**Comment by skyrpex** [comment]
I didn't know we could run externs in preflight! That solves my issue.
