### ISSUE TITLE
cli: wing test terraform logs are hidden

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#4996]
### I tried this:

running `wing test -t tf-aws main.w --platform s3.backend.js`

### This happened:

```
✔ Compiling main.w to tf-aws...

- terraform init

✖ terraform init

- terraform destroy

Command failed: terraform init

✖ terraform destroy

Command failed: terraform destroy -auto-approve
```

### I expected this:

```
command]/home/runner/work/_temp/6d881f43-a148-4395-bc01-3d1a4470967a/terraform-bin init

Initializing the backend...
Terraform encountered problems during initialisation, including problems
with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│
│ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
│       For verbose messaging see aws.Config.CredentialsChainVerboseErrors
│
│
│
╵

╷
│ Error: Duplicate provider configuration
│
│   on main.tf.json line 92, in provider:
│   92:     "docker": [
│
│ A default (non-aliased) provider configuration for "docker" was already
│ given at main.tf.json:92,15-16. If multiple configurations are required,
│ set the "alias" argument for alternative configurations.
╵
```

### Wing Version

0.47.7

### Node.js Version

18.7

### Platform(s)

Linux

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment]
we need to show the output if there was an error

**Comment by skorfmann** [comment]
Just stumbled upon the [debug](https://www.npmjs.com/package/debug) package which is being [used](https://github.com/winglang/wing/blob/1f575ddddfbe8c75a62aa811b9e65e2e67656337/apps/wing/src/commands/test/test.ts#L17)

Setting `DEBUG=wing:test` or `wing:*` will print the logs. Perhaps this should be default for `wing test`?

**Comment by staycoolcall911** [comment]
Shouldn't be too difficult to print the debug logs Sebastian referred to when there's an error. Setting this as a good-first-issue.

**Comment by tsuf239** [comment]
<img width="515" alt="image" src="https://github.com/winglang/wing/assets/39455181/7a71ad4c-8437-4242-88e7-583ef3e748b2">
It seems to be working (tested a sdk spec test file with an aws region of us-east-10)
is it good enough?

**Comment by staycoolcall911** [comment]
Yes, I think it's helpful, thank you @tsuf239.
I'll go ahead and close this issue - FYI @Chriscbr please reopen if you are after a different DX.
