### ISSUE TITLE
cli: run tests independent of compile

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing#4997]
### Feature Spec

while the `wing test` is highly opinionated in the way tests are executed, the new `wing test-runner` command allows to execute all tests or subset of them within an already compiled target (via `wing compile --include-tests`).

### Use Cases

- make multiple tests executable within a single compiled application (in contrast to the "one env per test" approach in the `test` command)
- fine grained control over the terraform setup and apply / destroy lifecycle 
- compile a single application without the duplication of `wing test`

### Implementation Notes

related to #3168 

### Component

CLI

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by skorfmann** [comment]
could be a workaround for https://github.com/winglang/wing/issues/5015

**Comment by Chriscbr** [comment]
@skorfmann Can you add any missing use cases to this issue instead? I think there's several potential issues that may be interrelated: https://github.com/winglang/wing/issues/4653

Some of the use cases you mentioned, like supporting multiple tests using the same resources, are already mentioned in that issue. The other ones like controlling the terraform lifecycle, or testing without re-compiling I'm not as familiar with so perhaps you can add them as a comment and explain the current pain point (is the issue that compile times / deployments are too slow? or that it's hard to debug failing tests?)

**Comment by skorfmann** [comment]
> fine grained control over the terraform setup and apply / destroy lifecycle

Just have the case where I'd like to perform actions outside of the `wing test` flow, once the `terraform apply` succeeded. In this case I want to perform http requests and perhaps execute a custom script interacting with the deployed resources. 

At the moment I can either run wing tests via `wing test` or compile and deploy manually, to perform actions outside of the scope of wing tests.
