### ISSUE TITLE
missing favicon in doc site

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#5014]
### I tried this:

https://winglang.io/docs

### This happened:

![image](https://github.com/winglang/wing/assets/1727147/4dd6b5cb-876c-4d54-8247-f3d52a4c66fd)

### I expected this:

to see a favicon

### Is there a workaround?

imagine it

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
@amielpb @polamoros can you please handle it?
