### ISSUE TITLE
wrong compiler log if same named method and field exists inside class

### ISSUE THREAD

**Issue by subh-cs** [winglang/wing#5026]
### I tried this:

To reproduce, 
```js
class Car{
  url: str?;
  new() {
    
  }
  pub inflight url(){

  }
}
```
[Playground link](https://www.winglang.io/play?code=YwBsAGEAcwBzACAAQwBhAHIAewAKACAAIAB1AHIAbAA6ACAAcwB0AHIAPwA7AAoAIAAgAG4AZQB3ACgAKQAgAHsACgAgACAAIAAgAAoAIAAgAH0ACgAgACAAcAB1AGIAIABpAG4AZgBsAGkAZwBoAHQAIAB1AHIAbAAoACkAewAKAAoAIAAgAH0ACgB9AA%3D%3D)

### This happened:

This error is occurring along with actual error and everything is red in vs code which is inappropriate. 

```
error: Compiler bug during type-checking ('panicked at libs/wingc/src/type_check.rs:4426:14:
Expected method type to be a function signature'), please report at https://www.winglang.io/contributing/start-here/bugs
  --> wing/main.w:1:1
  |  
1 | / class Car{
2 | |   url: str?;
3 | |   new() {
4 | |     
  . |
8 | |   }
9 | | }
  | \-^ Compiler bug during type-checking ('panicked at libs/wingc/src/type_check.rs:4426:14:
Expected method type to be a function signature'), please report at https://www.winglang.io/contributing/start-here/bugs
```

### I expected this:

The above error is so confusing, and should not exist in these situations. 

### Wing Version

0.48.6

### Node.js Version

18.13.0

### Platform(s)

Linux

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Duplicates #1635

**Comment by staycoolcall911** [comment]
Thanks for reporting @subh-cs! We actually have an issue for that bug already so I closed as duplicate.
