### ISSUE TITLE
The Console freezes if the server is disconnected

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#5092]
### I tried this:

Use `wing it` on an wing application and open the Console tab in the browser. Then, stop the `wing it` command.

### This happened:

After stopping the `wing it` command, the Console browser tab remains frozen.

### I expected this:

A message should open in the Console browser tab static that the server isn't reachable anymore. 

I'd expect it to reconnect if the server started again.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
done
