### ISSUE TITLE
console: blue screen of death doesn't allow me to look at  past run logs

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#5099]
### I tried this:

1. I've written a test with `expect`
2. The test failed,  the logs showed why
3. I started working on the fixing the code
4. While the code is not complete (compilation error) I wanted to check the logs again to see what was the previous run log
5. on the console, I saw the BOD... which blocks the logs

### This happened:

BOD blocks logs

### I expected this:

To see that the application is not compiling but not have the entire screen blocked 

### Is there a workaround?

I fix the code momentarily 

### Wing Version

0.51.1

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
already resolved by @skyrpex in one of his console ui/ux improvements
