### ISSUE TITLE
number of new open console users doesn't make sense 

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#5100]
### I tried this:

Our segment reports number of new users of the console. 
It looks like these are not real users, maybe something in our automation is causing it

### This happened:

NA

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
perhaps Console instances open in wing cloud context

**Comment by ekeren** [comment]
> I don't want this to be a blocker

Right, could be...

**Comment by ainvoner** [comment]
@ekeren which analytics are we talking about here? since we have the "new" Console sign ups events, is this issue still relevant?

**Comment by ekeren** [comment]
https://app.amplitude.com/analytics/monada/chart/bxm8ei89/edit/wb0aw8qt

<img width="1085" alt="image" src="https://github.com/winglang/wing/assets/1727147/c1944b29-c465-4728-8fc1-f02801ff7f7e">

As you can see the numbers didn't add up on Nov and on Feb, but it is looking good now and correlates with what I am seeing in cli_sim_run.

Closing
