### ISSUE TITLE
cloud.Lock

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#5105]
### Feature Spec

A lock enables any running application code to obtain unique access over a resource to avoid race conditions that can occur from multiple applications trying to make changes to the same data.

AWS provides a dedicated locking client for dynamodb (https://github.com/awslabs/amazon-dynamodb-lock-client) but it's only available in Java. The client library handles logic like sending a heartbeat and automatically so the lock is automatically released in the case of crashes.

see also https://www.gomomento.com/blog/distributed-locks-making-them-easier-with-momento

### Use Cases

Preventing race conditions in distributed apps

For example, consider an application where user is booking a seat for a movie ticket. The backend must acquire a unique lock for that seat ID so that nobody else accidentally double-books the same seat.

```js
bring cloud;

let lock = new cloud.Lock(
  leaseDuration: 10m,
  hearbeatPeriod: 3s,
);

new cloud.Function(inflight () => {
  let seatId = "A5";
  let optionalItem = lock.acquire(seatId);
  if let item = optionalItem {
    log("Seat {seatId} is reserved. Complete your transaction in the next 10min.");
    // finish purchase steps...
    item.release();
    log("Thanks for your purchase, seat {seatId} is yours.");
  } else {
    log("Seat {seatId} seems to be in another transaction. Try another seat.");
  }
});
```

### Implementation Notes

For AWS, this can use DynamoDB under the hood (like cloud.Counter)

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by ekeren** [comment]
keep

**Comment by Chriscbr** [comment]
`bring lock` is now available as a dedicated winglib here: https://github.com/winglang/winglibs
