### ISSUE TITLE
wing init

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#5107]
### Feature Spec

From now you can use `wing init` to start a new wing project, the result of this is 

```
package.json 
main.w
```  

The package.json should include the current wing version in the `peer-dependencies` 

### Use Cases

- Be binded to a specific `wing` version
- Support for wing.cloud (@ainvoner) 

### Implementation Notes

from @eladb : Maybe we should use engine 
Open Questions: 
- Documentation 

### Component

CLI

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by ekeren** [comment]
In the future we can support templates

**Comment by Chriscbr** [comment]
`wing new`?

**Comment by ekeren** [comment]
> `wing new`?

`wing init` is more intuitive **for me**, probably because I am most familiar with `npm init`.

**Comment by eladb** [comment]
yes, I think `init` that's a pretty common naming scheme for creating projects, no?

**Comment by staycoolcall911** [comment]
Eventually we went with `wing new` in #5515 - closing.
