### ISSUE TITLE
test from checks should have a descriptive name 

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#5109]
### I tried this:

```ts
bring checks;

new checks.Check(inflight () => {}) as "one";
new checks.Check(inflight () => {}) as "two";

test "test name example" {}
```

### This happened:

when running wing test
```
% wing test main.w
pass ─ main.wsim » root/env0/one/test
pass ─ main.wsim » root/env1/two/test
pass ─ main.wsim » root/env2/test:test name example

```

but in the console:
![image](https://github.com/winglang/wing/assets/1727147/b70647cb-b3b1-4ff2-ab16-e93b8aa84430)

### I expected this:

- The name of the test to indicate that this test is coming from checks `cloud.Check/one/test` or something 
- To see a relevant name in the UI 

### Wing Version

0.51.1

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by subh-cs** [comment]
hey @staycoolcall911, I would like to work on this. Can you assign this to me?

**Comment by staycoolcall911** [comment]
Great! You got it @subh-cs

**Comment by Chriscbr** [comment]
Maybe it's possible reuse the ID from the parent? For example, here

https://github.com/winglang/winglibs/blob/65192881205a7df6702f4c2c7c55b4a89b74d1d2/checks/check.w#L81

The line could be changed to

```
  new std.Test(handler) as "{this.node.id}Test";
```
