### ISSUE TITLE
ex.ReactApp doesn't work well with single page routes

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#5118]
### I tried this:

I created a react app with routes

### This happened:

When deployed to tf-aws.

Routes works well on the client side, but when I refresh and access the page directly to the new route I get 
```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>1QF238DEGTQN69KT</RequestId>
<HostId>JVOthSYww13H56/8U3OH3Oqpg5bJJ7srJ851eTb9BZSX0XUeQSQmvr9TVG+lqggLITt86PG5Ujs=</HostId>
</Error>
```

I think we need to make sure that all CDN routes goes into the same S3 resource

### I expected this:

- [ ] To have all routes lead to the single page on AWS
- [ ] To have all routes lead to the single page on sim 
- [ ] To have all routes lead to the single page on wing cloud

### Wing Version

0.51.6

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment]
@skorfmann do you know the cloufront incantation required to make this work?

**Comment by skyrpex** [comment]
We do this:

```wing
bring ex;
bring util;

pub class ReactAppPatch {
  pub static apply(reactApp: ex.ReactApp) {
    if util.env("WING_TARGET") != "tf-aws" {
      return;
    }

    let distribution = unsafeCast(std.Node.of(reactApp).children.at(0).node.findChild("Distribution"));

    // Fallback to `/index.html`.
    distribution?.addOverride("custom_error_response", [
      {
        error_code: 403,
        response_code: 200,
        response_page_path: "/index.html",
      },
    ]);

    // Set a short default TTL.
    distribution?.addOverride("default_cache_behavior.default_ttl", 1m.seconds);
    distribution?.addOverride("default_cache_behavior.min_ttl", 1m.seconds);

    // Cache assets forever.
    distribution?.addOverride("ordered_cache_behavior", {
      path_pattern: "/assets/*",
      allowed_methods: ["GET", "HEAD"],
      cached_methods: ["GET", "HEAD"],
      target_origin_id: "s3Origin",
      // See https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html#managed-cache-caching-optimized.
      cache_policy_id: "658327ea-f89d-4fab-a63d-7e88639e58f6",
      min_ttl: 1y.seconds,
      default_ttl: 1y.seconds,
      max_ttl: 1y.seconds,
      compress: true,
      viewer_protocol_policy: "redirect-to-https",
    });
  }
}

```

**Comment by skyrpex** [comment]
One of the most important things to make ReactApp work with SPAs (single page applications) is the fallback of unexisting URLs to `/index.html`.

Also, the cache configuration should be flexible enough. In our case, we use Vite, which generates files in `/assets/*` that can be cached forever.

**Comment by skyrpex** [comment]
These customizations belong to the Website resource IMO. Also, the ReactApp resource doesn't include anything related to React, so I don't think it should be named ReactApp.

**Comment by skyrpex** [comment]
For reference, we should check out the most used web frameworks. I think these are the top ones:

- https://nextjs.org/
- https://nuxt.com/
- https://astro.build/
- https://vitejs.dev/
- https://kit.svelte.dev/
- https://start.solidjs.com/getting-started/what-is-solidstart

**Comment by tsuf239** [comment]
fixed with https://github.com/winglang/wing/pull/5307
