### ISSUE TITLE
unable to detect where and why program fails for `tf-azure` tests

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#5125]
### I tried this:

`wing test --platform tf-azure`

### This happened:

![image](https://github.com/winglang/wing/assets/10464497/8da133f1-18b5-4889-89e3-bedd5e7380cd)

### I expected this:

I expected the error to tell me on which line of my `.w` file it failed.
Additionally, I expected to see the outputs of `log() `and `expect.equal()`.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by tsuf239** [comment]
you're right!
we have it covered by two open issues:
#4574 
#5111

**Comment by garysassano** [comment]
Dupliate of #5111
