### ISSUE TITLE
`expect.be` and `expect.equal` 

### ISSUE THREAD

**Issue by olivernybroe** [winglang/wing#5147]
### Feature Spec

Currently the expectations api only have `equal`, this proposal adds a `be` comparison also. 
The reason why it mentions `equal` is that it will impact how `equal` will compare objects, so it looks at structure and not reference. 

So essentially the following test should pass
```
bring expect;

inflight class Work {
    name: str;

    new(name: str) {
        this.name = name;
    }
}

test "works" {
    expect.equal({"test": "test"}, {"test": "test"});
    expect.equal(new Work("test"), new Work("test"));
    expect.notBe(new Work("test"), new Work("test"));
}
```

I am not convinced necessarily that this is the best naming scheme, I am considering if `equal` and `strictEqual` might be better? 

### Use Cases

For comparing objects based on structure and not reference.

Currently this can be solved by wrapping the objects in `Json.stringify`

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by eladb** [comment]
I think `equal` is good for now, but we need to expand the `expect` library with many more utilities.
