### ISSUE TITLE
console: wrong reporting to console_session_start

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#5178]
### I tried this:

It looks like console MAU/WAU is lying
it is based on: rolling window of uniques of console_session_start
While it should be similar to MAU/WAU of basing the same analysis of cli__run  event (AKA wing run)

### This happened:

**console_session_start**

![image](https://github.com/winglang/wing/assets/1727147/0f1dfea7-0628-4f12-b1ec-3269507801e8)

 while 
 **cli__run**
 
![image](https://github.com/winglang/wing/assets/1727147/155d10a4-a3d4-40d7-8ead-4c1fbdeb7568)

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
@ekeren can we close this one?

**Comment by ekeren** [comment]
Yes
