### ISSUE TITLE
better error message for compiling unknown platforms

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#5234]
### I tried this:

I wanted to test wing code the awscdk target, I didn't have it installed on my machine.
I ran:
`wing test -t  @winglang/platform-awscdk path-to-file`

### This happened:

<img width="721" alt="image" src="https://github.com/winglang/wing/assets/39455181/ea1cec25-f127-408c-bb82-a039735177c3">

### I expected this:

Wing cli to display a friendly error such as "seems like "platform-name" isn't installed, try running `npm i -g <package name>`?"
*I assume that the same error is displayed even for mistyped or unexisting platforms, please take that in account
@hasanaburayyan do you have an idea for a friendly error message to display?

### Anything else?

Dear contributor, you are welcome to assign yourself to the task! before you start, please verify that you have the exact wording for the error message and that edge cases are all covered :) 

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by revitalbarletz** [comment]
@srinumadhavv let me know what do you think about this issue!

**Comment by srinumadhavv** [comment]
@Chriscbr  @revitalbarletz  ![image](https://github.com/winglang/wing/assets/43718077/8502d1af-cfed-4fa3-b2e5-2ff48b7b903a)
Seems the error comes from here but its still picking up the old change as per the description any headsup at where to start looking at ?

**Comment by tsuf239** [comment]
found a duplication to this issue- https://github.com/winglang/wing/issues/6147
and it seems like it was closed by @hasanaburayyan in #6176 
I think we can close this one :) 
@srinumadhavv please let us know if you need help choosing another issue
