### ISSUE TITLE
`expect.error` should replace all assertThrows across wing code

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#5238]
### Use Case

Until now, when we want to ensure that a specific method is throwing an error as expected,
we used `assertThrows` that had to be coded (in different versions) multiple times across the codebase. 
It's a terrible code duplication, especially now, when we have the expect lib :) 

### Proposed Solution

Adding a new method- 
```
expect.error(method: () => any, errorMsg ?: str )
```
it will take a method and a regex as the error message- then run the method inside of a try/catch block, and if we caught an error if the `errorMsg` arg matches the error (or non exists) the expect fulfilled, other- we'll throw an error, either saying that the method didn't throw, or the error doesn't match the expected message

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by staycoolcall911** [comment]
Duplicates #5502
