### ISSUE TITLE
The simulator fails to start when using a queue with no subscribers

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#525]
### I tried this

I compiled the following wing code (using the sim target):

```ts
bring cloud;

let queue = new cloud.Queue();

inflight handler(message: str) :str {
//   print("Hello, ${message}!");
}

// queue.on_message(handler);
```

The compilation went correctly but starting the simulator with the `app.wx` file throwed an error.

### Expected

Opening the `app.wx` with the simulator should work.

### Instead, this happened

The instruction `await simulator.start();` throwed the following error:

`TypeError: props.subscribers is not iterable`

Which leads to the following SDK code. Seems like the Queue is expecting `props.subscribers` to be an array and was undefined.

![image](https://user-images.githubusercontent.com/1077520/200865130-3d976d2c-4866-4d59-9759-846358748142.png)

### Component

SDK

### Environment

```markdown
- Wing Version: 0.2.120
- OS: MacOS
- Node version: 16.18.0
```

**Comment by Chriscbr** [comment]
Keep
