### ISSUE TITLE
Duplicate Wing test panes in VSCode

### ISSUE THREAD

**Issue by eladb** [winglang/wing#5259]
### I tried this:

VSCode now has two different test panels for wing tests. 

### This happened:

Now that we are integrated with the standard testing feature of VSCode, we don't need the custom one.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
The vscode extension no longer embeds wing console features (including the test pane)
