### ISSUE TITLE
console: logs are not printed

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#5272]
### I tried this:

When working with @eladcon on [winglibs/github](https://github.com/winglang/winglibs/pull/39/files#diff-c5b7382792e3a9f7aee4fab519a24a9bd9754aa5b462062676bdf7abaa4a2caaR19) we've encounter a situation that logs entries are not visible in the console.

@eladcon actually made a comment that "you can't trust log" and replace them with "fs.writeFs" 

**We need to fix this!**

### This happened:

log entires that should be printed are missing

### Anything else?

I am wondering if we should try to actually base our logs on files, and the console should tail -f these files... 

a simulator 

### Wing Version

0.52.7

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
I am aware that this ticket is missing ways to reproduce this... maybe @eladcon can produce an example

**Comment by eladb** [comment]
This seems like a P1 @ainvoner

**Comment by ekeren** [comment]
Not sure if it is still happening, did you encounter this @eladb a d @eladcon ?

**Comment by ainvoner** [comment]
@eladb Leaving it as P2 for now

**Comment by eladb** [comment]
Let's just close
