### ISSUE TITLE
Cloud function timeout difference between sim and AWS

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#5274]
### I tried this:

```
bring util;

test "never fail" {

  for i in 1..10 {
    util.sleep(10s);
  }
}
```

### This happened:

```
 % wing test lock/stress.test.w -t tf-aws
✔ Compiling lock/stress.test.w to tf-aws...

✔ terraform init

✔ terraform apply

✔ Setting up test runner...

✔ Running tests...

fail ─ stress.test.tfaws.711950 » root/Test.pLsNTBW5w9/env0/test:stress test
One or more tests failed. Cleaning up resources...
✔ terraform destroy

 
 
Tests 1 failed (1)
Test Files 1 failed (1)
Duration 1m54.92s
```

### Wing Version

0.52.7

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
I wonder if the test failed due to a timeout error? When a `cloud.Function` times out, perhaps we should raise it as a dedicated error in the Wing SDK when `invoke()` is called (timing out is a functional aspect of serverless functions).

**Comment by ekeren** [comment]
What is the default timeout of a function ? (This is actually a test
function )

**Comment by Chriscbr** [comment]
The default timeout for `cloud.Function` in our docs is 1 min

**Comment by ekeren** [comment]
Yikes

1. As you mentioned, We need a way to let the user know about this (maybe
something similar to node’s setUncaughtExceptionCaptureCallback)
2. Maybe we need to change the default of the test cloud.Function to a
longer period
3. Does it make sense for cloud.Function to default to 1 minutes?

**Comment by Chriscbr** [comment]
@ekeren The other issue is the "timeout" option isn't working on the simulator - see https://github.com/winglang/wing/issues/1980. So the test should have failed on both targets

**Comment by Chriscbr** [comment]
Running this test now raises an error on the simulator, so there's no longer a difference between `sim` and AWS targets:

```
fail ┌ main.wsim » root/env0/test:never fail
     └ Error: Function timed out (it was configured to only run for 60000ms)
 
 
Tests 1 failed (1)
Test Files 1 failed (1)
Duration 1m0.34s
```

Marking as solved
