### ISSUE TITLE
How to test Wing repo locally?

### ISSUE THREAD

**Issue by meirdev** [winglang/wing#5286]
Hi,

Until now I used Codespaces to work on the code:

I have a Mac M1 and I couldn't install on the computer directly or use the devcontainer that comes with the repo.

In a normal installation the error I get:

```
.../@cdktf/node-pty-prebuilt-multiarch install$ node scripts/check-prebuild.js || prebuild-install || node scripts/install.js
│ Prebuild binary missing for platform darwin
```

In devcontainer:

```
vscode ➜ /workspaces/wing (main) $ pnpm install
Scope: all 33 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +2590
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 2590, reused 2573, downloaded 0, added 0, done
node_modules/.pnpm/tree-sitter-cli@0.20.6/node_modules/tree-sitter-cli: Running install script, failed in 99ms
.../node_modules/tree-sitter-cli install$ node install.js
│ Cannot install tree-sitter-cli for platform linux, architecture arm64
└─ Failed in 100ms at /workspaces/wing/node_modules/.pnpm/tree-sitter-cli@0.20.6/node_modules/tree-sitter-cli
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by MarkMcCulloh** [comment]
Yeah unfortunately devcontainers don't work on m1, but your local build should work.

What version of node are you using (`node -v`) and how was it installed (brew/nvm/volta?).

Also, what is the output of `node -e "console.log(process.arch)"`? It should be `arm64`, otherwise you may have the wrong arch version of node installed

**Comment by meirdev** [comment]
The output from my computer:

```
meir@Meirs-MacBook-Pro-2 ~ % node -v
v21.2.0
meir@Meirs-MacBook-Pro-2 ~ % which npm
/opt/homebrew/bin/npm
meir@Meirs-MacBook-Pro-2 ~ % node -e "console.log(process.arch)" 
arm64
```

**Comment by MarkMcCulloh** [comment]
Development for this repo is currently pinned to node `18.16.0`, could you try with that version instead? Also check out https://www.winglang.io/contributing/start-here/development for other info/prerequisites for a full build.

I would also suggest uninstalling node/npm from homebrew and using something like [volta](https://github.com/volta-cli/volta) or [nvm](https://github.com/nvm-sh/nvm) to make it easier to switch versions, but that's not a requirement.

**Comment by meirdev** [comment]
Thanks!

### Solution

Install volta:

`curl https://get.volta.sh | bash`

Install Node v18.16.0:

`volta install node@18.16.0`

Verify:

`which node` (Example: `/Users/meir/.volta/bin/node`)

Install PNPM:

`curl -fsSL https://get.pnpm.io/install.sh | sh -`

**Make sure there are no remnants of files from previous attempts (`node_modules`, `.cargo`, `.turbo`, ...)**

**Comment by MarkMcCulloh** [comment]
Awesome, and thanks for the step-by-step!
