### ISSUE TITLE
`sim.Resource` and `sim.Attribute`

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#5305]
### Use Case

Before (the API we have today):
```js
class MyService {
  state: sim.State;
  pub startTime: str;
  
  new() {
    this.state = new sim.State();

    new cloud.Service(inflight () => {
      let res = // create a websocket, etc.
      this.state.set("start_time", "2023-10-16T20:47:39.511Z");
      return () => { res.close(); };
    });

    this.startTime = this.state.token("start_time");
  }
}
```

After (proposed API):
```js
class MyService {
  state: sim.State;
  pub startTime: str;
  
  new() {
    this.state = new sim.State(inflight (ctx) => {
      let res = // create a websocket, etc.

      ctx.trace("custom message"); // new!
      fs.write(fs.join(ctx.statedir, "state.json"), "data"); // new!
      
      return {
        attributes: {
          "start_time": "2023-10-16T20:47:39.511Z",
        },
        teardown: () => { res.close(); },
      };
    });

    this.startTime = this.state.token("start_time");
  }
}
```

<details>
<summary>Alternative API</summary>

```js
class MyService extends sim.State {
  pub startTime: str;
  new() {
    this.startTime = this.token("start_time");
  }

  inflight res: Websocket;
  
  init(ctx: sim.Context): Map<str> {
    this.res = // create a websocket, etc.

    ctx.trace("custom message"); // new!
    fs.write(fs.join(ctx.statedir, "state.json"), "data"); // new!

    return Map<str>{ "start_time": "2023-10-16T20:47:39.511Z" };
  }

  teardown() {
    this.res.close();
  }
}
```

</details>

Benefits:
- Using simulator logger
- Setting/restoring simulator state for the resource
- Values can still be shared between init and teardown functions (for opening and closing long-lived objects like websockets or database connections)
- If sim.State returns a map without all the runtime attributes set (like `start_time`), we could detect the error sooner in the simulator

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by eladb** [comment]
Would it make sense to simply add this to the `cloud.Service`?

**Comment by Chriscbr** [comment]
I wasn't sure -- here was my thinking:

1. I'm imagining the semantics of the inflight code may be different. A lot of people probably expect `cloud.Service` to support automatic scaling based on the service's incoming traffic. That means the inflight code you pass to `cloud.Service` for starting or stopping the service may run multiple times as the service scales to more or less compute instances. By contrast, the API for `sim.State` would be tied 1:1 to the resource's lifecycle (in the simulator).

2. The API I proposed would expose APIs for interacting with the simulator, like saving/storing state in the resource's state directory and setting deploy-time attributes, so it wouldn't work on AWS or other targets.

Here's a gist showing how it could look to implement `cloud.Bucket` sim implementation in Wing: https://gist.github.com/Chriscbr/e484fdeb43cef00f4a1c3258f689f6e9

**Comment by eladb** [comment]
Yes, i see. So maybe the terminology `sim.State` is not clear enough. How about `sim.Resource` and then and maybe we can do something like `sim.Attribute` to represent tokensized state.

```js
class Bucket extends sim.Resource {
  url: str;
  urlToken: sim.Attribute;

  new() {
    this.urlToken = new sim.Attribute("url");
    this.url = this.urlToken.token;
  }

  inflight startup() {
     this.urlToken.resolve("http://localhost:1234");
  }

  inflight shutdown() {
    // ...
  }
}
```

What do you think?

**Comment by Chriscbr** [comment]
I like it 👍

**Comment by Chriscbr** [comment]
Closing as duplicate of https://github.com/winglang/wing/issues/4781

**Comment by eladb** [comment]
Reopening this to supersede #4781 because this issue has more context and better ideas.

**Comment by Chriscbr** [comment]
@eladb That API makes sense / looks good to me! We can also add a dedicated `update()` capability in the future once the sim engine supports it

**Comment by Chriscbr** [comment]
Adding some notes here

See https://github.com/winglang/wing/pull/5882#issuecomment-2002339174 re: a potential DX issue around remote calls.

Btw, it will be nice if we can ensure that non-serializable types can't accidentally be passed / returned from methods that are remoted. For example, it's not possible for a simulated resource to have an inflight-class-typed parameter because inflight classes aren't immutable or serializable

**Comment by eladb** [comment]
> Btw, it will be nice if we can ensure that non-serializable types can't accidentally be passed / returned from methods that are remoted

We discussed in the past that I think we should limit inflight methods to only allow serializable types (inputs and outputs). Otherwise it will be impossible to implement them in the simulator and will also block us from supporting additional programming languages through a sidecar architecture.

I am in favor of adding a compiler restriction to force inflight APIs to only use serializable types as a defensive measure. It will be much easier to relax this constraint later than the other way around.

**Comment by Chriscbr** [comment]
sim.Resource has been implemented in https://github.com/winglang/wing/pull/6389. Closing
