### ISSUE TITLE
`wing test` doesn't print test results for `tf-gcp` platform

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#5339]
### I tried this:

```
wing test -t tf-gcp examples/tests/sdk_tests/bucket/*.test.w
```

### This happened:

![image](https://github.com/winglang/wing/assets/10464497/19e43077-543a-4d33-938f-7ecb2c01167b)

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Shouldn't be too difficult to align this with the behavior for tf-aws.

**Comment by tsuf239** [comment]
@garysassano can you please describe further what isn't working? what errors are you getting? 
the screenshot you sent is for 3 unsupported cases, I see that the rest of the tests are compiling...
it's working for me the same way :)

**Comment by garysassano** [comment]
@tsuf239 It's not printing the results after compiling. It shouldn't matter if some tests fail, it should still print all the results at the end.

**Comment by tsuf239** [comment]
@garysassano it sounds weird, what wing version are you using? is it happening on more platforms? what happens if you're running a single test file? 
(you can try returning to the original task by running the tests one by one if it works for you)

**Comment by garysassano** [comment]
Continuing on #5362
