### ISSUE TITLE
Wing Console sometimes does not start correctly

### ISSUE THREAD

**Issue by marciocadev** [winglang/wing#5351]
### I tried this:

When I start the Wing Console, either with the `wing it` command or in vscode, sometimes it does not start correctly.

### This happened:

I can check the log generated, and when it starts correctly, it generates the following sequence:
```bash
Wing Console is running at http://localhost:3000
[verbose] @winglang/sdk.sim.State created.
[verbose] ...
```

But occasionally, it only generates the log entry: `Wing Console is running at http://localhost:3000`

When this happens, nothing works correctly, and there is no additional information generated in the log.

### Is there a workaround?

I haven't found any
I keep trying to execute until it starts correctly

### Wing Version

0.54.2

### Node.js Version

v18.17.1

### Platform(s)

Linux

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
might be related to https://github.com/winglang/wing/issues/5349

**Comment by marciocadev** [comment]
I think you're right 

I will test it and if this is the cause I close this

**Comment by marciocadev** [comment]
Closing this because its related with #5349 as @ainvoner point it

Thanks @ainvoner
