### ISSUE TITLE
parsing user input is terrible (wingly raffle conclusion)

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#5374]
### Use Case

The type system seems a bit off when it comes to input coming from a user, for example, parsing an optional API request's body as a JSON and retrieving one of its properties, will make you do something like this:

```js
str.formJson(Json.parse(req.body) ?? "\{\}").tryGet("email));
```

it also throws an error when the body is `nil` (unexpected end of JSON)

### Proposed Solution

Do we have something like this?

```js
struct ReqBody {
  email: string,
  name: string
}
// .......

try {
  let body: ReqBody = ReqBody.fromStr(req.body ?? "");

} catch (error) {
  // property "email" doesn't exist on req.body
  // property "name" doesn't exist on req.body
  // req.body is nil
  // unable to parse the string
}
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by eladb** [comment]
This is already supported:

```js
struct ReqBody {
  email: str;
  name: str;
}

let body = Json.stringify({
  email: "eladb@wing.cloud",
  name: "elad ben-israel"
});

let b = ReqBody.parseJson(body);
log(b.email);
log(b.name);
```

Closing for now.
