### ISSUE TITLE
tests with `expect.equals` do not exit (wingly raffle conclusion)

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#5382]
### I tried this:

```
bring cloud;
bring expect;
bring http;

let WINGLY_URL = "someUrl";

let RESPONSE = "....";
let b = new cloud.Bucket() as "raffle-bucket";
b.addObject(WINGLY_URL, RESPONSE);

let api = new cloud.Api();

api.get("/wingly", inflight () => {
  return {
    status: 200,
    body: b.get(WINGLY_URL)
    };
});

test "endpoints" {
  expect.equal(http.get("{api.url}/wingly").body, RESPONSE);
}
```

### This happened:

the test ran and passed, but didn't exit (I had to exit manually with ctrl+c)

### I expected this:

to run and exit

### Is there a workaround?

 ctrl+c after each run

### Wing Version

0.54.15

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
@tsuf239 - I have updated the code sample so it could run (added the `bring` statements and assigning value to the WINGLY_URL variable).
I am then running it with `wing test main.w` with no problems. 
I am closing for now, please reopen if you can find a reproducible scenario for the failure you described.

**Comment by tsuf239** [comment]
interesting, I tried again and found out that my problem was a reactApp resource in the beginning of the file, I'll open another issue

**Comment by tsuf239** [comment]
opened https://github.com/winglang/wing/issues/5391, thanks!
