### ISSUE TITLE
`+=` isn't working for strings

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#5383]
### I tried this:

```
let var message = "Yay! another user registered to the raffle!\n";
message  += "*email:* {email} *name:* {name}\n";
```

### This happened:

<img width="758" alt="image" src="https://github.com/winglang/wing/assets/39455181/f92b08a7-d93e-47e1-94a0-58be99d47e6d">

### I expected this:

to just work :) 

### Is there a workaround?

```
message = message + "*email:* {email} *name:* {name}\n";

```

### Anything else?

Discovered while working on this project: https://github.com/winglang/wing-raffle

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by lausuarez02** [comment]
Hey i would like to take this one but, where exactly should i tackled this issue? folder/architecture wise

**Comment by staycoolcall911** [comment]
You got it @lausuarez02 :)
Here's how Chris added string concat with + a while ago: #2429 
It should give you a hint how to start. 
You should have some relevant guides on our doc site, such as this one: https://www.winglang.io/contributing/start-here/development#how-do-i-make-changes-to-the-wing-grammar

**Comment by Warkanlock** [comment]
@lausuarez02 are you going to take this one? I might be able to do it during my weekend

**Comment by revitalbarletz** [comment]
@Warkanlock I just assigned this issue to Ignacio, how about joining our slack channel and continue this discussion there https://t.winglang.io/slack ?

**Comment by revitalbarletz** [comment]
@Warkanlock its all yours :)
