### ISSUE TITLE
graphql wing lib

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#5385]
### Use Case

Another suggestion for wing lib, is adding support to Graphql including the schema handling and endpoint

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by staycoolcall911** [comment]
Duplicates #4769
