### ISSUE TITLE
Throwing does not bypass return typecheck

### ISSUE THREAD

**Issue by MarkMcCulloh** [winglang/wing#5414]
### I tried this:

https://www.winglang.io/play/?code=bABlAHQAIAB4ADoAIAAoACkAOgAgAG4AdQBtACAAPQAgACgAKQAgAD0APgAgAHsACgAgACAAdABoAHIAbwB3ACAAIgBuAG8AdAAgAGkAbQBwAGwAZQBtAGUAbgB0AGUAZAAiADsACgB9ADsA

```wing
let x: (): num = () => {
  throw "not implemented";
};
```

### This happened:

Compiler error, A function whose return type is "num" must return a value.

### I expected this:

The compiler should detect that that function never returns

### Is there a workaround?

Add a fake return after the `throw`

### Anything else?

Proposal for fix: The type checker should detect a `throw` statement at the top-level of a function. If detected, the function should not have this error regardless of the existence of a return statement anywhere in the functino. This correctly covers the common case without adding false negatives.

```wing
let x: (): num = () => {
  if true {
    return 0;
    // Without data flow analysis, the compiler does not know for sure this will happen
  }

  throw "not implemented";
  // There are only two possible cases here: Either the function will return or it will throw.
  // Either way, `A function whose return type is "num" must return a value` is satisfied
};
```

```wing
let x: (): num = () => {
  if true {
    return 0;
  }

  if true {
    throw "not implemented";
    // This case should still not work without DFA
  }
};
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
Sounds like a reasonable fix 👍 

For anyone that wants to pick it up, here's where the current logic is: https://github.com/winglang/wing/blob/6437741d19632ae502fc335441c895cd94729db3/libs/wingc/src/type_check.rs#L3198-L3210

**Comment by Warkanlock** [comment]
I'll try to tackle this issue this weekend!

**Comment by staycoolcall911** [comment]
Completed in #5555
