### ISSUE TITLE
Resource declaration: JSify inflight methods

### ISSUE THREAD

**Issue by yoav-steinberg** [winglang/wing#542]
wingc currently doesn't JSify inflight methods as inflight code (into some JS file to be used as an inflight asset). Instead it just treats them as preflight methods. This makes creating resources with inflight code useless.

Here: https://github.com/winglang/wing/blob/572499b6b20b14bb68daee56474461d10e09c23a/libs/wingc/src/jsify.rs#L359-L386 you can see inflight methods aren't handled specially.

So this:
```
resource R {
  init() {}
  ~inf() {}
}
```
turns into this (notice `inf` is treated as a preflight method):
```js
class R  {
  constructor() {}
  inf() {}
}
```
Which is a bug.
-------------------------------------------------------------
Sub tasks list by @yoav-steinberg:
- [ ] 1. Support resource initialization in wing (access `this` from `init`).
    - [x] 1. At first with no verification that all fields are initialized.  ** p1 **
    - [ ] 2. #1446 ** p2 **
- [ ] 2. JSIfy inflight and preflight for custom resources.
    - [x] 1. First assume all captures are resources and are passed via constructor.  ** p1 **
    - [x] 2. #1519 ** p1 **
    - [ ] 3. #1447 ** p2 **
- [ ] 3. Binding metadata phases (policy metadata):
    - [x] 1. All methods of resource are marked as used.
    - [ ] 2. #76 ** p1 **
    - [ ] 3. Basic CFA (control flow analysis) for generating the binding metadata. Compiler error (unless custom binding metadata is provided). At this phase we don’t allow stuff like variable assignments, passing a resource as an argument, returning a resource… 
    	#1449 ** p1 **
    - [ ] 4. More advanced CFA (this can be multiple stages). ** p2 **
- [ ] 4. Generate custom resources from inflight ~functions~ closures (until this is done we need to manually create resources that adhere to the required wingsdk interface). 
	#1448  ** p2 **
- [ ] 5. Support importing JSII interfaces (so we can understand stuff like IFunctionHandler).
	- [ ] #123  ** p1 **
	- [x] #1024  ** p1 **

**Comment by staycoolcall911** [comment]
Closing since all sub tasks have an issue.
