### ISSUE TITLE
The simulator hangs on compiling

### ISSUE THREAD

**Issue by meirdev** [winglang/wing#5431]
### I tried this:

`mylib.w`:

```wing
bring "cdktf" as cdktf;
bring "@cdktf/provider-aws" as tfaws;

pub class Test {
    bucket: tfaws.s3Bucket.S3Bucket;
    object: tfaws.s3BucketObject.S3BucketObject;

    new() {
        this.bucket = new tfaws.s3Bucket.S3Bucket(bucket: "test1");
        this.object = new tfaws.s3BucketObject.S3BucketObject(
            bucket: this.bucket.id,
            key: "test",
        );
    }
}
```

`main.w`:

```wing
bring "./mylib.w" as mylib;

let testBucket = new mylib.Test();
```

### This happened:

The simulator hangs on compiling.

### I expected this:

To work or at least show an error (because it's wrong to use terraform in the simulator).

### Anything else?

With one object it works:

```wing
bring "cdktf" as cdktf;
bring "@cdktf/provider-aws" as tfaws;

pub class Test {
    bucket: tfaws.s3Bucket.S3Bucket;

    new() {
        this.bucket = new tfaws.s3Bucket.S3Bucket(bucket: "test1");
    }
}
```

With two objects it doesn't work:

```wing
bring "cdktf" as cdktf;
bring "@cdktf/provider-aws" as tfaws;

pub class Test {
    bucket1: tfaws.s3Bucket.S3Bucket;
    bucket2: tfaws.s3Bucket.S3Bucket;

    new() {
        this.bucket1 = new tfaws.s3Bucket.S3Bucket(bucket: "test1");
        this.bucket2 = new tfaws.s3Bucket.S3Bucket(bucket: "test2");
    }
}
```

If I use 'as' it works:

```wing
bring "cdktf" as cdktf;
bring "@cdktf/provider-aws" as tfaws;

pub class Test {
    bucket1: tfaws.s3Bucket.S3Bucket;
    bucket2: tfaws.s3Bucket.S3Bucket;

    new() {
        this.bucket1 = new tfaws.s3Bucket.S3Bucket(bucket: "test1") as "test1";
        this.bucket2 = new tfaws.s3Bucket.S3Bucket(bucket: "test2") as "test2";
    }
}
```

But `as` doesn't work for two different objects (the first example).

### Wing Version

0.54.30

### Node.js Version

v18.16.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
@meirdev Could you share what's the exact command you ran to caused the simulator to hang?

**Comment by meirdev** [comment]
I assume it's fixed already, now I get the error (as I would expect):

<img width="1000" alt="Screenshot 2024-03-01 at 9 23 16" src="https://github.com/winglang/wing/assets/21178966/1bc21894-ae35-4d91-bc3c-afbcbf502a79">
