### ISSUE TITLE
Allow using a mouse to navigate the Console map

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#5446]
### Use Case

Users without trackpads can't navigate through the Console map.

### Proposed Solution

Use the mouse click to navigate the Console map.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by skyrpex** [comment]
This will be necessary after https://github.com/winglang/wing/pull/5433 is merged.

**Comment by ainvoner** [comment]
resolved
