### ISSUE TITLE
hybrid function?

### ISSUE THREAD

**Issue by meirdev** [winglang/wing#5480]
### Use Case

A lot of functions belong to both `inflight` and `prelight`, for example: the functions of the library `fs`.

Is it possible to write hybrid functions? If not, is it planned to support it in the future?

Basically, almost any library that is not a "cloud component" fits into this category.

### Component

Language Design, Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by eladb** [comment]
Yes, here is the tracking issue https://github.com/winglang/wing/issues/435
