### ISSUE TITLE
Stage 4 of the interactive tutorial at the [interactive tutorial](winglang.io/learn) is failing to start the simulator

### ISSUE THREAD

**Issue by omer-vishlitzky** [winglang/wing#5482]
### I tried this:

I entered https://www.winglang.io/learn/ and clicked next 3 times to get to stage 4

### This happened:

![image](https://github.com/winglang/wing/assets/22615781/ba285cf9-5f06-418d-ad83-d60b48653838)

### I expected this:

Simulator should start

### Is there a workaround?

It doesn't happen all the time so chances are that after refresh it will work

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
working well in current version


![Image](https://github.com/winglang/wing/assets/2538825/419d6f71-98be-49dc-ad5b-8686c6c67e55)
