### ISSUE TITLE
No visual indication that wing it server stopped

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#5498]
### I tried this:

I ran `wing it` with a Wing file:

```
bring cloud;

new cloud.Function(inflight () => {
  log("hello world!");
});
```

Then I pressed Ctrl + C to stop running the server.

With the Wing Console still open in my browser, I tried opening the function and clicking "Invoke" on the function.

### This happened:

Nothing happens, and I think that something is broken

### I expected this:

Perhaps some kind of message in the UI (e.g. a toast) indicating that the Wing Console has lost connection to the simulator / the process may have been killed etc.

### Wing Version

0.54.51

### Node.js Version

20.9.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
Oh man, this is exactly what is bothering me and I didn't know it

**Comment by ainvoner** [comment]
resolved

![Image](https://github.com/winglang/wing/assets/2538825/c8bd50c3-6d9b-47ed-97c2-a919a154dee7)
