### ISSUE TITLE
Incorrect `Map.get` documentation

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#5512]
### I tried this:

Hovering over the `get()` on a map to see the method's behavior

### This happened:

https://github.com/winglang/wing/blob/4677fe1657c1061a3520f974ebc07b0347746c2b/libs/wingsdk/src/std/map.ts#L36-L50

It tells me that the method returns "the element associated with the specified key, or undefined if the key can't be found"

### I expected this:

It always returns a key, and throws an error otherwise

### Wing Version

0.54.51

### Node.js Version

20.9.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Nice catch! Very quick fix for the fastest gun out there, whoever you may be.
Fix the docs at https://github.com/winglang/wing/blob/main/libs/wingsdk/src/std/map.ts#L47

**Comment by Warkanlock** [comment]
I can take a look at this!

**Comment by staycoolcall911** [comment]
Completed in #5553
