### ISSUE TITLE
Console stuck forever when missing a required class prop

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#5534]
### I tried this:

Run `wing it` on this wingfile:

```
bring cloud;
bring util;

struct FooProps {
	foo: str;
}

class Foo {
	new(props: FooProps) {
		//
	}
}

new Foo(
	// foo: "foo",
);
```

Notice the commented `foo` prop.

### This happened:

The Console is stuck in the "compilation" step, while `wing compile` correctly reports the compilation error.

### I expected this:

The Console should report the compilation error.

### Wing Version

0.54.61

### Node.js Version

20.9.0

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
@skyrpex is it the same as in: https://github.com/winglang/wing/issues/5505

**Comment by skyrpex** [comment]
Right, closing.
