### ISSUE TITLE
Evaluate using Profile-Guided Optimization (PGO) for the Wingc compiler

### ISSUE THREAD

**Issue by zamazan4ik** [winglang/wing#5558]
### Use Case

Potentially improve the Wingc performance.

### Proposed Solution

According to my [tests](https://github.com/zamazan4ik/awesome-pgo), Profile-Guided Optimization (PGO) helps with achieving better performance in many applications in different domains like compilers, static analysis, interpreters, etc like Rust, GCC, Clang, Go compiler (and many other similar projects). Since the Rust language [supports](https://doc.rust-lang.org/rustc/profile-guided-optimization.html) PGO, and the Wingc compiler is written in Rust, it could be an interesting idea to optimize the compiler with PGO.

I can suggest the following things to do:

* Perform PGO benchmarks on the Wingc compiler. If it shows improvements - add a note about possible improvements in the Wingc compiler performance with PGO somewhere to the documentation (maybe a note in the README file will be enough).
* Providing an easier way (e.g. a build option) to build scripts with PGO can be useful for the end-users and maintainers since they will be able to optimize the compiler according to their workloads.
* Optimize prebuilt binaries with PGO

### Implementation Notes

For the Rust project, I can recommend starting with [cargo-pgo](https://github.com/Kobzol/cargo-pgo) tool to perform PGO on a Rust program.

Here are some examples of how PGO is already integrated into other projects' build scripts/pipelines:

* Rustc: a CI [script](https://github.com/rust-lang/rust/blob/master/src/ci/stage-build.py) for the multi-stage build
* GCC:
  - Official [docs](https://gcc.gnu.org/install/build.html), section "Building with profile feedback" (even AutoFDO build is supported)
  - A [part](https://github.com/gcc-mirror/gcc/blob/4832767db7897be6fb5cbc44f079482c90cb95a6/configure#L7818) in a "wonderful" `configure` script 
* Clang: [Docs](https://llvm.org/docs/HowToBuildWithPGO.html) 
* Python: 
  - CPython: [README](https://github.com/python/cpython#profile-guided-optimization)
  - Pyston: [README](https://github.com/pyston/pyston#building)
* Go: [Bash script](https://github.com/golang/go/blob/master/src/cmd/compile/profile.sh)
* V8: [Bazel flag](https://github.com/v8/v8/blob/main/BUILD.gn#L184)
* ChakraCore: [Scripts](https://github.com/chakra-core/ChakraCore/tree/master/Build/scripts/pgo)
* Chromium: [Script](https://chromium.googlesource.com/chromium/src/build/config/+/refs/heads/main/compiler/pgo/BUILD.gn)
* Firefox: [Docs](https://firefox-source-docs.mozilla.org/build/buildsystem/pgo.html)
* PHP: [Makefile command](https://github.com/php/php-src/blob/master/build/Makefile.global#L138) and old Centminmod [scripts](https://github.com/centminmod/php_pgo_training_scripts)
* MySQL: [CMake script](https://github.com/mysql/mysql-server/blob/8.0/cmake/fprofile.cmake)
* YugabyteDB: [GitHub commit](https://github.com/yugabyte/yugabyte-db/commit/34cb791ed9d3d5f8ae9a9b9e9181a46485e1981d)
* FoundationDB: [Script](https://github.com/apple/foundationdb/blob/1a6114a66f3de508c0cf0a45f72f3687ba05750c/contrib/generate_profile.sh)
* Zstd: [Makefile](https://github.com/facebook/zstd/blob/dev/programs/Makefile#L232)
* [Foot](https://codeberg.org/dnkl/foot): [Scripts](https://codeberg.org/dnkl/foot/src/branch/master/pgo)
* Windows Terminal: [GitHub PR](https://github.com/microsoft/terminal/pull/10071)
* Pydantic-core: [GitHub PR](https://github.com/pydantic/pydantic-core/pull/741)
* file.d: [GitHub PR](https://github.com/ozontech/file.d/pull/469)
* OceanBase: [CMake flag](https://github.com/oceanbase/oceanbase/blob/master/cmake/Env.cmake#L55)

I would be happy to answer all your questions about PGO. I am not sure about how the Wingc performance is important right now - I am sure authors can decide better than me in this case :)

P.S. I thought the better place to share this idea is the Discussion GitHub section ("Ideas" part of it) but it seems like I don't have enough rights to create a discussion there - that's why I created the issue.

### Component

Compiler

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by MarkMcCulloh** [comment]
Hey there! Thanks for the links and working on an interesting project.

Our rust code exclusively targets wasm32-wasi, which seems to be unsupported based on https://github.com/Kobzol/cargo-pgo/issues/42 and https://github.com/rust-lang/rust/issues/81684

So I'll close this issue for now, but if I got that wrong or it becomes supported in the future then feel free to reopen

**Comment by revitalbarletz** [comment]
@zamazan4ik how about joining our slack channel https://t.winglang.io/slack? I am curious to hear more about this project!
