### ISSUE TITLE
Resource ID hashes are altered by aliases as`bring module as x`

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#5570]
### I tried this:

Compare the resource IDs in these programs:

```wing
bring cloud;

// Bucket prefix in tf-aws is `"cloud-bucket-c87175e7-"`
let bucket = new cloud.Bucket();
```

```wing
bring cloud as c;

// Bucket prefix in tf-aws is `"c-bucket-c8d6b016-"`
let bucket = new c.Bucket();
```

### This happened:

The IDs are affected by aliases in `bring` statements.

### I expected this:

The IDs shouldn't be affected by the name of the import group. I guess the hash could use the original name of the package (if at all), since that doesn't change.

### Wing Version

0.56.3

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment]
Duplicate #5564
