### ISSUE TITLE
Landing page (@nathan)

### ISSUE THREAD

**Issue by revitalbarletz** [winglang/wing#5574]
Nathan & Amiel will work together to get this crafted. 

Nathan to unblock this item.

Landing page should create the following:
- [ ] An cool image related to the use case
- [ ] An intro to the tutorial including a link
- [ ] An intro to the workshop including a link to the invite
- [ ] A link to the short video in YouTube

**Comment by amielpb** [comment]
- [ ] Short paragraph summarizing the use case complete with keywords that will maximize marketing juju
I'll take care of the image and start building the landing page on webflow

**Comment by amielpb** [comment]
[Google Doc with the copy](https://docs.google.com/document/d/1-t5iCGQIzvH_hzhHT6KftF8R-KTpIt7B6pBXd2nzj4I/edit)
