### ISSUE TITLE
Simulator should fail when there are a cyclic dependency

### ISSUE THREAD

**Issue by eladb** [winglang/wing#5601]
### I tried this:

```js
bring cloud;

let api = new cloud.Api();

api.get("/my_url", inflight () => {
  return {
    status: 200,
    body: api.url
  };
});
```

### This happened:

This works in the simulator but when deploying to tf-aws we get this error:

```
│ Error: Cycle: aws_api_gateway_deployment.cloudApi_api_deployment_545514BF, aws_api_gateway_stage.cloudApi_api_stage_BBB283E4, aws_lambda_function.cloudApi_get_my_url0_C529619B, aws_api_gateway_rest_api.cloudApi_api_2B334D75
```

### I expected this:

The `api.url` is a token that only resolves during deployment. Our simulator should prevent this type of cyclic dependency because it's a huge pain to only discover this when deploying to the cloud.

### Is there a workaround?

The solution to such an issue for now is to store this info in something like a bucket and load it from there.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
Isn't this error platform-specific? This is a terraform (or just our impl) limitation, not an intrinsic one (which is why it works in the sim).

I agree that it sucks to run into this at deploy time, but I think it should still be a preflight-time error specific to the platform. Is there a way to catch this before deploying? would https://github.com/winglang/wing/issues/4288 solve it (specifically, embedding `validate` into tf platforms)

**Comment by eladb** [comment]
Theoretically this is indeed platform specific but it is currently an issue for all supported platforms and any future platform I can think of (including Pulumi as far as I understand), so pragmatically I think this would be valuable to catch in the simulator as well.

**Comment by Chriscbr** [comment]
The simulator does fail when there are cyclic dependencies, see for example:

```js
bring cloud;

class A {
  var fn1Handler: inflight (): str;
  pub fn1: cloud.Function;
  new() {
    this.fn1Handler = inflight (): str => {
      return "stub";
    };

    this.fn1 = new cloud.Function(inflight () => {
      return this.fn1Handler();
    }) as "fn1";
    let fn2 = new cloud.Function(inflight () => {
      return this.fn1.invoke("");
    }) as "fn2";
    this.fn1Handler = inflight (): str => {
      return fn2.invoke("");
    };
  }
}

let a = new A();

test "test" {
  log(a.fn1.invoke(""));
}
```

wing compile:

```
Error: Dependency cycle detected: root/Default/A/fn1 => root/Default/A/fn2 => root/Default/A/fn1
```

**Comment by Chriscbr** [comment]
We have an existing issue for the problem of api.url introducing dependency cycles - let's continue the discussion there: https://github.com/winglang/wing/issues/2740
