### ISSUE TITLE
Wingly Update #27 (February 6, 2024)

### ISSUE THREAD

**Issue by NathanTarbert** [winglang/wing#5620]
Wingly Show #27 

- **Guests:** Huzaifa AsifHuzaifa Asif

- - **E-book title:** **Designing Scalable Systems: The Art of Growth: Scalable Solutions for Tomorrow**
- - **Amazong link:** https://www.amazon.com/dp/B0CS75FLD9

- **Event Link:** 

- **Preperation:** 

 - - @amielpb, can you please generate the thumbnail for this show?
 - - @MarkMcCulloh, can you please provide the music video you want to use?

- **Notes:** 
- - **Title:** The Wingly Update: Designing Scalable Systems with  Huzaifa AsifHuzaifa Asif
- - **Description:** Join us for an exciting interview with the author of the book: 

Designing Scalable Systems: The Art of Growth: Scalable Solutions for Tomorrow by Huzaifa AsifHuzaifa Asif. 

Show topics we will be covering:
- Guest interview
- Changelog
- Good first issue

**Comment by amielpb** [comment]
Thumbnail done, will also create the agenda overlays and add to the Streamyard broadcast

**Comment by amielpb** [comment]
Overlays done and in the Streamyard studio
