### ISSUE TITLE
no analytics events from wing cli since 0.57

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#5653]
### I tried this:

😢 
![image](https://github.com/winglang/wing/assets/1727147/093bbcb8-f4f9-497b-bcf7-520e3e4388a8)

### This happened:

I ain't seeing events 

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
@hasanaburayyan FYI

**Comment by hasanaburayyan** [comment]
I need to revive this PR so we catch this: https://github.com/winglang/wing/pull/4994

**Comment by ekeren** [comment]
@staycoolcall911 , @ainvoner 
Can we please prioritize this (very high)

**Comment by hasanaburayyan** [comment]
@ekeren This is only `wing run` commands right? It looks like segment source is still showing other CLI events since version 0.57 (console signin required)

**Comment by ainvoner** [comment]
@ekeren I do see cli__run events from 3.2 - 7.2

<img width="1714" alt="Screenshot 2024-02-08 at 20 19 13" src="https://github.com/winglang/wing/assets/2538825/aced568b-d8bf-40e4-bd87-06e2f46943e4">

**Comment by ekeren** [comment]
@ainvoner can you send the link 

Also, can you group by wing_version? It might be only installed (or it might be that I was wrong...)

**Comment by ainvoner** [comment]
latest wing version that reported `cli__run` was 0.56:
https://app.amplitude.com/analytics/monada/chart/gf1tz92y/edit/jcgkurjk

**Comment by ainvoner** [comment]
@ekeren a new event name was introduced: cli_sim_run since `0.56.13`
https://app.amplitude.com/analytics/monada/chart/gf1tz92y/edit/fv9allzh

**Comment by ainvoner** [comment]
@ekeren @hasanaburayyan 
from: https://github.com/winglang/wing/pull/5585
this one: https://github.com/winglang/wing/blob/3d3bbcb7cb33709ec992e115e894500276753e22/apps/wing/src/cli.ts#L152
and this is the output:
https://github.com/winglang/wing/blob/3d3bbcb7cb33709ec992e115e894500276753e22/apps/wing/src/analytics/collect.ts#L34

**Comment by hasanaburayyan** [comment]
After discussion with @ekeren and @ainvoner..

The analytics were not actually failing to send, rather they now come in with the Platform name in the metric, so downstreams of the segment need to update dashboards/monitors to expect updated naming convention. 

This also means that some analytics will be lost/ignored until users update their cli version, but this is acceptable for now.

closing issue..
