### ISSUE TITLE
`this` can be referenced from static methods

### ISSUE THREAD

**Issue by MarkMcCulloh** [winglang/wing#5656]
### I tried this:

```wing
class A {
  pub static f() {
    this;
  }
}
```

### This happened:

compiles

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
@MarkMcCulloh Is your code inside of an entrypoint file (a file that ends with `main.w` or `test.w`)?

If so it's not a bug. Your code would be basically equivalent to this:

```js
class App {
  new() {
    class A {
      pub static f() {
        this; // OK - we have a scope to access
      }
    }
  }
}
```

**Comment by MarkMcCulloh** [comment]
I suppose it's not a bug, but I feel like it looks strange in the context of a simple class at the root of the file. I'll close this if it's supposed to be intentional
