### ISSUE TITLE
Inference fails for optional function argument

### ISSUE THREAD

**Issue by MarkMcCulloh** [winglang/wing#5680]
### I tried this:

```wing
let sorted = (fn: ((num): void)?) => {};

sorted((a) => {});
```

### This happened:

Unable to infer type of `a`

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
@MarkMcCulloh this was fixed in #5681, right? Closing, please reopen if I misunderstood
