### ISSUE TITLE
App ID compiler switch

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#57]
I think we can perhaps add support for a "root id" for apps. Maybe we can support this as a compiler switch (or through some config file):

```sh
$ wing compile --appid deployment1
```

Maybe open an issue to track this idea in our roadmap.

_Originally posted by @eladb in https://github.com/monadahq/rfcs/pull/42#discussion_r952322543_

**Comment by eladb** [comment]
Keep

**Comment by eladb** [comment]
Keep

**Comment by Chriscbr** [comment]
This has since been added (see `--help` output below), so marking this as resolved.

```
Usage: wing compile [options] [entrypoint]

Compiles a Wing program

Arguments:
  entrypoint                                       program .w entrypoint

Options:
  -h, --help                                       display help for command
  -r, --rootId <rootId>                            App root id
```
