### ISSUE TITLE
Console does not recover after complaining that docker isn't running

### ISSUE THREAD

**Issue by bjrnt** [winglang/wing#5712]
### I tried this:

1. I ran `wing it` with the quickstart example
2. I added this to my `main.w` file:
```
bring ex;

new ex.DynamodbTable(name: "My Table", attributeDefinitions: {}, hashKey: "id");
```
3. I saw an error saying docker isn't running and that I need to start it.
4. I commented out the line with the DynamodbTable

### This happened:

The console kept showing a loading spinner in the right-hand pane and became largely unresponsive.

### I expected this:

I expected the console to recover from the error given that docker was no longer required.

### Is there a workaround?

Restart the console

### Wing Version

0.58.6

### Node.js Version

20.11.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
I'm able to reproduce this - thanks for the bug report @bjrnt!

**Comment by skyrpex** [comment]
The console had a fix a few release ago so doesn't get stuck anymore. If you happen to `wing it ` without docker started, you can use the reset button located in the status bar of the console to try again after you start docker.
