### ISSUE TITLE
Unable to find wing from "wing" (not in PATH).

### ISSUE THREAD

**Issue by aaditmshah** [winglang/wing#5713]
### I tried this:

I installed `winglang` globally using both pnpm and npm.

```zsh
$ pnpm i -g winglang
$ which wing
/home/aaditmshah/.local/share/pnpm/wing
$ wing -V
0.58.8
```

After that, I installed the VSCode Wing extension and use `wing new empty` to create a new wing project.

### This happened:

When I opened `main.w` in VSCode, I got the following error.

```
Unable to find wing from "wing" (not in PATH).
Install globally with `npm install -g winglang@latest`?
(Error: not found: wing)
```

I also set `wing.bin` to `/home/aaditmshah/.local/share/pnpm/wing` in my `settings.json` file. However, I got the following error.

```
wing not found at "/home/aaditmshah/.local/share/pnpm/wing"
```

This is weird because the `wing` binary is definitely at that path.

![Screenshot of the errors.](https://github.com/winglang/wing/assets/813511/fca23170-e0c0-4da1-b069-d8fa05f6ea2a)

### I expected this:

I expected the VSCode Wing extension to find the `wing` binary in the PATH. I also expected it to find it when I literally provided it the path by configuring `wing.bin`.

### Is there a workaround?

No. I can't use the VSCode Wing extension because of this issue.

### Anything else?

No. This is all the information I have.

### Wing Version

0.58.8

### Node.js Version

v21.5.0

### Platform(s)

Linux

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
Could you provide the logs available in the "Output" tab under the dropdown "Wing" when you try loading a wing file or changing the wing.bin?

<img width="957" alt="image" src="https://github.com/winglang/wing/assets/1237390/37b3bd71-ce42-407f-82ea-1fd8e7c31f3c">

**Comment by aaditmshah** [comment]
Here's the output I get when I try to load a wing file or change the `wing.bin`.

```
Setting up wing bin...
wing not found
Setting up wing bin...
Failed to get wing version from /home/aaditmshah/.local/share/pnpm/wing:
Error: Command failed: "/home/aaditmshah/.local/share/pnpm/wing" -V --no-update-check
/home/aaditmshah/.local/share/pnpm/wing: line 16: exec: node: not found
```

For some reason, it can't find the `node` binary either. However, if I run `wing -V --no-update-check` in my terminal then I get the correct output. Here's some more debug information.

```zsh
$ which wing
/home/aaditmshah/.local/share/pnpm/wing
$ wing -V --no-update-check
0.58.8
$ which node
/home/aaditmshah/.nvm/versions/node/v21.5.0/bin/node
$ node -v
v21.5.0
$ echo $PATH | tr : '\n'
/home/aaditmshah/.cabal/bin
/home/aaditmshah/.ghcup/bin
/home/aaditmshah/.local/share/pnpm
/home/aaditmshah/.nvm/versions/node/v21.5.0/bin
/usr/local/sbin
/usr/local/bin
/usr/bin
/home/aaditmshah/.local/share/flatpak/exports/bin
/usr/bin/site_perl
/usr/bin/vendor_perl
/usr/bin/core_perl
```

Here's the screenshot.

![Screenshot of debug output.](https://github.com/winglang/wing/assets/813511/a8f153a7-3dd2-471b-a785-1043b45fcbba)

**Comment by aaditmshah** [comment]
I should mention that I'm using [Zsh](https://en.wikipedia.org/wiki/Z_shell). The paths to `~/.local/share/pnpm` and `~/.nvm/versions/node/v21.5.0/bin` are added to my `PATH` in `.zshrc`. Could that be the problem? Perhaps, `.zshrc` is not being sourced before the `wing` binary is executed.

**Comment by aaditmshah** [comment]
It seems that not sourcing `.zshrc` was indeed the problem. I opened VSCode directly from my desktop environment. Hence, it didn't source `.zshrc`. So I tried opening VSCode from my terminal and now the wing extension is working as expected.

![Screenshot of the working wing extension.](https://github.com/winglang/wing/assets/813511/9a554eb5-d8e2-46b1-9e39-cb9d32bd3d31)

Although my problem has been resolved, I'll leave this issue open in case you want to take some action. Perhaps make a note of this edge case in your documentation. You can also close this issue if you want. Thank you for your help. I really appreciate it.

**Comment by revitalbarletz** [comment]
@aaditmshah how about joining our slack channel so that we can connect there as well? https://t.winglang.io/slack

**Comment by staycoolcall911** [comment]
I'll close this issue for now.
