### ISSUE TITLE
`bring slack`

### ISSUE THREAD

**Issue by eladb** [winglang/wing#5733]
### Use Case

Create Slack apps with Wing.

Ideally I want Wing to also *provision* the app for me so that I can update the app manifest from my Wing code.

When running in the simulator:
- in development (or Wing Cloud), the app needs to be provisioned in Slack (which implies that I need some kind of token).
- in test mode (`isTestEnvironment`) the library should basically behave as a mock and we need to figure out how to configure it's mocked behavior for testing.

Webhooks:
- When starting, the Slack library should configure the Slack app (through the manifest API) with the a webhook URL that will be associated with an API endpoint that calls the `onEvent` handlers.
- The should use the `cloud.Endpoint(url)` resource which is respected by Wing Cloud and all the app needs to do is automatically configure the Slack webhook to get to this endpoint.
- But when running in localhost, we want an "ngrok-like" tunnel that will be automatically created through the Wing Cloud service. Basically, when a `cloud.Endpoint` is instantiated locally, it will start a tunnel connected to your Wing Cloud account (@eladcon already has a prototype of this).

(Future) Auto-generate the permission scopes based on the Wing usage (e.g. which events I am listening to and which inflight methods I am calling).

### Proposed Solution

Sketch:

```js
bring slack;

const bot = new slack.App(
  manifest: {
    // slack app manifest
  }
);

bot.onEvent("app_mention", inflight (ctx, event) => {
  let mention = slack.AppMentionEvent.fromJson(event);
  let text = mention.text;

  let message = new slack.Message(); // <-- blocks api
  message.addHeader("Hello!");
  message.addSection(...);
  ctx.thread.post(message);
});
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by hasanaburayyan** [comment]
So some initial thoughts from first pass exploration. 

Creating a slack application from a manifest is trivial, so its definitely something we can do, where this process would then get a bit more complicated is installing the slack application into the workspace. Without installing it, theres no way to obtain the required oath token to perform actions on behalf of the app/user.

The issue with installing an app into a slack workspace is that it requires the `admin.apps.approve` permission which so far I have not found a way to provide to a `Configuration Token` (these are the tokens for working within workspace and creating app manifests)

Slack has [5 token types](https://api.slack.com/authentication/token-types#service) Bot/User/App tokens all have to be created within the scope of an App, so you could create an App and then generate a user token that has the required permissions for creating apps, and approving them into workspaces but then that means that before you create slack apps with wing you would need some sort of "App Factory" bootstrapping to the workspace.

Another option is `Service Tokens` which I have not tried yet but from the docs sounds like it would work. The issue these token types only work for `next-generation` slack platforms which Im not quite sure yet what that even means.

Alternatively we can also just make the install into workspace step manual part of the process, the downside here is if we are tearing down and recreating apps when developing in the sim then the ux is kinda crappy, and at that point it might just be Bring Your Own App Token (BYOAT)

--

All that said Im still exploring these service tokens to see if they fit the bill, but thought I would share early thoughts about this manifest idea in @eladb 's above proposal.

**Comment by hasanaburayyan** [comment]
> Basically after the app is created, users have to install it manually.

Yea I actually just realized that this wouldnt work on its own, since the required token (bot/app/user) that would be needed by the app is only generated after its installed into a workspace. 

Im going to play with this a bit more and read a bit deeper

**Comment by eladb** [comment]
@hasanaburayyan I suppose we can close this ceremoniously?

**Comment by hasanaburayyan** [comment]
> @hasanaburayyan I suppose we can close this ceremoniously?

Oh I thought I had attached this to the PR 😅 closing now..
