### ISSUE TITLE
no vite endpoint on terraform outputs

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#5749]
### I tried this:

following [Eyal's tutorial](https://www.winglang.io/docs/guides/react-vite-websockets) through the end, compiling to tf-aws and performing terraform apply.
main.w looks like that: 
```
bring vite;
bring cloud;
bring "./broadcaster.w" as b;

let broadcaster = new b.Broadcaster();
let api = new cloud.Api(cors: true);

new vite.Vite(
  root: "../frontend",
  publicEnv: {
    title: "Wing + Vite + React",
    API_URL: api.url,
    WS_URL: broadcaster.wsUrl
  }
);
let counter = new cloud.Counter();
api.get("/counter", inflight () => {
  return {
    status: 200, 
    body: "{counter.peek()}"
  };
});

api.post("/counter", inflight () => {
  let oldValue = counter.inc();
  broadcaster.broadcast("refresh");
  return {
    status: 200, 
    body: "{oldValue + 1}"
  };
});
```

### This happened:

<img width="657" alt="image" src="https://github.com/winglang/wing/assets/39455181/4eb4de27-0a18-4ce7-8088-507a7e3fd569">

only the API Gatway endpoint is listed, and the vite one isn't

### I expected this:

to show both vite app and api gw

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment]
It should be straightforward to include a `cloud.Endpoint` inside the Vite class. @eladcon can help

**Comment by ekeren** [comment]
@tsuf239 - I think this is it https://github.com/winglang/winglibs/pull/99

@eladcon can you please confirm
