### ISSUE TITLE
Support other cloud platforms.

### ISSUE THREAD

**Issue by wildaces215** [winglang/wing#5773]
### Use Case

While only on AWS, it would be nice to add features for WingLang to go to say Azure and Linode for a write once deploy anywhere model.  By doing so it could ease shifting cloud providers as a less painless transition. Or to be used to create test environments in different cloud environments to ensure maybe compliance or testing the best performance for said app.

**Comment by staycoolcall911** [comment]
Thanks for creating this issue @wildaces215 !
If I understand you correctly, this is actually one of the main benefits working with Wing's standard library (a.k.a WingSDK) and that is already supported today.

If you use the `cloud` package's abstractions (e.g. `cloud.Bucket`, `cloud.Queue`, etc.) in your Wing program, you can compile it to different platforms. We have a few built-in platforms that will yield the experience you're suggesting here: `tf-aws` (terraform for AWS), `tf-azure` (terraform for Azure) and `tf-gcp` (terraform for GCP).

You can read more about the Platforms concept in our docs: https://www.winglang.io/docs/concepts/platforms

I'll close this issue for now, but feel free to reopen of course if I misunderstood.
