### ISSUE TITLE
Playground error with `ex.DynamoDB`: `enoent spawn docker`

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#5783]
Playground reproduction [here](https://www.winglang.io/play?code=YgByAGkAbgBnACAAZQB4ADsACgAKAG4AZQB3ACAAZQB4AC4ARAB5AG4AYQBtAG8AZABiAFQAYQBiAGwAZQAoAAoAIAAgAG4AYQBtAGUAOgAgACIAdABhAGIAbABlACIALAAKACAAIABoAGEAcwBoAEsAZQB5ADoAIAAiAGkAZAAiACwACgAgACAAYQB0AHQAcgBpAGIAdQB0AGUARABlAGYAaQBuAGkAdABpAG8AbgBzADoAIAB7AAoAIAAgACAAIABpAGQAOgAgACIAUwAiACwACgAgACAAfQAsAAoAKQA7AAoA).

The code that triggers the issue is:

```wing
bring ex;

new ex.DynamodbTable(
  name: "table",
  hashKey: "id",
  attributeDefinitions: {
    id: "S",
  },
);
```

**Comment by skyrpex** [comment]
Fly is having an incident right now. I think that's the cause of the issue: https://status.flyio.net/

**Comment by MarkMcCulloh** [comment]
Did this ever work? The container running the console server was previously a plain node one, and now its a super minimal distroless image https://github.com/winglang/playground/pull/732

**Comment by skyrpex** [comment]
Maybe not, I don't really know. @eladcon when you have time, can you chime in?

**Comment by Chriscbr** [comment]
Closing since we have deprecated ex.DynamoDB in favor of the `dynamodb` [winglib](https://github.com/winglang/winglibs).
