### ISSUE TITLE
Simulator state is not remembered

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#5798]
### I tried this:

I wrote an app that has some state (a bucket and counter):

```js
bring cloud;

let b = new cloud.Bucket();
let c = new cloud.Counter();

new cloud.Function(inflight () => {
  b.put("file-{c.inc()}", "data");
});
```

Then I ran `wing it` in my terminal, and called the function a few times, which increased the counter and added files to the bucket.

I pressed ctrl + C in my terminal to stop the simulation.

Later, I ran `wing it` again to start the simulation again.

### This happened:

The counter is back to 0 and the bucket is empty

### I expected this:

The last state I had for the simulator was saved

### Wing Version

0.59.12

### Node.js Version

20.11.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
@skyrpex should the Wing Console be stopping the simulator when the user presses Ctrl + C so that the simulation state is saved?

**Comment by Chriscbr** [comment]
This may fix the problem where containers seem to keep running after the Wing Console is stopped

**Comment by skyrpex** [comment]
> @skyrpex should the Wing Console call `stop()` on the simulator and wait for it to finish when the user presses Ctrl + C so that the simulation state is saved?

Yeah, will check how the console is handling the interrupt signal...

**Comment by skyrpex** [comment]
Is it still happening to you? Using a globally installed `wing` works well for me (everything is stopped during Ctrl+C). Now, using npm scripts such as `npm run dev` doesn't really handle the interruption signals so resources don't get cleaned up.

**Comment by skyrpex** [comment]
Signal handling works as expected with the newest versions of npm (10.7.0) and pnpm (9.5.0), so the console can properly save the simulator state.

**Comment by skyrpex** [comment]
@Chriscbr feel free to reopen if it's still a problem to you.
