### ISSUE TITLE
this.node and nodeof(this) give different behaviors

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#5840]
### I tried this:

```js
class A {
  new() {
    this.node.hidden; // type checking error
    nodeof(this).hidden; // OK
    
    log("root:   " + this.node.root.node.path);
    log("nodeof: " + nodeof(this).root.node.path);
  }
}

new A();

test "a" {
  assert(2 == 2);
}

test "b" {
  assert(2 != 3);
}

```

### This happened:

Two visible differences in behavior

1. We see `this.node` does not have a hidden field, but the node returned by `nodeof()` does
2. If we comment out the previous error and run the tests, we see the following is logged:

root:   root
nodeof: root/env0
root:   root
nodeof: root/env1

This shows the "root" values are different also.

### I expected this:

No difference / or only one of the syntaxes to be allowed

### Is there a workaround?

We recommend only using `nodeof(this)`

### Anything else?

`nodeof(this)` returns a special Node instance, not the `Node` instance that normally exists on classes from the [constructs](https://github.com/aws/constructs) framework. Some of the differences in behavior are because

Perhaps we can hide the node field from classes extending `Construct` somehow

### Wing Version

0.59.12

### Node.js Version

20.9.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment]
I think we should just hide `.node` and only keep `nodeof()`.
