### ISSUE TITLE
Discussion: Allow collapsing and expanding map nodes

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#5861]
Think of a good approach to this.

**Comment by Chriscbr** [comment]
I imagine when nodes are collapsed, the connections will have to be combined in some way

<img width="683" alt="Screenshot 2024-05-09 at 12 21 36 PM" src="https://github.com/winglang/wing/assets/5008987/b4d5f8db-c916-4f0d-8fe0-3f3ebb38096c">

**Comment by polamoros** [comment]
Some thoughts:

* Add a button on the map action bar to collapse/expand all the container nodes
* How should we display a collapsed node? I imagine something like this:
<img width="307" alt="image" src="https://github.com/winglang/wing/assets/5547636/71f03301-1c68-46f6-8d20-0ccf94057134">
<img width="290" alt="image" src="https://github.com/winglang/wing/assets/5547636/18e1ee1c-5e29-4082-afed-23054fd69565">
* Should we hide the collapsed resources from the tree? For example, the bucket in this case:
<img width="942" alt="image" src="https://github.com/winglang/wing/assets/5547636/d62bc294-3a63-47f4-9a32-fc38d5c81287">
  * If we don't hide them, and the user clicks on one, I would expand the parent resource.
* What should we do with connections that go to an inner resource?

**Comment by skyrpex** [comment]
<img width="362" alt="image" src="https://github.com/winglang/wing/assets/1077520/bd4f2043-f4ed-401d-8cca-8860356f70e3">

In this scenario, I believe the node `c` should be always displayed, since it isn't really abstracted away by `b` but contained hierarchically.

In fact, I believe the construct hierarchy should be less preeminent in our map view. I don't mean removing hierarchy altogether but use the pseudo containers I created some weeks ago. There's also this idea of mine of being able to display some resources more than once, in a special way (e.g. 50% opacity), if the layout becomes simpler that way. Of course, the user would still see that with the resource ID that it belongs somewhere else. I'll prepare some mocks... maybe we could discuss it during one of our meetings.

**Comment by polamoros** [comment]
WIP

We have two proposals for the collapsing feature..

* Add the ability to collapse container nodes (easier)
It looks quite well in small applications, (even tho it causes jumps on the map that can't be easily fixed..)
https://github.com/winglang/wing/assets/5547636/5f5823e0-9ec0-4798-9e7f-79731985ec41

In bigger apps like wingcloud it doesn't really help too much and the UI jumps will increase..
https://github.com/winglang/wing/assets/5547636/5bd64bab-fdb3-456b-914e-6300dd27c2d4

* Another solution (@skyrpex proposal) is to expand the node on another layer, on top of the map.

Something like this
<img width="1113" alt="image" src="https://github.com/winglang/wing/assets/5547636/3d4192c0-615c-4042-8de2-158fe7577f4d">

**Comment by skyrpex** [comment]
> I like the first approach, though I can see how the sudden jump when the UI layout changes when you expand or collapse a node could be jarring. It could be nice to have some smooth animation when the nodes change layouts, but I'm not sure how hard that would be to add.

The problem is the possible total rearrangement of the nodes. We can suggest ELK to keep previous node positions with the interactive mode but not sure how well it holds. We should play with that feature a bit.

> maybe with breadcrumbs at the top to go back higher in the hierarchy.

That's exactly the idea, like what Unity folks do. Let's say `UI Canvas` is our class that abstracts some other nodes through inflight API:

<img width="641" alt="image" src="https://github.com/winglang/wing/assets/1077520/04311143-89d0-49fe-9fe5-9ed1557c0fef">

Then, we can dive in inside of `UI Canvas` (notice the header change in the tree, the breadcrumbs in the map and the buttons to go back):

<img width="557" alt="image" src="https://github.com/winglang/wing/assets/1077520/5eb3dc34-1a31-44c9-964f-3ed601b620a2">

**Comment by skyrpex** [comment]
> I imagine when nodes are collapsed, the connections will have to be combined in some way
> 
> <img alt="Screenshot 2024-05-09 at 12 21 36 PM" width="683" src="https://private-user-images.githubusercontent.com/5008987/329313560-b4d5f8db-c916-4f0d-8fe0-3f3ebb38096c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MDc1NjEsIm5iZiI6MTcxNjkwNzI2MSwicGF0aCI6Ii81MDA4OTg3LzMyOTMxMzU2MC1iNGQ1ZjhkYi1jOTE2LTRmMGQtOGZlMC0zZjNlYmIzODA5NmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjhUMTQ0MTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGU1ZTMyYTJiZWMyZjc3ZTY3MmVhMjM2NDYxNzc5ODA4MDQxYWI3Zjc4MTRiYjY5NTcxMzU1MzA1MTIzNWE5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Swtuz9HHdg_lnhpwCLjJiyC36_GtcmBy2VzQ6IhTGYk">

I like that. I feel like we don't need to display the inflights in the default map view. A simplified relationship (one relationship max between two nodes) helps by removing clutter.

Now, we could offer an additional view (called flows, maybe?) that show the inflight relationships of nodes.

**Comment by skyrpex** [comment]
These are the subtasks needed to implement my proposal:

- [ ] Implement context header in Tree view
   - [ ] Gray out hierarchy items that are invisible in the explorer
   - [ ] Double click on invisible items changes the context to the parent
- [ ] Implement context header in Map view
   - [ ] Implement breadcrumbs
   - [ ] Keep previous map visible, faded out in the background
- [ ] Compute subtree when inside a context
   - [ ] When inside of a context, direct relationships to outsider nodes must be shown too

None of the tasks above are hard to implement, but some refactors may be required to wire everything together.

**Comment by skyrpex** [comment]
<img width="819" alt="image" src="https://github.com/winglang/wing/assets/1077520/41abf573-c4b1-45d1-9a78-05efdfde7e5c">

<img width="818" alt="image" src="https://github.com/winglang/wing/assets/1077520/6da7e747-2b51-41ac-84ca-131485b6e84c">

<img width="855" alt="image" src="https://github.com/winglang/wing/assets/1077520/b7b58976-8a16-415c-a8be-4e49a81d01ab">

**Comment by polamoros** [comment]
Just for the record, this is how the WingCloud map looks right now

https://github.com/winglang/wing/assets/5547636/68612d2f-6527-4532-8e1e-ec21883c5a08

**Comment by polamoros** [comment]
<img width="1377" alt="image" src="https://github.com/winglang/wing/assets/5547636/032eb569-91ca-400e-9e4a-7f4ffbd6e144">

**Comment by skyrpex** [comment]
Notes from yesterday's meeting:

- List of resources by type would be useful
- Command bar to search
- Allow customizing the levels of detail (1 = hide all child nodes, 2 = show direct child nodes but hide deeper children, etc)
- Maybe use an algorithm that uses the number of resources and connections (e.g. if there’s more than 10 resources, hide the implementation details)
- Distinguish between the logical map view (simulator) and the infrastructure map view (tf-aws). They are different and will have different amounts of resources
- Yoav:
> Hey, two visual thoughts regarding how to show that the outer Function is accessing to the inner table of MyBucket in your example, without showing the inner Table:
>
> You can add a hole :hole:  and make the arrow point to it, hinting it's directly accesing something inside MyBucket
>
> You can make the arrow fade out inside MyBucket hinting that it's not really pointing to MyBucket but rather to something inside it.

**Comment by eladb** [comment]
I would keep this project contained and go for now with the in-place collapse/expand instead of the layers. It's more incremental and something that can move us forward faster without a huge investment (the layers are going to require a major ux design$.

Basically I vote to implement option 1 proposed in:

https://github.com/winglang/wing/issues/5861#issuecomment-2134999984

One thing I would add is that if I click to expand a node, the view should zoom in to show the expanded node.

I also suggested in the past that when a node is selected, the view will automatically zoom to show it. It will dramatically improve the navigatability of the map.

Let's keep this as incremental as possible because major ux changes now are going to take too much time and we need this capability asap. 

As a separate issue we should discuss search (command + P)
