### ISSUE TITLE
Connect to AWS infrastructure deployed on AWS, and interact with them from locally developed system

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#5879]
### Use Case

You can now develop only a portion of your system in wing and reference existing resources that are deployed on your remote dev environment.  This allows teams that have micro-stack to focus only on developing their own stack, while communicating with existing services. Wing Console support this behavior seamlessly, and although these resource are not simulated and are actually running on the cloud, you are able to view them and interact with them on the simulator. 

### Component

SDK, Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by garysassano** [comment]
I think this is related to #5170

**Comment by ekeren** [comment]
@garysassano 💯 

@eladb, lets start small. I would like to see:
```wing
bring cloud;

let bucket = aws.Bucket.byId("id123");
let counter = new cloud.Counter(initial: 1);
let queue = new cloud.Queue();

queue.setConsumer(inflight (message: str) => {
  let index = counter.inc();
  bucket.put("wing-{index}.txt", "Hello, {message}");
  log("file wing-{index}.txt created");
});
```
And some mapping file:
```
id123: ARN
```

Where the Bucket is something that is already deployed on my dev account on AWS.
And the result should that:
- The code works 
- The bucket look like a bucket in wing console

**Comment by ekeren** [comment]
The mapping file might be an overkill, but consider that different developers will have different mappings.

**Comment by ainvoner** [comment]
@ekeren can we close it?

**Comment by ekeren** [comment]
Yes. We can close this
