### ISSUE TITLE
`MutJson.del`

### ISSUE THREAD

**Issue by eladcon** [winglang/wing#5916]
### Use Case

want to delete a key of a json object

```wing
let x = MutJson{a:1};
x.del("a");
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by partha04patel** [comment]
If no one’s working on this/ no one minds, I could try giving this a shot!

**Comment by staycoolcall911** [comment]
Sounds good, @partha04patel - you got it!
In case you have any questions, you're welcome to ask them here or on our [Slack’s `#dev` channel](https://t.winglang.io/slack)

**Comment by staycoolcall911** [comment]
This was implemented in #6236
