### ISSUE TITLE
wing test with vite resource hangs

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#5938]
### I tried this:

create a main.w file with the following test and vite resource:
```

let my_vite = new vite.Vite(
  root: "../frontend",
) as "Vite"; 

test "test" {
  log("test");
  assert(true);
}
```
and run `wing test`

### This happened:

saws the correct output but the process hangs...
```
pass ┌ main.wsim » root/env0/test:test
     └ test
 
 
Tests 1 passed (1)
Test Files 1 passed (1)
Duration 0m2.85s
```

### Is there a workaround?

to see the correct output and the process to exit

### Wing Version

0.61.4

### Node.js Version

20.11.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skyrpex** [comment]
The Vite for the simulator starts a long running process (the vite process), which keeps running after the tests are finished.

```wing
    new cloud.Service(inflight () => {
      let url = Vite_sim.dev({
        root: props.root,
        publicEnv: props.publicEnv ?? {},
        // ...
      });
      state.set("url", url);
    });
```

AFAIK, there's no API in wing to listen to a "stop" event... @eladb @staycoolcall911 any ideas?

**Comment by eladb** [comment]
The `cloud.Service` handler should return a closure that is called on shutdown:

```js
new cloud.Service(inflight () => {
  log("startup");
  return () => {
    log("shutdown");
  }
});
```

If I recall, you proposed this API :-)

**Comment by staycoolcall911** [comment]
@skyrpex - Elad is correct, of course:
https://www.winglang.io/docs/standard-library/cloud/service#stopping-and-starting-a-service

**Comment by skyrpex** [comment]
🤦🏻
