### ISSUE TITLE
Add support for assigning resource names on class member declaration

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#5941]
### Use Case

The below code is not intuitive for me:

```ts
bring cloud;

class A {
  b1: cloud.Bucket;
  b2: cloud.Bucket;

  new () {
    this.b1 = new cloud.Bucket() as "B1";
    this.b2 = new cloud.Bucket() as "B2";
  }
}

new A();
```

It is not intuitive since it makes more sense that all the naming decisions are made in the declaration instead of initialization

### Proposed Solution

Be able to write it like this:

```ts
bring cloud;

class A {
  b1: cloud.Bucket as "B1";
  b2: cloud.Bucket as "B2";

  new () {
    this.b1 = new cloud.Bucket();
    this.b2 = new cloud.Bucket();
  }
}

new A();
```

### Implementation Notes

Maybe we can support both, but I think it is more correct to support in declaration only.
We also need to update the example in the compiler error in case we do this to show how to do it in a class

### Component

Language Design

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by eladb** [comment]
Related to https://github.com/winglang/wing/issues/4604 - maybe add your notes there and close as duplicate

**Comment by staycoolcall911** [comment]
Duplicates #4604
