### ISSUE TITLE
Update Docsite Opengraph Image

### ISSUE THREAD

**Issue by amielpb** [winglang/wing#5968]
### Use Case

The docsite preview thumbnail is of a dated image.
![image](https://github.com/winglang/wing/assets/95175829/1978c6fc-2ea1-46c6-ac0e-5af89c0f3740)

### Proposed Solution

Update the image to this file:
![opengraph-winglang](https://github.com/winglang/wing/assets/95175829/87497413-6bb6-4458-b9a1-228d9b2f8e91)

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by ainvoner** [comment]
@amielpb is this still relevant?

**Comment by ainvoner** [comment]
@boyney123 not sure if it is still relevant... I guess you will handle all relevant previews during your refactor and upgrades

**Comment by boyney123** [comment]
Yeah no problem, This new open graph image looks great. Will add it!

**Comment by boyney123** [comment]
Opened PR https://github.com/winglang/docsite/pull/952
