### ISSUE TITLE
Node title in Wing Console doesn't reflect it's ID

### ISSUE THREAD

**Issue by eladb** [winglang/wing#5994]
### I tried this:

```js
bring cloud;

new cloud.Queue() as "my-queue";
new cloud.Queue() as "your-queue";
```

### This happened:

![image](https://github.com/winglang/wing/assets/598796/7611c960-f835-45a6-b4a9-a683f30a0289)

### I expected this:

I expected to see `my-queue` and `your-queue` instead of `Queue` and `Queue` :-)

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
Related to https://github.com/winglang/wing/pull/5963

**Comment by ainvoner** [comment]
The current logic in the UI is simple:
- If the node's title has value - use the title. 

- Otherwise, use the node's name (if not assigned a custom name using `as`, the default node's name is the class name).

The issue here is that all of our cloud resources actually has a default `title` value.
For example (for cloud.Queue): 
```
    Node.of(this).title = "Queue";
    Node.of(this).description = "A distributed message queue";
```

**Comment by ekeren** [comment]
@ainvoner , in some cases the class name is a poor choice, for example `new tsoa.Service()` default is  **Service**.

**Comment by ekeren** [comment]
I think desired behavior should be:
- As the resource author I can decide what is the default name of a node 
```
    // Maybe
    Node.of(this).defaultTitle = "TSOA Service";
```
- If the user use the `as` functionality, it overrides the name on screen 
- If the user is using the ` Node.of(this).title = "Users Controller" ` is overrides the name on screen

**Comment by eladb** [comment]
We can just delete the default title from our sdk resources. I think it's redundant given the logic you described.

**Comment by ekeren** [comment]
Not in the case of `new react.App()` and `new tosa.Service()` where classes names (without the namespace) are not descriptive enough

**Comment by eladb** [comment]
@ekeren I see what you mean. We can open a new issue to implement something like `defaultTitle` as you suggest.
