### ISSUE TITLE
Console doesn't show resource names defined in "as"

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#5999]
### I tried this:

wrote this code:
```js
new cloud.Bucket() as "Custom Name";
```

### This happened:

the bucket is displayed in the console as "Bucket"

### I expected this:

The bucket to be displayed as "Custom Name"

### Wing Version

0.61.18

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Duplicates #5994
