### ISSUE TITLE
Distribute binaries for experimental Rust-based CLI

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#6035]
### Use Case

To allow users to start trying the experimental Rust-based CLI on common/popular platforms.

### Proposed Solution

Publish the binaries along with our GitHub releases perhaps? For example see https://github.com/BurntSushi/ripgrep/releases

### Implementation Notes

Consider looking at how other Rust-based CLIs do this

For now we'll assume the JavaScript runtime (Node.js) is an external dependency and doesn't need to be linked.

### Component

CLI

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by MarkMcCulloh** [comment]
https://github.com/axodotdev/cargo-dist looks beautiful

**Comment by Chriscbr** [comment]
Closing for now - l think we can revisit this if/when we get the Rust-based CLI further along
