### ISSUE TITLE
Add a validation during PR validation that all of the code samples in the docs compile without errors

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#6056]
### Use Case

We are making breaking changes almost every day and it is hard to make sure that our docs are properly up to date to reflect them. One of the most painful issues is that code samples throughout the docs can break and developers who copy them end up with code that doesn't compile. It makes it hard for them to learn.

### Proposed Solution

Add validation to our CI process that compiles all of these samples and makes sure that no errors occur

### Component

Documentation

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by staycoolcall911** [comment]
@ShaiBer, I think this duplicates #552
