### ISSUE TITLE
`cloud.Function` is timing out during a debugging session

### ISSUE THREAD

**Issue by eladb** [winglang/wing#6063]
### I tried this:

Debug a `cloud.Function`

### This happened:

The timeout caused my app to stop mid-flight

### I expected this:

When a debugger is attached, we should disable the timeout in the simulator

### Is there a workaround?

Manually set the timeout?

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
Duplicate of #5986
