### ISSUE TITLE
terraform security groups in `ex.Redis` are recreated

### ISSUE THREAD

**Issue by eladcon** [winglang/wing#6103]
### I tried this:

compile and deploy this (`tf-aws`)

```wing
bring ex;
bring cloud;

let api = new cloud.Api() as "api1";
// let ap2 = new cloud.Api() as "api2";

new ex.Redis();
```

security group id is `Redis_KEN25securityGroup_D3232AB7`

uncomment the second api creation and recompile and redploy

security group id is `Redis_KEN35securityGroup_E4111F48`

### This happened:

the id of the security group changed without touching the redis resource itself. this causes terraform to fail on deployment since the security group name itself didn't change

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Have you tried using the [Redis winglib](https://github.com/winglang/winglibs/tree/main/redis)?
We migrated `ex.Redis` on tf-aws to the winglib. We plan to also migrate the `sim` level to the winglib and once that's done we'll deprecate `ex.Redis`.

**Comment by staycoolcall911** [comment]
You're right, my mistake. `sim` is supported on the `redis` winglib, `tf-aws` still isn't.

**Comment by Chriscbr** [comment]
I think there's an issue in how the resource IDs are being generated - I noticed in the Terraform output for your example that the resource with a Terraform name of "Redis_KEN31securityGroup_2ECF73BF" is annotated with a construct path of "root/Default/Default/Redis/KEN.31]}securityGroup"

**Comment by Chriscbr** [comment]
I believe the plan's to move this code into the `redis` winglib: https://github.com/winglang/wing/issues/5857

**Comment by Chriscbr** [comment]
Closing as `ex.Redis` has been deprecated in favor of the redis winglib: https://github.com/winglang/winglibs/tree/main/redis
