### ISSUE TITLE
Support creating secrets through CLI

### ISSUE THREAD

**Issue by hasanaburayyan** [winglang/wing#6105]
### Use Case

Wing now supports creating secrets interactively through the CLI

Running the blow command will result in an interactive prompt where you can input the Slack credentials:

```bash
wing secrets main.w --create

2 secrets found in main.w

Enter the value for SLACK_SIGNING_SECRET: ********
Enter the value for SLACK_BOT_TOKEN: ********

Secrets saved to .env file
```

This results in a `.env` file being created with the secrets stored in it.

### AWS secret configuration

Just like the local configuration, the AWS configuration is done in the same way, but with the `-t tf-aws` flag:

```bash
wing secrets main.w --create -t tf-aws

2 secrets found in main.w

Enter the value for SLACK_SIGNING_SECRET: ********
Enter the value for SLACK_BOT_TOKEN: ********

Secrets saved to AWS Secrets Manager
```

### Proposed Solution

**Needs RFC**

### Implementation Notes

**Needs RFC**

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by staycoolcall911** [comment]
When implementing `wing secrets`, the team decided to leave `--create` out. I'll close this
