### ISSUE TITLE
Create `slack-bot` template

### ISSUE THREAD

**Issue by hasanaburayyan** [winglang/wing#6106]
### Use Case

**Placeholder**
Need to create a quick-start template for `wing new slack-bot` 

**Blocked by:**
https://github.com/winglang/wing/issues/5733

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by staycoolcall911** [comment]
We have that - closing
