### ISSUE TITLE
Cognito should not throw an exception for regular flow control

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#6109]
### I tried this:

Tried a simple setup of a `cloud.Api` with `cognito`. Ran `wing test`
```ts
bring cloud;
bring cognito;
bring expect;
bring http;

let api = new cloud.Api();
api.get("/hello", inflight (req) => {
  return  {
    status: 200
  };
});

let auth = new cognito.Cognito(api);
auth.get("/hello");

test "auth happy path" {
  auth.signUp("fakeId@wing.cloud", "This-is-my-test-99!");
  auth.adminConfirmUser("fakeId@wing.cloud");
  let token = auth.initiateAuth("fakeId@wing.cloud", "This-is-my-test-99!");
  let res = http.get("{api.url}/hello", headers: {
    "Authorization": "Bearer {token}"
  });
  expect.equal(res.status, 200);
}

test "auth wrong password" {
  auth.signUp("fakeId@wing.cloud", "This-is-my-test-99!");
  auth.adminConfirmUser("fakeId@wing.cloud");
  let token = auth.initiateAuth("fakeId@wing.cloud", "wrong-password-typing-with-kebab-fingers");
  let res = http.get("{api.url}/hello", headers: {
    "Authorization": "Bearer {token}"
  });
  expect.equal(res.status, 401);
}
```

### This happened:

1. Testing the happy path (with matching username/password) - works as expected (returns correctly with http code 200) ✅ 
2. Testing when passing a wrong password - an exception is thrown ❌ 

### I expected this:

When passing a wrong password I would like to get a result object telling me I passed `Invalid Credentials` instead of an exception.

### Is there a workaround?

Wrap the call to `cognito`'s `.initiateAuth(...)` with  a `try/catch` clause.

### Anything else?

Shouldn't use exceptions for regular flow control.

### Wing Version

0.65

### Node.js Version

20.11.1

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
>  I think AWS SDK behaviour is throwing an error when executing the initiateAuth API, so it makes sense the winglib will do the same

I agree. We are not creating an auth abstraction here (e.g. `@winglibs/auth`) this is `@winglibs/congnito` and the API should be similar to  the AWS version

**Comment by staycoolcall911** [comment]
I see your point. The dx was surprising to me, but maybe we can close this issue. If it seems useful to you, maybe add a docstring on that method explaining the behavior

**Comment by staycoolcall911** [comment]
Closing - the issue doesn't seem too relevant anymore.
