### ISSUE TITLE
bring ses

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#6173]
### Use Case

You can now use `winglibs/ses` to send emails from [Amazon Simple Email Service](https://aws.amazon.com/ses/)

This module works for tf-aws, awscdk and sim targets

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by staycoolcall911** [comment]
Done: https://github.com/winglang/winglibs/tree/main/ses
