### ISSUE TITLE
Support customizing domain for `@winglibs/react` app

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#6178]
### Use Case

Similar to how `cloud.Domain` can be used for customizing the domain of `cloud.Website`. See https://www.winglang.io/docs/standard-library/cloud/domain

### Component

Libraries

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by staycoolcall911** [comment]
Closed by https://github.com/winglang/winglibs/pull/190
