### ISSUE TITLE
dynamodb.Table with more than one attribute hangs in Wing Console

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#6203]
### I tried this:

```
// main.w
bring dynamodb;

new dynamodb.Table(
  attributes: [
    { name: "Name", type: "S" },
    { name: "Score", type: "N" },
  ],
  hashKey: "Name",
) as "EntiresTable";
```

### This happened:

Wing Console doesn't load.

If I run `wing test main.w` then it hangs

### Anything else?

Using @winglibs/dynamodb version 0.1.5

### Wing Version

0.68.2

### Node.js Version

20.12.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
I haven't figured out the root cause yet but if I comment out the second attribute ("Score") then the app seems to work.

@skyrpex any ideas? Maybe I'm configuring the table wrong?

**Comment by skyrpex** [comment]
I believe it's silently failing. You only need to define attributes that appear as the hashKey and sortKey.

**Comment by ainvoner** [comment]
@skyrpex @Chriscbr what is the conclusion here? Is it just making sure it won't fail silently and throw some kind of an error?

**Comment by skyrpex** [comment]
@ainvoner yes, we should wrap the code that creates the table and throw somehow to let the user know.
