### ISSUE TITLE
Postgres winglib does not retain state in simulator after reloading

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#6284]
### Use Case

Postgres db is currently losing its state when the simulator is reloaded. 
The use case here is to use postgres populated with some test data and avoiding having to re-populate the data frequently.

### Proposed Solution

The [Postgres Winglib](https://github.com/winglang/winglibs/tree/main/postgres) `sim` implementation should save state to a local dir, similar to what was done for `cloud.Bucket`s in #5164

### Implementation Notes

See #5164 which added this capability to `cloud.Bucket`s

### Component

Libraries

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by Chriscbr** [comment]
I tested this locally - the state is retained as long as `WING_ENABLE_INPLACE_UPDATES=true` is enabled in your shell.

We have an issue for removing this feature flag here https://github.com/winglang/wing/issues/6185, so I'll mark this resolved - @staycoolcall911 feel free to reopen if needed

**Comment by ekeren** [comment]
I expect to have it serialized between wing ribs and not just in
hotreloading

**Comment by ekeren** [comment]
I mean persistent between two new runs

**Comment by ekeren** [comment]
You'll notice that I am using this flag in package.json

**Comment by Chriscbr** [comment]
Ah, I misunderstood. Thanks @ekeren, makes sense 👍 

I'll look into this, it feels like there should be some way to do this with the `volumes` option in `sim.Container`
