### ISSUE TITLE
Wing Console Windows support

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#630]
### Summary

Ability to run Wing console on windows

### Component

Wing Console

Note: when this is done we should consider implementing #875

**Comment by ainvoner** [comment]
- [ ] CI multi-platform
- [x] tests
- [ ] artifacts
- [ ] S3 upload
- [x] icon
- [x] installer
- [x] quit app - zombies
- [x] open app using protocol
- [x] open app with file input
- [x] cancel file input - process still exists in task manager
- [x] application manu
- [ ] auto updater
- [x] multiple windows (simulators)
- [ ] update docs

**Comment by ekeren** [comment]
Nice work @ainvoner

**Comment by staycoolcall911** [comment]
Wow nice @ainvoner!!!
