### ISSUE TITLE
Preserve the API state after restarting the simulator

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#6315]
### Use Case

When interacting with an API through the Console, I need to fill in some request details such as the body, headers, and variables.

In some scenarios, such as when restarting the simulator, the API’s state is reset, and I need to re-enter all the values.

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by ekeren** [comment]
> In some scenarios, such as when restarting the simulator, the API’s state is reset, and I need to re-enter all the values.

:100 This happens a lot

**Comment by polamoros** [comment]
I think this was already fixed here:
https://github.com/winglang/wing/pull/6527
https://github.com/winglang/wing/pull/6288

I'm able to fill in some data in the API interaction view, remove the resource, continue using the console, and then recreate the API. The data is still there.

https://github.com/winglang/wing/assets/5547636/b9558a0e-2594-4c39-b630-0a211956e372
