### ISSUE TITLE
Can access `this` from static methods in entry point files

### ISSUE THREAD

**Issue by yoav-steinberg** [winglang/wing#6323]
### I tried this:
```wing
class Foo {
  pub static foo() {
    let x = this; // Expected `this` not to be defined since we're in a static method
  }
}

Foo.foo();
```
### This happened:

it compiles

### I expected this:

nd error that `this` is undefined

### Anything else?

This **might** be a feature and not a bug. But it does fail (correctly) on non entry-point files. WDYT?

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment]
I kind of feel like it's a feature?

**Comment by Chriscbr** [comment]
Right now it's intended behavior. Currently "this" in an entrypoint file can refer to the root of the app (handy for doing things with the construct tree). But it's possible this needs some more work to get right. Related: https://github.com/winglang/wing/issues/6058

**Comment by yoav-steinberg** [comment]
> Right now it's intended behavior.

Ok, for me this was kind of unexpected. Feel free to close this.

I'm also for getting rid of `this` in entry point files. We can have some builtin `app()` or something which is clearer and perhaps can work in non entry point files. I feel like we're abusing `this` (pun intended). But if you agree that's for another issue.

**Comment by Chriscbr** [comment]
Yes, I'm totally up for changing it so you need to use `thisApp` or something else to avoid the confusion

**Comment by yoav-steinberg** [comment]
Closing in favor of continued discussion in #6058
