### ISSUE TITLE
Impossible to work with `Json` in TypeScript without `as any`

### ISSUE THREAD

**Issue by eladb** [winglang/wing#6352]
### Use Case

In our SDK TypeScript code and in Wing code written in TypeScript, every API that accepts/returns `Json` is awkward to use because it basically requires `as any`.

For example:

```ts
import { cloud, lift, main } from "@wingcloud/framework";

main((root, test) => {
  const b = new cloud.Bucket(root, "Bucket");

  const fn = new cloud.Function(
    root,
    "Function",
    lift({ b }).grant({ b: ["putJson"]}).inflight(async (ctx) => {
      await ctx.b.putJson("hello", "world");
//                                 ^^^^^^^ Argument of type 'string' is not assignable to parameter of type 'Json'.ts(2345)

      return undefined;
    })
  );
});
```

### Proposed Solution

Not ideal but at least it will keep things within the framework and not escape the type system: perhaps we can offer some utility methods on the `Json` type to make it easy to construct:

```js
Json.fromString("hello");
Json.fromNumber(123);
Json.fromObject({ df: 123 });

Json.toString(myJsonString)
// ...
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by Chriscbr** [comment]
A helper named `asJson` was added for converting any values to `Json`, so something like this should now work:

```ts
import { cloud, lift, main, asJson } from "@wingcloud/framework";

main((root, test) => {
  const b = new cloud.Bucket(root, "Bucket");

  const fn = new cloud.Function(
    root,
    "Function",
    lift({ b }).grant({ b: ["putJson"]}).inflight(async (ctx) => {
      await ctx.b.putJson("hello", asJson("world"));
    })
  );
});
```

Closing
