### ISSUE TITLE
`aws.xxxRef` Resources Creates Unneeded TF Resources For `tf-aws`

### ISSUE THREAD

**Issue by hasanaburayyan** [winglang/wing#6383]
### I tried this:

```js
bring aws;

new aws.BucketRef("blah");
```

`wing compile -t tf-aws`

THEN

`tf apply`

### This happened:

~40 some resources are going to be made
<img width="561" alt="image" src="https://github.com/winglang/wing/assets/45375125/ea134973-c875-48d1-b933-6f5f5c796599">

### I expected this:

No resources

### Anything else?

I think this is because the ui fields we add for interacting with Refs in the simulator, and they are being turned into lambda functions in AWS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment]
Oh, seems like this is the resources used for the `ui` elements, no @Chriscbr ?

**Comment by Chriscbr** [comment]
> Oh, seems like this is the resources used for the `ui` elements, no @Chriscbr ?

Yup 👍 

Perhaps for now we can disable the ui elements from creating various child resources when you're compiling to non-sim targets, since Wing Console only works with simulated apps at the moment. ie

```js
if app.target != "sim" {
  // existing logic
}
```

**Comment by eladb** [comment]
👍
