### ISSUE TITLE
Verbose logging CLI flag

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#6405]
### Use Case

For debugging issues related to the lifecycle of simulator resources, serialization, or just to get more info in general, it's possible to stream verbose logs when running wing tests by passing the DEBUG=verbose environment variable

```
DEBUG=verbose wing test
```

It would be convenient if there was a dedicated CLI flag for this, like `--verbose`, `--debug=verbose`, or `--loglevel verbose` etc.

### Component

CLI

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by Chriscbr** [comment]
@MarkMcCulloh thoughts?

**Comment by MarkMcCulloh** [comment]
My pick would be `--traceLevel` or `--logLevel`, I don't have a strong feeling though.
As a side point, the `DEBUG` env is more of a compiler internal thing so I think whatever flag is added here should work perpendicular to it.

**Comment by Chriscbr** [comment]
For now the TRACE and DEBUG log levels in the simulator were collapsed into just DEBUG, so I'll leave this as closed until we have a need for more log levels.
