### ISSUE TITLE
Show winglibs in wing docs

### ISSUE THREAD

**Issue by eladb** [winglang/wing#6429]
### Use Case

We should make winglibs discoverable through the wing documentation. 

### Proposed Solution

At the minimum, just render a list with the description and links of winglibs like we have in the readme. It will go a long way to improve discoverability

Longer term we would want it to be a full catalog with api docs and all the magic

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by boyney123** [comment]
Think this is a great idea @eladb , the winglibs seem to be hidden at the moment.

First step maybe we can add some automation to pull in the READMES into the docs website? 
[I found this script on the docs site](https://github.com/winglang/docsite/blob/main/scripts/updateDocs.ts), maybe we can extend it? 

My thoughts:

1. Extend docs script to grab the README files from winglib. Using octokit.
2. When script is run on prebuild, it will fetch the required README wing libs and put them into our docs.

Next phase could be exploring API docs for winglibs.

Example below:

![Screenshot 2024-06-24 at 09 22 54](https://github.com/winglang/wing/assets/3268013/f8f9d7e6-cf4b-4ee2-a520-2819e0143daf)

**Comment by eladb** [comment]
The next step would be to implement something like `wing docs` which will generate API docs based on Wing docstrings (`///`). @yoav-steinberg @MarkMcCulloh @Chriscbr @staycoolcall911 any thoughts about the best way to do this? (probably deserves a separate issue).

**Comment by Chriscbr** [comment]
I found an issue for it here: https://github.com/winglang/wing/issues/4449

I think the most direct approach would be to add some docs-generating code to the existing compiler code in Rust and expose it through the CLI via `wing docs` (avoid coupling the toolchain to jsii-docgen for now). When we eventually have #6655 we can always revisit this.

**Comment by eladb** [comment]
I am wondering if it makes sense to generate .jsii manifest (+some custom annotations) instead and then use our variant of jsii-docgen that supports Wing.

**Comment by boyney123** [comment]
Winglibs are now in docs. We have more work to to include the APIs of the winglibs into the docs, but that work is captured here #6905, so going to close this one.
