### ISSUE TITLE
I want to be able to connect a Domain to an API GW

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#6451]
### Use Case

I have a front-end that is not served by Wing and needs to access a backend developed in Wing.
Therefore, all the API URLs and ports need to be hard-coded in the frontend code, so they can't change every deployment.

### Proposed Solution

I want to be able to connect a `cloud.API` to a domain and also be able to set a port for each route.

### Implementation Notes

This needs to work both locally and in the cloud. The local domain can be a path in local host.

### Component

Language Design

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by staycoolcall911** [comment]
[This discussion](https://winglang.slack.com/archives/C048QCN2XLJ/p1715270162072959) prompted @ShaiBer to open this issue.
