### ISSUE TITLE
Type Inference forcing to destructure object

### ISSUE THREAD

**Issue by thoroc** [winglang/wing#6462]
### I tried this:

I have a class as follow:

```rust
pub class MyHandler impl cloud.IFunctionHandler {
  _credentials: dynamodb.Credentials?;

  new(options: types.SessionHandlerOptions) {
    this._credentials = options.credentials;
  }
```

The struct for the options has the following:
```rust
pub struct SessionHandlerOptions {
  ...
  credentials: dynamodb.Credentials?;
}
```

In a follow up method on the class I can do:

```rust
    let client = new dynamodb.Client({
      tableName: this._table.tableName, 
      credentials: {
        accessKeyId: this._credentials?.accessKeyId!, 
        secretAccessKey: this._credentials?.secretAccessKey!
      }
    });
```

But not this

```rust
    let client = new dynamodb.Client({
      tableName: this._table.tableName, 
      credentials: this._credentials
    });
```

I am still trying to find my way around so apologies if it seems that I am writing the code the wrong way around. 

### This happened:

I am getting this error message:
```sh
Expected type to be "Credentials?", but got "Credentials?" instead
```

### I expected this:

To be able to assign the class property instead of having to destructure it and create a new object.

### Anything else?

Potential duplicate. 

### Wing Version

0.73.41

### Node.js Version

20.11.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by thoroc** [comment]
I have now tried the following:

1. hard code the values in the `main.w`:
```rust
let sessionDbConnection: dynamodb.Connection = {
  tableName: sessionTable.tableName,
  clientConfig: {
    endpoint: "http://localhost:3000",
    region: AwsRegion,
    credentials: {
      accessKeyId: "local",
      secretAccessKey: "local"
    },
  }
};
```
2. Pass them to the `handler.w`:
```rust
  new(options: types.SessionHandlerOptions) {
    this._credentials = options.clientOptions?.clientConfig?.credentials;
  }
```
3. Create the client instance:
```rust
    let client = new dynamodb.Client({
      tableName: this._table.tableName, 
      credentials: {
        accessKeyId: this._credentials?.accessKeyId!, 
        secretAccessKey: this._credentials?.secretAccessKey!
      }
    });
```

I am now encountering the following error:

```sh
UnrecognizedClientException: The security token included in the request is invalid.
```

I am either doing it wrong and cannot read the docs (sic) or the local isn't being respected.

**Comment by skyrpex** [comment]
@thoroc Is that still an issue with `@winglibs/dynamodb` `0.1.11`? Previously, there were two `Credentials` interfaces and now there's only one.

I think it's expected that two different interfaces can't be mixed, even if they have the same properties. I may be wrong, though. @MarkMcCulloh is that correct?

Anyways, the error message is confusing if both interfaces are named the same. Any ideas to improve it? Maybe referring to the filename where they are declared, if the names are the same?

**Comment by MarkMcCulloh** [comment]
> I think it's expected that two different interfaces can't be mixed @MarkMcCulloh is that correct?

Yeah, although I opened an issue to possibly change that behavior (for structs) https://github.com/winglang/wing/issues/6467

**Comment by thoroc** [comment]
> referring

I'll need to double check, although as per advice I've moved away from creating a client directly. 

I'll test it at first opportunity.

**Comment by thoroc** [comment]
@skyrpex The changes to the `dynamodb` has fixed the discrepancy. Thank you.

**Comment by staycoolcall911** [comment]
Nice! Thanks for following up @thoroc
