### ISSUE TITLE
DynamoDB Credential for sim

### ISSUE THREAD

**Issue by thoroc** [winglang/wing#6463]
### I tried this:

I have tried to hardcode the credentials for the sim as per the test: https://github.com/winglang/winglibs/blob/main/dynamodb/tests/connection.test.w

### This happened:

Still getting the following error message:
```sh
UnrecognizedClientException: The security token included in the request is invalid.
```

### I expected this:

The credentials to be accepted as is

### Is there a workaround?

Need to figure out how to give it actual credentials

### Anything else?

Might need to figure out if Wing is capable to read creds from Leapp: https://www.leapp.cloud/

### Wing Version

0.73.41

### Node.js Version

20.11.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by thoroc** [comment]
I have now tried the following:

1. hard code the values in the `main.w`:
```rust
let sessionDbConnection: dynamodb.Connection = {
  tableName: sessionTable.tableName,
  clientConfig: {
    endpoint: "http://localhost:3000",
    region: AwsRegion,
    credentials: {
      accessKeyId: "local",
      secretAccessKey: "local"
    },
  }
};
```
2. Pass them to the `handler.w`:
```rust
  new(options: types.SessionHandlerOptions) {
    this._credentials = options.clientOptions?.clientConfig?.credentials;
  }
```
3. Create the client instance:
```rust
    let client = new dynamodb.Client({
      tableName: this._table.tableName, 
      credentials: {
        accessKeyId: this._credentials?.accessKeyId!, 
        secretAccessKey: this._credentials?.secretAccessKey!
      }
    });
```

I am now encountering the following error:

```sh
UnrecognizedClientException: The security token included in the request is invalid.
```

I am either doing it wrong and cannot read the docs (sic) or the local isn't being respected.

**Comment by skyrpex** [comment]
Ideally, you don't have to create a DynamoDB client by yourself. You should use the inflight API of the table directly, as in:

```wing
let table = new dynamodb.Table(...);

new cloud.Function(inflight () => {
  table.get(...);
});
```

The credentials, client instantiation and function permissions are managed for you this way.

**Comment by MarkMcCulloh** [comment]
Part of the confusion is that there are two structs called "Credentials" in the dynamodb winglib.
1. https://github.com/winglang/winglibs/blob/d457129c67d3b0764a834d429642aae42fdeb28e/dynamodb/dynamodb-types.w#L184
2. https://github.com/winglang/winglibs/blob/d457129c67d3b0764a834d429642aae42fdeb28e/dynamodb/dynamodb-client.w#L16

So wing considers these different types, and currently we don't structurally type check these so it fails (opened #6467 for this).
Also worth noting the second is not public, so https://github.com/winglang/wing/issues/4655 is related as well.

**Comment by thoroc** [comment]
@skyrpex I have followed your suggestion and used a `dynamodb.Table` directly.

**Comment by thoroc** [comment]
@MarkMcCulloh Ok so already known issue. Feels free to close this. Thank you.

**Comment by skyrpex** [comment]
> Part of the confusion is that there are two structs called "Credentials" in the dynamodb winglib.

Good catch, I can refactor that...
