### ISSUE TITLE
playground is not loading (inconsistent) 

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#6479]
### I tried this:

I hope you can reproduce it, it is pretty consistent on my device (but sometime it works)

### This happened:

Stuck in "Compiling..."
![image](https://github.com/winglang/wing/assets/1727147/143dbcc2-573b-40de-9871-269204638e54)

### Wing Version

0.73.44

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
also, for https://www.winglang.io/play/?code=LwAvACAAVABoAGkAcwAgAGkAcwAgAHQAaABlACAAaQBtAHAAbwByAHQAIABzAHQAYQB0AGUAbQBlAG4AdAAgAGkAbgAgAFcAaQBuAGcALgAKAC8ALwAgAEgAZQByAGUAIAB3AGUAIABiAHIAaQBuAGcAIAB0AGgAZQAgAFcAaQBuAGcAIABzAHQAYQBuAGQAYQByAGQAIABsAGkAYgByAGEAcgB5ACAAdABoAGEAdAAKAC8ALwAgAGMAbwBuAHQAYQBpAG4AcwAgAGEAYgBzAHQAcgBhAGMAdABpAG8AbgBzACAAbwBmACAAcABvAHAAdQBsAGEAcgAgAGMAbABvAHUAZAAgAHMAZQByAHYAaQBjAGUAcwAuAAoAYgByAGkAbgBnACAAYwBsAG8AdQBkADsACgAKAC8ALwAgAFQAaABpAHMAIABjAG8AZABlACAAZABlAGYAaQBuAGUAcwAgAGEAIABiAHUAYwBrAGUAdAAgAGEAcwAgAHAAYQByAHQAIABvAGYAIAB5AG8AdQByACAAYQBwAHAALgAKAC8ALwAgAFcAaABlAG4AIABjAG8AbQBwAGkAbABpAG4AZwAgAHQAbwAgAGEAIABzAHAAZQBjAGkAZgBpAGMAIABjAGwAbwB1AGQAIABwAHIAbwB2AGkAZABlAHIACgAvAC8AIABpAHQAIAB3AGkAbABsACAAYgBlACAAcwB1AGIAcwB0AGkAdAB1AHQAZQBkACAAYgB5ACAAYQBuACAAaQBtAHAAbABlAG0AZQBuAHQAYQB0AGkAbwBuACAAZgBvAHIACgAvAC8AIAB0AGgAYQB0ACAAYwBsAG8AdQBkAC4AIABJAC4AZQAsACAAZgBvAHIAIABBAFcAUwAgAGkAdAAgAHcAaQBsAGwAIABiAGUAIABhAG4AIABTADMAIABCAHUAYwBrAGUAdAAuAAoAbABlAHQAIABiAHUAYwBrAGUAdAAgAD0AIABuAGUAdwAgAGMAbABvAHUAZAAuAEIAdQBjAGsAZQB0ACgAKQA7AAoACgAvAC8AIAAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEACgAvAC8AIABZAG8AdQAgAGMAYQBuACAAaQBuAHQAZQByAGEAYwB0ACAAdwBpAHQAaAAgAHQAaABlACAAYQBwAHAAIABpAG4AIAB0AGgAZQAgAGMAbwBuAHMAbwBsAGUAIAAtAC0APgAKAC8ALwAKAC8ALwAgAEMAbABpAGMAawAgAG8AbgAgAHQAaABlACAARgB1AG4AYwB0AGkAbwBuACwAIABhAG4AZAAgAHQAaABlAG4AIABpAG4AdgBvAGsAZQAgAGkAdAAgAGkAbgAgAHQAaABlAAoALwAvACAAbABvAHcAZQByACAAcgBpAGcAaAB0ACAAcABhAG4AZQBsACwAIABvAHIAIABjAGwAaQBjAGsAIABvAG4AIAB0AGgAZQAgAEIAdQBjAGsAZQB0AAoALwAvACAAdABvACAAcwBlAGUAIABpAHQAcwAgAGMAbwBuAHQAZQBuAHQAcwAgAGkAbgAgAHQAaABlACAAcABhAG4AZQBsACwAIABlAHQAYwAuAAoALwAvACAAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhACEAIQAhAAoACgAvAC8AIABgAGkAbgBmAGwAaQBnAGgAdABzAGAAIAByAGUAcAByAGUAcwBlAG4AdAAgAGMAbwBkAGUAIAB0AGgAYQB0ACAAcgB1AG4AcwAgAGwAYQB0AGUAcgAsACAAbwBuAAoALwAvACAAbwB0AGgAZQByACAAbQBhAGMAaABpAG4AZQBzACwAIABpAG4AdABlAHIAYQBjAHQAaQBuAGcAIAB3AGkAdABoACAAYwBhAHAAdAB1AHIAZQBkACAAZABhAHQAYQAgAGEAbgBkAAoALwAvACAAcgBlAHMAbwB1AHIAYwBlAHMAIABmAHIAbwBtACAAdABoAGUAIABwAHIAZQAtAGYAbABpAGcAaAB0ACAAcABoAGEAcwBlAC4ACgBsAGUAdAAgAGgAZQBsAGwAbwBfAHcAbwByAGwAZAAgAD0AIABpAG4AZgBsAGkAZwBoAHQAIAAoACkAIAA9AD4AIAB7AAoAIAAgAGIAdQBjAGsAZQB0AC4AcAB1AHQAKAAiAGgAZQBsAGwAbwAuAHQAeAB0ACIALAAgACIASABlAGwAbABvACwAIABXAG8AcgBsAGQAIQAiACkAOwAKAH0AOwAKAAoALwAvACAASQBuAGYAbABpAGcAaAB0AHMAIABjAGEAbgAgAGIAZQAgAGQAZQBwAGwAbwB5AGUAZAAgAGEAcwAgAHMAZQByAHYAZQByAGwAZQBzAHMAIABmAHUAbgBjAHQAaQBvAG4AcwAKAG4AZQB3ACAAYwBsAG8AdQBkAC4ARgB1AG4AYwB0AGkAbwBuACgAaABlAGwAbABvAF8AdwBvAHIAbABkACkAOwAKAAoALwAvACAAkSEgAFMAdwBpAHQAYwBoACAAZgBpAGwAZQBzACAAYQBuAGQAIABzAGUAZQAgAG8AdABoAGUAcgAgAGUAeABhAG0AcABsAGUAcwAgAHcAaQB0AGgAIABtAG8AcgBlAAoALwAvACAAZQB4AHAAbABhAG4AYQB0AGkAbwBuAHMAIABhAGIAbwB2AGUALgAKAA%3D%3D

![Screenshot 2024-05-15 at 9 47 31](https://github.com/winglang/wing/assets/2538825/7c1e4981-d752-414e-933a-a0e30e3efc5d)

missing an inflight function in bucket - after trigger a recompile by change something in the code - it looks OK
