### ISSUE TITLE
rename refactor for class/struct/interface members

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#6484]
### Use Case

currently, we can't rename class properties, structs keys, and interface keys since it wasn't supported on #6461 

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by eladb** [comment]
Can we at least not give the user a false sense that this is supported until this actually works?

Currently the feature feels broken...

**Comment by tsuf239** [comment]
> Can we at least not give the user a false sense that this is supported until this actually works?
> 
> Currently the feature feels broken...

yes, as soon as we implement this: https://github.com/winglang/wing/issues/6564
