### ISSUE TITLE
playground and console doesn't render properly on hot reloading

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#6503]
### I tried this:

How to reproduce:
1. Implement the following code:
```wing
bring cloud;

let q = new cloud.Queue();
let b = new cloud.Bucket();

// q.setConsumer(inflight (m: str) => {
//   b.put("latest.txt", m);
// });

// new cloud.Function(inflight (s: str?) => {
//   log("Function was called with {s!}");
//   q.push(s!);
// });
```

2. Run `wing it`
3. Un-comment all the commented lines, the browser will show:
![image](https://github.com/winglang/wing/assets/1727147/18fb5cb8-3d34-451f-86c8-2d9e37bb0078)

If I open another tab on localhost:3000, it will be:
![image](https://github.com/winglang/wing/assets/1727147/f57503cb-8441-4718-9c8f-d994bb5ef94e)

I've also noticed this when running the learn experience (after seeing a drop in conversations) 
![image](https://github.com/winglang/wing/assets/1727147/b0aa44e8-f7f9-41fc-b260-3e6abc5778aa)

### This happened:

wing console doesn't re-render correctly

### Wing Version

0.73.46

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
@eladcon  I think it is related to the initial issue of rendering the map.

**Comment by ekeren** [comment]
Right, it is happening on wing running locally (and on the playground)

**Comment by skyrpex** [comment]
I think it's related to z-indices and sorting. I'll check it out.

**Comment by ainvoner** [comment]
was resolved after reverting the map V2 PR
