### ISSUE TITLE
PNPM issue: missing dependencies for dynamodb

### ISSUE THREAD

**Issue by thoroc** [winglang/wing#6522]
### I tried this:

I have just upgraded to `0.74.0` of `Wings` and `0.1.9` of `@winglibs/dynamodb` and attempting to compile the project again, I am getting the following errors:

```sh
error: Unable to load "cdktf": Module not found in "/Users/thomas.roche/Projects/github/thoroc/kingfisher/node_modules/@winglibs/dynamodb/dynamodb.tf-aws.w"
  --> node_modules/@winglibs/dynamodb/dynamodb.tf-aws.w:3:1
  |
3 | bring "cdktf" as cdktf;
  | ^^^^^^^^^^^^^^^^^^^^^^^


error: Unable to load "@cdktf/provider-aws": Module not found in "/Users/thomas.roche/Projects/github/thoroc/kingfisher/node_modules/@winglibs/dynamodb/dynamodb.tf-aws.w"
  --> node_modules/@winglibs/dynamodb/dynamodb.tf-aws.w:4:1
  |
4 | bring "@cdktf/provider-aws" as tfaws;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


error: Unknown symbol "tfaws"
   --> node_modules/@winglibs/dynamodb/dynamodb.tf-aws.w:44:10
   |
44 |   table: tfaws.dynamodbTable.DynamodbTable;
   |          ^^^^^


error: Unknown symbol "tfaws"
   --> node_modules/@winglibs/dynamodb/dynamodb.tf-aws.w:49:22
   |
49 |     this.table = new tfaws.dynamodbTable.DynamodbTable({
   |                      ^^^^^


error: Unknown symbol "tfaws"
    --> node_modules/@winglibs/dynamodb/dynamodb.tf-aws.w:111:11
    |
111 |       new tfaws.lambdaEventSourceMapping.LambdaEventSourceMapping(
    |           ^^^^^


error: "unresolved" is not a legal JSON value
    --> node_modules/@winglibs/dynamodb/dynamodb.tf-aws.w:113:27
    |
113 |           eventSourceArn: this.table.streamArn,
    |                           ^^^^^^^^^^^^^^^^^^^^
```

I have attempted to add [cdktf](https://www.npmjs.com/package/cdktf) and [@cdktf/provider-aws
](https://www.npmjs.com/package/@cdktf/provider-aws) as dependencies thinking that would be the issue, but the errors remained the same.

### This happened:

I did not expect breakage.

### I expected this:

The code to compile.

### Is there a workaround?

Use `npm` instead works fine.

### Anything else?

Steps to reproduce: 

1. clone: https://github.com/thoroc/kingfisher
2. `cd` to the directory
3. run `pnpm i`
4. run `pnpm run compile`

### Wing Version

0.74.0

### Node.js Version

20.11.0

### Package Manager

Pnpm

### Package Manager Version

9.1.1

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skyrpex** [comment]
The error message is misleading, but you almost got it there: you need to also add the `constructs` package.

This is the error message after adding `cdktf`:

```
Failed to compile.

error: Cannot find jsii module "cdktf" in source directory: Unable to load "constructs": Module not found from "/Users/cristian/Code/kingfisher/node_modules/cdktf"
  --> node_modules/@winglibs/dynamodb/dynamodb.tf-aws.w:3:1
  |
3 | bring "cdktf" as cdktf;
  | ^^^^^^^^^^^^^^^^^^^^^^^
```

There's an open issue for this missing dependencies somewhere, I'll look for it.

**Comment by Chriscbr** [comment]
Wing doesn't officially support the pnpm package manager right now (issue with further discussion: https://github.com/winglang/wing/issues/6129), but we've recently added a compilation warning for if we detect you're using pnpm. Closing
