### ISSUE TITLE
`bring momento;` library for Momento serverless cache

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#6524]
### Use Case

[Momento](https://www.gomomento.com/) provides a serverless cache service that's relatively easy to set up and doesn't require an AWS account. There are Terraform bindings that should make it easy to model the infrastructure in a Wing class.

### Proposed Solution

```js
bring cloud;
bring moment;

let cache = new momento.Cache();

new cloud.Function(inflight() => {
  cache.set("key", "value");
  cache.get("key");
  // etc.
});
```

### Implementation Notes

Implementing the library will be simplified if we can easily generate Wing bindings for arbitrary Terraform modules (https://github.com/winglang/wing/issues/4922)

### Component

Libraries

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Discord](https://t.winglang.io/discord).

**Comment by eladb** [comment]
Wow, I didn't know that they have Terraform bindings. Cool!

**Comment by Chriscbr** [comment]
Implemented in https://github.com/winglang/winglibs/pull/259
