### ISSUE TITLE
No syntax highlighting when logging JSON objects

### ISSUE THREAD

**Issue by eladb** [winglang/wing#6580]
### I tried this:

```js
new cloud.Function(inflight () => {
  let blob = { hello: 123, world: "hello" };
  log(blob);
});
```

### This happened:

<img width="279" alt="image" src="https://github.com/winglang/wing/assets/598796/784c1345-b96f-40c2-aebb-8adfb0439e83">

### I expected this:

<img width="314" alt="image" src="https://github.com/winglang/wing/assets/598796/5eec083e-2262-4ae8-952a-bb7bdf7820c0">

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
Note: if you log a `Json` object in preflight and run `wing compile`, the text is colored on most terminals -- but this is mostly a side effect of how we're emitting `console.log()` in JavaScript preflight code. If you log something inflight and run `wing test` it's still uncolored:

<img width="295" alt="Screenshot 2024-05-28 at 3 00 21 PM" src="https://github.com/winglang/wing/assets/5008987/784646af-d994-4821-96dc-72369aea3a93">

It might be worthwhile to unify how logs are colored across all of these areas (preflight STDOUT, wing test STDOUT, and the Wing Console UI)

**Comment by skyrpex** [comment]
We have a `TextHighlight` component so it should be easy to highlight the log entries.

@Chriscbr worth having a discussion! Not sure if the benefits are worth the effort, though 👀
