### ISSUE TITLE
IDE completion shows internal APIs

### ISSUE THREAD

**Issue by eladb** [winglang/wing#6583]
### I tried this:

Dot complete a preflight object

### This happened:

<img width="706" alt="image" src="https://github.com/winglang/wing/assets/598796/2c27ac76-5d62-4109-ba0e-1562e1ade028">

### I expected this:

I think we should figure out a way to hide `toString`, `onLift`, and `node` from this list because they are internal APIs.

As an initial implementation maybe we can just add something like a `@hidden` doctag and hide them from the IDE completion list (I believe we will need to hard-code the addition of `@hidden` to `constructs.Construct` in the JSII importer because we can't modify the source).

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by MarkMcCulloh** [comment]
What version of the CLI are you using? In the latest LSP rework ([v0.74.17](https://github.com/winglang/wing/releases/tag/v0.74.17)) members inherited from the `constructs` lib and from `Resource` should be hidden in completions.

**Comment by eladb** [comment]
Okay! Let me recheck

**Comment by staycoolcall911** [comment]
@eladb - can we close this?

**Comment by eladb** [comment]
Yap looks good
