### ISSUE TITLE
Timeout when closing `cloud.Api` in the simulator

### ISSUE THREAD

**Issue by eladb** [winglang/wing#6610]
### I tried this:

Use `cloud.Api` in the simulator

### This happened:

Occasionally, when working with `cloud.Api`, the simulator hangs when trying to stop the API service.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
Hey @eladb, looking for how we can reproduce this more easily - have you worked any Wing apps where this issue happens more often? Maybe there's a project we can investigate to narrow down the problem.

**Comment by eladb** [comment]
I am just playing around with the `bring slack` test and ran into this issue.
