### ISSUE TITLE
Merge to main only when the team's working hours

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#6628]
### Use Case

To avoid failure of the main build, which triggers on-call notification in the early morning, we can try to merge to main only at certain hours and days, preferably the working hours of our different sites, but waking hours are good too :)

### Proposed Solution

chatGPT says we can do it with a mergify condition
https://chatgpt.com/share/c30c3b21-1799-43d6-bb4c-373420096e6e

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Discord](https://t.winglang.io/discord).

**Comment by eladb** [comment]
Not sure I agree that's the right approach. If we want to prevent off hours oncall alerts we should configure pagerduty to treat build failures as a less severe case.

**Comment by eladb** [comment]
@tsuf239 if that's okay, I am closing for now.
