### ISSUE TITLE
intrinsic function doesn't have struct expansion and signature completion 

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#6647]
### I tried this:

try using `@inflight(...)`  inside vscode and noticed that it is missing struct expansion and signature completion 

### This happened:

it is missing 

### Wing Version

0.74.17

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
Closing since `@inflight` has been deprecated
