### ISSUE TITLE
wing run crash when using `@inflight(..)` on an un-existing file

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#6649]
### I tried this:

```
wing run main.w
```

```wing
bring cloud;
let bucket = new cloud.Bucket();

bucket.onCreate(@inflight("./bucket_create.ts"));
```

if `bucket_create.ts` doesn't exists, wing run will crash

### This happened:

wing run crashed

### Wing Version

0.74.17

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
Closing since `@inflight` has been deprecated
