### ISSUE TITLE
Application with a single resource should be expanded by default in the Console

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#6657]
### Use Case

Collapsed Wing application with a single resource looks strange in the Console.
UX improvement in addition to https://github.com/winglang/wing/issues/6645

### Proposed Solution

If a Wing application has only one resource, show expanded view of this resource by default

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Discord](https://t.winglang.io/discord).

**Comment by polamoros** [comment]
Done here 
https://github.com/winglang/wing/issues/6645
