### ISSUE TITLE
util.env not reading string correctly

### ISSUE THREAD

**Issue by springbok** [winglang/wing#6677]
### I tried this:

Here is an example string in my .env:
```sh
AI_PASSWORD="$2b$fsafrrewru3DSVF12$dnZV3fssfiV4Y1D/6MdCNBthKLKSj24560uXEH2zfHK9IMEK43GkcvF9YUTWzJcGJK"
```
And read it using:
```sh
util.env("AI_PASSWORD")
```
### This happened:

It returns a partial string rather than the full string:
```sh
/6MdCNBthKLKSj24560uXEH2zfHK9IMEK43GkcvF9YUTWzJcGJK
```

### I expected this:

I expected to get the full string back:
```sh
$2b$fsafrrewru3DSVF12$dnZV3fssfiV4Y1D/6MdCNBthKLKSj24560uXEH2zfHK9IMEK43GkcvF9YUTWzJcGJK
```
### Is there a workaround?

I've hard coded the string for now.

### Wing Version

0.74.38

### Node.js Version

v20.13.0

### Platform(s)

Linux

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment]
@springbok thanks for reporting. This looks like a nasty one

**Comment by eladb** [comment]
Closing for now as this doesn't seem to be an issue.
