### ISSUE TITLE
Eslint rule for SDK - only allow barrel imports to cdktf providers

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#669]
### Summary

Add an eslint rule to the SDK for development that disallows direct imports to @cdktf/aws-provider

### Feature Spec

The Wing SDK library uses `@cdktf/aws-provider` as one of its dependencies. Importing namespaces or constructs from the root of `@cdktf/aws-provider`, like so:

```ts
import { dynamodbTable } from "@cdktf/provider-aws";
```

... is problematic because it takes much longer to import, even on very fast machines (10+ seconds). The best way to import cdktf constructs (also recommended in the cdktf 0.13 docs) is by using their full import path:

```ts
import { DynamodbTable } from "@cdktf/provider-aws/lib/dynamodb-table";
```

### Use Cases

N/A

### Implementation Notes

Could be implemented as an eslint plugin. For inspiration, take a look at how the AWS CDK monorepo includes its own eslint-plugin package: https://github.com/aws/aws-cdk/tree/main/tools/%40aws-cdk/eslint-plugin

### Component

SDK, Contributor Experience

**Comment by staycoolcall911** [comment]
Keep

**Comment by Chriscbr** [comment]
Closing since we are now generating cdktf bindings during the build (no longer using `@cdktf/provider-blah` libraries) so this doesn't apply anymore.
