### ISSUE TITLE
create a folder on cloud.Bucket

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#6726]
### Use Case

Mimic the following code that uses S3 SDK directly to create a folder
```js
var AWS = require("aws-sdk");
var s3 = new AWS.S3();

var params = { 
  Bucket: "mybucket", 
  Key: "mykey/"  // notice trailing backslash 
}; 

s3.putObject(params).promise();
```

### Proposed Solution

```wing
bucket.addFolder(key);
```

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Discord](https://t.winglang.io/discord).

**Comment by Chriscbr** [comment]
reference: https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-folders.html

I'm curious, if a folder in S3 is just an object whose key has a trailing slash and the contents are 0 bytes, is it possible to achieve this already using cloud.Bucket today?

```js
bucket.put("folder/", "");
```

**Comment by hasanaburayyan** [comment]
So I think this could spark some heated debates 😁 but none of the major 3 cloud providers actually have folders. They all use a flat structure and their consoles give ways to mimic folder structures.

I think @Chriscbr work around would probably work to make a 0 byte object, with the disclaimer that this is only useful for the AWS S3 Console view.

I think adding a dedicated API on bucket that mentions `folder` would be a misnomer.

**Comment by ekeren** [comment]
I like @Chriscbr suggestion , it solves my issue

**Comment by Chriscbr** [comment]
Marking as resolved
