### ISSUE TITLE
`python.InflightBucketEvent` should be renamed to `python.InflightBucketEventHandler`

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#6728]
### I tried this:

We need to have Handler suffix on all python Handlers

### This happened:

NA

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Should be easy to rename in the [python winglib](https://github.com/winglang/winglibs/tree/main/python)

**Comment by DoronV** [comment]
Does this only apply to InflightBucketEvent, or also to the other handlers in the lib/file?

**Comment by revitalbarletz** [comment]
> Does this only apply to InflightBucketEvent, or also to the other handlers in the lib/file?

Other handlers as well! Would you like to take this one?
