### ISSUE TITLE
wing test -t sim stopped working after wing update

### ISSUE THREAD

**Issue by asterkin** [winglang/wing#6800]
### I tried this:

wing test -t sim test/*.w

### This happened:

[ec2-user@ip-172-31-92-156 endor (main)]$ wing test -t sim test/*.w
Invalid Wing app (/home/ec2-user/endor.w/endor/test/target/test/apiResource.test.wsim) - simulator.json not found.
Invalid Wing app (/home/ec2-user/endor.w/endor/test/target/test/apiRetrieveResources.test.wsim) - simulator.json not found.
Invalid Wing app (/home/ec2-user/endor.w/endor/test/target/test/apiStubAuth.test.wsim) - simulator.json not found.
Invalid Wing app (/home/ec2-user/endor.w/endor/test/target/test/apiHeadersParser.test.wsim) - simulator.json not found.
Invalid Wing app (/home/ec2-user/endor.w/endor/test/target/test/apiBasicAuth.test.wsim) - simulator.json not found.
Invalid Wing app (/home/ec2-user/endor.w/endor/test/target/test/apiDeleteResource.test.wsim) - simulator.json not found.
Invalid Wing app (/home/ec2-user/endor.w/endor/test/target/test/cookieAuthFilters.test.wsim) - simulator.json not found.
Invalid Wing app (/home/ec2-user/endor.w/endor/test/target/test/qsParser.test.wsim) - simulator.json not found.
Invalid Wing app (/home/ec2-user/endor.w/endor/test/target/test/dynamodb.test.wsim) - simulator.json not found.
Invalid Wing app (/home/ec2-user/endor.w/endor/test/target/test/fixedSecretTokenFilters.test.wsim) - simulator.json not found.
Error: Key collision (2) in preflight types map
Error: Key collision (2) in preflight types map
Error: Key collision (2) in preflight types map

Results:
    × test/apiResource.test.w
    × test/apiRetrieveResources.test.w
    × test/apiStubAuth.test.w
    × test/apiHeadersParser.test.w
    × test/apiBasicAuth.test.w
    × test/apiDeleteResource.test.w
    × test/cookieAuthFilters.test.w
    × test/qsParser.test.w
    × test/dynamodb.test.w
    × test/fixedSecretTokenFilters.test.w
    × test/apiCreateResource.test.w
    × test/samlLoginFilter.test.w
    × test/apiReplaceResource.test.w

Errors:
At test/apiResource.test.w
Invalid Wing app (/home/ec2-user/endor.w/endor/test/target/test/apiResource.test.wsim) - simulator.json not found.
At test/apiRetrieveResources.test.w
Invalid Wing app (/home/ec2-user/endor.w/endor/test/target/test/apiRetrieveResources.test.wsim) - simulator.json not found.
At test/apiStubAuth.test.w
Invalid Wing app (/home/ec2-user/endor.w/endor/test/target/test/apiStubAuth.test.wsim) - simulator.json not found.
At test/apiHeadersParser.test.w
Invalid Wing app (/home/ec2-user/endor.w/endor/test/target/test/apiHeadersParser.test.wsim) - simulator.json not found.
At test/apiBasicAuth.test.w
Invalid Wing app (/home/ec2-user/endor.w/endor/test/target/test/apiBasicAuth.test.wsim) - simulator.json not found.
At test/apiDeleteResource.test.w
Invalid Wing app (/home/ec2-user/endor.w/endor/test/target/test/apiDeleteResource.test.wsim) - simulator.json not found.
At test/cookieAuthFilters.test.w
Invalid Wing app (/home/ec2-user/endor.w/endor/test/target/test/cookieAuthFilters.test.wsim) - simulator.json not found.
At test/qsParser.test.w
Invalid Wing app (/home/ec2-user/endor.w/endor/test/target/test/qsParser.test.wsim) - simulator.json not found.
At test/dynamodb.test.w
Invalid Wing app (/home/ec2-user/endor.w/endor/test/target/test/dynamodb.test.wsim) - simulator.json not found.
At test/fixedSecretTokenFilters.test.w
Invalid Wing app (/home/ec2-user/endor.w/endor/test/target/test/fixedSecretTokenFilters.test.wsim) - simulator.json not found.
At test/apiCreateResource.test.w
Error: Key collision (2) in preflight types map
At test/samlLoginFilter.test.w
Error: Key collision (2) in preflight types map
At test/apiReplaceResource.test.w
Error: Key collision (2) in preflight types map

Tests 13 failed (13)
Snapshots 13 skipped
Test Files 13 failed (13)

### I expected this:

Tests to run

### Is there a workaround?

M.b. to revert back to the previous version

### Wing Version

0.75.15

### Node.js Version

22.3.0

### Platform(s)

Linux

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
Fixed in Wing 0.75.16
