### ISSUE TITLE
`fs.chmod`

### ISSUE THREAD

**Issue by eladb** [winglang/wing#6914]
### Use Case

Need to chmod

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Discord](https://t.winglang.io/discord).

**Comment by tsuf239** [comment]
ok, so this functionality exists, but called `fs.setPermissions` do I need to do something?

**Comment by eladb** [comment]
No, we can close
