### ISSUE TITLE
Some rendering issue in doc site

### ISSUE THREAD

**Issue by eladb** [winglang/wing#6958]
### I tried this:

Browse to https://winglang.io/docs

### This happened:

<img width="1279" alt="image" src="https://github.com/user-attachments/assets/f2b0400a-4ac6-434e-a14c-4803fd8d0e62">

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
Looks fixed on my end - thanks @boyney123!

**Comment by boyney123** [comment]
Yeah sorry forgot to close the issue, thanks for clean up @Chriscbr
