### ISSUE TITLE
Replace `util.env("WING_TARGET")` with `@app.target` everywhere

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#7098]
### Use Case

Getting the current target through an environment variable is a bit weird and it requires an extra import. I think it might be better if we expose the "platform string" through a field like `@app.target`. This might require updating our existing platforms.

I don't think there's any critical need to deprecate the old API. But it will feel good to update our code examples and tests and winglibs to use the new syntax.

### Component

Documentation

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Discord](https://t.winglang.io/discord).

**Comment by Chriscbr** [comment]
We could also name it simply `@target`

**Comment by boyney123** [comment]
Yeah I think having `@app.target` or `@target` feels clean to me. TBH I actually prefer the `@target` naming... for what its worth

**Comment by Chriscbr** [comment]
Added `@target` in https://github.com/winglang/wing/pull/7161
