### ISSUE TITLE
Consolidate all snapshot tests into hangar

### ISSUE THREAD

**Issue by MarkMcCulloh** [winglang/wing#715]
### Summary

We currently have snapshot tests in both wingc and hangar. We should just move the JSIR snapshots to hangar so that is the only place needed to update.

### Feature Spec

Add additional snapshots to hangar and delete the existing ones in wingc

### Use Cases

Reduces contributor friction

### Implementation Notes

As part of this, we can additionally move the snapshot files to be next to the examples themselves to aid in discovery/clarity.

### Component

Contributor Experience

**Comment by staycoolcall911** [comment]
keep

**Comment by MarkMcCulloh** [comment]
This was completed in #754
