### ISSUE TITLE
DynamoDB WingLib will not deploy to AWS without startingPosition, but this is not documented

### ISSUE THREAD

**Issue by boyney123** [winglang/wing#7178]
### Use Case

Using the WingLib for DynamoDB trying to deploy my application to AWS with terraform. Says the startingPosition is required, but nothing states this in the documentation or examples.

### Proposed Solution

Add missing docs.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Discord](https://t.winglang.io/discord).

**Comment by Chriscbr** [comment]
@boyney123 Can you include an example or the error message in full?

**Comment by boyney123** [comment]
Yeah sure

here is the error

```
 Error: creating Lambda Event Source Mapping (arn:aws:dynamodb:us-east-1:654654508474:table/SpacesTable/stream/2024-09-30T10:24:17.260): operation error Lambda: CreateEventSourceMapping, https response error StatusCode: 400, RequestID: 497bc8b2-d962-4f09-bb50-187a59a3e650, InvalidParameterValueException: 1 validation error detected: Value null at 'startingPosition' failed to satisfy constraint: Member must not be null.
 ```
 
 So a DDB stream to a Lambda function
 
This example won't work as the startingPosition is not defined.
```
db.setStreamConsumer(inflight (record: dynamodb.StreamRecord) => {
     // LOGIC....
});
```

This works
```
db.setStreamConsumer(inflight (record: dynamodb.StreamRecord) => {
     // LOGIC....
}, { startingPosition: "LATEST" });
```

@Chriscbr what you think? Should we default this value for folks in in the winglib? Maybe default to LATEST? Or somehow give them errors to help them at least?

**Comment by Chriscbr** [comment]
Default to LATEST sounds reasonable.

**Comment by boyney123** [comment]
Will try and make the change

**Comment by boyney123** [comment]
OK PR open https://github.com/winglang/winglibs/pull/324

**Comment by boyney123** [comment]
This is now merged, closing this issue
