### ISSUE TITLE
inflight function expected type error in tutorial

### ISSUE THREAD

**Issue by kevinjone25** [winglang/wing#7196]
// **wing version:** 0.85.19 
// **tutorial name:** Introduction

In tutorial LOG 4/8
The code what tutorial write is `inflight(s:str?)` but the compiler will appear the error that indicates it should be `inflight(s:Json)`
After correct the code to `inflight(s:Json)`, the compiler work normally
![image](https://github.com/user-attachments/assets/3817341d-2120-4b82-8359-068b08f2abc8)

![image](https://github.com/user-attachments/assets/09868658-c142-404b-b742-ed9202532168)

**Comment by eladb** [comment]
Thanks for reporting. We’ll fix this asap.
