### ISSUE TITLE
Add wing cli autocomplete to fig

### ISSUE THREAD

**Issue by schosterbarak** [winglang/wing#768]
### Use Cases

autocomplete of CLI in fig terminal, It's pretty simple to add and makes the life of a user simpler. Here is an example: https://github.com/withfig/autocomplete/pull/829/files

PR should be made to: https://github.com/withfig/autocomplete/

### Component

Development Environment

**Comment by ShaiBer** [comment]
@all-contributors please add @itaikeren

**Comment by ShaiBer** [comment]
@all-contributors please add @itaikeren for adding is to the fig tool with this PR: https://www.reddit.com/r/ProgrammingLanguages/comments/10fb4pi/wing_a_cloudoriented_programming_language_request into this repo:  https://github.com/withfig/autocomplete/
