### ISSUE TITLE
GSG: wing.txt never written to S3 bucket

### ISSUE THREAD

**Issue by perpil** [winglang/wing#773]
### I tried this

Followed the GSG, deployed to cloud with `terraform apply` and dropped a message into the SQS queue.  Nothing ever written to the S3 bucket, but logs appear fine.

I've tried the following steps, terraform destroy and redeploy.  Pushed multiple messages. Turned on cloudtrail S3 data event logging for the S3 bucket to see if any requests were made.  I see nothing coming from the lambda to write to the bucket.

It works fine in the wing console (it writes to `wing.txt`, but I don't see logs due to #730) 

### Expected

A file called `wing.txt` in my S3 bucket.

### Instead, this happened

Nothing

### Component

Documentation

### Environment

```markdown
- Wing Version: 0.2.192
- OS: MacOS 13.0.1
- Node version: v18.12.1
```

### Anything else?

[Slack Thread w/more Details](https://winglang.slack.com/archives/C04BBDQUWQP/p1669354917914099)

**Comment by staycoolcall911** [comment]
Fixed in #732

**Comment by perpil** [comment]
Confirmed this works with 0.4.50.

**Comment by staycoolcall911** [comment]
Thanks @perpil - highly appreciate that you tested this!
