### ISSUE TITLE
Wing version bumping

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#808]
### Summary

Support multiple types of version bumps

### Feature Spec

Success criteria: any commit made to the main branch with "!" after the conventional commit type (i.e. "feat!" or "fix(scope)!:") or "BREAKING CHANGE:" in its commit body should result in a major version bump when Wing is released.

When Wing is pre-1.0, this should result in a change to the minor version number. For example, from 0.3.x to 0.4.0.

When Wing is post 1.0, this should result in a change to the major version number. For example, from 1.2.3 to 2.0.0.

**Comment by MarkMcCulloh** [comment]
I believe this issue was solved in https://github.com/winglang/wing/pull/1989
