### ISSUE TITLE
Add release notifications in Slack

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#828]
### Summary

We'd like to be able to announce new releases in Slack

### Feature Spec

Since every PR goes straight to main, we have multiple releases each day, so we'd like to have a channel where they are announced.

There are two options:
1. Announce every release (which might be too noisy)
2. Have daily aggregated announcements with all the content that entered that day

### Use Cases

This solves the hardship of community members to keep up to date with all the different advancement in Wing

### Implementation Notes

This is a GitHub bot for Slack we can use: https://slack.github.com/

### Component

Contributor Experience

**Comment by staycoolcall911** [comment]
@revitalbarletz, @eladb , @ShaiBer - we share release notes every 2 weeks. Should we close this?

**Comment by staycoolcall911** [comment]
Done by @Chriscbr as part of dogfooding sprint. `#releases` on Slack
