### ISSUE TITLE
Strings: str object API

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#836]
We need to add to the spec, then implement standard string API methods such as `concatenate`, `substr`, etc.

**Comment by staycoolcall911** [comment]
For sprint 10 we wanted to support these methods of the str API:
- [ ] .len
- [ ] .contains

**Comment by MarkMcCulloh** [comment]
Resolved in https://github.com/winglang/wing/pull/1074

Note: final API method naming (must match original JS string APIs):
- .length
- .includes
- .split
