### ISSUE TITLE
Resource declaration: `this` in constructor and inflight fields

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#864]
https://github.com/winglang/wing/blob/main/docs/04-reference/winglang-spec.md#33-resources

This was split from #467 to represent what we need for the [TODO app epic](https://github.com/winglang/wing/pull/656).

- [x] support `this` in the constructor
- [ ] #1596

**Comment by ekeren** [comment]
What would be a good use case for inflight fields? 

@eladb/ @Chriscbr ?

**Comment by Chriscbr** [comment]
@ekeren

`queue.approx_size` is an inflight field

**Comment by ekeren** [comment]
> queue.approx_size is an inflight field

@Chriscbr , I am assuming it is a getter that gets calculated on the actual resource.... not an actual QueueClient field 

I was thinking about a use case to save some actual field that store a value on the client

**Comment by yoav-steinberg** [comment]
> I was thinking about a use case to save some actual field that store a value on the client

`queue._cached_approx_size` which isn't updated on each access if the getter is called too frequently.

**Comment by ekeren** [comment]
created a ticket for inflight fields
