### ISSUE TITLE
Don't move to next compilation phase if previous phase had errors

### ISSUE THREAD

**Issue by yoav-steinberg** [winglang/wing#890]
We currently do this:

1. Do tree sitter parsing
2. Build AST
3. Run type-checker

Each of these phases might produce a compilation error:
1. tree sitter `ERROR` nodes.
2. parser calls to `add_error`.
3. type-checker call to `stmt_error`/`type_error`/`expr_error` etc.

Now my question is: if we collect all errors, when do we abort compilation?
It might make sense that if after **1** there are any errors we abort and don't try to continue collecting errors in **2** and the same for **3**. That way there are less unexpected situations down the line. For example the parser phase 2 above, will only expect valid but unimplemented grammar. Otherwise, will we be reporting multiple errors on the same invalid grammar?

@MarkMcCulloh Please let me know what you think.

**Comment by staycoolcall911** [comment]
@yoav-steinberg , @MarkMcCulloh - do we want to close this?

**Comment by yoav-steinberg** [comment]
Our last discussion about this leaned towards just continuing and adding a message (without flagging the actual types/captures/etc as a result of an error). Lets stay with that approach for now and revisit this when/if it comes up again.
