### ISSUE TITLE
Data & Analytics in Wing Console

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#919]
Related to winglang/console#185.

**Comment by ainvoner** [comment]
@ekeren mixpanel integration with segment
need to update payment

**Comment by ekeren** [comment]
done

**Comment by ekeren** [comment]
upgraded segment (not mixpanel yet)

**Comment by ekeren** [comment]
WIP - https://docs.google.com/presentation/d/1Vo87TYb_Iw6c0HJGotzSWtKTsDe0AXagQ23yiyyP67w/edit#slide=id.g24d3dbd5e4d_0_30

**Comment by ekeren** [comment]
@ainvoner , do you need anything from me here?
