### ISSUE TITLE
Add E2E testing for Wing Console

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#923]
- [ ] Prepare a doc suggesting the best framework to use and which tests we need
- [ ] Add infra and tests

**Comment by ainvoner** [comment]
Playwright testing framework for E2E testing.
Vitest for unit testing.
 
 E2E:
 1. test application is loading
 2. test the loader indicator is not visible (the application doesn't get stuck while compiling and loading the simulator)
 3. snapshot test for the app tree view
 4. snapshot test for the app map view

unit test:
1. test application state machine
