### ISSUE TITLE
User story idea: transforming JSON

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#967]
### Summary

As a user, I want to be able to manipulate JSON objects in Wing

### Feature Spec

(hypothetical README for the new feature:)

Wing 0.x now supports several features for transforming structured JSON values. It is very common to have to parse JSON events, transform them, and stringify them when writing business logic for cloud services. Wing now provides the following builtins/standard library functions for parsing and stringifying JSON values:

> TODO: code snippet

Wing also now provides several ways to manipulate JSON values. For example, an object's fields can be accessed directly, or it can be destructured, allowing fields to be accessed as local variable:

> TODO: code snippet

Wing JSON values into Wing struct types, so you can manipulate the values with type safety:

> TODO: code snippet

### Use Cases

To connect different cloud services together, I often want to transform one kind of JSON event into another. Filtering values, selecting fields, introducing new fields, and so on. Anything you might want to do in [jq](https://stedolan.github.io/jq/manual/).

### Component

Language Design

**Comment by ekeren** [comment]
duplicate #1053
