### ISSUE TITLE
Console shows spinner when run with non-existing file

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#972]
### I tried this

I ran `wing run hello.wsim` in my project folder. This opened my Wing console, but I just saw the message "Compiling..." with the spinner loading forever. Since it was showing a loading spinner, I thought as a user I should just wait until it loads.

### Expected

I expected an error message saying the file doesn't exist)

### Component

Wing Console

### Environment

```markdown
- Wing Version: 0.4.25
- OS: macOS 13.1
- Wing Console version: 0.1.10
- Node version: v19.2.0
```

### Anything else?

After some confusion I realized I had the file name wrong, so `wing run target/hello.wsim` got the console working.

**Comment by staycoolcall911** [comment]
Already fixed - probably in #1533 or an earlier PR
