### ISSUE TITLE
Fabulous compiler diagnostics 

### ISSUE THREAD

**Issue by eladb** [winglang/wing#984]
### Feature Spec

When the Wing compiler is attached to a tty, compiler diagnostics are now colorful, fancy and beautiful. They show a the relevant code, an arrow that points to exactly where the error is, etc etc.

Basically, inspired by the amazing Rust compiler diagnostics.

### Use Cases

Enjoy errors.

### Component

Compiler

**Comment by staycoolcall911** [comment]
Should be easy to add some nice colors - we already have the [Colored rust crate](https://docs.rs/colored/latest/colored/), so just need to `use` it in https://github.com/winglang/wing/blob/main/libs/wingc/src/bin.rs

**Comment by staycoolcall911** [comment]
@eladb - I'm closing this. If anyone has additional suggestions how to improve our diagnostics please open a new issue.
