### ISSUE TITLE
View text files inside Wing Console bucket explorer

### ISSUE THREAD

**Issue by eladb** [winglang/wing#994]
### Feature Spec

Wing Console now supports quickly viewing `.txt` and `.json` files within the console's bucket explorer.

(json is displayed nicely formatted of course).

### Use Cases

I want to quickly view the contents of a JSON or text object in my bucket.

### Component

Wing Console

**Comment by eladb** [comment]
@ainvoner @ekeren I believe this is still relevant, right?

**Comment by ekeren** [comment]
Yes, funny enough, we just talked about it yesterday with @polamoros

**Comment by polamoros** [comment]
Related to https://github.com/winglang/wing/issues/1419
