### ISSUE TITLE
Playground should have a link to report a new bug, which automatically includes the Wing version

### ISSUE THREAD

**Issue by eladb** [winglang/wing#995]
### Feature Spec

The infamous Wing playground (playground.winglang.io) should add a link to report a bug in the compiler:
https://github.com/winglang/wing/issues/new?assignees=&labels=bug&template=bug.yml

It should show the version number of the compiler (Wing version).

### Use Cases

Reporting bugs

**Comment by staycoolcall911** [comment]
@eladb - the playground uses the latest version of the compiler. Do we still think this is important to show explicitly?

**Comment by eladb** [comment]
Yes, I think it's useful when you want to report a bug and you need to specify the version.

Ideally we should have a quick link in the playground that opens a bug report with the contents of the playground and the version info and all that.

**Comment by staycoolcall911** [comment]
That makes sense - I'm editing the bug title and description to add a link to open a bug.

**Comment by staycoolcall911** [comment]
Should be easy to add it on https://github.com/winglang/wing/blob/main/apps/wing-playground/index.html
